### ISSUE TITLE
ElasticSearch aliases, rollovers, lifecycle management? 

### ISSUE THREAD

**Issue by dmille6** [OpenCTI-Platform/opencti#1000]
i'm new to opencti and have a moderate understanding of elasticsearch. Really impressed with opencti so far, my question is, it seems to put data into multiple elasticsearch indexes. It doesnt seem to use aliases for those indexes and has no mechanism for data management within ES. Am I missing something? Are new indexes created monthly? Are there any plans for data management in ES? these indexes are going to get pretty big pretty quickly. Without any management things would fall apart pretty quickly wouldnt they?

**Comment by SamuelHassine** [comment]
Hello @dmille6,

We have implemented a proper management of ElasticSearch aliases/rollovers in 4.1.X. @richard-julien is preparing a blog post about that. I will keep you informed here as soon as it is ready!

Kind regards,
Samuel

**Comment by lcia-projects** [comment]
thank you so much, this is the one feature I needed before I really put this system into place. Where are blog posts posted? www.opencti.io/blog?

**Comment by richard-julien** [comment]
Hi, the blog post is not ready yet sorry. Im of course available to discuss/help about this subject on the slack.

**Comment by manonviallet** [comment]
Hello, @dmille6 @lcia-projects,
Documentation on OpenCTI is posted there (still a work in progress) https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518
Blog posts are published under the Luatix profile here : https://medium.com/luatix
They are advertised on the Slack Channel, which you can join to ask further questions and exchange with users, as Julien indicated above.
Does this answer correctly your question ? If it is the case, I will close this issue

**Comment by manonviallet** [comment]
Hello, since there have been no futher comments, I will close this issue. Don't hesitate to re-open it if you have additional comment or questions.
