### ISSUE TITLE
Question - additional data feeds

### ISSUE THREAD

**Issue by mfiedler144** [OpenCTI-Platform/opencti#1001]
Hello everyone, 

I am trying openCTI for my research project (bachelor thesis) and I would need to implement additional data sources (osint feeds). Is this possible or is the platform limited to the already existing connectors?

Best regards

Maurice

**Comment by jbfeldman** [comment]
You can pull from any OSINT feed that serves data over TAXII2 with this connector https://github.com/jbfeldman/opencti-taxxi2-connector

**Comment by dmille6** [comment]
TAXII2 is the best choice but, you can also use the alienvault otx connector and subscribe to different feeds through alienvault otx.

**Comment by SamuelHassine** [comment]
We plan to introduce a lot more connectors in next releases, in the mean time feel free also to contribute and develop new ones!
