### ISSUE TITLE
LDAP Group import

### ISSUE THREAD

**Issue by summershrimp** [OpenCTI-Platform/opencti#1007]
## Problem to Solve
assign different privilege to different user based on LDAP Group info.

## Current Workaround
Add `(memberOf=xxxx)` on ldap search filter.

## Proposed Solution
Import group info from LDAP

**Comment by SamuelHassine** [comment]
Implemented and documented here: https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#09d04027d96d4193b952979cdcfb2bcc.
