### ISSUE TITLE
Login redirection failed in Firefox ESR

### ISSUE THREAD

**Issue by b4b857f6ee** [OpenCTI-Platform/opencti#101]
## Description

During the login process, just after enter login and password, press enter and the gui behavior is like this. /login  /dashboard /login.
So i do not have access to the dashboard.

## Environment

1. OS : Ubuntu 18.04
2. OpenCTI version: last 1.0.0 for docker
3. OpenCTI client: mozilla
4. Other environment details: docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Follow the documentation for run docker
2. Docker-composer up
3. Trying to login with default credentials

## Expected Output

Login successful 

## Actual Output

Redirection to login page.
 
## Additional information

The behavior is like this
/login 
/dashboard
/login

**Comment by SamuelHassine** [comment]
Hello @b4b857f6ee do you have the same problem on the [demonstration instance](https://demo.opencti.io)? Could you please provide us with your Firefox version?

**Comment by b4b857f6ee** [comment]
Yes i have the same problem with it...
Last Mozilla esr 60.7.2

**Comment by b4b857f6ee** [comment]
I have try private and not private session. But as you say. Maybe it is a Mozilla problem no?

**Comment by SamuelHassine** [comment]
@b4b857f6ee: thanks for your report, I successfully reproduced the bug.

**Comment by SamuelHassine** [comment]
@b4b857f6ee: We successfully fixed this issue, it will be solved in the next release.

**Comment by SamuelHassine** [comment]
@b4b857f6ee: could you confirm that you are now able to login on the demo (and on a fresh docker deployment)?

**Comment by b4b857f6ee** [comment]
Hello,
Ok for the demo.
For my local i erase my folder. Reinstall. Run docker.
Same behavior. Restart mozilla, private session. Same. Strange.

**Comment by SamuelHassine** [comment]
@b4b857f6ee: did you clone the repository from **OpenCTI-Platform**/opencti and not **LuatixHQ**/opencti? There was a typo in the documentation that is [now fixed](https://github.com/OpenCTI-Platform/opencti/commit/cdb57b8f1dec653747db8d7891dddd6511e22b89).

**Comment by b4b857f6ee** [comment]
Yes the LuatixHQ, sorry.
I just test your's. And i got an error about your persistence data modification.
When i run it, i get " opencti_1 elasticsearch:  forward host lookup failed: unknown host
Waiting Elasticsearch to launch"
Over and over.

**Comment by SamuelHassine** [comment]
@b4b857f6ee: I just pushed to the repository, could you please pull and retry?

**Comment by b4b857f6ee** [comment]
Same behavior

**Comment by SamuelHassine** [comment]
@b4b857f6ee: please do the following:

1. Stop Docker daemon (ie. `/etc/init.d/docker stop`)
2. Remove all files of docker (ie. `rm -Rf /var/lib/docker`)
3. Start Docker daemon (ie. `/etc/init.d/docker start`)
4. Delete the repository of OpenCTI
5. Clone the repository `https://github.com/OpenCTI-Platform/opencti`
6. Chmod 777 the folders the opencti/opencti-docker/volumes/*
7. `docker-compose up`

**Comment by b4b857f6ee** [comment]
Thank's. It's work!
