### ISSUE TITLE
Generic entities "Location" are not correctly handled

### ISSUE THREAD

**Issue by tellerj** [OpenCTI-Platform/opencti#1019]
## Description

Platform fails to properly handle "Location" SDO's when they are missing the "Latitude" and "Longitude" fields--even though those fields are optional, per the spec ([section 4.9](https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_th8nitr8jb4k)). Furthermore, when creating a "Country" entity, the platform does not allow the user to add "Latitude" and "Longitude" data, meaning that "Location" entities created within the OpenCTI GUI will always display improperly.

## Environment

OpenCTI GUI v4.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to "Entities" > "Countries" > "+" and create a made-up country
2. Export the entity using the ExportFileStix2 connector
3. Import the entity to another OpenCTI instance using the ImportFileStix2 connector
 -- or --
3. Import this entity into OpenCTI 4.0.7 using the ImportFileStix2 connector: 
`{
    "type": "bundle",
    "id": "bundle--ce809d26-0f2c-4825-bd7f-bcde241ca766",
    "objects": [
        {
            "id": "location--afaab66b-dcc4-5964-a91e-04a7c24513eb",
            "spec_version": "2.1",
            "revoked": false,
            "confidence": 0,
            "created": "2021-01-25T04:45:38.095Z",
            "modified": "2021-01-25T04:45:38.095Z",
            "name": "Made-Up Land",
            "description": "Made-Up Land is made-up!",
            "x_opencti_id": "25342c63-cf8c-4470-b091-e9519cc30526",
            "type": "location"
        }
    ]
}`
4. Create relationship between Country entity and, for example, a Report entity
5. Navigate to "Knowledge" tab of Report entity, and view Country (location) object. 

## Expected Output

The platform should display the Country object as a location entity in the "Knowledge" section of a "Report" object. Like so: 
![image](https://user-images.githubusercontent.com/41540591/105664050-97c89400-5e88-11eb-9bd0-25c349f1b126.png)

## Actual Output

The platform renders the country object as a string saying, "/dashboard/entities/geo/positions"
![image](https://user-images.githubusercontent.com/41540591/105663783-f93c3300-5e87-11eb-9f98-c960b8f90d2b.png)

 
## Additional information

Recommendation:
- Add ability to specify Lat/Long in "Country" creation screen
- Fix handling of imported "location--" entities which are missing lat/long to render using the same icon as other "Country" (location--) entities

This error also shows up whenever the entity in question is listed in an entity list, like so:
![image](https://user-images.githubusercontent.com/41540591/105664121-c34b7e80-5e88-11eb-8c88-c3e0e5ca89b3.png)

**Comment by SamuelHassine** [comment]
Hello @tellerj,

Thanks for opening this issue, the problem is not linked to the absence of latitude/longitude fields, it's just that the UI is not ready to handle generic "locations". We will introduce that in the next release.

Kind regards,
Samuel

**Comment by tellerj** [comment]
Sounds good! Thanks for the explanation. I was guessing about the source of the problem. Looking forward to the fix!
