### ISSUE TITLE
Platform initialization fail after data corruption

### ISSUE THREAD

**Issue by ghost** [OpenCTI-Platform/opencti#1023]
## Description

The machine running my OpenCTI instance crashed yesterday. After restart, Elasticsearch failed to start because of data corruption (a translog of a shard copy became corrupted). I have fixed this by removing the corrupted data as describe in Elastic documentation ([here](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/shard-tool.html)). I have changed the allocation of a shard and some data have been lost.

Unfortunately, OpenCTI still fail to start, as described below.

## Environment

1. OS (where OpenCTI server runs): OSX 11.1
2. OpenCTI version: OpenCTI 4.0.7
3. OpenCTI client: frontend
4. Other environment details: Elasticsearch and Redis are running on OSX. Other components are running in docker.

## Reproducible Steps

I suppose the problem could be reproduced by manually changing the allocation of a shard. The elastic command I run was:

```
POST /_cluster/reroute
{
  "commands" : [
    {
      "allocate_stale_primary" : {
        "index" : "opencti_internal_objects",
        "shard" : 0,
        "node" : "cwsESJu9RoefNvZO9amoSA",
        "accept_data_loss" : true
      }
    }
  ]
}
```

## Expected Output

'It works?' ?

## Actual Output

```
$ node build/index.js

{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-01-26T09:40:40.229Z","data":{"reason":"Expected one element only through relation","category":"technical","sources":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","relationType":"authorized-by","targetEntityType":"Token"},"internalData":{}},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-01-26T09:40:40.229Z"}

error Command failed with exit code 1.
```
 
## Additional information

I have read the issue #991 and I have tried to cleanup as this is suggested. It doesn't work, the output stay the same.

Thank you for your help.

**Comment by SamuelHassine** [comment]
Hello @h51un6,

You data are not cleaned, please delete the whole ElasticSearch directory and the whole Redis directory, then restart your services, then retry.

Kind regards,
Samuel

**Comment by ghost** [comment]
Hello Samuel,

Thank you for your answer. Sorry, but I don't know Elasticsearch very well: what do you mean by "the whole ElasticSearch directory"? The whole database or something else?

Regards,

**Comment by SamuelHassine** [comment]
On Unix systems, data should be in /var/lib/elasticsearch and /var/lib/redis.

**Comment by ghost** [comment]
Hello Samuel,

I solved the problem by rolling back with TimeMachine to the latest clean versions of the databases. It works and I just lost a few days of data instead of the whole database. 

Thanks for your help. 

Regards,
