### ISSUE TITLE
Attack patterns layouts

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#1024]
## Problem to Solve

Attack patterns (and course of actions) always have to be presented with their external ID visible to be comprehensible.

## Current Workaround

Having a TTP matrix hanging on the wall next to your desk.

## Proposed Solution

- In the research layouts, external ID has to be displayed each time an attack pattern is displayed
- In the knowledge graphes, external ID has to be displayed
- In the attack pattern view, external IDs of the sub-patterns have to be displayed (and sorted : 001, 002, 003...)
- In the attack pattern view, it should be easy to go to the parent attack pattern or any other sibling for a sub-technics
- In the attack-pattern list view, sub-technics should only appear once, under their parent. They currently appear twice in my case, once as a standalone and once under the parent
- A specific menu should be created for adding multiple TTPs to a knowledge graph. One possible layout is a display of a matrix ordered by killchain phase, which can be filtered based on any keyword appearing in the ID, name or description of a TTP. More details on a TTP can appear in an overlay when clicking a (i) icon. Already selected TTPs continue to appear in the matrix once they have been selected to be added to the graph even if the filters have changed.

## Additional Information

The last one is tough but necessary for manual ingestion of data. Searching for TTPs one by one in the search field has proven to be too long.

**Comment by SamuelHassine** [comment]
All the bullet points have been covered except the last one, which will be covered in #1207.
