### ISSUE TITLE
Dashboard map not loading even with proxy set

### ISSUE THREAD

**Issue by trocade** [OpenCTI-Platform/opencti#1036]
## Description

The dashboard map fails to load even thou the proxy parameters are set.

## Environment

1. Ubuntu 18.04 LTS
2. OpenCTI 4.0.7
3. Frontend
4. Docker setup behind proxy

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure opencti/platform to use http and https proxy via env variables
2. Logon to dashboard
3. Map is greyed out

## Expected Output

The map data to be fetched via proxy
## Actual Output

Map is not displayed.
 
## Additional information

There are no logged requests in the proxy logs of any requests.

Config in the docker-compose file:
```
      - HTTP_PROXY=http://<proxy>:8080
      - HTTPS_PROXY=http://<proxy>:8080
      - NO_PROXY="opencti,redis,minio,rabbitmq,localhost,0,1,2,3,4,5,6,7,8,9"
```

I have checked so the proxy is working via curl from the same system.
```
curl https://map.opencti.io/styles/1fdd936a-084b-46ac-a948-22ce1686aadf/2/3/0.png -o test.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3397  100  3397    0     0  19192      0 --:--:-- --:--:-- --:--:-- 19084
```
I did do a insepction on when loading the page and it throws this error:
`Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data <URL> <URL>".`

**Comment by richard-julien** [comment]
Hi @trocade ,

The map is loaded directly by the client. We need to take a look if the browser of the client have access to https://map.opencti.io

**Comment by trocade** [comment]
Hi @richard-julien ,

Then it is very simple, the browser client does not have this access as it is now. Thanks.
