### ISSUE TITLE
How to increase number of "worker"?

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1039]
Installed latest OpenCTI in Ubuntu 20. 
OpenCTI is running in docker as one of the recommended install.
How to increase number of "worker"?

**Comment by steve-qm** [comment]
You can modify the "replicas: 3" value in the docker-compose.yml under the worker section.


...
  worker:
    image: opencti/worker:4.1.1
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
...

**Comment by NetEyes** [comment]
Thank you. 
I hope the next release, this configuration can be control from the dashboard UI (admin section)

**Comment by crym** [comment]
@NetEyes As this is related to Docker and not OpenCTI you can do this on the fly with `docker service scale opencti_worker=[number of workers]`  

[https://docs.docker.com/engine/reference/commandline/service_scale/](https://docs.docker.com/engine/reference/commandline/service_scale/)
