### ISSUE TITLE
Hash Verification

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1042]
## Description

{When creating a File observable, OpenCTI no longer verifies that the MD5 value entered is a legitimate MD5 hash. The same goes for SHA1, SHA256}

## Environment

1. OS (where OpenCTI server runs): { Demo instance }
2. OpenCTI version: { OpenCTI 4.1.1 }
3. OpenCTI client: { frontend}
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create new File object
2. Enter random digits as MD5
3. Click "Create"

## Expected Output

Error - this is not a valid hash

## Actual Output

Successfully created File object
 
## Additional information

{
![image](https://user-images.githubusercontent.com/78382789/106513611-ce119f00-6498-11eb-8cf2-a6de71faa1b1.png)

}

**Comment by richard-julien** [comment]
Hi @securitiz,

And lib/rules in mind to check that? Thanks

**Comment by CyberDaedalus00** [comment]
If you want to be aligned with STIX 2.1 hash values, here are the regex patterns for hash algorithms in the spec:

- MD5 pattern: "^[a-fA-F0-9]{32}$"
- SHA-1 pattern: "^[a-fA-F0-9]{40}$"
- SHA-256 pattern: "^[a-fA-F0-9]{64}$"
- SHA-512 pattern: "^[a-fA-F0-9]{128}$"
- SHA3-256 pattern: "^[a-fA-F0-9]{64}$"
- SHA3-512 pattern: "^[a-fA-F0-9]{128}$"
- SSDEEP pattern: "^[a-zA-Z0-9/+:.]{1,128}$
- TLSH pattern: "^[a-zA-Z0-9]{70}$"

**Comment by richard-julien** [comment]
Thanks for your insights @securitiz and @CyberDaedalus00 .
