### ISSUE TITLE
Create a TAXII2.1 compliant endpoint in the API

### ISSUE THREAD

**Issue by vxsh4d0w** [OpenCTI-Platform/opencti#1044]
Is there any plan to add a connector to export info in opentaxii format? It would be great to consider it alternative.

**Comment by SamuelHassine** [comment]
Description of the feature: Implementation of a TAXII2.1 compliant API endpoint on `/taxii`. Multiple custom endpoints for Storage or Authentication are configured in the [App.js](https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/app.js) file.

TAXII 2.1 specifications: https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.html
