### ISSUE TITLE
Unable to connect to "http://{IP_ADDRESS}:8080" 

### ISSUE THREAD

**Issue by V0lundr** [OpenCTI-Platform/opencti#1047]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I am trying to follow the tutorial for for Virtualbox testing, and everything is deployed ok and then I get to this part and fail: "Once the virtual machine is launched, the OpenCTI platform can take 3 to 5 minutes to start the first time. Then you have access to the platform using the URL `http://{IP_ADDRESS}:8080` and credentials `admin@opencti.io` / `admin`."

Also, if I try http://{IP_ADDRESS}:3000 I get the response, and I can log in (everything fine)

Also "ss -tulnp" gives the following output:

<img width="355" alt="1" src="https://user-images.githubusercontent.com/20555405/106630676-587eff00-657c-11eb-8f02-8629c12a45da.png">

My vm is in a bridged mode and I can ping it from my host machine.

Am I missing something?

My virtual box version: Version 6.1.16 r140961

## Environment

1. OS (where OpenCTI server runs): Windows 10 and Ubuntu 20.04
2. OpenCTI version: 4.1.1
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
It will be fixed in the next release.
