### ISSUE TITLE
Add Kill Chain Phase selection when adding observable

### ISSUE THREAD

**Issue by cdiraimondi** [OpenCTI-Platform/opencti#105]
## Problem to Solve

There is currently no way to specify the Kill Chain phases, more specifically Lockheed Martin Kill Chain phases to specific observables when adding them to a report. 

## Current Workaround

None

## Proposed Solution

When adding an Observable, provide a dropdown list that contains all the Kill Chain values added from the settings page. 

## Additional Information

I was able to add the custom Lockheed Martin Cyber Kill Chain phases to the Kill Chain settings page but was unable to add them to the observable.

**Comment by SamuelHassine** [comment]
Users must be able to add a kill chain phase not directly on the observable but on the relation between the observables and the associated threat. So kill chain phases will be implmented in the "relation form" form relations of type `indicates`.
