### ISSUE TITLE
Reports have system set as creator and have no history

### ISSUE THREAD

**Issue by trocade** [OpenCTI-Platform/opencti#1050]
## Description

Reports are said to be created by system and missing all history. 
While for example malware and attack patterns have the correct creator and history

## Environment

1. Ubuntu 18.04 LTS 
2. OpenCTI 4.1.1
3. OpenCTI frontend/python
4. Docker implementation

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create connector-user and id (for example mitre)
2. Start to import data
3. Incorrect creator and missing history on reports

## Expected Output

The reports should have correct creator  and history

## Actual Output

No history, system is set as creator.
 
## Additional information

There are no logged errors in the logs.
This is the rerport:
![image](https://user-images.githubusercontent.com/9382220/106725654-e48b3800-6609-11eb-8cad-efcd394d1d46.png)

And this is how attack pattern looks for the same report:
![image](https://user-images.githubusercontent.com/9382220/106725867-1bf9e480-660a-11eb-8f6d-cddb9ae75d3c.png)

And history:
![image](https://user-images.githubusercontent.com/9382220/106725922-2916d380-660a-11eb-95b5-061267cb3f54.png)

Permissions for the connector are set as this:
![image](https://user-images.githubusercontent.com/9382220/106726194-654a3400-660a-11eb-8556-30adda4328fe.png)

The history connector is also running as a dedicated user with the permissions shown above.

**Comment by SamuelHassine** [comment]
Hello,

Can you please check the "state" of the history connector?

![image](https://user-images.githubusercontent.com/1334279/106740779-24a6e680-661b-11eb-89ab-c22c6439d3c3.png)


If you restart it, do you see a lot of logs to catch old history entries?

Kind regards,
Samuel

**Comment by trocade** [comment]
Hi,

It did have a connectorlasteventid, restarting it did not change that. Then I did a state reset on it and now it does not seem to have been updated since the state reset.

**Comment by trocade** [comment]
Now it says this after the state reset:
```
config_connector-history_1[897]:   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 425, in listen_stream
config_connector-history_1[897]:     if current_state["connectorLastEventId"] == last_event_id:
config_connector-history_1[897]: TypeError: string indices must be integers
config_connector-history_1[897]: INFO:root:Listing Threat-Actors with filters null.
config_connector-history_1[897]: INFO:root:Connector registered with ID:fe964a8e-004d-4747-9b2e-485673c53151
config_connector-history_1[897]: INFO:root:Starting ping alive thread
config_connector-history_1[897]: INFO:root:Getting logs worker config...
config_connector-history_1[897]: INFO:root:Starting listening stream events with SSL verify to: True
config_connector-history_1[897]: Traceback (most recent call last):
config_connector-history_1[897]:   File "history.py", line 71, in <module>
config_connector-history_1[897]:     HistoryInstance.start()
config_connector-history_1[897]:   File "history.py", line 66, in start
config_connector-history_1[897]:     self.helper.listen_stream(self._process_message)
config_connector-history_1[897]:   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 425, in listen_stream
config_connector-history_1[897]:     if current_state["connectorLastEventId"] == last_event_id:
config_connector-history_1[897]: TypeError: string indices must be integers
```

**Comment by SamuelHassine** [comment]
The connector is now is dead state, this is a bug, it will be fixed in the next release.
