### ISSUE TITLE
Websocket related? error when starting the DEV environment

### ISSUE THREAD

**Issue by cyb3rfox** [OpenCTI-Platform/opencti#1051]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I'm trying to start up the developement environment according to https://www.notion.so/Environment-setup-606996f36d904fcf8d434c6d0eae4a00

The docker containers start fine. Also opencti-graphql comes up using yarn. When I start the opencti-frontend, it also starts but when a webbrowser opens the webpage it will shortly show the login page and a few seconds later bring up an error message shown below. That appears to be happening when it tries to switch over to websockets. At the same time opencti-graphql shows the following error:

`{"type":"READ_ERROR","operation_query":"query RootQuery{me{id name lastname language user_email capabilities{name id}}settings{platform_map_tile_server ...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}","inner_relation_creation":0,"operation":"RootQuery","time":31,"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (webpack-internal:///./src/config/errors.js:28:10)","at AuthRequired (webpack-internal:///./src/config/errors.js:36:40)","at AuthDirective.authenticationControl (webpack-internal:///./src/graphql/authDirective.js:46:89)","at field.resolve (webpack-internal:///./src/graphql/authDirective.js:85:131)","at field.resolve (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql-extensions/dist/index.js:134:26)","at field.resolve (/root/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","at resolveField (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:466:18)","at executeFields (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:294:18)","at executeOperation (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:238:122)","at executeImpl (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:118:14)","at Object.execute (/root/opencti/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:62:35)","at /root/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","at Generator.next (<anonymous>)","at /root/opencti/opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"]},"level":"warn","message":"API Call","timestamp":"2021-02-03T10:59:07.535Z"}
`

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1 LTS
2. OpenCTI version: e.g. OpenCTI 4.1.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
according to devguide, described above.

## Expected Output

gui working

## Actual Output

**Output Webbrowser:**

`rror: 
Wrapper
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/wrapNativeSuper.js:22
_createSuperInternal
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createSuper.js:12
ApplicationError
src/relay/environment.js:42

  39 | // Default application exception.
  40 | export class ApplicationError extends Error {
  41 |   constructor(errors) {
> 42 |     super();
  43 |     this.data = errors;
  44 |   }
  45 | }

render
src/relay/environment.js:101

   98 |     const { error } = data;
   99 |     const types = error ? map((e) => e.name, error) : [];
  100 |     const unmanagedErrors = difference(types, managedErrorTypes || []);
> 101 |     if (!isEmpty(unmanagedErrors)) throw new ApplicationError(error);
      | ^  102 |     return render(data);
  103 |   }}
  104 | />

render
node_modules/react-relay/lib/ReactRelayQueryRenderer.js:210
finishClassComponent
node_modules/react-dom/cjs/react-dom.development.js:17160
updateClassComponent
node_modules/react-dom/cjs/react-dom.development.js:17110
beginWork
node_modules/react-dom/cjs/react-dom.development.js:18620
callCallback
node_modules/react-dom/cjs/react-dom.development.js:188
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:237
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:292
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:23203
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:22154
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:22130
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:21756
flushSyncCallbackQueueImpl/<
node_modules/react-dom/cjs/react-dom.development.js:11089
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11039
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11084
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11072
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21199
enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js:12639
./node_modules/react/cjs/react.development.js/Component.prototype.setState
node_modules/react/cjs/react.development.js:471
componentDidMount/retryCallbacks.handleDataChange
node_modules/react-relay/lib/ReactRelayQueryRenderer.js:138
error/<
node_modules/react-relay/lib/ReactRelayQueryFetcher.js:195
error
node_modules/react-relay/lib/ReactRelayQueryFetcher.js:194
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
both/<
node_modules/relay-runtime/lib/network/RelayObservable.js:190
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
error/<
node_modules/relay-runtime/lib/util/RelayReplaySubject.js:104
error
node_modules/relay-runtime/lib/util/RelayReplaySubject.js:103
error
node_modules/relay-runtime/lib/query/fetchQueryInternal.js:127
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
_error
node_modules/relay-runtime/lib/store/RelayModernQueryExecutor.js:256
error
node_modules/relay-runtime/lib/store/RelayModernQueryExecutor.js:112
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
both/<
node_modules/relay-runtime/lib/network/RelayObservable.js:190
error
node_modules/relay-runtime/lib/network/RelayObservable.js:552
subscribe/<
node_modules/react-relay-network-modern/node8/RelayNetworkLayer.js:59`
 
## Additional information

none

**Comment by SamuelHassine** [comment]
Hello @cyb3rfox,

Your development environment is perfectly running :) It's just in the login page. Close the error on the frontend using the top right cross and then login.

![image](https://user-images.githubusercontent.com/1334279/106740550-dabe0080-661a-11eb-9726-3e214b3c696a.png)

Kind regards,
Samuel

**Comment by cyb3rfox** [comment]
Awesome, that worked. I hope I get rid of the error when I push the changes to production though.
