### ISSUE TITLE
MISP integration is not working

### ISSUE THREAD

**Issue by oz17il** [OpenCTI-Platform/opencti#106]
Hi, 
The MISP integration is not working after the initial settings. (misp url, api key, tags. etc.)
Can't find any log event that indicates about the problem. 

Reproducible Steps
1. I validate that the misp.py is run without any issues directly from the CLI. 
2. Network connection from OpenCTI to MISP in port 443 is alright. 

Environment
1. OS Ubuntu 18.04
2. OpenCTI version: Version 1.0.1
3. Manual installation.

**Comment by AntoninHL** [comment]
same issue on my side with same verifications.

**Comment by SamuelHassine** [comment]
@oz17il, @weSh: could you please look at the log file `scheduler.log` in the `integration` docker (and the `/opt/opencti/integration` folder? You should have also a `/opt/opencti/integration/connectors/misp/misp.log` file.

**Comment by AntoninHL** [comment]
no log files for me...
Nothing you describe exists on my install

**Comment by oz17il** [comment]
> 
> 
> no log files for me...
> Nothing you describe exists on my install

also on my side ..

**Comment by SamuelHassine** [comment]
@oz17il, @weSh:

```
$ docker exec -ti openctidocker_integration_1 /bin/bash
$ cd /opt/opencti/integration
$ cat scheduler.log
$ cd connectors/misp
$ cat misp.log
```
Please provide us the content of these logs.

**Comment by AntoninHL** [comment]
For me:

scheduler.log:

```
[2019-07-02 08:36:41] Running misp
[2019-07-02 08:37:41] Configuring connectors
[2019-07-02 08:37:42] Connector misp configured
[2019-07-02 08:37:42] Connector mitre configured
[2019-07-02 08:37:42] Connector openctidata configured
[2019-07-02 08:37:42] Running misp
```

misp.log doesn't exists.

**Comment by SamuelHassine** [comment]
@weSh: your log is correct and no error. Do you tag an event in your MISP instance with the tag you specified in the configuration of your connector?

**Comment by AntoninHL** [comment]
@SamuelHassine 
yep.
In my MISP, I have: 
![image](https://user-images.githubusercontent.com/50768/60499160-30505f80-9cb8-11e9-893f-b5650ec38fca.png)

so in my configuration I put: OSINT

**Comment by SamuelHassine** [comment]
You have to put `type:OSINT` in your configuration.

**Comment by oz17il** [comment]
In my case I implemented OpenCti without docker. 
Logs not found:
$ cat scheduler.log
$ cat misp.log

**Comment by AntoninHL** [comment]
On my side it's ok now.
I think the issue with persistence was linked to this...
I'm not sure, but since the configuration works, MISP also works...

**Comment by oz17il** [comment]
> 
> 
> On my side it's ok now.
> I think the issue with persistence was linked to this...
> I'm not sure, but since the configuration works, MISP also works...

Can you explain what do you mean when you say persistence?

**Comment by SamuelHassine** [comment]
@oz17il: Is `scheduler.py` launched from the `integration` directory? You should have a `scheduler.log` in the same directory. Could you please try with the new release: https://github.com/OpenCTI-Platform/opencti/releases/download/1.0.1/opencti-release.tar.gz.

@oz17il: the persistence is just for ElasticSearch and Grakn running with Docker (for volumes).

**Comment by oz17il** [comment]
> 
> 
> @oz17il: Is `scheduler.py` launched from the `integration` directory? You should have a `scheduler.log` in the same directory. Could you please try with the new release: https://github.com/OpenCTI-Platform/opencti/releases/download/1.0.1/opencti-release.tar.gz.
> 
> @oz17il: the persistence is just for ElasticSearch and Grakn running with Docker (for volumes).

The scheduler.log not found.

I try to run the connectors_scheduler.py and I got this error:
root@:/opt/opencti/integration# python3 connectors_scheduler.py
[Errno 2] No such file or directory: '/opt/opencti/integration/config.yml'

**Comment by SamuelHassine** [comment]
@oz17il: According to [the documentation](https://opencti-platform.github.io/docs/installation/manual#configure-the-integration) you have to create the `config.yml` file. 

If you create this file, the connectors scheduler should work.

**Comment by SamuelHassine** [comment]
@oz17il : did you manage to make the scheduler working?

**Comment by oz17il** [comment]
> 
> 
> @oz17il : did you manage to make the scheduler working?

Hi, where can I find the values for the config.yml? 
api_url: 'http://REPLACE_API_URL'
api_key: 'REPLACE_API_KEY'

The log now looks ok but still no event from MISP: 
root@ip-xxxxx:/opt/opencti/integration# tail -f scheduler.log 
[2019-07-04 13:54:58] Updating connector config of misp...
[2019-07-04 13:54:59] Running misp
[2019-07-04 13:54:59] Connector mitre configured
[2019-07-04 13:54:59] Connector openctidata configured
[2019-07-04 13:54:59] Running misp
[2019-07-04 13:55:59] Configuring connectors
[2019-07-04 13:56:00] Connector misp configured
[2019-07-04 13:56:00] Connector mitre configured
[2019-07-04 13:56:00] Connector openctidata configured
[2019-07-04 13:56:00] Running misp

**Comment by SamuelHassine** [comment]
@oz17il: We just fully refactor the MISP connector and the way it communicates with our API. We will release this in a few hours.

**Comment by syloktools** [comment]
Question, when I try I get the following error:
```
[2019-07-05 18:51:40] Configuring connectors
[2019-07-05 18:51:40] You are not allowed to do this.
```

**Comment by Deventual** [comment]
Hi,

Any updates on this issue?
Our setup could import only 2 indicators from our misp instance.

**Comment by SamuelHassine** [comment]
Hi everyone,

We are working hard to fully refactor the connectors/schedulers/worker architecture for the next major release. Please see #121. For the moment, we just advise you to check the scheduler and the  worker log files.

**Comment by deyae-cyber** [comment]
Hello Community,
I am using the docker-compose file to run the the images and i want to know which version we can setup on the image line (opencti/connector-misp:{WHICH VERSION})
Thank you in advance
