### ISSUE TITLE
Platform initialization fail

### ISSUE THREAD

**Issue by KunwarAkanksha** [OpenCTI-Platform/opencti#1060]
{ I am trying to install the opencti manually with all the version is like the opencti website asked for }

1.Redis server v=6.0.10 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=48afb8ef69256162
2. nodejs --version = v12.20.1
3. minio version RELEASE.2021-02-01T22-56-52Z
4. rabbitmqctl version  3.8.11
5. python 3.6.9
6. elasticsearch 7.10.2

Still, I am getting an error to configure the environment. Please guide me in the right direction.

## Command
yarn serv 

yarn run v1.17.3
$ node build/index.js
{"version":"4.1.2","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-02-05T09:26:23.080Z"}
{"version":"4.1.2","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-02-05T09:26:23.102Z"}
{"version":"4.1.2","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-02-05T09:26:23.114Z"}
{"version":"4.1.2","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-02-05T09:26:23.185Z"}
{"version":"4.1.2","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-02-05T09:26:23.187Z"}
{"version":"4.1.2","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-02-05T09:26:23.452Z"}
{"version":"4.1.2","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2021-02-05T09:26:23.470Z"}
{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-02-05T09:26:23.471Z","data":{"reason":"You need to configure the environment vars","category":"technical"},"internalData":{}},"version":"4.1.2","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-02-05T09:26:23.471Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by richard-julien** [comment]
Hi @KunwarAkanksha ,

The error seems clear: "reason":"You need to configure the environment vars"
Please check the documentation: https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1#977f1beff2a247fc8bbba240c45673be
Double check your configuration.

**Comment by KunwarAkanksha** [comment]
I have gone through the whole doc but which env vars do I need to set is still not clear. There is no such mention of env vars in doc. /config/Production.json is updated as per the username and password though.

**Comment by KunwarAkanksha** [comment]
For manual installation I have no .env file in my opencti folder , though the config/production.json is configured correctly. So which variables do I need to set is still not clear. I am using opencti-4.1.2

**Comment by SamuelHassine** [comment]
Hello @KunwarAkanksha,

I think your production.json is not correct. The error you have comes from a check which verifies if:

- the ADMIN_TOKEN is a UUIDv4.
- the ADMIN_PASSWORD is not the default one.

Kind regards,
Samuel

**Comment by KunwarAkanksha** [comment]
Thanks a lot. This solved my issue.
