### ISSUE TITLE
Filtering based on area of concern & Watch List feature request

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1063]
This is more a "how to" request.
In OpenCTI dashboard, how to filter based on verticals and geoloc as the first priorities?
For example,
I would like to see all the threat feeds being filtered or prioritize based on Canada and Financial related threats. This is my area of concern and I would like to see all threats related to this criteria.

Feature Request:
Next, is OpenCTI the ability to do "watch list" - let's say I have list of "watch list" like "cisco ngfw model xxxx", "Apache tomcat", etc .. any IoCs related to these list I will be alerted and the dashboard should have a panel that display all your related IoC based on your "watch list".
In the dashboard, select IoC and add to your watch list also.

**Comment by SamuelHassine** [comment]
Subscription system has been developed.
