### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1064]
OS: Ubuntu 20
OpenCTI latest version (running on docker)

I don't see any heat map or map activities.
Where do I check if map is working or not?

![image](https://user-images.githubusercontent.com/20463433/107121578-37aaf800-6861-11eb-9ed8-778eda6a51b5.png)

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

The Map is based on STIX 2.1 `targets` relationships to countries. Do you have the `OpenCTI datasets` connector enabled? And another connector which gives you victimology?

Kind regards,
Samuel

**Comment by xme** [comment]
Same issue here... I don't see any connector related to datasets.

**Comment by SamuelHassine** [comment]
Hello,

To enable cartography, you have to:

1. Enable the `OpenCTI datasets` connector: https://github.com/OpenCTI-Platform/connectors/tree/master/opencti
2. Have some sources creating `target` relationships between "threats" (Intrusion-Sets, Malwares, Tools, Threat Actors, etc.) and countries.

Kind regards,
Samuel

**Comment by VaheOfficial** [comment]
Hello,

I have a similar issue. I already have the openCTI dataset connector connected and working. The issue I have is on the latest version with latest dataset connector it is unable to add country aliases. I understand thats what is needed to populate the heatmap. I already have datasets that associate the country codes with actual threats but as long as I cant add the aliases I wont be able to make those relationships. 

Is there a way to force aliases as ive tried manual country import and automated opencti dataset import. 

Thank you,
Vahe
