### ISSUE TITLE
Question : is there specific configuration documentation, tutorials for connectors importation, get started info ? 

### ISSUE THREAD

**Issue by Veve025** [OpenCTI-Platform/opencti#1065]
Hello,
I'm new in this community, just installed OpenCTI last few days, but the dashboard is definitely empty.
Unfortunately I'm not a developer and  my knowledge in Linux is a little bit morethan low.
After reading lots of links, articles etc, the last 3 days, I'm still wondering how to have a dashboard plenty of info and to have so, how to integrate Connectors : is there any tutorials ?
Is there any pre-configred package available to have the same dashboard as the demo, to have a ready-to-use solution to start with  ?
I'm bit frightened by the codes I can see in the detailed configuration (python ?).

Thanks for your help, I know these are certainly basic question but I really want to start with this tool.

Best regards,
Vévé

**Comment by eehP** [comment]
Hello, you can find all the documentation about connectors here :
https://github.com/OpenCTI-Platform/connectors

**Comment by manonviallet** [comment]
Good afternoon @Veve025 
Did the above answer helped you ?
Documentation on the project is still a work in progress and is also available here : https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518
You can also join the slack channel to have help and feedback from the community.
If it answered your question, I will close this issue.

**Comment by Veve025** [comment]
Hello,

Thanks a lot for taking care of the follow-up of the related subject !
Unfortunately the documentation didn't answer my needs and is maybe very
complex to put Open-CTI up and running for everyone. I would maybe just
have expected a description of how the application would run, the links
between modules and how to implement them, maybe to better understand the
technical notes.
I believe this application is a real extraordinary one, and I'm quite
frustrated to not be able to deploy it :(, despite my knowledge in IT &
security.
I really wish and cross the fingers the docs will evolve to allow me in a
close future to put hands-on this amazing-breaking app.

Thanks a lot !
Vévé


Le jeu. 8 juil. 2021 à 16:45, manonviallet ***@***.***> a
écrit :

**Comment by SamuelHassine** [comment]
Closing this question as the documentation is now way more advanced.
