### ISSUE TITLE
Docker documentation persistance data

### ISSUE THREAD

**Issue by b4b857f6ee** [OpenCTI-Platform/opencti#107]
Hello,
I am not an expert in Docker.
Regarding the Data persistence.
I manage to add in the service section what the documentation say but just after the docker-compose up, i get an error. 
I think i have to add the volume in other section of the docker-compose.yaml. 
I find others "volumes" section but i didn't manage to write it clearly.
Can you do something with more description :).

Error message "Named volume "esdata:/usr....data:rw" is used in service "elasticsearch" but no declaration was found in the volumes section"

Docker 1.0.1

**Comment by AntoninHL** [comment]
Hey,

just follow the issue #100 ;-)

**Comment by SamuelHassine** [comment]
@b4b857f6ee: I just pushed to the `master` branch of this repository a working configuration with the Docker volumes. This should work :)

**Comment by b4b857f6ee** [comment]
Oh i just find the older issue. Sorry #100

**Comment by AntoninHL** [comment]
I think you can close this issue.
#100 is here for all answers

**Comment by b4b857f6ee** [comment]
I got my answer from another but yes :)
