### ISSUE TITLE
Indicator Toggle when Creating File Observable doesn't Generate an Indicator

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1070]
## Description

Upon creating an Observable, there is an option to create an Indicator based on the Observable properties. This functionality doesn't work (or, at least, the Indicator isn't visible in the Indicator page).

This appears to be specific to File Observables, and possibly others. IP Observables seem to generate indicators properly

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.0.4
2. OpenCTI version: OpenCTI 4.1.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create File observable
2. Set value to be "test.txt"
3. Toggle "Create an indicator from this observable" switch at the bottom of the "Create an observable" box
4. Navigate to Observations -> Indicators page

## Expected Output

The resulting indicator should be visible in the Indicators page.

## Actual Output

No new visible indicator is created

**Comment by CedBlandam** [comment]
I'm experiencing the same issue dealing with "File" observable type. The indicator is not created when toggling "Create an indicator from this observable" on the Observable creation box
