### ISSUE TITLE
No way to implement STIX's Windows Service (and Process) extensions

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1071]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

There is not good way to input malicious services into OpenCTI

## Current Workaround

n/a

## Proposed Solution

Implement STIX's Windows Service extension

**Comment by SamuelHassine** [comment]
* windows-process-ext
* windows-service-ext
