### ISSUE TITLE
Be able to click on visuals throughout the plateform

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1073]
## Problem to Solve

It would be useful to be able to click on a display and access directly the entity's page. 
For instance : 
- on the welcome board, for the visual " top 10 of active entities in the last 3 months" --> if I have "emotet" on a ligne, be able to click on emotet and land on the "malware" page of emotet. 
- on the maps, be able to click on the countries and access the page.
Etc.

**Comment by manonviallet** [comment]
Edit for the attack matrices visual in attack patterns: in V5, the box is clickable, but send the user on the technic description, it does not allow the user to visualize the relation, whereas in kill chain view, it is the relation of use which is displayed. It would be better to have the same for both, and to visualize the relation every time

**Comment by manonviallet** [comment]
This would also be useful for knowledge overview pages, to be able to able to:
- click on "total reports" and land on analysis (same for indicators)
- click on a box on the distribution of relation to go to the type of entity within the object
- maybe be able to click on the graph of authors repartition and access to analysis but with a filter with this author pre-set

![Capture d’écran du 2021-10-26 11-14-24](https://user-images.githubusercontent.com/49722941/138848730-d7590ec3-ab92-417c-97f4-355a93550ea3.png)

**Comment by SamuelHassine** [comment]
First scope of this feature is:

* Related to #1770, on maps, be able to click on Region => go on the Region page
* On horizontal bars, when representing an entity, be able to click => go on the Entity page

**Comment by SamuelHassine** [comment]
Splitting this issue into multiple features to make a smooth transition.
