### ISSUE TITLE
Implement the registration system for new users

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#108]
## Problem to Solve

Currently, only already created users or persons who have a Github/Facebook/Google account can login. If administrators of a platform want to open it to new users, a registration system should allow this.

## Current Workaround

None.

## Proposed Solution

Implement a registration system for new users.

## Additional Information

None.

**Comment by richard-julien** [comment]
I think we can postpone that and do ldap configuration first.

**Comment by SamuelHassine** [comment]
Will use SSO everywhere, no registration system is planned. If you are a community user and really need this feature, please create a new one and refer to this one.
