### ISSUE TITLE
Start OpenCTI using Systemd

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1083]
Hello,

I have successfully installed and started OpenCTI [Issue #1054]
I'm trying to start it as a service.

I have created ct-start.sh:
```
#!/bin/sh

# Correct working directory
cd /home/cti/opencti/

# Start CTI
yarn serv
```
And I tested it, working great.

But when I created a service to call it, it fails:

cti.service:
```
[Unit]
Description=X-CTI
After=network.target

[Service]
User=cti
Group=cti
WorkingDirectory=/home/cti/opencti/
Environment="/home/cti/opencti/"
ExecStart=/home/cti/opencti/ct-start.sh

[Install]
WantedBy=multi-user.target
```
Status:
```
root@cti:/etc/systemd/system# systemctl status cti.service
● cti.service - X-CTI
   Loaded: loaded (/etc/systemd/system/cti.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-02-15 08:55:02 UTC; 7min ago
  Process: 83380 ExecStart=/home/cti/opencti/ct-start.sh (code=exited, status=203/EXEC)
 Main PID: 83380 (code=exited, status=203/EXEC)

Feb 15 08:55:02 cti systemd[1]: Started X-CTI.
Feb 15 08:55:02 cti systemd[83380]: cti.service: Failed to execute command: Exec format error
Feb 15 08:55:02 cti systemd[83380]: cti.service: Failed at step EXEC spawning /home/cti/opencti/ct-start.sh: Exec format error
Feb 15 08:55:02 cti systemd[1]: cti.service: Main process exited, code=exited, status=203/EXEC
Feb 15 08:55:02 cti systemd[1]: cti.service: Failed with result 'exit-code'.
```
Any advices?

Regards,
Khalid

**Comment by eehP** [comment]
Don't you have miss the Service type ?
[Service]
Type=simple # Another Type: forking

**Comment by khalidrehan** [comment]
> Don't you have miss the Service type ?
> [Service]
> Type=simple # Another Type: forking

I've tried:
`Type=oneshot`, and it failed.

I will try `Type=simple`

Regards,
Khalid

**Comment by khalidrehan** [comment]
> > Don't you have miss the Service type ?
> > [Service]
> > Type=simple # Another Type: forking
> 
> I've tried:
> `Type=oneshot`, and it failed.
> 
> I will try `Type=simple`
> 
> Regards,
> Khalid

It did not work.

**Comment by eehP** [comment]
Try : ExecStart=/home/cti/opencti/yarn serv

**Comment by khalidrehan** [comment]
> Try : ExecStart=/home/cti/opencti/yarn serv

It did not work, this was the first thing I tried..
Yarn command must run inside the `~/opencti` directory, otherwise it won't work.
I tried using `yarn --cwd /path/to/package.json` , and it did not work as well.

**Comment by JeromeSRT** [comment]
> > Try : ExecStart=/home/cti/opencti/yarn serv
> 
> 
> 
> It did not work, this was the first thing I tried..
> 
> Yarn command must run inside the `~/opencti` directory, otherwise it won't work.
> 
> I tried using `yarn --cwd /path/to/package.json` , and it did not work as well.

Hello,

I made use of OpenCTI on Ubuntu 20, and ran OpenCTI as a service with systemd.
If you want, i can send you the files for systemd.

My mail yeyaleliahhel@gmail.com

**Comment by eehP** [comment]
Please share the file here, i'm sure it will be helpful for other.

**Comment by JeromeSRT** [comment]
> Please share the file here, i'm sure it will be helpful for other.

How can i share the files here ?

**Comment by JeromeSRT** [comment]
> Please share the file here, i'm sure it will be helpful for other.

1. OpenCTI Platform Start Script

```

#!/bin/bash
#
#
#Script Lancement Platform / Workers / Connectors OpenCTI
#
#
#Lancement Platform OpenCTI
#
if [ `netstat -lnp | grep tcp | grep 4000 | grep node | wc -l` = 0 ] ; then
	cd /usr/share/opencti
	if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-platfrom.log ] ; then
		touch /var/log/opencti/`date +%Y%m%d`_opencti-platform.log
	fi
	touch /tmp/opencti-platform.pid
	yarn serv 1>>/var/log/opencti/`date +%Y%m%d`_opencti-platform.log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-platform.log &
	echo $! >> /tmp/opencti-platform.pid
#
#
#Vérification Ecoute Port Plateforme OpenCTI
#
	while [ `netstat -lnp | grep tcp | grep 4000 | grep LISTEN | grep node | wc -l` = 0 ] ; do
#		sleep 0.5
	done
#
#
#Lancement Workers OpenCTI
#
	cd /usr/share/opencti
	for ((i = 1 ; i <= 10 ; i++)) ; do
		if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log ] ; then
			touch /var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log
		fi
		touch /tmp/opencti-worker-"$i".pid
		python3 ./worker/worker.py 1>>/var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log &
		echo $! >> /tmp/opencti-worker-"$i".pid
	done
#
#
#Lancement Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
#
	cd /usr/share/opencti
	for con in "export-file-stix" "import-file-pdf-observables" "import-file-stix" ; do
		for rep in `ls ./connectors | grep "$con"` ; do
			if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log ] ; then
				touch /var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log
			fi
			touch /tmp/opencti-"$rep".pid
			python3 ./connectors/"$rep"/src/"$rep".py 1>>/var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log &
			echo $! >> /tmp/opencti-"$rep".pid
		done
	done
fi
#
#
#

```


2. OpenCTI Platform Stop Script

```

#!/bin/bash
#
#
#Script Arret Connectors / Workers / Platform OpenCTI
#
#
#Arret Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
#
if [ `netstat -lnp | grep tcp | grep 4000 | wc -l` != 0 ] ; then
	cd /usr/share/opencti
	for con in export-file-stix import-file-pdf-observables import-file-stix ; do
		for fic in `ls /tmp | grep "$con"` ; do
			if [ -f /tmp/"$fic" ] ; then
				echo "fichier-$fic"
				kill -s TERM `cat /tmp/"$fic"`
			fi
		done
	done
#
#
#Arret Workers OpenCTI
#
	cd /usr/share/opencti
	for ((i = 1 ; i <= 10 ; i++)) ; do
		if [ -f /tmp/opencti-worker-"$i".pid ] ; then
			echo "fichier-worker-$i"
			kill -s TERM `cat /tmp/opencti-worker-"$i".pid`
		fi
	done
#
#
#Arret Platform OpenCTI
#
	cd /usr/share/opencti
	if [ -f /tmp/opencti-platform.pid ] ; then
		echo "fichier-opencti-platform"
		kill -s TERM `cat /tmp/opencti-platform.pid`
	fi
fi

```

3. OpenCTI Platform Ubuntu Systemd File

```

[Unit]
Description=OpenCTI Platform
After=network-online.target elasticsearch.service minio.service redis-server.service rabbitmq-server.service
Wants=network-online.target
Requires=elasticsearch.service minio.service redis-server.service rabbitmq-server.service

[Service]
Type=forking

User=opencti
Group=opencti

ExecStart=/usr/share/opencti/01-Start-OpenCTI-Platform
#ExecStop=/usr/share/opencti/02-Stop-OpenCTI-Platform

WorkingDirectory=/usr/share/opencti

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target

```

Sorry i did not find how to upload the files here...

**Comment by khalidrehan** [comment]
> > Please share the file here, i'm sure it will be helpful for other.
> 
> 1. OpenCTI Platform Start Script
> 
> ```
> 
> #!/bin/bash
> #
> #
> #Script Lancement Platform / Workers / Connectors OpenCTI
> #
> #
> #Lancement Platform OpenCTI
> #
> if [ `netstat -lnp | grep tcp | grep 4000 | grep node | wc -l` = 0 ] ; then
> 	cd /usr/share/opencti
> 	if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-platfrom.log ] ; then
> 		touch /var/log/opencti/`date +%Y%m%d`_opencti-platform.log
> 	fi
> 	touch /tmp/opencti-platform.pid
> 	yarn serv 1>>/var/log/opencti/`date +%Y%m%d`_opencti-platform.log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-platform.log &
> 	echo $! >> /tmp/opencti-platform.pid
> #
> #
> #Vérification Ecoute Port Plateforme OpenCTI
> #
> 	while [ `netstat -lnp | grep tcp | grep 4000 | grep LISTEN | grep node | wc -l` = 0 ] ; do
> #		sleep 0.5
> 	done
> #
> #
> #Lancement Workers OpenCTI
> #
> 	cd /usr/share/opencti
> 	for ((i = 1 ; i <= 10 ; i++)) ; do
> 		if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log ] ; then
> 			touch /var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log
> 		fi
> 		touch /tmp/opencti-worker-"$i".pid
> 		python3 ./worker/worker.py 1>>/var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-worker-"$i".log &
> 		echo $! >> /tmp/opencti-worker-"$i".pid
> 	done
> #
> #
> #Lancement Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
> #
> 	cd /usr/share/opencti
> 	for con in "export-file-stix" "import-file-pdf-observables" "import-file-stix" ; do
> 		for rep in `ls ./connectors | grep "$con"` ; do
> 			if [ ! -f /var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log ] ; then
> 				touch /var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log
> 			fi
> 			touch /tmp/opencti-"$rep".pid
> 			python3 ./connectors/"$rep"/src/"$rep".py 1>>/var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log 2>>/var/log/opencti/`date +%Y%m%d`_opencti-"$rep".log &
> 			echo $! >> /tmp/opencti-"$rep".pid
> 		done
> 	done
> fi
> #
> #
> #
> ```
> 
> 1. OpenCTI Platform Stop Script
> 
> ```
> 
> #!/bin/bash
> #
> #
> #Script Arret Connectors / Workers / Platform OpenCTI
> #
> #
> #Arret Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
> #
> if [ `netstat -lnp | grep tcp | grep 4000 | wc -l` != 0 ] ; then
> 	cd /usr/share/opencti
> 	for con in export-file-stix import-file-pdf-observables import-file-stix ; do
> 		for fic in `ls /tmp | grep "$con"` ; do
> 			if [ -f /tmp/"$fic" ] ; then
> 				echo "fichier-$fic"
> 				kill -s TERM `cat /tmp/"$fic"`
> 			fi
> 		done
> 	done
> #
> #
> #Arret Workers OpenCTI
> #
> 	cd /usr/share/opencti
> 	for ((i = 1 ; i <= 10 ; i++)) ; do
> 		if [ -f /tmp/opencti-worker-"$i".pid ] ; then
> 			echo "fichier-worker-$i"
> 			kill -s TERM `cat /tmp/opencti-worker-"$i".pid`
> 		fi
> 	done
> #
> #
> #Arret Platform OpenCTI
> #
> 	cd /usr/share/opencti
> 	if [ -f /tmp/opencti-platform.pid ] ; then
> 		echo "fichier-opencti-platform"
> 		kill -s TERM `cat /tmp/opencti-platform.pid`
> 	fi
> fi
> ```
> 
> 1. OpenCTI Platform Ubuntu Systemd File
> 
> ```
> 
> [Unit]
> Description=OpenCTI Platform
> After=network-online.target elasticsearch.service grakn-core.service minio.service redis-server.service rabbitmq-server.service
> Wants=network-online.target
> Requires=elasticsearch.service grakn-core.service minio.service redis-server.service rabbitmq-server.service
> 
> [Service]
> Type=forking
> 
> User=opencti
> Group=opencti
> 
> ExecStart=/usr/share/opencti/01-Start-OpenCTI-Platform
> #ExecStop=/usr/share/opencti/02-Stop-OpenCTI-Platform
> 
> WorkingDirectory=/usr/share/opencti
> 
> StandardOutput=journal
> StandardError=journal
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Sorry i did not find how to upload the files here...

@JeromeSRT Thank you for sharing :) ..
I'm going to test asap and post my feedback here..

**Comment by khalidrehan** [comment]
@JeromeSRT 
Thank you for sharing :) ..
I'm going to test asap and post my feedback here..

**Comment by khalidrehan** [comment]
@JeromeSRT 
I believe I have to install grakn-core.service as a perquisite, right?

**Comment by JeromeSRT** [comment]
> @JeromeSRT 
> 
> I believe I have to install grakn-core.service as a perquisite, right?
> 
> 

For OpenCTI V4, grakn-core is not needed so you can erase grain-core.service from the lines "After=" and "Requires=".

I updated the OpenCTI Platform Ubuntu Systemd File.

**Comment by khalidrehan** [comment]
> > @JeromeSRT
> > I believe I have to install grakn-core.service as a perquisite, right?
> 
> For OpenCTI V4, grakn-core is not needed

Yes, I'm using v4.1..

**Comment by JeromeSRT** [comment]
> > > @JeromeSRT
> 
> > > I believe I have to install grakn-core.service as a perquisite, right?
> 
> > 
> 
> > For OpenCTI V4, grakn-core is not needed
> 
> 
> 
> Yes, I'm using v4.1..

For OpenCTI V4, grakn-core is not needed so you can erase grain-core.service from the lines "After=" and "Requires=".

I updated the OpenCTI Platform Ubuntu Systemd File.

**Comment by khalidrehan** [comment]
> > > > @JeromeSRT
> > 
> > 
> > > > I believe I have to install grakn-core.service as a perquisite, right?
> > 
> > 
> > > 
> > 
> > 
> > > For OpenCTI V4, grakn-core is not needed
> > 
> > 
> > Yes, I'm using v4.1..
> 
> For OpenCTI V4, grakn-core is not needed so you can erase grain-core.service from the lines "After=" and "Requires=".
> 
> I updated the OpenCTI Platform Ubuntu Systemd File.

Noted..
Thanks!

**Comment by khalidrehan** [comment]
@JeromeSRT 
I applied it, with un-hashing the ExecStop script..

```
root@cti:/home/cti# systemctl status cti
● cti.service - X-CTI Platform
   Loaded: loaded (/etc/systemd/system/cti.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-02-17 14:01:45 UTC; 9s ago
  Process: 4104 ExecStart=/usr/share/opencti/cti-start.sh (code=exited, status=0/SUCCESS)
    Tasks: 45 (limit: 19146)
   CGroup: /system.slice/cti.service
           ├─4133 node /usr/share/yarn/bin/yarn.js serv
           ├─4185 /bin/sh -c node build/index.js
           ├─4186 /usr/bin/node build/index.js
           ├─4606 python3 ./worker/worker.py
           ├─4611 python3 ./worker/worker.py
           ├─4616 python3 ./worker/worker.py
           ├─4621 python3 ./worker/worker.py
           ├─4626 python3 ./worker/worker.py
           ├─4631 python3 ./worker/worker.py
           ├─4636 python3 ./worker/worker.py
           ├─4641 python3 ./worker/worker.py
           ├─4646 python3 ./worker/worker.py
           ├─4650 python3 ./worker/worker.py
           ├─4659 python3 ./connectors/export-file-stix/src/export-file-stix.py
           └─4675 python3 ./connectors/import-file-stix/src/import-file-stix.py

Feb 17 14:01:43 cti cti-start.sh[4104]:  will not be shown, you would have to be root to see it all.)
Feb 17 14:01:43 cti cti-start.sh[4104]: (Not all processes could be identified, non-owned process info
Feb 17 14:01:43 cti cti-start.sh[4104]:  will not be shown, you would have to be root to see it all.)
Feb 17 14:01:44 cti cti-start.sh[4104]: (Not all processes could be identified, non-owned process info
Feb 17 14:01:44 cti cti-start.sh[4104]:  will not be shown, you would have to be root to see it all.)
Feb 17 14:01:45 cti cti-start.sh[4104]: (Not all processes could be identified, non-owned process info
Feb 17 14:01:45 cti cti-start.sh[4104]:  will not be shown, you would have to be root to see it all.)
Feb 17 14:01:45 cti cti-start.sh[4104]: (Not all processes could be identified, non-owned process info
Feb 17 14:01:45 cti cti-start.sh[4104]:  will not be shown, you would have to be root to see it all.)
Feb 17 14:01:45 cti systemd[1]: Started CTI Platform.
```

Thank you so much 👍 👍 💯

**Comment by khalidrehan** [comment]
10 workers started, but none of the connectors, any advise?
@JeromeSRT

**Comment by JeromeSRT** [comment]
> 10 workers started, but none of connectors, any advise?
> 
> @JeromeSRT 

You need to configure the config.yml of your connectors :
- make use of an user or admin token in the token field,
- make use of an UUID identifier in the id field.

Check the token and id fields in the config.yml file of connectors and workers.

User and admin tokens are generated by OpenCTI Platform when you create a user in the OpenCTI Platform.

Enjoy,

**Comment by khalidrehan** [comment]
Hi @JeromeSRT 
It worked, but I had to change ```for rep in `ls ./connectors | grep "$con"` ; do``` to ```for rep in `ls ./connectors` ; do``` in the start script.

**Comment by allexBR** [comment]
Hi guys!

Hope you all are doing well!

I am trying to use this script to start my OpenCTI instance as a system service, but I have not been successful yet.

In my case, the application is installed in /var/opencti and I have already changed this in the script.

Is there anything else I should do?



opencti 01-Start-OpenCTI-Platform[2921]:  will not be shown, you would have to be root to see it all.)
opencti 01-Start-OpenCTI-Platform[2924]: (Not all processes could be identified, non-owned process info
opencti 01-Start-OpenCTI-Platform[2924]:  will not be shown, you would have to be root to see it all.)
opencti 01-Start-OpenCTI-Platform[2927]: (Not all processes could be identified, non-owned process info
opencti 01-Start-OpenCTI-Platform[2927]:  will not be shown, you would have to be root to see it all.)
opencti systemd[1]: opencti.service: start operation timed out. Terminating.
opencti systemd[1]: opencti.service: Failed with result 'timeout'.
opencti systemd[1]: Failed to start opencti.service - OpenCTI Platform.
opencti systemd[1]: opencti.service: Consumed 7.760s CPU time.



Regards,
Allex

**Comment by JeromeSRT** [comment]
> Hi guys!
> 
> Hope you all are doing well!
> 
> I am trying to use this script to start my OpenCTI instance as a system service, but I have not been successful yet.
> 
> In my case, the application is installed in /var/opencti and I have already changed this in the script.
> 
> Is there anything else I should do?
> 
> opencti 01-Start-OpenCTI-Platform[2921]: will not be shown, you would have to be root to see it all.) opencti 01-Start-OpenCTI-Platform[2924]: (Not all processes could be identified, non-owned process info opencti 01-Start-OpenCTI-Platform[2924]: will not be shown, you would have to be root to see it all.) opencti 01-Start-OpenCTI-Platform[2927]: (Not all processes could be identified, non-owned process info opencti 01-Start-OpenCTI-Platform[2927]: will not be shown, you would have to be root to see it all.) opencti systemd[1]: opencti.service: start operation timed out. Terminating. opencti systemd[1]: opencti.service: Failed with result 'timeout'. opencti systemd[1]: Failed to start opencti.service - OpenCTI Platform. opencti systemd[1]: opencti.service: Consumed 7.760s CPU time.
> 
> Regards, Allex

Hello,

First, i think you need to specify the User/Group owner of the /var/opencti in the systemd file.
Second, you have to specify RabbitMQ, MinIO, redis and elasticsearch services in the « After » parameter in the systemd file : OpenCTI needs these services to run.

Regards, Jerome

**Comment by allexBR** [comment]
> > Hi guys!
> > Hope you all are doing well!
> > I am trying to use this script to start my OpenCTI instance as a system service, but I have not been successful yet.
> > In my case, the application is installed in /var/opencti and I have already changed this in the script.
> > Is there anything else I should do?
> > opencti 01-Start-OpenCTI-Platform[2921]: will not be shown, you would have to be root to see it all.) opencti 01-Start-OpenCTI-Platform[2924]: (Not all processes could be identified, non-owned process info opencti 01-Start-OpenCTI-Platform[2924]: will not be shown, you would have to be root to see it all.) opencti 01-Start-OpenCTI-Platform[2927]: (Not all processes could be identified, non-owned process info opencti 01-Start-OpenCTI-Platform[2927]: will not be shown, you would have to be root to see it all.) opencti systemd[1]: opencti.service: start operation timed out. Terminating. opencti systemd[1]: opencti.service: Failed with result 'timeout'. opencti systemd[1]: Failed to start opencti.service - OpenCTI Platform. opencti systemd[1]: opencti.service: Consumed 7.760s CPU time.
> > Regards, Allex
> 
> Hello,
> 
> First, i think you need to specify the User/Group owner of the /var/opencti in the systemd file. Second, you have to specify RabbitMQ, MinIO, redis and elasticsearch services in the « After » parameter in the systemd file : OpenCTI needs these services to run.
> 
> Regards, Jerome


Hi, @JeromeSRT.

Here are my current settings:

![Image](https://github.com/user-attachments/assets/c5a5804b-88ab-4d82-8d3d-ce47013198a7)

![Image](https://github.com/user-attachments/assets/66d46856-d1a4-4096-a9dc-0d57ab743a38)

![Image](https://github.com/user-attachments/assets/1661d22d-470f-4f45-ac8a-b712204902f7)

![Image](https://github.com/user-attachments/assets/cb6be4a3-ee39-44c3-9647-385475418f9a)

![Image](https://github.com/user-attachments/assets/98af9978-63b3-43fb-bab7-9bf1ecebb07e)

![Image](https://github.com/user-attachments/assets/e435d258-2e0b-454a-8839-aa2e8945609a)

![Image](https://github.com/user-attachments/assets/1061f6b7-f649-465c-a9dd-f65c536c819a)


I believe the settings are OK, but I don't know what else is missing to make it work.

Is there anything else I should do?


Regards,
Allex

**Comment by JeromeSRT** [comment]
Hi, @allexBR,
Where are the opencti logs ?
Try to find a how to about systemd configuration.

May be the user/group of the /var/opencti directory must be the same as the elasticsearch directory.

Best regards

**Comment by allexBR** [comment]
> Hi, [@allexBR](https://github.com/allexBR), Where are the opencti logs ? Try to find a how to about systemd configuration.
> 
> May be the user/group of the /var/opencti directory must be the same as the elasticsearch directory.
> 
> Best regards


Hi, @JeromeSRT,

I made some revisions to the settings, including the script you developed, and now everything is OK.

It works great now!

![Image](https://github.com/user-attachments/assets/6f566e22-3f67-49b9-99dd-423a70b8db47)


Thank you very much for your attention.

Best regards,

**Comment by JeromeSRT** [comment]
Hi, @allexBR,

Have fun with OpenCTI...

Best regards,
