### ISSUE TITLE
The items "Countries" and "Sectors" should be present in the right menu of an Organisation

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#1085]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When on the page of an Organisation, we can see that there are relations to countries and to sectors for that specific organisation, but we can't see which those countries or sectors are. 

## Current Workaround

There is no workaround. The relation between the organisation and the country/sectors exists, but it is not possible to visualise it. 

## Proposed Solution

In the right menu, to add the items 
- Countries
- Sectors
See the image attached.
## Additional Information

![img1](https://user-images.githubusercontent.com/65337190/107963159-173d1500-6fa8-11eb-8278-1b2e44430808.png)

**Comment by maertv** [comment]
Perhaps instead of countries it should be locations, in case the organization is located for example in a region.

Should it be countries (or countries and regions) or locations?

**Comment by csandu-certeu** [comment]
Right, it can be Locations. Good point
