### ISSUE TITLE
Newly created Marking Definitions can't be accessed when creating/editing objects

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1086]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

A user is able to create a new marking definition. However, the new marking definition doesn't show up as an option when trying to assign it to a newly created/already existing object.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.4
2. OpenCTI version: OpenCTI 4.2.2
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new Marking Definition "testMark"
2. Create a new Observable or SDO
3. Assign the marking definition "testMark" to the new object

## Expected Output

A user sees the new marking definition, and can select it

## Actual Output

The new marking definition does not appear in the list of available marking definitions

**Comment by SamuelHassine** [comment]
Hello,

To have it in the proposed markings when creating/updating an object, the new markings must be added in the permissions of the current user's group.

Kind regards,
Samuel

**Comment by securitiz** [comment]
Thank you Samuel! Closing this issue.
