### ISSUE TITLE
Missing reference to handle creation

### ISSUE THREAD

**Issue by eehP** [OpenCTI-Platform/opencti#1087]
## Description

{ I'm running AlienVault Connector and after 13k indicators my worker display this
 ERROR:root:{'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}
INFO:root:Report expectation for opencti-work--a4d7d316-0267-43ef-81ae-d36fb5639d4d
ERROR:root:Error updating elastic
ERROR:root:Cannot report expectation
INFO:root:Message processed, thread terminated
INFO:root:Message (delivery_tag=118) acknowledged
INFO:root:Processing a new message (delivery_tag=119), launching a thread...
INFO:root:Creating stix_core_relationship {indicator--beb7b136-6f86-11eb-8a33-08002789e100, malware--be8e8fcc-6f86-11eb-8a33-08002789e100}.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=119) reprocess (retry nb: 1)
INFO:root:Creating stix_core_relationship {indicator--beb7b136-6f86-11eb-8a33-08002789e100, malware--be8e8fcc-6f86-11eb-8a33-08002789e100}.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=119) reprocess (retry nb: 2)
INFO:root:Creating stix_core_relationship {indicator--beb7b136-6f86-11eb-8a33-08002789e100, malware--be8e8fcc-6f86-11eb-8a33-08002789e100}.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=119) reprocess (retry nb: 3)
INFO:root:Creating stix_core_relationship {indicator--beb7b136-6f86-11eb-8a33-08002789e100, malware--be8e8fcc-6f86-11eb-8a33-08002789e100}.
ERROR:root:Missing reference to handle creation
INFO:root:Message (delivery_tag=119) reprocess (retry nb: 4)
INFO:root:Creating stix_core_relationship {indicator--beb7b136-6f86-11eb-8a33-08002789e100, malware--be8e8fcc-6f86-11eb-8a33-08002789e100}.
ERROR:root:Missing reference to handle creation}

## Environment

1. OS (where OpenCTI server runs): {Debian Buster. }
2. OpenCTI version: { OpenCTI 4.2.1 }
3. OpenCTI client: { frontend }
4. Other environment details:

**Comment by eehP** [comment]
Hello,
I assume this error is related to Disk free space as it occurs on a 97% full disk. When new free space is added and all current job killed, everything run smooth again.

**Comment by mwatermolen** [comment]
Hey All, Im bumping this As I believe its related to https://github.com/OpenCTI-Platform/client-python/issues/175
