### ISSUE TITLE
Export feed / stream from OpenCTI 

### ISSUE THREAD

**Issue by azzarin** [OpenCTI-Platform/opencti#1088]
This is might be a question as well as a feature request. Would like to use OpenCTI as a platform for all CTI information and make firewalls and other security systems subscribe to a feed from OpenCTI so it can automatically block known bad stuff. 

More or less like a taxii server. Would love to see the feed have different formats. but freetxt, CSV and Stix2 would work just fine. 
Is this possible today ? 

Is it possible to make this feature ? it would be really helpful and nice. Not needing to export manually and apply to security appliances would be great! incidents would be enough i belive.

**Comment by eehP** [comment]
Hello, as mentionned in the readme:
OpenCTI not only allows imports but also exports of data under different formats (CSV, STIX2 bundles, etc.). Connectors are currently developed to accelerate interactions between the tool and other platforms.

**Comment by richard-julien** [comment]
Hi @azzarin ,

Today OpenCTI exposes a data stream with Redis that any platform can consume. (take a look to the history connector)
We also expose data through our GraphQL API. 
A taxii2 api is currently in development.

**Comment by azzarin** [comment]
> Hi @azzarin ,
> 
> Today OpenCTI exposes a data stream with Redis that any platform can consume. (take a look to the history connector)
> We also expose data through our GraphQL API.
> A taxii2 api is currently in development.

Thank you, just what i wanted to hear. I believe we will continue setting up OpenCTI and try using Redis before the Taxii api is available. Is there any road map for that?

**Comment by richard-julien** [comment]
Im currently implementing it. Cant commit on a date for now, still early stage.

**Comment by SamuelHassine** [comment]
The TAXII2 API endpoints are part of the last stable release. More export connectors will be developed for SIEMs and other tools.

**Comment by trappersec** [comment]
Hi all,

How would I go about getting the feeds into SIEM? In my the best way to do this is just link it to the taxi server hostname (URL). Could someone give me some pointers please ? Much appreciated.

**Comment by LiamWBA** [comment]
@trappersec Also looking to work out how to export feeds into SIEM. Have you managed to find any solutions?
