### ISSUE TITLE
Import is really really slow

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/opencti#109]
I started MISP import since 3 hours...
Only 268 observables, 1 report and 5 entities...
😯
Is it normal?

**Comment by SamuelHassine** [comment]
@weSh: depending on your hardware but we are aware of that. Our next priority is to provide statistics and status for all connectors and progress of integration and implement parallel insertions. We will keep you informed on this issue on the progresses we made on it in the next days.

**Comment by AntoninHL** [comment]
👍

**Comment by AntoninHL** [comment]
1471 observables in 22 hours...
😥

![image](https://user-images.githubusercontent.com/50768/60576328-7d4a3980-9d7d-11e9-8d56-e26896291343.png)

**Comment by SamuelHassine** [comment]
@weSh: we found a quick solution to enhance the MISP connector and speed-up the ingestion speed.

**Comment by AntoninHL** [comment]
@SamuelHassine Good news!
I can't wait to try it!
😉

**Comment by SamuelHassine** [comment]
@weSh: you can follow the setup of this feature here in [this issue](https://github.com/OpenCTI-Platform/connectors/issues/9).

**Comment by AntoninHL** [comment]
@SamuelHassine 
A very strange thing: for some reasons, I must restart my server.
And after restart, MISP import restart at the begining... 😯
So, the last 28 hours passed to import 1450 observables are lost...
