### ISSUE TITLE
Notes web page is flashing...

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1092]
## Description

In "Notes" web page, there is a mistake with "Anstract" instead of "Abstract".
When i click on "Anstract", the web page is flashing.

## Environment

1. OS (where OpenCTI server runs): MacOS Big Sur 11.2.a
2. OpenCTI version: 4.2.2
3. OpenCTI client: frontend with Safari 14.0.3 or Firefox 85.0.2
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. On the left, click on "Analysis,
2. On the top, click on "Notes"
3. Then, click on "Anstract"
4. And the web page is flashing...

## Expected Output

The web page should not be flashing...

## Actual Output

The web page is flashing...
 
## Additional information

No additional information.

**Comment by eehP** [comment]
Hello,

Same

## Environment

1. OS (where OpenCTI server runs): Debian Buster
2. OpenCTI version: 4.2.1
3. OpenCTI client: FrontEnd Edge 88
4. Other environment details:
