### ISSUE TITLE
Grakn Storage Fails to Start when using Docker-Compose in Ubuntu

### ISSUE THREAD

**Issue by jeFF0Falltrades** [OpenCTI-Platform/opencti#110]
# Environment
* Ubuntu 19.04 (Disco Dingo)
* OpenCTI latest version (commit ce47de9228aa3c724d70029c4285ba04044da062)

# Reproducible Steps
Steps to create the smallest reproducible scenario:

`docker-compose up`

# Actual Output
```
grakn_1          | Starting Storage......FAILED!
grakn_1          | Unable to start Storage.
...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
...
```

# Relations
* Possibly related to #95, but a pull of the latest repo did not resolve the issue

# Description
It appears that something is causing Grakn storage startup to fail. 

I have not been able to find any logging by Grakn to show what exactly is causing the problem, but other posters with the same issue have suggested a problem with [memory allocation or the Java environment](https://discuss.grakn.ai/t/not-able-to-start-grakn-on-unix/685/3).

**Comment by richard-julien** [comment]
Seems to be a docker grakn issue. Can you confirm you have at least 4Go of memory available when you start the grakn docker image?

**Comment by jeFF0Falltrades** [comment]
Interestingly enough, the Grakn issue was resolved upon restarting the host machine running the Ubuntu VM I had OpenCTI running in.

Unfortunately, the app continues to hang when using docker-compose:

```
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for token in shared config...
```

**Comment by richard-julien** [comment]
Can you try to `docker-compose down -v` and the retry a docker-compose up with the latest release?

**Comment by SamuelHassine** [comment]
@jeFF0Falltrades: we just pushed an update of the Docker compose configuration. Could you please clear all Docker config (stop Docker daemon, rm -R /var/lib/docker/*, start Docker daemon) and pull the repository and retry?

**Comment by richard-julien** [comment]
Grakn part is resolved.
For the `Waiting for token in shared config.`, see https://github.com/OpenCTI-Platform/opencti/issues/119
