### ISSUE TITLE
Visualitation of Countries

### ISSUE THREAD

**Issue by Alfon-sec** [OpenCTI-Platform/opencti#1101]
## Description
Cant see the countries in the API

## Reproducible Steps
1. Go to the Countries window

## Expected Output
All countries should be seen

## Actual Output
No country is seen (even after creating a new one)

**Comment by SamuelHassine** [comment]
Hello @Alfon-sec,

Did you enable the "OpenCTI datasets" connector? This connector provides you with sectors and countries/regions.

By default, countries list is empty.

Kind regards,
Samuel

**Comment by Alfon-sec** [comment]
Hi @SamuelHassine !!
I might not explained myself correctly, what i mean is that even after creating and assigned countries to one intrusion-set, if i travel to the countries page i cannot see them, e.g. i can create a country named RU and assign it to an intrusion-set, but when traveling to countries i see nothing (even if i can see that RU exists and i can assign it to any intrusion-set)

**Comment by SamuelHassine** [comment]
Hello @Alfon-sec,

What is your version of OpenCTI, this may be a bug solved in the latest release.

Kind regards,
Samuel

**Comment by Alfon-sec** [comment]
Hi @SamuelHassine ,

pycti: 4.2.3
Opencti:  4.2.3

**Comment by SamuelHassine** [comment]
Hello @Alfon-sec,

Problems with all locations in OpenCTI have been definitely solved in OpenCTI 4.5.0. Please let us know if you still have any problem.

Kind regards,
Samuel
