### ISSUE TITLE
Problem creating indicators from obervables type file without hash also in 4.2.3

### ISSUE THREAD

**Issue by Alfon-sec** [OpenCTI-Platform/opencti#1102]
## Description
Thought that the issue https://github.com/OpenCTI-Platform/opencti/issues/1093#issue-809975142  was solved but when creating an observable type File with just a name via pycti or API, and selecting the option "Create an indicator from this observable" or "x_opencti_create_indicator=True" doesn't work.
## Reproducible Steps
1. Try to create a new observable via pycti or from the api
2. In pycti execute : 
observable = opencti_api_client.stix_cyber_observable.create(observableData={"type":"File", "name":"malicious_file.gz", **"x_opencti_create_indicator": True**})
3. In the API create a new observable, include a name **select "Create an indicator from this observable"**
## Expected Output
In both ways an observable and an indicator from the observable should be created

## Actual Output
Just the observable is created

**Comment by SamuelHassine** [comment]
Sorry for that, one use case has not been tested in the last version. The problem will be definitely solve in the next release.
