### ISSUE TITLE
Multiple login access

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1105]
Hello,

Is it possible to give access to multiple personal for OpenCTI with different level of privileges using LDAP integration or manual?

Regards,
Khalid.

**Comment by richard-julien** [comment]
Hi @khalidrehan,

Today you can configure different providers for the login. See https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#f8d2b2bae57b401ab0bebb8e18782696

You can't map your ldap groups in opencti groups for now, (issue already open). But you can define groups and capabilities that will be assign by default to the new user.

**Comment by khalidrehan** [comment]
> Hi @khalidrehan,
> 
> Today you can configure different providers for the login. See https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#f8d2b2bae57b401ab0bebb8e18782696
> 
> You can't map your ldap groups in opencti groups for now, (issue already open). But you can define groups and capabilities that will be assign by default to the new user.

Hi @richard-julien ,
Thanks for the reference!
Understood, I will try it.
Regards,
Khalid
