### ISSUE TITLE
Mitre connector wait  "IN PROGRESS" status

### ISSUE THREAD

**Issue by wallece55** [OpenCTI-Platform/opencti#1107]
## Description
I created MITRE connector with docker but any MITRE data not loading on OpenCTI. MITRE connector "IN PROGRESS" status waiting for the last 1 day.
## MITRE docker-compose.yml
version: '3'
services:
  connector-mitre:
    image: opencti/connector-mitre:4.2.3
    environment:
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=**********
      - CONNECTOR_ID=**********
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report,external-reference-as-report
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
      - MITRE_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
## Screenshot
![image](https://user-images.githubusercontent.com/42739042/108773445-6b7b6280-756f-11eb-90b3-cb27e228e3b0.png)

**Comment by richard-julien** [comment]
Hi @wallece55 , do you have any workers deployed?

**Comment by wallece55** [comment]
Yes, there are more than one worker installed. But all of them completed their or just like this "IN PROGRESS" status is waiting.
![image](https://user-images.githubusercontent.com/42739042/108882143-1f82f900-7615-11eb-8552-9cfad09b72e5.png)

**Comment by richard-julien** [comment]
Im not talking about connectors, but workers.
Workers are responsible to take the messages of the connectors in the queue and processed them.

![image](https://user-images.githubusercontent.com/285555/108882744-070ae280-7605-11eb-9ac9-530b53153f86.png)

**Comment by wallece55** [comment]
Oh okey i understand, 
![image](https://user-images.githubusercontent.com/42739042/108883670-ca47e700-7616-11eb-8bc2-302add7a5948.png)
only 3 worker working.

**Comment by richard-julien** [comment]
Dont know exactly what happen but you doesnt have any messages in the queue... You reset your rabbitmq?
In this state I think you can:
1. Remove the MITRE job with the delete button
2. Reset your MITRE connector state.
3. Wait for MITRE connector to do another round (or restart it)
4. Check if your connector correctly fill the queue

**Comment by wallece55** [comment]
I tried what you said. However, there was no change. When I looked at the Docker logs, I saw that I got errors like "pika.adapters.utils.selector_ioloop_adapter: Address resolution failed: gaierror (-2, 'Name does not resolve')", what could be the reason?

**Comment by richard-julien** [comment]
Looks like your connector have no access to the rabbitmq.
If you deploy in docker but careful to use the same network between containers.

**Comment by Ken-Abruzzi** [comment]
> Dont know exactly what happen but you doesnt have any messages in the queue... You reset your rabbitmq?
> In this state I think you can:
> 
> 1. Remove the MITRE job with the delete button
> 2. Reset your MITRE connector state.
> 3. Wait for MITRE connector to do another round (or restart it)
> 4. Check if your connector correctly fill the queue

Hello, I also face this problem with CVE connectors. How should I restart the connector? Thank you.   @richard-julien

**Comment by richard-julien** [comment]
Hi, restarting the connector is restart the container if you use docker.

**Comment by SamuelHassine** [comment]
I'm closing this one due to inactivity. Please feel free to open a new one if you still have any problem.
