### ISSUE TITLE
Create relationships between observables in the context of a report

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1108]
## Description

STIX 2.1 allows for a "belongs to" relationship from IP to ASN observables. When creating this relationship in the Knowledge graph, the "relationship_belongs-to" relationship type is available. However, OpenCTI returns an error. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 4.2.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add an IP observable to a Report
2. Add an ASN observable to the same report
3. Create a relationship from the IP to ASN observables
4. Select the "relationship_belongs-to" relationship
5. Select "Create"

## Expected Output

A relationship is created between the two objects

## Actual Output

OpenCTI returns an error, and doesn't allow the relationship to be created. See screenshot below
 
## Additional information

![image](https://user-images.githubusercontent.com/78382789/108785670-8336f480-7537-11eb-8728-852e982c8ed7.png)

**Comment by securitiz** [comment]
I've found that this issue also pertains to the "relationship_resolves-to" relationship from IPs to domains. Related to this, OpenCTI only allows for "resolves to" relationships from IPs to domains, which doesn't make sense. STIX specifies that the relationship should go in the opposite direction, from domains to IPs. But, I'll create a separate issue for  this :)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

I let this feature open to allow the creation of relationships between observables from reports. But if you need to create a proper belongs-to relationship, please refer to: https://demo.opencti.io/dashboard/observations/observables/cd7325fa-bd90-4e3e-a12c-987114effe8c.

![image](https://user-images.githubusercontent.com/1334279/109128768-15194a00-7750-11eb-8b7f-885fc0e262be.png)

Kind regards,
Samuel

**Comment by securitiz** [comment]
Thanks Samuel,

I'm actually having trouble recreating your screenshot. When I select an IP observable -> Knowledge to create a relationship, I can only create relationships to Entity SDOs (not ASN). I have the same trouble relating a domain to an IP:

![image](https://user-images.githubusercontent.com/78382789/109350320-ee850d00-783c-11eb-8207-e93b83402107.png)

**Comment by securitiz** [comment]
Just kidding - I saw in another issue that you linked it from the Overview page
