### ISSUE TITLE
Can't view edit members of Group from Group's page

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1109]
## Description

Can't edit members of a Group from the Group page. Instead, we have to go to each individual User, and add them to a Group. This becomes an issues when needing to add many users to/from a single group

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 4.2.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Settings -> Accesses -> Groups
2. Select a group -> Update
3. Go to the Members tab
4. 

## Expected Output

View the members in the  group

## Actual Output

Error: An unknown error occurred. Please contact your administrator or the  OpenCTI maintainers
 
## Additional information

I was unable to test this on the demo instance, as changing users/groups (understandably) is not available to my account

**Comment by richard-julien** [comment]
Do you have more information/logs on your error?
Just tested without any problem on the demo

**Comment by richard-julien** [comment]
Hi @securitiz ,

Any news on that?

**Comment by securitiz** [comment]
Hi @richard-julien , we checked today, and it appears to be an issue with the admin user not having a name. Closing the issue.
