### ISSUE TITLE
TTP Not Properly Linking With Other Entities

### ISSUE THREAD

**Issue by cdiraimondi** [OpenCTI-Platform/opencti#111]
## Description

I've created a report and started mapping entities together. I've added an Intrusion Set, ATT&CK TTP, Incidents and a Country. When I access the report, click on Entities and then click on Spearphishing Link. After clicking on Knowledge then Intrusion Sets or Incidents I am not seeing the Intrusion Set or Incident that I previously defined. It appears that the data objects aren't properly linking for the TTP in the backend.

## Environment

1. Ubuntu 18.04.1 LTS
2. OpenCTI version: 1.0.0
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Report
2. Add entity TTP, Intrusion Set, etc
3. Once completed click on the specific TTP entry in the Entities section of the report
4. While in the Attack Patterns section click on Knowledge
5. On the right hand side try selecting Intrusion Set or Incidents
6. No results displayed despite the previous entity mapping having been completed.

## Expected Output

A list of mapped entities should be displayed for the ATT&CK TTP that was selected

## Actual Output

Nothing is displayed.
 
## Additional information

None

**Comment by SamuelHassine** [comment]
Hello,

Could you please provide us a screenshot of the report knowledge?

**Comment by cdiraimondi** [comment]
**Report Page**
![image](https://user-images.githubusercontent.com/22398020/60529412-83c8aa80-9cc4-11e9-9ce8-97080747b447.png)

**Clicking Spearphishing Link technique**
![image](https://user-images.githubusercontent.com/22398020/60529461-9fcc4c00-9cc4-11e9-8a56-3efa0117db9f.png)

**Clicking Knowledge** - Note the graphs with values
![image](https://user-images.githubusercontent.com/22398020/60529493-b2468580-9cc4-11e9-8d85-2b91aed45996.png)

**Clicking Intrusion Set with no results**
![image](https://user-images.githubusercontent.com/22398020/60529533-c7231900-9cc4-11e9-9625-26ade9dabdf2.png)

**Clicking Incidents**
![image](https://user-images.githubusercontent.com/22398020/60529568-ddc97000-9cc4-11e9-8acd-c82506b4ca2b.png)

**Comment by SamuelHassine** [comment]
@cdiraimondi: I do not see the relations graph? [An example here](https://demo.opencti.io/dashboard/reports/all/6cabab64-96c0-45dd-8bfa-a905eb4ef651/knowledge).

**Comment by SamuelHassine** [comment]
@cdiraimondi: I close this issue because all entities are properly linked together. In your example, you just added entities to a report but you forgot to create relationships in the knowledge graph.
