### ISSUE TITLE
IP / Domain relationships go the wrong way

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1112]
## Description

The relationship between Domain and IPv4 observables goes the wrong way. Currently it allows the "resolves to" relationship from the IP to the domain, which isn't in accordance with STIX. It doesn't allow a domain to resolve to the IP, as it should. (Also STIX doesn't allow these relationships to be created at all - see #1108 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 4.2.4
3. OpenCTI client: frontend
4. Other environment details: demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an IPv4 observablein a Report
2. Create a Domain observable  in a Report
3. Create a relationship from the Domain to the IP

## Expected Output

The ability to create a "resolves to" relationship

## Actual Output

Only the ability to create a "related to" relationship
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Thanks for reporting, this was indeed a bug. It has been fixed, nevetheless, for the moment, relationships between observables cannot be created in the context of a report. You should create this relation from here:

https://demo.opencti.io/dashboard/observations/observables/e1cc37d1-27ed-43b7-b2d0-5a8894791809

Kind regards,
Samuel
