### ISSUE TITLE
Improve Elasticsearch configuration options

### ISSUE THREAD

**Issue by danilo-massa** [OpenCTI-Platform/opencti#1113]
## Problem to Solve

Sometimes can be necessary to use an Elasticsearch instance outside docker, for perfomance reason o in order to better manage the database itself. The problem is related to the security of the database connections, i.e. in order to integrate the external ES can be necessary:

1. use HTTPS instead of HTTP
2. permit OpenCTI to accept eventually self signed digital certificates for the ES instance
3. specify a valid ES username and password

At present time these parameters cannot be specified in the docker-compose's OpenCTI configuration.

## Current Workaround

At present time I have solved this problem creating a dedicated apache's reverse proxy configuration that handle the issue, i.e. "translate" HTTPS to HTTP (accepting self signed certificates from ES instance) and add a Authetication header with correct credentials.

## Proposed Solution

Please add the possibility to better configure the connection to ES  adding three parameter like: 
ELASTICSEARCH__USER
ELASTICSEARCH__PASSWORD
ELASTICSEARCH__NO_SSL_CHECK

and let the ELASTICSEARCH_URL to accept https.

## Additional Information

If someone need my  workaround I am available to share it.

**Comment by SamuelHassine** [comment]
Hello @danilo-massa,

You can pass the user and the password directly in the ElasticSearch URL using : "http://user:password@elastic.hostname.com". We will add the no SSL check parameter shortly.

**Comment by KunwarAkanksha** [comment]
Does newer version of OpenCTI support HTTPS with ELASTICSEARCH__NO_SSL_CHECK now ??

**Comment by anasnaguib** [comment]
Hi, Any news about ELASTICSEARCH__NO_SSL_CHECK ? this is good to have instead of disabling xpack.security.enabled in elastic search, especially when elasticsearch is on separate machine.

**Comment by richard-julien** [comment]
You can use elasticsearch:ssl:reject_unauthorized

ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED
