### ISSUE TITLE
How to increase the number of connected workers?

### ISSUE THREAD

**Issue by Tyrell20** [OpenCTI-Platform/opencti#1114]
## Description
 The number of active workers remains fixed at one and we believe this is the cause of the slow emptying of the message queue of our OpenCTI instance.

At the moment we have only 2 import connector and the "replicas: 5" value in the docker-compose.yml under the worker section.
![screenshot 256](https://user-images.githubusercontent.com/64137969/109165258-a2be5f00-777b-11eb-94a4-8d36af81bd05.jpg)

## Environment

1. OS (where OpenCTI server runs): { Red Hat Enterprise Linux Server release 7.9 (Maipo) with Docker Compose }
2. OpenCTI version: { OpenCTI 4.2.3  }
3. OpenCTI client: { Frontend }
4. Other environment details:
Elasticsearch 7.11.0
RabbitMQ 3.8.12
Redis 6.0.10
MinIO Latest

## Expected Output
Number of workers increased 

## Actual Output
Connected Workers = 1
 
## Additional information

Worker configuration docker-compose.yml:
worker:
    image: opencti/worker:4.2.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 5
    restart: always

**Comment by richard-julien** [comment]
replicas: 5 in docker only works in swarm mode.
If you are not in swarm you need to declare the worker multiple times yourself

**Comment by Tyrell20** [comment]
It works, thank you!

**Comment by AntoninHL** [comment]
> 

Hello.
how to "to declare the worker multiple times"?

Many thanks
