### ISSUE TITLE
Unstable Service OpenCTI

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1118]
Hello, 

Reference to issue #1083 (Start OpenCTI using Systemd)

The service is working fine, but I have two considerations:
1.	The log is consuming a lot of diskspace on `/var/opencti` and `/var/elasticsearch` .
2.	The service webpage hangs within two days, and I have to restart the opencti for it to work.

What do you thing I should do with the logs? Do I create a cron job to archive/delete it?
For the service, I’m trying now using 24GB instead of 16GB RAM.

Regards,
Khalid.

@JeromeSRT

**Comment by JeromeSRT** [comment]
> Hello, 
> 
> 
> 
> Reference to issue #1083 (Start OpenCTI using Systemd)
> 
> 
> 
> The service is working fine, but I have two considerations:
> 
> 1.	The log is consuming a lot of diskspace on `/var/opencti` and `/var/elasticsearch` .
> 
> 2.	The service webpage hangs within two days, and I have to restart the opencti for it to work.
> 
> 
> 
> What do you thing I should do with the logs? Do I create a cron job to archive/delete it?
> 
> For the service, I’m trying now using 24GB instead of 16GB RAM.
> 
> 
> 
> Regards,
> 
> Khalid.
> 
> 
> 
> @JeromeSRT
> 
> 

Hi,

I updated the start script to reduce the log files of OpenCTI in /var/opencti
```

#!/bin/bash
#
#
#Script Lancement Platform / Workers / Connectors OpenCTI
#
#
#Lancement Platform OpenCTI
#
if [ `netstat -lnp | grep tcp | grep 4000 | grep node | wc -l` = 0 ] ; then
	cd /usr/share/opencti
	touch /tmp/opencti-platform.pid
	yarn serv &
	echo $! >> /tmp/opencti-platform.pid
#
#
#Vérification Ecoute Port Plateforme OpenCTI
#
	while [ `netstat -lnp | grep tcp | grep 4000 | grep LISTEN | grep node | wc -l` = 0 ] ; do
#		sleep 0.5
	done
#
#
#Lancement Workers OpenCTI
#
	cd /usr/share/opencti
	for ((i = 1 ; i <= 10 ; i++)) ; do
		touch /tmp/opencti-worker-"$i".pid
		python3 ./worker/worker.py &
		echo $! >> /tmp/opencti-worker-"$i".pid
	done
#
#
#Lancement Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
#
	cd /usr/share/opencti
	for con in "export-file-stix" "import-file-pdf-observables" "import-file-stix" ; do
		for rep in `ls ./connectors | grep "$con"` ; do
			touch /tmp/opencti-"$rep".pid
			python3 ./connectors/"$rep"/src/"$rep".py &
			echo $! >> /tmp/opencti-"$rep".pid
		done
	done
fi
#
#
#

```

For elasticsearch, you need to look at the configuration file elasticsearch.yml to reduce the log files in /var/elasticsearch.

Regards,

Jérôme

**Comment by khalidrehan** [comment]
> > Hello,
> > Reference to issue #1083 (Start OpenCTI using Systemd)
> > The service is working fine, but I have two considerations:
> > 
> > 1. The log is consuming a lot of diskspace on `/var/opencti` and `/var/elasticsearch` .
> > 2. The service webpage hangs within two days, and I have to restart the opencti for it to work.
> > 
> > What do you thing I should do with the logs? Do I create a cron job to archive/delete it?
> > For the service, I’m trying now using 24GB instead of 16GB RAM.
> > Regards,
> > Khalid.
> > @JeromeSRT
> 
> Hi,
> 
> I updated the start script to reduce the log files of OpenCTI in /var/opencti
> 
> ```
> 
> #!/bin/bash
> #
> #
> #Script Lancement Platform / Workers / Connectors OpenCTI
> #
> #
> #Lancement Platform OpenCTI
> #
> if [ `netstat -lnp | grep tcp | grep 4000 | grep node | wc -l` = 0 ] ; then
> 	cd /usr/share/opencti
> 	touch /tmp/opencti-platform.pid
> 	yarn serv &
> 	echo $! >> /tmp/opencti-platform.pid
> #
> #
> #Vérification Ecoute Port Plateforme OpenCTI
> #
> 	while [ `netstat -lnp | grep tcp | grep 4000 | grep LISTEN | grep node | wc -l` = 0 ] ; do
> #		sleep 0.5
> 	done
> #
> #
> #Lancement Workers OpenCTI
> #
> 	cd /usr/share/opencti
> 	for ((i = 1 ; i <= 10 ; i++)) ; do
> 		touch /tmp/opencti-worker-"$i".pid
> 		python3 ./worker/worker.py &
> 		echo $! >> /tmp/opencti-worker-"$i".pid
> 	done
> #
> #
> #Lancement Connectors Export File STIX / Import File PDF / Import File STIX OpenCTI
> #
> 	cd /usr/share/opencti
> 	for con in "export-file-stix" "import-file-pdf-observables" "import-file-stix" ; do
> 		for rep in `ls ./connectors | grep "$con"` ; do
> 			touch /tmp/opencti-"$rep".pid
> 			python3 ./connectors/"$rep"/src/"$rep".py &
> 			echo $! >> /tmp/opencti-"$rep".pid
> 		done
> 	done
> fi
> #
> #
> #
> ```
> 
> For elasticsearch, you need to look at the configuration file elasticsearch.yml to reduce the log files in /var/elasticsearch.
> 
> Regards,
> 
> Jérôme

I will test that, thank you :)

**Comment by khalidrehan** [comment]
@JeromeSRT,
I believe you have removed the logs from the start script totally!
Is there any other solution?

**Comment by JeromeSRT** [comment]
> @JeromeSRT,
> 
> I believe you have removed the logs from the start script totally!
> 
> Is there any other solution?
> 
> 

Yes, I removed all the logs.
Look at the production.json file in opencti/config you will fine the repertory for opencti Platform.
