### ISSUE TITLE
What should I set the value of "OPENCTI_URL" in the docker-compose.yml file?

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/opencti#1119]
In different yml files, the "OPENCTI_URL" values are different.
For example, in the [https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml](url), the OPENCTI_URL=http://opencti:8080
![image](https://user-images.githubusercontent.com/68931768/109462910-09ac7400-7a19-11eb-9d97-ec959c6a0dfa.png)
But in the [https://github.com/OpenCTI-Platform/connectors/blob/master/alienvault/docker-compose.yml](url), or [https://github.com/OpenCTI-Platform/connectors/blob/master/cve/docker-compose.yml](url), or [https://github.com/OpenCTI-Platform/connectors/blob/master/opencti/docker-compose.yml](url), OPENCTI_URL=http://localhost
![image](https://user-images.githubusercontent.com/68931768/109462414-49269080-7a18-11eb-9059-34e153895708.png)
![image](https://user-images.githubusercontent.com/68931768/109463182-6f006500-7a19-11eb-8140-00f17865c47c.png)
![image](https://user-images.githubusercontent.com/68931768/109463289-93f4d800-7a19-11eb-9778-494c974f82b0.png)
I'm confused at it. Please help me. Thank you!

**Comment by richard-julien** [comment]
Hi,

It should be opencti instead of localhost. But be careful to correctly configure your compose to permits communication between containers.

**Comment by Ken-Abruzzi** [comment]
Thank you! "OPENCTI_URL=http://opencti:8080" Is this right? I'm also confused about this url. Does the word "opencti" means "127.0.0.1"? Is it defined anywhere? @richard-julien

**Comment by richard-julien** [comment]
In docker compose you have an implicit dns based on the name of the container. 
So we use opencti in the uri simply because its the name of the opencti container in the stack.

**Comment by Ken-Abruzzi** [comment]
Thank you @richard-julien
