### ISSUE TITLE
Improper relationship mapping for Incident and TTP

### ISSUE THREAD

**Issue by cdiraimondi** [OpenCTI-Platform/opencti#112]
## Description

A report was created that contains an Incident and associated TTP Spearphishing Link in email. When attempting to create a relationship via the Knowledge graph dragging from Incident to TTP or TTP to Incident only allows for the "relates to" relationship however the documentation states that for an Incident you should be able to specific "uses". Example from documentation is below.

Incident (user) | uses | Attack Pattern (usage)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.1 LTS
2. OpenCTI version: 1.0.0
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Report
2. Add Incident entity
3. Add TTP entity
4. Click Knowledge
5. Add entity Incident and TTP to graph
6. Create link between Incident->TTP or TTP->Incident

## Expected Output

The relationships are probably defined as per STIX2 spec and documentation at https://opencti-platform.github.io/docs/reference/relations

## Actual Output

It only allows for the selection of "relates to" for a relationship.
 
## Additional information

Reference to documentation entry  https://opencti-platform.github.io/docs/reference/relations

**Comment by SamuelHassine** [comment]
@cdiraimondi: an incident entity can be connected to a TTP with a `uses` relationship since 1.0.1. Please find below a screenshot from the [demonstration instance](https://demo.opencti.io):

![relation](https://user-images.githubusercontent.com/1334279/60579802-24ca6a80-9d84-11e9-99e8-6dba405540c4.png)
