### ISSUE TITLE
Unable to create a new autonomous system in observables tab

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1120]
## Description
I can't create a new autonomous system observable in OpenCTI

## Environment

1. OS (where OpenCTI server runs): MacOS Big Sur 11.2.1
2. OpenCTI version: OpenCTI 4.2.4
3. OpenCTI client: Frontend in Safari 14.0.3
4. Other environment details: French langage for GUI

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Observables on the left column, then Observables button on top left
2. Click on (+) button, choose Autonomous system
3. Fill out the fields, then click on create button

## Expected Output

A new autonomous system do not appear in the list...

## Actual Output

No new autonomous system in the list, but a doublon of an autonomous system appears...
 
## Additional information

![image](https://user-images.githubusercontent.com/68632445/109477681-9cc8c680-7a78-11eb-982c-6583f7b1213f.jpeg)

**Comment by richard-julien** [comment]
`GraphQLError: Variable "$AutonomousSystem" got invalid value null at "AutonomousSystem.number"; Expected non-nullable type "Int!" not to be null.,`

**Comment by richard-julien** [comment]
Oh the bug is real :) OpenCTI should of course inform the user correctly. Thanks for the report.
