### ISSUE TITLE
Many dockers restart all the time after I restart my computer

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/opencti#1121]
## Description

I restart my computer, and many dockers restart all the time and the opencti web service cannot start normally.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.2 in VMWare
2. OpenCTI version: OpenCTI 4.2.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I add the services of alienvault-connector and cve-connector, and "docker-compose up -d".
2. The alienvault-connector works but the cve-connector doesn't work.
3. I shutdown the computer using "sudo shutdown -h now".
4. I reopen the Ubuntu in VMWare, and the dockers keep restarting for hours.

## Expected Output

The dockers should restart for several minutes.

## Actual Output

The dockers keep restarting all the time.
![image](https://user-images.githubusercontent.com/68931768/109490644-5d30b900-7a3d-11eb-9330-c283d8582525.png)
I check the logs of docker_opencti_1:
![image](https://user-images.githubusercontent.com/68931768/109491508-7ede7000-7a3e-11eb-854b-5a6336c5f091.png)
Then I check the logs of docker_elasticsearch_1:
![image](https://user-images.githubusercontent.com/68931768/109491879-ff04d580-7a3e-11eb-8a8f-0519f0230687.png)
Then I check the logs of docker_rabbitmq_1:
![image](https://user-images.githubusercontent.com/68931768/109492099-4be8ac00-7a3f-11eb-8cfb-237659a30cc8.png)

Can you tell me how to fix it?

**Comment by richard-julien** [comment]
Hi,

Looks like disk out of space prevent elastic to start.

![image](https://user-images.githubusercontent.com/285555/109496636-369c6d80-7a91-11eb-8f40-519ce5fe769d.png)

**Comment by Ken-Abruzzi** [comment]
@richard-julien Thanks for your answer. It is quite the reason.
