### ISSUE TITLE
No entity and relationship historic in activities tab

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1125]
## Description

There is no information about the entity and the associated relationship in the activities tab.

## Environment

1. OS (where OpenCTI server runs): Mac OS Big Sur 11.2.1
2. OpenCTI version: OpenCTI 4.2.4
3. OpenCTI client: Frontend with Safari 14.0.3
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on an entity
2. Click on activities tab
3. 

## Expected Output

Information about past activities linked with an entity or relationship

## Actual Output

No information about past activities
 
## Additional information

![image](https://user-images.githubusercontent.com/68632445/109786532-8acc5c80-7c0d-11eb-8ab3-314c7e008c28.jpeg)

**Comment by richard-julien** [comment]
This part is filled by the history connector. Do you have it running?

**Comment by JeromeSRT** [comment]
> This part is filled by the history connector. Do you have it running?

No. Where is it written to make use of the history connector to log the activities ?

**Comment by richard-julien** [comment]
No where. Just added an explanation in "browse the knowledge" page and "troubleshooting" of the documentation.

**Comment by SamuelHassine** [comment]
By the way, the "history" connector is present in the default `docker-compose.yml` configuration as well as in the virtual machine template.
