### ISSUE TITLE
Data retention limit settings

### ISSUE THREAD

**Issue by IOTech17** [OpenCTI-Platform/opencti#1128]
## Problem to Solve

There is currently no settings to control the amount of data we are keeping. By Default everything is kept.

## Proposed Solution

Could it be possible to implement within OpenCTI a setting per connector or per type of data with the maximum time range to keep.

For example some IP/Hashes etc... are obsolete after sometime but I might want to keep all the CVE/Mitre data. Purging this data every set amount of time keep only the relevant data and keeping the resources needed by Elasticsearch under control.

This will be especially useful if you host OpenCTi on AWS.

**Comment by SamuelHassine** [comment]
Linked to #1228.

**Comment by SamuelHassine** [comment]
This ticket will be followed in #1228.
