### ISSUE TITLE
Using DGraph instead of ElasticSearch/Grakn?

### ISSUE THREAD

**Issue by martinholovsky** [OpenCTI-Platform/opencti#1130]
## Problem to Solve

ElasticSearch is not a Graph database and I understand it's just an interim solution before Grakn 2.0 will be released. Just because of ElasticSearch (Java), OpenCTI has a high demand on memory (2,5GB without any data).
There might be better solutions even today.

## Current Workaround

ElasticSearch

## Proposed Solution

**DGraph** - Open source, distributed graph database with a **GraphQL** based query language.

## Additional Information

https://github.com/dgraph-io/dgraph

**Comment by SamuelHassine** [comment]
Hello @martinholovsky,

Thanks for the idea about dgraph. We are monitoring closely the evolution of all Graph databases. For the moment, we would like make OpenCTI as mature as possible on ElasticSearch before re-design our dependencies architecture. When we will start thinking about our dependencies, we will ask the community on Slack and gather feedback on our ideas.

Kind regards,
Samuel
