### ISSUE TITLE
Export Module in OpenCTI Dashboard

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1135]
Greetings,

I would like to request to have an "export" module in OpenCTI. 

- This "export" feature can be control in the OpenCTI GUI.
- The "export" form should have "filter" function where we can define what to export
- OR a predefined list of export where we can able to configure.
- External apps can then call the REST API to retrieve the data
![image](https://user-images.githubusercontent.com/20463433/110130622-3523bb80-7d97-11eb-9480-be9ca663da14.png)

**Comment by richard-julien** [comment]
Hi @NetEyes,
I think you can maybe can do that with the taxii api of the latest version of openCTI.
We should be able to create a collection with the filters and use the taxii2 api to get the data.
I dont think we have all the filters you want but maybe you should take a look :)

**Comment by SamuelHassine** [comment]
New capabilities of CSV Feed and TAXII collections are covering well this features, using advanced filters and searching.

If missing filters, please open a new issue.
