### ISSUE TITLE
Intrusion sets show threat actors instead of intrusion sets

### ISSUE THREAD

**Issue by rsi-art** [OpenCTI-Platform/opencti#1147]
Hi,

I don't know if it is really an issue, but in our deployment, in the Knowledge menu, threats actors are diplayed in the intrusion set tab instead of thrat actors one.

So, there is nothinf displayed in theat actors tab and we dont't show any intrusion set in intrusion set tab.

Any help to understand this behaviour ?

Our deployement is based on last docker version, build with docker-compose.

Regards

**Comment by richard-julien** [comment]
Hi @rsi-art ,

Can you check if the connector responsible for the creation really try to create threat actor?

**Comment by rsi-art** [comment]
Hi,

How can I check this ?
Intrusion sets are provided by Mittre connector.
Regards,

**Comment by richard-julien** [comment]
Maybe i'm wrong but i dont think the mitre have any threat-actor.
The connector insert https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json and https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json

**Comment by SamuelHassine** [comment]
For the moment, I don't know any CTI sources in OpenCTI connectors which is providing Threat Actors entities. So all "groups" are in intrusion sets right now.
