### ISSUE TITLE
Potential vulnerability with query of settings

### ISSUE THREAD

**Issue by kirintwn** [OpenCTI-Platform/opencti#1154]
## Description

Currently, the GraphQL schema Query `Settings` is open to anyone **even if they are not login**.
But the query like below can get all platform config INCLUDING environment variables:
```
{
  settings {
    platform_parameters
  }
}
```

Because we are using `nconf.env()` with no whitelist, and the GraphQL query `platform_parameters` just extract nearly all the information from `nconf` except some dissociated values.

I believe  `platform_parameters` should at least to have capability `@auth(for: [SETTINGS])` specified.
Also, what `platform_parameters` returns should be explicitly instead of return all things with blacklisting.

Ref:
https://github.com/OpenCTI-Platform/opencti/blob/ff167a76036ea043490ddac467bd536887364eec/opencti-platform/opencti-graphql/config/schema/opencti.graphql#L7318
https://github.com/OpenCTI-Platform/opencti/blob/ff167a76036ea043490ddac467bd536887364eec/opencti-platform/opencti-graphql/src/domain/settings.js#L28-L46

## Environment

1. OS (where OpenCTI server runs): Containers
2. OpenCTI version: OpenCTI 4.3.0
3. OpenCTI client: all
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Run the query:
```
{
  settings {
    platform_parameters
  }
}
```

## Expected Output

Block unauthenticated access & limit what to expose to the user.

## Actual Output

Shows nearly all configs & environment variables.

**Comment by richard-julien** [comment]
Just remove exposing internal configuration.
