### ISSUE TITLE
[BUG / ISSUE] Performance Issues with Worker / RabbitMQ

### ISSUE THREAD

**Issue by JustCodeIt4Head** [OpenCTI-Platform/opencti#1155]
## Description
While running OpenCTI in Docker on a Proxmox the Worker or RabbitMQ seems to not work correctly and using a lot of Memory with minimal performance

## Environment

1. Debian 64 Proxmox Host with a Debian 64 VM. Current Docker Version
2. OpenCTI version: latest OpenCTI available via Docker
3. OpenCTI client: Web frontend
4. Other environment details:
VM has 12 GB Memory (not shared), 4 CPU Cores, 200 GB Storage on a separate Hard drive (not used by the Host OS or other VMs). VM uses UEFI

## Reproducible Steps
When using a Connector to import IOCs or downloading Content from e.g. Alien vault OTX or something similar it seems that the Worker takes up almost the whole Memory of the VM and Processes at a Speed of 2-5 per second.
Shutting down the Worker Container drops the Memory usage to around 1/4th of the VM.
The Issue seems strange since on a regular old Notebook (4 cores, 8 GB DDR3, HDD) the System seems to run just fine at an acceptable performance.
Monitoring of the VMs Displays that CPU, HDD I/O and Network get rarely used above 20%).

## Expected Output
The worker / RabbitMQ should not take up that many Resources with little Performance

## Actual Output
Low Performance
 
Not sure if it's a Bug. Other Software (e.g. Splunk in Docker, ELK) runs just fine with no noticeable Performance impact.

As a comparison: I just installed the same Setup in a VM on my Desktop PC in VMware Workstation Pro on my non System HDD with same specs and I get ~ 10-15 per Second, bearing in mind that my Ram and HDD get used by my System as well (running Chrome, Twitch on 1080p and multiple Applications open etc) and my CPU is not as Powerful as my Server CPU

Could this be a Bug specific to Docker + Proxmox? Is there any useful Guide / Script to deploy Open CTI from Scratch on Debian? (seen the Ubuntu one but im a Debian Guy)

**Comment by richard-julien** [comment]
Hi @JustCodeIt4Head ,

Im sorry but I really don't know what can trigger this situation on your side.
We dont have official script to deploy but take a look to https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1

**Comment by SamuelHassine** [comment]
Closing this one due to inactivity. Please feel free to open a new issue if the problem persists.
