### ISSUE TITLE
Refactored Knowledge Graph

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#1156]
## Description

A few observations:

1. When opening the newly refactored Knowledge Graph (as of v4.3.0), the info icon (in the lower right) for any relation only becomes active if you previously click on a node.

2. Once the info icon is active and you select it for any relation, the resulting page is empty (URL leads to .../null/null).

3. After upgrading to v4.3.0 the new Knowledge Graph breaks several pre-existing relations created in former versions of OpenCTI. The respective relations still exist in the DB but node info shows: "related to entity_undefined"

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server 20.04.2 LTS
2. OpenCTI version: 4.3.0
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. In a report click on Knowledge and first select a relation in the graph (info icon inactive). Next select any node and then a relation again (info icon active)
2. Still in the Knowledge Graph, select any relation and click on info (empty page)
3. Select any node from a loosely floating entity or relation (previously related to the main cluster) and click on info. The relation still shows but says: "related to entity_undefined"

## Expected Output

1. Info icon should be active when you first select a relation in the Knowledge Graph
2. Selecting info for any relation should show the info like for any other node in the graph
3. Update to v4.3.0 should preserve all pre-existing relations of Knowledge Graphs created in previous versions

## Actual Output

refer to the beginning of this post

**Comment by SamuelHassine** [comment]
Hello @s3ns0r1um,

Thanks for all these observations, all of them should will be solved in the release 4.3.1. Please continue to open issues to enhance the graph view, since this view will be extended to a lot more screens in the platform.

Kind regards,
Samuel
