### ISSUE TITLE
OpenCTI UI : Create a "not clickable" external reference section for Threat Actors entities

### ISSUE THREAD

**Issue by nicolasleguillou** [OpenCTI-Platform/opencti#1159]
## User story

As a threat intelligence analyst we would like to securely add an URL to a cybercrime platform as an external reference for Threat Actors entities, in order to add more context about our entity and by avoiding at the same time any unwanted redirection to this malicious platform.

## Problem to Solve

The link to a cybercrime platform might be malicious (and hence should not be clickable) but is not necessarily an indicator of compromise. A link in the external reference section is dangerous because it might be easily followed by an analyst. We don't want to add it to the indicator section either, as it is not relevant.

## Current Workaround

The analyst needs to defang each URL submitted. It could be interesting to allow users to add a not clickable external reference to a Threat Actor entity.

## Proposed Solution

Make the external section not clickable or add a parameter to handle this use case (true: clickable, false:not clickable)?

**Comment by SamuelHassine** [comment]
Hello @nicolasleguillou,

As the external references may come from automatically ingested content (from connectors), it appears to be a bad move to implement a boolean `clickable` which will be relevant only if the external reference is created manually.

We've chosen a solution used by a lot of services/software: to warn the user before browsing the external link.

![image](https://user-images.githubusercontent.com/1334279/111906898-3faaaa00-8a53-11eb-8037-f7a8f2f9c2a0.png)
