### ISSUE TITLE
Unable to change confidence level on entities other than a report

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1160]
## Description

When modifying an entity, it is no longer possible to change the level of confidence for an entity except for reports. In all other entities (campaigns, threat actors, etc.), the field is by default "low" and does not appears when opening for modification. It is still possible for relations. 

## Environment

1. OpenCTI demo instance
2. V4.3 (latest, tried today the 15-03)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an intrusion set overview page (any should do)
2. Notice the confidence level set at "low"
3. Click on the orange pen bottom right side, or on the three dots right of the name (any will give the same result) to open the modification page
4. No field is available in the modification window to change the confidence level

![Capture d’écran du 2021-03-15 16-24-13](https://user-images.githubusercontent.com/49722941/111177861-eb16b300-85aa-11eb-8f71-61c42b03ee64.png)

**Comment by manonviallet** [comment]
Hello, I feel like this is a bug more than a feature, because we previously were able to set the confidence level of all entities as we wished when creating them or in modifying them, and it is something that disappeared in one of the lastest release. 
Or if you choose to willing drop this feature, because of another issue, then I think it would be much more satisfactory to not have any confidence level at all, than a confidence level set as "low" by default. I saw some previous entities with no confidence level, but I don't know if it is possible to implement it with today constraints with STI2.1

**Comment by SamuelHassine** [comment]
@manonviallet STIX 2.1 standard includes a `confidence` field for all SDOs. I've implemented this field on most of them. If I miss some entities let us know.
