### ISSUE TITLE
Add RabbitMQ Queue connector backpressure

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1161]
Dears,

Once I start the OpenCTI, the rabbitmq-server queue is consuming the diskspace to the top, which causes Elasticsearch to lock up.
![image](https://user-images.githubusercontent.com/37035465/111177824-a8110b80-85bb-11eb-896e-d5351245b686.png)

Is there anyway to limit the queue size?

Regards,
Khalid.

**Comment by richard-julien** [comment]
Hi @khalidrehan ,

Today there is no buffering on connectors side.

Maybe we could implement an option on the python connector library that activate the scheduling only if queue_size < to a specific amount,

**Comment by khalidrehan** [comment]
Hi @richard-julien ,
I'm using OpenCTI ver. 4.2.0 on Ubuntu 18.04 Server.
![image](https://user-images.githubusercontent.com/37035465/111258887-e85da180-862e-11eb-948e-d5c94177b1ef.png)

**Comment by khalidrehan** [comment]
Hello @richard-julien ,
Will a migration to the latest version solve the problem?

Regards,
Khalid

**Comment by richard-julien** [comment]
Hi @khalidrehan,
The feature is not available yet.
For now you have to give enough space to the rabbit to take care of the millions of messages you want to process.

**Comment by khalidrehan** [comment]
OK, I will have to test the minimum needed from the current system. Hopefully, we may have a solution soon for the queue size.

**Comment by khalidrehan** [comment]
Hello @richard-julien ,

I have increased the size for RabbitMQ queue, and I'm watching the system behavior.

## My question as best practice:
Do I have to keep collecting feeds all the time no matter the size it is consuming on the platform? or can I flush it periodically?

Regards,
Khalid.

**Comment by khalidrehan** [comment]
Hello @richard-julien ,

Any updates about this feature?

Regards,
Khalid

**Comment by richard-julien** [comment]
Hi @khalidrehan,

Not for the moment. We understand the interest but a bit less urgent than other subjects.

**Comment by khalidrehan** [comment]
> Hi @khalidrehan,
> 
> Not for the moment. We understand the interest but a bit less urgent than other subjects.

Hi @richard-julien 

Understood.

Regards,
Khalid

**Comment by Jipegien** [comment]
is it something still relevant @SamuelHassine ?

**Comment by romain-filigran** [comment]
@helene-nguyen @Megafredo : Can we close this issue, which seems to be covered by the latest improvements you've implemented?

**Comment by Megafredo** [comment]
Hello @romain-filigran, so indeed, with the new functionality of the scheduler, there will be protection for RabbitMQ (Queue backpressure), however it will be necessary to set up a method in the connector using either "schedule_iso()" or "schedule_unit()".
There will be a blog post soon that will explain the process, so I think you can close the topic ;)
