### ISSUE TITLE
After the VMware virtual machine is restarted, the OpenCTI platform cannot be accessed

### ISSUE THREAD

**Issue by A1oha** [OpenCTI-Platform/opencti#1164]
## Description
I downloaded the ova file of OpenCTI 4.2.2 version to install, and the platform can be accessed normally at first. But when I suspend Vmware and start it again, I can’t access {ip}:8080 and {ip}:3000, (I’m sorry, this may be a Docker usage problem, I don’t know how to configure it after restarting the virtual machine to access it normally. OpenCTI, so I asked this question, hope to get help, thank you very much!) 

## Environment
1. OpenCTI version: 4.2.2

## Additional information
![image](https://user-images.githubusercontent.com/40291952/111287824-8fb5f500-867e-11eb-9b54-d5a9151eac3d.png)

**Comment by SamuelHassine** [comment]
Hello,

We've made some update in the latest image (4.3.0), can you please give a try and see if the problem persists?

**Comment by A1oha** [comment]
Thank you very much. I re-downloaded and installed version 4.3.0. After the VM was running, restarted the opencti and portainer containers, which solved the problem.
