### ISSUE TITLE
Custom Dashboard makes the page refresh

### ISSUE THREAD

**Issue by Mokatsu** [OpenCTI-Platform/opencti#1167]
## Description

{ Please provide a clear and concise description of the bug. }
I created a custom dashboard, the first panel was great, once I added the second panel and saved. Not ever time I load the dashboard, the page seems to be refreshing non stop to the point where i cant event add more panel or the delete the old ones.

## Environment

1. OS (where OpenCTI server runs): { WSL Kali-Linux Docker}
2. OpenCTI version: opencti/platform:4.2.4}
3. OpenCTI client: frontend
4. Other environment details: Docker-Compose

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Custom Dashboard
2. Create Custom Dashboard Panel
3. Save and view the dashboard
4. Dashboard keep refreshing (every .5 seconds)

## Expected Output

Once the second panel was added I expected to be able to view and interact with my dashboard.

## Actual Output

Dashboard keeps refreshing non stop to the point where I can't even delete it
 
## Additional information

![image](https://user-images.githubusercontent.com/15014768/111418713-2f42aa00-86b6-11eb-95a8-0921f838aed4.png)
![image](https://user-images.githubusercontent.com/15014768/111418748-3d90c600-86b6-11eb-8b63-f865fe9e1dcb.png)
Not sure where I would find the logs for the web ui. 

I also tried viewing the dashboard in different browser and I get the same results.

**Comment by SamuelHassine** [comment]
Hello @Mokatsu,

Can you please tell us which kind of widget you used because it's not a general problem, seems to be linked to specific widgets?

Here, this is working: https://demo.opencti.io/dashboard/workspaces/dashboards/eee28d62-b90e-4477-82fe-011b87651ec2.

Thanks!

**Comment by Mokatsu** [comment]
It was the under threat, by specific actor, indicators, - I think it was the donut.  

So i tried replicating this on a different dashboard and I did not get the same results. Which is great, the thing is my docker container mounts some volumes to have the data persist. I would be okay with just some guidance on how to delete the dashboard without having to go into it.

**Comment by SamuelHassine** [comment]
Hello @Mokatsu,

Ok, please re-open this issue if you manage to have a reproduction case. To delete your broken dashboard, please go to the GraphQL playground (link in your profile: https://demo.opencti.io/dashboard/profile). 

And then type: 

```
mutation {
  workspaceEdit(id: "YOUR_WORKSPACE_ID") {
    delete
  }
}
```

Kind regards,
Samuel
