### ISSUE TITLE
Scheduler to export IoC 

### ISSUE THREAD

**Issue by sorenopsy** [OpenCTI-Platform/opencti#1168]
## Problem to Solve

Would be nice to  have a scheduler, configurable via GUI, that export IoC in various formats (i.e. csv, stix) with different protocols (taxii, http).
This would be very helpful to share intelligence with other partners or customer.

## Current Workaround
Export intelligence with API and leverage crontab and command lines tools

**Comment by SamuelHassine** [comment]
Given the number of current export capabilities (CSV, Stream, TAXII, etc.) implement a scheduled within the platform is not a priority right now.
