### ISSUE TITLE
ForbiddenAccess appears when importing AlienAault

### ISSUE THREAD

**Issue by A1oha** [OpenCTI-Platform/opencti#1169]
## Description
When I import AlienAault by configuring docker-compose.yml, I get a ForbiddenAccess error. Is this caused by an OTX Key error? (Everything is normal when I use OTX Key in python)

## Environment
1. OpenCTI version:4.3.0

## Actual Output

![image](https://user-images.githubusercontent.com/40291952/111450477-63b47580-874b-11eb-960f-92c91497a871.png)
![image](https://user-images.githubusercontent.com/40291952/111450597-834b9e00-874b-11eb-8a10-54f7c0685f56.png)
![image](https://user-images.githubusercontent.com/40291952/111450710-a1b19980-874b-11eb-9af1-4cebf5c167c9.png)

**Comment by richard-julien** [comment]
Hi @A1oha,

Looks like the restriction is on OpenCTI side.
Can you add the access rights of the customer related to the token you setup for your connector?

**Comment by A1oha** [comment]
> Hi @A1oha,
> 
> Looks like the restriction is on OpenCTI side.
> Can you can the access rights of the customer related to the token you setup for your connector?
------------------------------------------------------------------------------------------------------------------------------------
I created a user named “AlienVault”, , and the system generated the corresponding Token. I try to import AlienVault TI through docker-compose.yml. Among them, CONNECTOR_IMPORT_AlienVault_ID is the uuid4 string generated by myself, and OPENCTI_AlienVault_TOKEN is  generated by the system. How can I test whether  user “AlienVault”  can access? 

![image](https://user-images.githubusercontent.com/40291952/111570332-94de8580-87df-11eb-88cf-567b269ad86a.png)

![image](https://user-images.githubusercontent.com/40291952/111570348-a031b100-87df-11eb-8dc6-c8af8e4b7895.png)

![image](https://user-images.githubusercontent.com/40291952/111570368-aaec4600-87df-11eb-9b42-e8785a6616aa.png)

**Comment by richard-julien** [comment]
It's fine to create a user but you also needs to add a role with correct access rights.

**Comment by A1oha** [comment]
> It's fine to create a user but you also needs to add a role with correct access rights.
--------------------------------------------------------------------------------------------------------------------
Thank you, 'AlienVault  OTX' connector can be used after I configure user permissions. But I encountered the following 3 problems,if you can answer I would be very grateful.

Question 1: In local OpenCTI "Observable types", there is an extra string "entity_" (I use the same version as on the official demo platform, both are v4.3.0, but the official platform does not have these strings), may I ask you is there a problem with the configuration of?

![image](https://user-images.githubusercontent.com/40291952/111763020-a2c60080-88dc-11eb-837f-dcf353be2014.png)
![image](https://user-images.githubusercontent.com/40291952/111763233-d4d76280-88dc-11eb-894f-40b378e6ebf8.png)
![image](https://user-images.githubusercontent.com/40291952/111762812-64304600-88dc-11eb-8b2f-2ce6a791a811.png)


Question 2: After selecting multiple "Observable types", it cannot be cleared with one click (even if I jump back from other pages, the previous selection still exists)
![image](https://user-images.githubusercontent.com/40291952/111763991-b32aab00-88dd-11eb-9835-57c86ceaa017.png)

Question 3: Can I add type of Observable by myself?

**Comment by richard-julien** [comment]
Hi @A1oha ,

Question 1: Looks like OCTI have an issue to get your locale language. Its not normal. I will do some tests to try to identify what could cause this. Can you try to force the language of the platform to english and see if you still have the problem? (In Settings/Parameters/Language)

Question 2: We don't have the unselect all for now. Can you create a dedicated feature request for that? Thanks.

**Comment by richard-julien** [comment]
Question 1: bug identifier and fixed in https://github.com/OpenCTI-Platform/opencti/issues/1177. Will be in the next release. For now best solution is to fix the language of the platform in english

**Comment by A1oha** [comment]
Reply:
1. Thank you very much. After I restarted OPenCTI, the "Observable types" display returned to normal (I don't know what caused the previous situation).
2. I posted a new question（#1180） to explain the functionality expected to be implemented in the future.

The latest difficulty:
1. I tried to add a new Connector, but when I clicked 'Settings->Accesses' want to view the token, the page showed such an error. When this error appeared on the 'Accesses' page, I tried to click to jump to other pages under 'Settings', such as 'Parameters', 'Marking', etc. This error also appeared (other pages could be displayed normally), I don’t know what caused this error ? Which log do I need to analyze to analyze the error? 
![image](https://user-images.githubusercontent.com/40291952/111972467-760e2500-8b38-11eb-8557-8bdbec2c4d4d.png)
![image](https://user-images.githubusercontent.com/40291952/111973294-4e6b8c80-8b39-11eb-86a1-90a3cf38d5ff.png)

**Comment by SamuelHassine** [comment]
Hello @A1oha,

Can you please copy/paste the logs you have in the platform (on the API side) when you click on a section?

Kind regards,
Samuel

**Comment by A1oha** [comment]
Hello ,Samuel,
the log is as shown below :
![image](https://user-images.githubusercontent.com/40291952/111979901-96da7880-8b40-11eb-9601-409aafeda74a.png)

**Comment by SamuelHassine** [comment]
Hello @A1oha,

Thanks. it's a bug, referenced in #1181. It will be fixed in the next release.

**Comment by richard-julien** [comment]
Hi @A1oha ,

Its due to a sorting problem.
You should have something like that in your URL : /dashboard/settings/accesses/roles?sortBy=default_assignation&orderAsc=true&searchTerm=

Please change by /dashboard/settings/accesses/roles?sortBy=name&orderAsc=true&searchTerm=
