### ISSUE TITLE
Add Client Certificate Authentication

### ISSUE THREAD

**Issue by sho-illuminate** [OpenCTI-Platform/opencti#1170]
## Problem to Solve

Add Client Certificate Authentication for login.
I don't see an option for client certificate authentication within https://www.notion.so/Configuration-a568604c46d84f39a8beae141505572a although I do see you can add more passport strategies. 

## Proposed Solution

I found two options below which can be implemented.

Link 1 - http://www.passportjs.org/packages/passport-client-cert/
Link 2 - http://www.passportjs.org/packages/passport-client-certificate/

**Comment by sho-illuminate** [comment]
I am currently using centOS7 and running opencti v4.2.4 with docker containers.

**Comment by richard-julien** [comment]
Client cert will be available if your OCTI is configured with a correct https_cert configuration.

**Comment by sho-illuminate** [comment]
Thank you! Would you be able to provide instructions on how to configure OCTI with the https_cert configuration? I'm not sure what I would need to do once I generate the certificates. Is it possible to have a cert configuration docker deployment like the one below?

https://www.notion.so/Configuration-a568604c46d84f39a8beae141505572a
![image](https://user-images.githubusercontent.com/75804627/114747543-f0d4f500-9d1e-11eb-89a7-ba69ea30fc99.png)
