### ISSUE TITLE
Errors with history connector

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1178]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

History connector can't start

## Environment

1. OS (where OpenCTI server runs): macOS Big Sur 11.2.3
2. OpenCTI version: OpenCTI 4.3.0
3. OpenCTI client: FrontEnd with Safari 14.0.3
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. type "python3 history" in a terminal windows
2. History connector don't start and stop with errors

## Expected Output

{ Please describe what you expected to happen. }

## Additional information

Start logging of history connector :

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID:320d1768-e50d-4d85-bac6-cc8d1e130a80
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
Traceback (most recent call last):
  File "/Users/Jerome/Applications/OpenCTI/connectors/history/src/history.py", line 98, in <module>
    HistoryInstance = HistoryConnector()
  File "/Users/Jerome/Applications/OpenCTI/connectors/history/src/history.py", line 23, in __init__
    self.logger_config["elasticsearch_username"] is not None
KeyError: 'elasticsearch_username'

**Comment by richard-julien** [comment]
Hi, do you have a config.yml correctly setup?

**Comment by JeromeSRT** [comment]
my configuration of config.yml for history connector :
opencti:
  url: 'http://127.0.0.1:4000'
  token: 'user-token'
  ssl_verify: True

connector:
  id: '320d1768-e50d-4d85-bac6-cc8d1e130a80'
  type: 'STREAM'
  name: 'Historik Activités'
  scope: 'history'
  confidence_level: 15 # From 0 (Unknown) to 100 (Fully trusted)
  log_level: 'debug'

**Comment by richard-julien** [comment]
Ok. Looks like you use the master code. (4.3.0 tag doesnt have this source code, see https://github.com/OpenCTI-Platform/connectors/blob/4.3.0/history/src/history.py)
The master is use for development.
If you checkout the code yourself please use the appropriate tag.

**Comment by JeromeSRT** [comment]
Ok. I checked in the archive https://releases.opencti.io/opencti-20210321.tar.gz, and history.py code is different from https://github.com/OpenCTI-Platform/connectors/blob/4.3.0/history/src/history.py.
I will use the history.py code tagged 4.3.0.
Thanks for you help.

**Comment by richard-julien** [comment]
Still possible to use https://releases.opencti.io/opencti-release-4.0.3.tar.gz of course.
