### ISSUE TITLE
Infrastructure, Systems and Vulnerabilities

### ISSUE THREAD

**Issue by BeQUIET2** [OpenCTI-Platform/opencti#1182]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It will help us to process CVE faster 

## Current Workaround

Search one by one.

## Proposed Solution

Add a new filter on the Vulnerabilities dashboard 

## Additional Information

No

**Comment by SamuelHassine** [comment]
This will be implemented and covered after we introduce the System identity. So it will be possible to create sightings between systems/organizations and vulnerabilities. In the dashboard, it will be possible to filter vulnerabilities sighted in specific system/organization.

**Comment by SamuelHassine** [comment]
Precision about this:

Infrastructure already can have Vulnerability, what is missing in the UI:

* In all "Identity", Sightings from Knowledge to dedicated top tab
* In Vulnerability, add Infrastructures in Knowledge right menu
* In all "Sightings", add Vulnerability as a supported target of the relationships
