### ISSUE TITLE
Can't export report as JSON

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1183]
## Description

When exporting a report in the UI, the export fails with error: 'NoneType' object is not iterable

## Environment

1. OS (where OpenCTI server runs): demo instance
2. OpenCTI version: 4.3.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a Report  to export
2. Go to the Files section of the Report
3. Click the "Export Files" button, selecting the "Full export" option

## Expected Output

The Report and the objects that are contained in it are exported  to a file in STIX 2.1 json format

## Actual Output

The export fails with: 'NoneType' object is not iterable
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

It seems to not be with all reports, can you please point the report you are trying to export?

Thanks

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Hello @securitiz,

This issues should be solved as soon as the 4.3.1 will actually be released (demo env is not "fully" 4.3.1). Please re-open if it's still failing after the release.

Kind regards,
Samuel
