### ISSUE TITLE
Observable of type "user account" not displayed correctly in the GUI

### ISSUE THREAD

**Issue by sorenopsy** [OpenCTI-Platform/opencti#1187]
## Description

When creating an observable of type user account the display of the value appears as unknown

## Environment

1. OS Docker on RedHat
2. OpenCTI version: 4.3.0
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
From Frontend, Observable, Create Observable

## Expected Output

The value displayed should be  the value of "user_id"

## Actual Output

![image](https://user-images.githubusercontent.com/39803539/112141472-9c35d280-8bd5-11eb-8087-42541134b6b8.png)

**Comment by SamuelHassine** [comment]
Hello @sorenopsy,

I don't understand your issue, the user_id is on the top right of your screenshot. The value is not correct?

Kind regards,
Samuel

**Comment by sorenopsy** [comment]
Hello @SamuelHassine , the Title in the top left is unkown, i would expect to be filled with the value of "user_id", like other observables.
![image](https://user-images.githubusercontent.com/39803539/112142393-d18ef000-8bd6-11eb-84bb-a9398f5868f7.png)
