### ISSUE TITLE
Replace individualal with individual in source code

### ISSUE THREAD

**Issue by azahzah** [OpenCTI-Platform/opencti#1189]
## Description

When we tried to add the **individual-gain** motivation of a threat actor via the python client, it would not add it because of a potential spelling error in the source code.

- https://github.com/OpenCTI-Platform/opencti/blob/a1946d8a7844b7ab5bbc5e101f0e008f6fade2d4/opencti-platform/opencti-front/src/private/components/threats/threat_actors/ThreatActorEditionDetails.js
- https://github.com/OpenCTI-Platform/opencti/blob/4633d4a9509ab6b33b5a767395eeff8a586c5b75/opencti-platform/opencti-front/src/utils/Localization.js
- https://github.com/OpenCTI-Platform/opencti/blob/a1946d8a7844b7ab5bbc5e101f0e008f6fade2d4/opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetEditionDetails.js

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: OpenCTI 4.3.0
3. OpenCTI client: 
4. Other environment details:

## Expected Output

We expected to have a motivation on the interface but we don't have it because of the typo

## Actual Output

The analyst has to reproduce the typo to get the information
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @azahzah,

Thanks for pointing this issue. STIX 2.1 motivation-ov is now `personal-gain` and `personal-satisfaction`.

It will be fixed in the next release.

Kind regards,
Samuel
