### ISSUE TITLE
New error "'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/opencti#119]
Hey,

after the new pull to correct "stix2 module error", I have a new error

```
integration_1    | You are not allowed to do this.
integration_1    | 'NoneType' object is not subscriptable
integration_1    | You are not allowed to do this.
integration_1    | 'NoneType' object is not subscriptable
```

:-(

Antonin

**Comment by SamuelHassine** [comment]
This is linked to the configuration of the integration that is generated or present in the volume "config". You can either: clear your Docker and start fresh with new volumes, or change directly the configuration in this volume and change the API key. I do not know why the key is stick to the old one, but is clearly a problem of how you implement the persistence.

**Comment by AntoninHL** [comment]
:-(
ok... so I will destroy volumes... and restart all imports :-(

**Comment by richard-julien** [comment]
Sorry for that situation @weSh. It's clearly a kind of situation we want to avoid in the future. We plan to refactor this part to prevent any future problem of this nature.

**Comment by richard-julien** [comment]
Will be fix by https://github.com/OpenCTI-Platform/opencti/issues/74 and https://github.com/OpenCTI-Platform/opencti/issues/121
