### ISSUE TITLE
Problem with VM credentials 

### ISSUE THREAD

**Issue by kenshinsamue** [OpenCTI-Platform/opencti#1193]
I've installed the VM version in a virtualbox virtual machine, it's all ok but when i try to autenticate either in 
`{IP VM}:8080` or `{IP VM}:3000` with the credentials  that are in the documentation:

`opencti`/`openctiopencti`  for the 3000 port on the stack and `admin@opencti.io`/`admin` for the 8080

I HAVE access to the machine, so in that part there is not problem, what can i do ?

**Comment by SamuelHassine** [comment]
Hello @kenshinsamue,

What do you see on the port 3000, can you give us a screenshot?

Kind regards,
Samuel

**Comment by kenshinsamue** [comment]
ok, @SamuelHassine 
This is the portal on the port `8080`
![imagen](https://user-images.githubusercontent.com/25704766/112307277-aa005c00-8c98-11eb-919b-aae12e6a3fba.png)
In the `POST` request there is the credentials correct:
![imagen](https://user-images.githubusercontent.com/25704766/112307362-c56b6700-8c98-11eb-83b3-e94e028fcd3a.png)

And in the `3000` Port I have the following:
![imagen](https://user-images.githubusercontent.com/25704766/112307560-03688b00-8c99-11eb-84fa-05900cfcf3b6.png)
The `POST` request:
![imagen](https://user-images.githubusercontent.com/25704766/112307628-154a2e00-8c99-11eb-825a-43522dbc1fb6.png)

**Comment by SamuelHassine** [comment]
Hello,

You take the OpenEx virtual machine image and not the OpenCTI one. 

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Is your problem solved?

**Comment by kenshinsamue** [comment]
yes ! i downloaded the wrong ova file. Thanks
