### ISSUE TITLE
Unable to filter reports by status in the frontend

### ISSUE THREAD

**Issue by maertv** [OpenCTI-Platform/opencti#1197]
## Description

It seems that it is not possible to filter reports by status in the frontend.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.5 LTS
2. OpenCTI version: _master_ (4.3.1)
3. OpenCTI client: frontend (4.3.1)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Activities > Analysis > Reports
2. Click on the Filter icon.
3. Try to select the Status as filter, but there are no options to choose from.

## Expected Output

The report list shows reports matching the selected status(es).

## Actual Output

Unable to select the status as filter.

**Comment by maertv** [comment]
I have proposed a possible solution.

I am not sure if this is the best way to solve it. I could be wrong but I think that the original implementation didn't work because the https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/database/elasticSearch.js#L1287 uses `.keyword` but the value of _x_opencti_report_status_ is an integer.

I haven't created a PR for this yet for the given reason.

**Comment by SamuelHassine** [comment]
Hello @maertv,

Nice catch, and you're right about the reason. I've fixed it :)

Kind regards,
Samuel
