### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by SvenScherf** [OpenCTI-Platform/opencti#120]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description
after the logon the dashboard has no informations

## Environment
OS  Ubuntu 18.4.2 LTS
OpenCTI version latest

## Reproducible Steps
1. docker-compose up -d
2. docker logs <container ID from opencti/integration> 
3. docker logs <container ID from opencti/worker> 

## Actual Output
Waiting for token in shared config...
Waiting for token in shared config...
Waiting for token in shared config...
Waiting for token in shared config...

**Comment by SamuelHassine** [comment]
Hello, please see #119.
