### ISSUE TITLE
When click on the "Linked Observables +" of Observable, it does not show any of the observables.

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1210]
## Description
When I clicked on the "Linked Observables +" of an observable to add LINKED OBSERVABLES, I did not see any of the observables. It seems to be a bug.

## Environment

1. OS (where OpenCTI server runs):  AWS 
2. OpenCTI version:  OpenCTI 4.2 
3. OpenCTI client: Frontend
4. Other environment details: na

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click "Observations"
2. Click one observables 
3. Click LINKED OBSERVABLES +
4. It shows nothing

## Expected Output

It should show some observables for me to select.

## Actual Output

![image](https://user-images.githubusercontent.com/10161931/112810357-83ce2800-90ad-11eb-8bb9-953fb2a7c2af.png)
![image](https://user-images.githubusercontent.com/10161931/112810441-9a747f00-90ad-11eb-8ea0-36fa8d3d8ed1.png)

 
## Additional information

N/A

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

We intend to enhance this in the future, but for the moment this list shows only the possible observables to link in the right direction. For instance, if you create an email address and an email content obsevables, you will be able to link them from the email content to create from/to/cc/bcc relationships. Same for instance with IPv4 and Domain. 

![image](https://user-images.githubusercontent.com/1334279/112823185-3fc92c00-9089-11eb-8aba-c071a4a9f7d7.png)

Some relationships may be missing (such as Hostname to IPv4), please can you open an issue with the relationships you need?

Kind regards,
Samuel

**Comment by ckane** [comment]
I just installed 4.3.4 using the docker method, and this list is always empty for me. I've got 244 observables: hostnames, IPs, files, email addresses, and none of them let me forge relationships to other observables. If I try to manually do it with the "+" by typing in the value of an existing observable, the dialog silently goes away without doing anything after I click "CREATE". If I enter info for a non-existent observable, the observable is created at the global level and never gets related to this observable.

**Comment by tanyawang1218** [comment]
Hi @SamuelHassine, 

As @ckane mentioned, this is what I also encountered, that's why I submit the ticket. Could you please help this?
Thank you a lot.

Regards,
Tanya

**Comment by tanyawang1218** [comment]
Hi @SamuelHassine , just like @ckane mentioned above, **"this list is always empty for me"** do you have any idea? :)

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

This problem is now solved in OpenCTI 4.5.0. Please let us know if you still have any problem!

Kind regards,
Samuel
