### ISSUE TITLE
Doesn't show the new added observable added by the bottom right button "+" in "LINKED OBSERVABLES +" of observable 

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1211]
## Description

In an observations, click one observable, and click the LINKED OBSERVABLES + to add a new observable, but it doesn't show in the list.

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: e.g. OpenCTI 4.2
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click "Observations"
2. Click one observables
3. Click LINKED OBSERVABLES +
4. Click the bottom right button "+" to add observable
5. Click Create
6. It didn't be displayed in the list to add relationship
## Expected Output

It should show the new added observable in the relationship list

## Actual Output

Nothing is displayed.
 
## Additional information

na

**Comment by SamuelHassine** [comment]
Duplicate with #1210.
