### ISSUE TITLE
Country can be created, but not showing in the country list.

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1213]
## Description
I created a "Country" , but it's not there, it's all blank for some reason.
But when I searched I found it.

ps. It should be because it doesn't be linked to a region when creating, so it can't be shown there. Maybe to add a relation to a region when creating a country can solve the issue.

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: OpenCTI 4.2
3. OpenCTI client: Frontend
4. Other environment details: na

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Entities 
2. Click Countries
3. Click the bottom right corner + to create one
4. The new added country doesn't be listed. 

## Expected Output

The new created country should be displayed in the list. 

## Actual Output

The new created country doesn't be displayed in the list
 
## Additional information

NA

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

The best practice is to enable the `OpenCTI datasets` connector to create proper countries/regions. If you want your country to appear in the list, please create a "Region" first and then add your country to the region (here an example: https://dmeo.opencti.io/dashboard/entities/regions/b1f8981f-4626-4ea8-acc7-39c7b3c2c212/knowledge/countries).

Kind regards,
Samuel

**Comment by tanyawang1218** [comment]
Got it, thank you for the response.

**Comment by manonviallet** [comment]
Good afternoon, if this issue is solved, I am closing it. Don't hesitate to open it back, to open a new one or/and to join the slack channel if you have additional questions !
