### ISSUE TITLE
Error importing/exporting CSV

### ISSUE THREAD

**Issue by naxonez** [OpenCTI-Platform/opencti#122]
## Description
When I try to export CSV with data, the file is not correctly enconded. If you test to run a file this show the following line:

$> file Reports.csv 
Reports.csv: UTF-8 Unicode (with BOM) text

And its imposible to import again:
[2019-07-06 16:56:58] An unexpected error occurred: { Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0) }

## Environment
Docker OpenCTI

## Reproducible Steps
Steps to create the smallest reproducible scenario:
1. Export to CSV.
2. Try to Import.
3. Error: [2019-07-06 16:56:58] An unexpected error occurred: { Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0) }

**Comment by SamuelHassine** [comment]
Hello @naxonez, please see #123 and #65.
