### ISSUE TITLE
Freezed Dashboard

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1222]
## Description
The main dashboard is not changing no matter how much feeds I receive, it looks the same

## Feeds & Dashboard Yesterday:
![image](https://user-images.githubusercontent.com/37035465/113016393-1abae300-9187-11eb-8917-4473f4ddc71c.png)
![image](https://user-images.githubusercontent.com/37035465/113016451-29a19580-9187-11eb-853a-2c09ab74b9f4.png)

## Feeds & Dashboard Today::
![image](https://user-images.githubusercontent.com/37035465/113016676-640b3280-9187-11eb-9252-1ae5fd3180ea.png)
![image](https://user-images.githubusercontent.com/37035465/113016723-6d949a80-9187-11eb-9728-8fac6e8937f1.png)

## Environment
1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 4.2

## _
How can I reset the dashboard to allow it be rebuild?

Regards,
Khalid

**Comment by SamuelHassine** [comment]
Hello,

Can you please take a look to the worker(s) logs? Any errors?

Kind regards,
Samuel

**Comment by khalidrehan** [comment]
Hello @SamuelHassine ,

unfortunately, I have disabled it; as it was consuming my diskspace.
I will have to enable it and get back to you.

Regards,
Khalid

**Comment by khalidrehan** [comment]
> Hello,
> 
> Can you please take a look to the worker(s) logs? Any errors?
> 
> Kind regards,
> Samuel

Hello @SamuelHassine ,

## Errors:
```
ERROR:root:Unknown object type "x-mitre-tactic", doing nothing..
..
...
..
ERROR:root:Missing reference to handle creation..
```

Attached workers logs.

Regards,
Khalid
[Workers.zip](https://github.com/OpenCTI-Platform/opencti/files/6235418/Workers.zip)

**Comment by khalidrehan** [comment]
Hello @SamuelHassine 

Can I flush the dashboard so it regenerates?

I updated the OpenCTI to the latest version, and still get the same dashboard.

Regards,
Khalid

**Comment by manonviallet** [comment]
Good afternoon @khalidrehan
Did you manage to solve this question, or do you still have this issue ? 
I would suggest turning to the slack channel if you would like real-time help from the community !

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
