### ISSUE TITLE
First object added to  Report not visible in Knowledge graph

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1223]
## Description

The first object added to a Report (whether created from within the report, or  created previously), is not visible in the Knowledge Graph. It reappears upon the addition of a second object to the Report.

This doesn't appear to be specific to a particular type of object.

## Environment

1. OS (where OpenCTI server runs): demoo
2. OpenCTI version: OpenCTI 4.3.4
3. OpenCTI client: Front End
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Report
2. Add an object to the Report via the Knowledge Graph

## Expected Output

The added object is visible in Knowledge Graph

## Actual Output

There are no objects visible in the Knowledge Graph
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @securitiz,

I'm not able to reproduce your issue. Can you please take a screenshot or a video?

Thanks.

Kind regards,
Samuel

**Comment by securitiz** [comment]
Samuel,

I've attached a ZIP that contains a screen recording. 
[OpenCTI_Error_20210331.zip](https://github.com/OpenCTI-Platform/opencti/files/6240091/OpenCTI_Error_20210331.zip)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Ok I see, but still unable to re-produce it.... What is the version of your Chrome browser?

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Hello @securitiz,

This should now be solved in the demo instance. Can you please give a try and confirm me?

Thanks!

Kind regards,
Samuel

**Comment by securitiz** [comment]
Hi Samuel,

I've tested in the demo instance (4.3.5), and continue getting the same issue in both  Firefox  and Chrome browsers. I'm also having the issue in our own deployment of OpenCTI 4.3.4
