### ISSUE TITLE
Question: Why is it my map does not show any color just like OpenCTI demo?

### ISSUE THREAD

**Issue by fareedfauzi** [OpenCTI-Platform/opencti#1224]
Here we can see the map does not show any color unlike the Demo dashboard. The data from workers works like charm.

![image](https://user-images.githubusercontent.com/56353946/113096407-adab5a00-9227-11eb-9871-63b0af18d27c.png)

My connectors:
![image](https://user-images.githubusercontent.com/56353946/113096527-ea775100-9227-11eb-829d-803773cddbaa.png)

Any idea why and where the source of the map come from?

**Comment by SamuelHassine** [comment]
Hello,

Please enable the "OpenCTI datasets" connector to have countries/regions (and their latitude/longitude). Then the map is built using victimology (targets relationships to the countries).

Kind regards,
Samuel

**Comment by fareedfauzi** [comment]
@SamuelHassine hi samuel, may I ask the system requirements for OpenCTI?

I have allocated 32GB resources of RAM for OpenCTI, but still I have trouble with my memory resources.

![image](https://user-images.githubusercontent.com/56353946/113479012-f761a200-94be-11eb-8768-eb21daf46f84.png)

**Comment by SamuelHassine** [comment]
@fareedfauzi You've deployed all the components in one VM? The only `java` process in our components is ElasticSearch, have you put memory limits for the ElasticSearch JVM? On Debian-based systems, it's in `/etc/elasticsearch/jvm.options`: 

```
# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms10g
-Xmx10g
```

If you're in Docker, let's fix the environment variable `"ES_JAVA_OPTS=-Xms512m -Xmx512m"` as described in https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html.

**Comment by fareedfauzi** [comment]
Yup. I deployed all components in one VM. Alright, I'll try first.
