### ISSUE TITLE
Introduce a garbage collector on revoked entities and old observables (with customizable settings)

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#1228]
## Problem to Solve

Currently, the platform just store everything without any retention policy.

## Current Workaround

Management of ElasticSearch rollover.

## Proposed Solution

Introduce a garbage collector on revoked entities and old observables (with customizable settings)

## Additional Information

None.

**Comment by kudrew** [comment]
Hey @SamuelHassine , our analysts have a request for the vision of the garbage collector:

When they go through the ingested reports and delete any unimportant observables, they also want the platform to delete the observable from the entirety of the platform if it doesn't have any relationships to anything else after. 

They currently have to manually delete the observable after removing it from a report. 

They would also like this feature to check if it should trigger after an entity is removed from a report. (As opposed to checking whenever and deleting all observables that have no relationships to anything in the entire platform)

**Comment by richard-julien** [comment]
Hi @kudrew , 
I will take a look for the "orphan" condition for deletion but i dont think the retention manager will be able to react to specific behavior in report. So basically you will be able to configure something like

> OBSERVABLES deletion IF OLDER_THAN (last updated) > 3 days AND ORPHAN=true

If an analyst remove the observable from a report the deletion will occurs 3 days after.

**Comment by richard-julien** [comment]
Not completely sure also about the ORPHAN definition.

For me its:
* Not contained in a container (not part of any object_refs)
* No existing stix relations from or to it (uses, part_of, ...)

So if your observables is inside an observed_data or report = is not an orphan, if observable have only a "linked-to" other observable is not an orphan.

@SamuelHassine any idea on that?
