### ISSUE TITLE
How to query SDO relationship by SDO  ?

### ISSUE THREAD

**Issue by Songchunbo** [OpenCTI-Platform/opencti#1233]
Hi,
     I  created a 'indicates' relationship between attack-pattern and indicator. Now I know the MITRE technique ID such T1548, I can query attack-pattern by 'x_mitre_id' such as T1548,  how can I query the indicator related to the attack-pattern ?

 I can use the following GraphQL statement query the attack-pattern.

```
{
  attackPatterns(filters:{key:x_mitre_id,values:["T1548"]}) {
    edges {
      node {
        id
        x_mitre_id
        externalReferences {
          edges {
            node {
              external_id
            }
          }
        }
      }
    }
  }
}
```

But I don't find any clue to query the relationship by attack-pattern 
```
{
  stixCoreRelationships  {
    edges {
      node {
        id
        entity_type
        standard_id
        description
        relationship_type 

        }
      }
    }
  
}
```

**Comment by SamuelHassine** [comment]
Hello,

Please use:

```
query {
  stixCoreRelationships(fromId: "INDICATOR_ID") {
    edges {
      node {
        id
        from {
          ... on StixDomainObject {
            id
          }
          ... on Indicator {
            pattern
         }
        }
        to {
          ... on StixDomainObject {
            id
          }
          ... on AttackPattern {
             name
          }
        }
      }
    }
  }
}
```

As a filter for StixCoreRelationships, you have:

fromId: this is the fromId of the relationships
toId: this is the toId of the relationships
elementId: you don't know if this is from or to, you want everything related to this Id
toTypes: array of types you want.
relationship_type: the type of relationship for instance

**Comment by Songchunbo** [comment]
Got it. Thanks for your quick answer, SamuelHassine
