### ISSUE TITLE
Its says it has 1 indicator relationships BUT there is nothing listed under Indicators 

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1235]
## Description

Its says it has a indicator relationships BUT there is nothing listed under Indicators (or any of the other knowledge tabs actually)
https://demo.opencti.io/dashboard/arsenal/vulnerabilities/e63a7971-5e4b-4175-8f0d-e12f097e4f7c/knowledge/overview

## Environment

1. OS (where OpenCTI server runs): demo site
2. OpenCTI version: demo site
3. OpenCTI client: frontend
4. Other environment details: n/a

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add a vulnerability to an indicator.
![image](https://user-images.githubusercontent.com/10161931/113679467-5d823b00-96f2-11eb-8812-4e617cc56d9c.png)

2. Go to the vulnerability, and it shows one indicator related to it
![image](https://user-images.githubusercontent.com/10161931/113679582-7ee32700-96f2-11eb-8adf-9a3786477fcd.png)

3. Go to indicator tag, it shows no indicator
![image](https://user-images.githubusercontent.com/10161931/113679673-99b59b80-96f2-11eb-8c55-7860b8fe311b.png)

## Expected Output

Show the indicator.

## Actual Output

It didn't show the indicator
 
## Additional information

n/a

**Comment by SamuelHassine** [comment]
Hello,

This is because the relationship should be "indicates" and not "related-to". We will add a generic section for all "related-to" relationships in the future.

**Comment by SamuelHassine** [comment]
You have now access to a "Related to" generic section as here: https://demo.opencti.io/dashboard/threats/intrusion_sets/66bce514-9d8e-48a5-9fcb-23416c37b193/knowledge/related.
