### ISSUE TITLE
There seems to be a limit to how many entities are shown on a page

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1236]
## Description

It shows many entities in "individuals", but can't scroll down. 
(It seems only "individuals" with this kind of bug.)

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: 4.2
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the individuals, it shows there are 345 entities.
![image](https://user-images.githubusercontent.com/10161931/113685672-12b7f180-96f9-11eb-8973-9682b63a6c19.png)

2. Scroll down, but can't scroll down to see completed entities.

## Expected Output
Can scroll down for "individuals"

## Actual Output
Can't scroll down for "individuals"

 
## Additional information
n/a

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

This is a bug, it will be solved in the next release.

Kind regards,
Samuel
