### ISSUE TITLE
Can't import Mitre/OpenCTIData

### ISSUE THREAD

**Issue by naxonez** [OpenCTI-Platform/opencti#124]
## Description

I cant retrieve information from Mitre/OpenCTI 

## Environment
Docker OpenCTI

## Reproducible Steps
1.- Configure connector
2.- Force it
3.- Get the following error in schedule.log:
[2019-07-07 11:23:30] Unable to run openctidata: {<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>}

**Comment by SamuelHassine** [comment]
Hello @naxonez, the configured URL for the sectors file is `https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json`?

**Comment by naxonez** [comment]
Hello @SamuelHassine ,

Yes:

![Selección_001](https://user-images.githubusercontent.com/7959568/60767711-ab9c8180-a0bb-11e9-82b7-77b99c39bb48.png)

**Comment by naxonez** [comment]
Hi again,

Solved, was a problem with Iptables and Docker.

Thanks!
