### ISSUE TITLE
Add more filters on the export taxii module

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1243]
Hi,
You guys did a great job in enhancing OpenCTI.
I would like to request to add more filters in the export section.
Can you please add in the filter the confidence level and score? Reason, we don't want our endpoint to pull data from opencti with low confidence level or low score value.

![image](https://user-images.githubusercontent.com/20463433/114197267-2b562080-9920-11eb-9346-38a0729ec410.png)

Let's say, I only want to grab those indicators with confidence level => 15 or score => 50
![image](https://user-images.githubusercontent.com/20463433/114198042-e41c5f80-9920-11eb-8713-142993f93727.png)

**Comment by rguignard** [comment]
I suggest to take in account the "x_opencti_detection" attribute too

**Comment by NetEyes** [comment]
> I suggest to take in account the "x_opencti_detection" attribute too

the more the filter, the better
