### ISSUE TITLE
Ability to customize TA types, motivations, etc.

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1244]
## Problem to Solve

Currently, TA types and motivations may not fit the taxonomy model of an org. The ability to add custom options, or edit/remove options, would be helpful.

## Current Workaround

Use the existing TA types, motivations. 

## Proposed Solution

Add the ability for admins to make changes to parameters available to users to describe TAs, such as the available TA types, motivations, etc.

**Comment by SamuelHassine** [comment]
All work around custom ontology will be followed in #1602.
