### ISSUE TITLE
Filtering of "observed data" in "Data curation" returns nothing

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#1245]
## Description

Filtering of "observed data" in "Data curation" returns nothing.

## Environment

https://demo.opencti.io/ 

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1.  Open https://demo.opencti.io/dashboard/observations/observables and check that you have a few observables 
2. open https://demo.opencti.io/dashboard/data/curation
3. filter with "Observed Data"

## Expected Output

The observables 

## Actual Output

No observables

**Comment by SamuelHassine** [comment]
Hello @2xyo,

The "Entities" in data curation only relates to SDO. Observed data is the actual entities listed here:  https://demo.opencti.io/dashboard/events/observed_data. 

If you with to manage Observables, go directly to: https://demo.opencti.io/dashboard/observations/observables.

You will now see the same features as in the data curation module ;)

Kind regards,
Samuel

**Comment by 2xyo** [comment]
My bad, I confused "observables"  / "observed data"   :sweat_smile:

As observables are not in data curation, how can I bulk delete observables from the UI ?
