### ISSUE TITLE
OpenCTI strategic roadmap

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#126]
## Problem to Solve

Everyone should be able to consult the strategic roadmap around openCTI

## Current Workaround

No

## Proposed Solution

Create the roadmap on https://www.opencti.io/roadmap

## Additional Information

The roadmap is a view of the openCTI strategic target.

**Comment by SamuelHassine** [comment]
The strategic roadmap is now available on: https://www.opencti.io/en/roadmap/. In English and French.
