### ISSUE TITLE
Synchronization does not work completely.

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#1262]
## Description

When 2 OpenCTI platforms are connected, not all data synchronizes. This does not allow this synchro connector to be used as a data backup.

For instance, severals reports, users, roles,... are not synchronized.

## Environment
	1. OS : Debian
	2. OpenCTI version: 4.3.5
	3. OpenCTI client: Frontend
	4. Other environment details:

## Reproducible Steps

Connect 2 instances with data and check if all data is present in the 2 platforms.

## Expected Output

You need perfect synchronization. In addition, synchronization errors do not appear in the sync connector. This does not improve the speed of fixing bugs.

## Actual Output

Severals information, missing whole reports

**Comment by richard-julien** [comment]
Built in synchronization is now available in OPENCTI https://github.com/OpenCTI-Platform/opencti/releases/tag/5.0.0
