### ISSUE TITLE
MISP Connector | 0 events have been processed

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1263]
## Description
MISP Connector is running, but not importing any events.
![image](https://user-images.githubusercontent.com/37035465/114531726-d5051c80-9c54-11eb-9ab2-7a70d86756aa.png)

Connector `config.yml`
![image](https://user-images.githubusercontent.com/37035465/114531696-cd457800-9c54-11eb-8675-4b95c6cd1d8e.png)

## Connector log tail:
```
INFO:root:Reporting work update_received opencti-work--89ce519a-f03e-421f-9a6d-bbbf5db87d58
INFO:root:Initiate work for 6b039104-178a-456d-97ea-e1d7ee6372b8
INFO:root:Connector last run: 2021-04-13 09:36:52
INFO:root:Fetching MISP events with args: {"tags": {"OR": ["*"]}, "null": 1618306612, "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector successfully run (0 events have been processed), storing last_run as 1618306672
INFO:root:Reporting work update_received opencti-work--382342bb-f1cd-46e1-8037-d11be3ab331e
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 4.3.5
3. PyMISP: ver. 2.4.141.1

## Attached resent log files.
[202104_opencti-misp.zip](https://github.com/OpenCTI-Platform/opencti/files/6302744/202104_opencti-misp.zip)

Regards,
Khalid

**Comment by SamuelHassine** [comment]
Hello @khalidrehan,

Please juste let the "import_tags" empty if you want to import everything. Here you are importing events tagged with "*".

Kind regards,
Samuel

**Comment by khalidrehan** [comment]
Hi @SamuelHassine ,
I changed it, and still nothing.
![image](https://user-images.githubusercontent.com/37035465/114729073-54274d00-9d48-11eb-9a5f-90fe2441fcdb.png)

I will try to give more time, and fetch recent MISP events.

Regards,
Khalid

**Comment by khalidrehan** [comment]
![image](https://user-images.githubusercontent.com/37035465/114734413-d9acfc00-9d4c-11eb-9e3e-a4b64240dbc6.png)

**Comment by SamuelHassine** [comment]
Can you please give the logs of the connector when doing this query? Which MISP version are you using?

**Comment by ckane** [comment]
Make sure to reset the connector after changing that tag filter, too. I think it uses "time since last run" vs. "timestamp of event" to decide what to import, too.

**Comment by khalidrehan** [comment]
> Can you please give the logs of the connector when doing this query? Which MISP version are you using?
Hello @SamuelHassine 

MISP Version: v2.4.141

Log sample:
```
INFO:root:Processing event eb8ec4e4-ea78-4cf5-80bc-974e765f08df
INFO:root:Event creator organization CIRCL not in import_creator_orgs, do not import
INFO:root:Processing event 174f7375-c811-4c4a-81e0-1d41582f340d
INFO:root:Event creator organization CIRCL not in import_creator_orgs, do not import
INFO:root:Processing event 9362e0e3-62ff-475e-8d32-1ffbb5078e8d
INFO:root:Event creator organization CIRCL not in import_creator_orgs, do not import
INFO:root:Fetching MISP events with args: {"tags": {}, "null": 1618901799, "limit": 50, "page": 30}
INFO:root:MISP returned 0 events.
INFO:root:Connector successfully run (1427 events have been processed), storing last_run as 1618901878
INFO:root:Reporting work update_received opencti-work--fcaef527-9b13-4ba3-9b0d-a2889b2db835
```

The log started to look different when I used the `uuid `from the sync-user [`create sync`] as the connector id !

Regards,
Khalid

**Comment by khalidrehan** [comment]
Hello @SamuelHassine 

I hashed some optional filters, and the connector started to import events:
![image](https://user-images.githubusercontent.com/37035465/115352753-64b04b00-a1c0-11eb-9633-d11a278c06da.png)


Regards,
Khalid
