### ISSUE TITLE
The description content is different from the preview page.

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#1265]
## Description
Add a table by html tag to the description on a report, in preview toggle, it can show the table, but in the description of report, it didn't show table, it shows html tag. 

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: Demo site
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report https://demo.opencti.io/dashboard/analysis/reports/bbababd7-0bf7-4066-9ddf-420726fd874f
2. When you look at the Description , you can see the Bold / Italics etc works – but the HTML Tags I added are escaped
3. However, if you edit that page and click the Preview toggle (instead of Write) – you can see really nicely formatted tables 
4. So what I’m wondering – it seems a bug that Descriptions didn't show the table correctly.

## Expected Output

Text fields (or at least Descriptions) should use the style of the Preview instead of the Escaped version. (Table should be shown instead of showing HTML tag)
![image](https://user-images.githubusercontent.com/10161931/114646041-1d801100-9d0d-11eb-8f53-c29183a3be88.png)

## Actual Output

Text fields (or at least Descriptions) didn't use the style of the Preview : - (
![image](https://user-images.githubusercontent.com/10161931/114646013-0e00c800-9d0d-11eb-9173-ce8b019a668a.png)

 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
LInked to #904.
