### ISSUE TITLE
OpenCTI fails to start with clean Redis instance

### ISSUE THREAD

**Issue by dcode** [OpenCTI-Platform/opencti#1269]
## Description

If starting OpenCTI that has already been initialized and the redis instance has been replaced, thus missing `stream.opencti`, then opencti will fail to start with the following logs:

```
{"category":"APP","version":"4.4.0","level":"info","message":"[OPENCTI] Servers ready on port 8080","timestamp":"2021-04-16T15:19:58.526Z"}
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^
ReplyError: ERR no such key
    at ue (/opt/opencti/build/index.js:1:85637)
    at i (/opt/opencti/build/index.js:1:86101)
    at /opt/opencti/build/index.js:1:86401
    at Object.start (/opt/opencti/build/index.js:1:86444)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async xt (/opt/opencti/build/index.js:1:227086) {
  command: { name: 'XINFO', args: [ 'STREAM', 'stream.opencti' ] }
}
```

## Environment

1. OS (where OpenCTI server runs): Kubernetes  1.18.16-gke.502 
2. OpenCTI version:  OpenCTI 4.4.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run a clean opencti environment (this works from the docker-compose environment too)
2. Ensure the environment is initialized, has a user, etc
3. Delete redis and its persistent storage
4. Create a new instance of redis
5. Restart opencti

## Expected Output

I expected that anything in the current work queue of OpenCTI would be lost, but that it would re-initialize redis with a clean work queue

## Actual Output

OpenCTI fails to read information about the stream `stream.opencti` and crashes.
 
## Additional information

I understand this isn't a desirable state to be in and it shouldn't happen, but sometimes Redis crashes and there's not a smooth process to recover from this.

**Comment by dcode** [comment]
I was able to work around this by using `redis-cli` and issuing the following

```
XADD stream.opencti * {}
```

After restarting the opencti instance, I'm back in business 🥳 

**NOTE** for others finding this in the future, this is not the recommended fix. It could cause other bad things to happen to your install.

**Comment by ckane** [comment]
I also was running into this problem too after upgrading to 4.4.0.

**Comment by richard-julien** [comment]
If you had this problem after upgrade you have a problem in your install configuration.
Data from redis must not be loss after a container upgrade/restart.

**Comment by mwatermolen** [comment]
Seems to be affecting docker version 4.50, when I spin up everything in Kubernetes .. For visibility [https://github.com/OpenCTI-Platform/docker/issues/26](https://github.com/OpenCTI-Platform/docker/issues/26)
