### ISSUE TITLE
OpenCTI and dependencies memory documentation 

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#127]
## Problem to Solve

Currently its not clear the amount of memory required to have openCTI running

## Current Workaround

No

## Proposed Solution

Write documentation about openCTI and dependencies.
- Grakn (4go) + Inner cassandra (4go)
- Elasticsearch (2go)
- Redis (512 Mo)
- RabbitMQ (256 Mo)
- OpenCTI API. (64 Mo)
- OpenCTI worker (64 Mo)
- OpenCTI connector (64 Mo)

## Hints
- Grakn: Open question https://discuss.grakn.ai/t/memory-configuration-in-docker/1245

> The Cassandra heap should be no less than 2GB, and no more than 50% of your system RAM
> Heaps smaller than 12GB should consider ParNew/ConcurrentMarkSweep garbage collection
> Heaps larger than 12GB should consider G1GC

- Elastic: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
- Redis: https://hub.docker.com/r/bitnami/redis/
- NodeJS: By default the memory limit in Node.js is 512MB. https://medium.com/@ashleydavis75/node-js-memory-limitations-30d3fe2664c0
- Python: https://docs.python.org/3.7/library/resource.html, or with container https://ss64.com/bash/ulimit.html / https://www.admin-linux.fr/controle-des-ressources-systemes-ulimit/

**Comment by SamuelHassine** [comment]
@richard-julien This will be in a specific documentation page with links to documentation of dependencies on how enforce memory limits (ElasticSearch, Grakn, Redis and Minio).

**Comment by richard-julien** [comment]
I think we need to enforce a default configuration that work with the minimal requirement. And of course explains this choice in the doc.
