### ISSUE TITLE
Add ARM support by building OCTI with multi-arch

### ISSUE THREAD

**Issue by Dviros** [OpenCTI-Platform/opencti#1271]
Hi there,
Having the exact same issue, even when running with the latest default docker.yml config:
standard_init_linux.go:211: exec user process caused "exec format error"

Running on Ubuntu 18.04

_Originally posted by @Dviros in https://github.com/OpenCTI-Platform/opencti/issues/88#issuecomment-821906450_

**Comment by richard-julien** [comment]
Hi @Dviros , do you use x86 or ARM hardware?

**Comment by Dviros** [comment]
Hey @richard-julien, attempting to run on Nvidia Jetson Nano (which is ARM based...)
Could that be the issue? Are the docker images not optimized for ARM?

**Comment by richard-julien** [comment]
Hi @Dviros, today the OCTI docker images is only built for x86. 
Supporting ARM looks interesting. I change a bit your ticket to make it a feature request.
Interesting link https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
Of course if you have some time you can try directly yourself to build OCTI for ARM with buildx.

**Comment by Dviros** [comment]
Thanks a lot for the clarifications. Will take a deeper look into that

**Comment by richard-julien** [comment]
Start trying to build for ARM.
### First result for building the frontend
`#12 431.5 error /opt/opencti-build/opencti-front/node_modules/node-sass: Command failed.`
Looks like node-sass are not built for ARM yet. See https://github.com/sass/node-sass/issues/3033

### First result for building the API
Compiled with success.

So looks like we need to wait for node-sass or try to remove it from the front stack. We currently used it with react-timeline-range-slider, so maybe not so easy to do :) @SamuelHassine ?

**Comment by kirintwn** [comment]
FYI, `node-sass` is also not compatible with node.js 16: https://github.com/sass/node-sass/issues/3077.
