### ISSUE TITLE
Add custom entities to OpenCTI

### ISSUE THREAD

**Issue by cyberkun12** [OpenCTI-Platform/opencti#1272]
## Problem to Solve

I was asked to add new entitles(tat are not included in STIX) to my instance of OpenCTI.
Add custom entities to my system

## Current Workaround

Add custom JSON structure to the system

## Proposed Solution

Allow custom JSON structures to the system

## Additional Information

Thank you

**Comment by SamuelHassine** [comment]
Hello @cyberkun12,

For the moment, we don't plan to allow custom entities / relationships. That being said, we regularly extend the STIX model in the platform to allow more use cases for FIMI, vulnerabilities management, etc.

Please open an issue with what you need and a quick description of your use case and we will be glad to take a look and implement this asap.

Kind regards,
Samuel
