### ISSUE TITLE
OpenCTI & Threat Hunting & GraphDB

### ISSUE THREAD

**Issue by cuserdzy** [OpenCTI-Platform/opencti#1289]
Hello Guys, I have some conceptual and methodological confusion on OpenCTI.
Recently I see a nice picture describe some OSS TIPs.
![image](https://user-images.githubusercontent.com/30541731/115823780-81a38300-a439-11eb-9659-08199b30cd45.png)

I see OpenCTI is almost a Knowledge Management, so I think how could I use OpenCTI to do threat hunting, I found an article talk about this [Releasing an integration with the field: OpenCTI + Tanium Platform](https://medium.com/luatix/releasing-an-integration-with-the-field-opencti-tanium-platform-bec70a06dfce), from the article, I could understand use Tanium is Live-Hunt, and search in logs/data lake is Retro-Hunt, they are basic hunting.

But most of the time, I need to pivot from one to another in threat hunting, so why OpenCTI doesn't use GraphDB(I see Grakn removed in OpenCTI v4) rather than using ES to search data, isn't Pivot useful than Search? 

And another question, some details information I want to Pivot doesn't supported by OpenCTI now, I try to use STIX2 extension, if I use a new Observable, it couldn't store into OpenCTI, if I use an extension property in Observable, it could store into OpenCTI, but OpenCTI couldn't show the detail extension in UI and couldn't search the extension property in OpenCTI.
So, should I do threat-hunting outside OpenCTI, and just use OpenCTI to store Knowledge and Indicators?

By the way, are there any other practical materials I could learn? Thank you very much!

**Comment by SamuelHassine** [comment]
Dear @cuserdzy,

Our 2023 roadmap includes a lot of threat hunting features:

* Apply YARA rules on artifacts stored on the platform
* Connector for VT Enterprise Hunting
* Enrichment connectors for SIEMs / logs
* Case management
* Automated rules for IOCs matching in the platform

Kind regards,
Samuel
