### ISSUE TITLE
Ability to Merge Observables of the same type

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1299]
## Problem to Solve

Often when importing data, related data is entered as separate IOCs. For example, test.exe and its hash are entered as separate observables. I would propose a way to select multiple observables of the same type, but with different properties and merge them.

So

## Current Workaround

Manually merge the observables by deleting one, and copying its data to the remaining observable.

## Proposed Solution

The ability to select observables of the same type and merge their properties.

**Comment by securitiz** [comment]
This functionality appears to already be available :) I can merge observables of the same type when selecting them from the main Observables page.

**Comment by SamuelHassine** [comment]
Now it's possible :)
