### ISSUE TITLE
Export full indicator via SSE upon deletion

### ISSUE THREAD

**Issue by 0snap** [OpenCTI-Platform/opencti#1302]
## Problem to Solve

When a user deletes an indicator (e.g., in the web UI), OpenCTI only exports the `opencti_id` alongside some other metadata to connectors via SSE. Once deleted, one cannot query that indicator anymore via the API. Connectors/tools that want to work with the deleted indicator are left dangling because it is impossible to find out details about the deleted indicator (i.e., the pattern).

It would be great if OpenCTI could export the entire indicator via SSE and flag it as `deleted`.

## Current Workaround

There is none to my knowledge

## Proposed Solution

OpenCTI pushes the full indicator into the SSE stream upon deletion instead of just some metadata.

## Additional Information

[This](https://luatix.slack.com/archives/CHZC2D38C/p1619512841152600) slack question and the following 4 comments.

**Comment by richard-julien** [comment]
Handled in https://github.com/OpenCTI-Platform/opencti/commit/0a1b923f2011f16208a487988da0d5998142f202
Will be available in the next release.
