### ISSUE TITLE
UnknownError: 'No reason specify' - Connectors

### ISSUE THREAD

**Issue by ghost** [OpenCTI-Platform/opencti#1309]
## Description
Error when running "python misp.py", but the connect still keeps runnings.

## Environment
OS: Centos 7
OpenCTI version: 2.4.141
Python 3.6.8

## Reproducible Steps
Steps to create the smallest reproducible scenario:

python3 misp.py

## Expected Output
Get data into OpenCTI.

## Actual Output
ERROR:root:No reason specify
Traceback (most recent call last):
  File "misp.py", line 1299, in <module>
    mispConnector.run()
  File "misp.py", line 160, in run
    self.helper.connect_id, friendly_name
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_work.py", line 72, in initiate_work
    query, {"connectorId": connector_id, "friendlyName": friendly_name}
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 275, in query
    {"name": error_name, "message": main_error["data"]["reason"]}
ValueError: {'name': 'UnknownError', 'message': 'No reason specify'}

This also happens with the **CVE connector.**

I'm completly lost here.

**Comment by SamuelHassine** [comment]
Hello,

Please can you share the error logs on the platform side please?

Kind regards,
Samuel

**Comment by ghost** [comment]
## audit.log (nothing suspicious)
```
{"resource":{"provider":"Bearer"},"auth":{"email":"admin@opencti.io","ip":"::ffff:172.19.0.2","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","version":"4.4.1","level":"info","message":"LOGIN","timestamp":"2021-04-28T11:13:04.514Z"}
{"resource":{"provider":"Bearer"},"auth":{"email":"admin@opencti.io","ip":"::ffff:172.19.0.2","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"category":"AUDIT","version":"4.4.1","level":"info","message":"LOGIN","timestamp":"2021-04-28T11:19:57.963Z"}
```

## error.log (the same appears for the misp connecter)
`{"user":{"ip":"::ffff:","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"type":"WRITE_ERROR","operation_query":"mutation workAdd($connectorId:String!$friendlyName:String){workAdd(connectorId:$connectorId friendlyName:$friendlyName){id}}","inner_relation_creation":0,"operation":"workAdd","time":9,"variables":{"connectorId":"dockercve","friendlyName":"CVE run @ 2021-04-28 11:19:58"},"size":74,"error":{"stacktrace":["ReplyError: EXECABORT Transaction discarded because of previous errors.","at Z (/root/opencti/build/index.js:1:82472)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (internal/process/task_queues.js:93:5)"]},"category":"APP","version":"4.4.1","level":"error","message":"API Call","timestamp":"2021-04-28T11:19:58.679Z"}`

## opencti (similar to error.log)
`{"type":"WRITE_ERROR","operation_query":"mutation PingConnector($id:ID!$state:String){pingConnector(id:$id state:$state){id connector_state}}","inner_relation_creation":0,"operation":"PingConnector","time":1,"size":60,"error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at m (/root/opencti/build/index.js:1:4727)","at k (/root/opencti/build/index.js:1:4870)","at Aa.authenticationControl (/root/opencti/build/index.js:1:214373)","at t.resolve (/root/opencti/build/index.js:1:215095)","at field.resolve (/root/opencti/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","at resolveField (/root/opencti/node_modules/graphql/execution/execute.js:464:18)","at /root/opencti/node_modules/graphql/execution/execute.js:261:18","at /root/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10","at Array.reduce (<anonymous>)","at promiseReduce (/root/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)","at executeFieldsSerially (/root/opencti/node_modules/graphql/execution/execute.js:258:37)","at executeOperation (/root/opencti/node_modules/graphql/execution/execute.js:236:55)","at executeImpl (/root/opencti/node_modules/graphql/execution/execute.js:116:14)","at Object.execute (/root/opencti/node_modules/graphql/execution/execute.js:60:35)"]},"category":"APP","version":"4.4.1","level":"warn","message":"API Call","timestamp":"2021-04-28T11:24:25.898Z"}`

My Redis Server is running and doesn't have any errors. The same with RabbitMQ (the queues are even created).

**Comment by ghost** [comment]
We can close this.
There was a problem with the bucket on Redis.
