### ISSUE TITLE
LDAP Group import v2

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#1311]
## Problem to Solve

The first implementation allows for a LDAP group to be matched with an OpenCTI role (defining permissions).
The goal of this feature is to be able to also match a LDAP group with an OpenCTI group (defining data segregation).

## Current Workaround

A few clicks per user to move to a specific group.

## Proposed Solution

Have a matching in the config as for the first implementation with roles.

## Additional Information

Shouldn't a Group be able to have a Role ?

**Comment by richard-julien** [comment]
Add configuration option

```
        "groups_management": {
          "group_attribute": "cn",
          "groups_mapping": ["REMOTE_GROUP:OCTI_GROUP"]
        }
```
