### ISSUE TITLE
Worker - OpenCTI API is not reachable 

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1316]
Hi,
This is related to my previous issue that the "worker" have some issue since version 4.4.1. 
I have a clean Ubuntu 20.0.4 (updated) and just installed v4.5.0. (on docker) and I enabled the AlienVault connector (docker).
The connector can able to connect to opencti, but it seems the 'worker' is the issue 

Notice that the alienvault connector's "in progress" keeps filing-up.
![image](https://user-images.githubusercontent.com/20463433/116711004-63410880-a9a0-11eb-8986-17929035130e.png)

Here's the docker's log for the worker ...
![image](https://user-images.githubusercontent.com/20463433/116711175-997e8800-a9a0-11eb-9e83-f600d120dd13.png)
![image](https://user-images.githubusercontent.com/20463433/116711316-bc10a100-a9a0-11eb-8d72-e0da6e1b5e18.png)
![image](https://user-images.githubusercontent.com/20463433/116711377-c92d9000-a9a0-11eb-8217-eecf758de819.png)

I would like to know if you can able to simulate this issue on your end (fresh ubuntu + opencti docker)

Please help.

**Comment by EXC3L-ONE** [comment]
I have the same issue.
Fresh docker based install on ubuntu 20.04.2. 

All connectors seem to work fine (CVE, CrowdStrike, MITRE etc.), except for AlienVault. It worked for a bit, imported some old reports, but then the progress suddenly stopped. Other connectors still work correctly.  

I tried the following:
* resetting the connector state
* rebuilding the connector
* clearing RabbitMQ queues
* other steps recommended in #1288
Nothing helps. 

It seems that this was was fine prior to 4.5.0 😢  

The logs in my case look roughly the same as for NetEyes:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/48698766/117070620-46a12980-ad2e-11eb-8f5c-0c7d50893944.png">

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
