### ISSUE TITLE
Implement sightings on knowledge graphs and enable export in STIX bundles

### ISSUE THREAD

**Issue by dcode** [OpenCTI-Platform/opencti#1321]
## Problem to Solve

I would like to be able to plot STIX sightings on the knowledge graph of reports and incidents and also include them in STIX bundle exports.

## Current Workaround

Currently do not have one. I attempted to do a STIX JSON bundle export of the report or incident, but it does not include the sighting relationship object.

## Proposed Solution

Implement an icon of a sighting and plot edges of relationships similar as documented in STIX documentation. For instance, a relationship of an identity SDO (organization, system, individual, etc) that `Saw` the sighting, what was seen (e.g. Indicator, Malware, or other appropriate SDO), as well as relationships to observed data objects (Observables).

**Example**:
![sighting-of-indicator](https://oasis-open.github.io/cti-documentation/img/sighting-of-an-indicator.PNG)

Additionally, when using the time range selector, the object and relationships would remain visible as long as an intersection exists between the (`first_seen`, `last_seen`) and the filtered range selection.

## Additional Information

Keep being awesome.

**Comment by peasead** [comment]
👍 agreed, this would be super helpful.
