### ISSUE TITLE
Bezier is not exported from 'bezier-js'

### ISSUE THREAD

**Issue by kostiadovhyi** [OpenCTI-Platform/opencti#1329]
Steps to reproduce:

1. `npm i` in both directories (front, graphql)
3. Run all the services needed, rabbitmq, minio, elasticsearch, redis
4. `npm run start` for both (graphql first just to avoid)
4. set default.json for all services
5. Open http://localhost:3000/dashboard
6. `Bezier is not exported from 'bezier-js'`

Clearing NPM cache doesn't work, tried yarn, doesn't work.

**Comment by richard-julien** [comment]
You need to use yarn to install the packages.
> yarn install
> yarn start

Not sure why you have any problems.
Do you use the master code?
What version of nodejs are you using?

**Comment by kostiadovhyi** [comment]
What does it expect to be running on port 8734 ?

**Comment by richard-julien** [comment]
No its "normal". Click escape on your keyboard.
In development mode error stack are displayed to help debugging and no authorization is an error like any others. So the stack is displayed but you can just escape the error to see the login screen

**Comment by kostiadovhyi** [comment]
Thank you Richard. You helped me a lot,. Have a great day!

**Comment by richard-julien** [comment]
No problem. Glad to have people trying to setup the dev env.

**Comment by kenzoname** [comment]
HI @mykolasolonynka , I getting same error: "Bezier is not exported from 'bezier-js'" when start frontend.
how do you fixed ?

**Comment by lyminhooo** [comment]
Hi @richard-julien,

I do the same, but i got this issuse!
Complete clean cache by cmd: yarn cache clean
And: rm yarn.lock && rm -rf node_modules &&  yarn install 
No thing change.
Node version: 14.16.1
Yarn Version: 1.22.5

**Comment by richard-julien** [comment]
Can you check if you have the same error without removing the yarn.lock file?
the lock file must not be deleted, its the only way to be sure that the dependencies installed are version fixed.

**Comment by lyminhooo** [comment]
Hi @richard-julien, 

I got it. Thank you.

But i want to new system installed without yarn.lock file? What is exactly package.json file for this action?

**Comment by richard-julien** [comment]
In fact yarn.lock is generate from the package.json at "yarn install" execution. Its a way to "freeze" the real version of the dependencies that will be installed at yarn install the next time.
So you need to keep the yarn.lock to be sure that yarn install will install the correct version of the libs.

**Comment by lyminhooo** [comment]
Hi @richard-julien,

Yes, i known that. But dependencies in package.json wasn't change. I copied from your project and add to my project (forked from your project) and do some command:
- rm -rf node_modules
- rm yarn.lock
- rm package-lock.json (if i use npm i)
- yarn install or yarn add <some_package> 

And i got an issues

**Comment by lyminhooo** [comment]
Hi @richard-julien,
I understand. You can close this issues

Thank you!
