### ISSUE TITLE
Any ideas of the starting point of altering the graphql schema?

### ISSUE THREAD

**Issue by kostiadovhyi** [OpenCTI-Platform/opencti#1331]
Hello!

The backend clearly uses a different way than just declaring types in the .schema file,  I want to know the source of the auto generation of the schema? I'm trying to add some attributes to some models but I can't even find the definition.

Mark as question please. Thanks

**Comment by kostiadovhyi** [comment]
And what's the command to update the schema after altering .js files for it?

**Comment by richard-julien** [comment]
Hi @mykolasolonynka,
Our usage of graphQL is I think really standard.
We dont have any auto generation of the schema.
The schema is available in https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/schema/opencti.graphql
Resolvers are define in https://github.com/OpenCTI-Platform/opencti/tree/master/opencti-platform/opencti-graphql/src/resolvers.
Take also a look to https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/graphql/schema.js

**Comment by kostiadovhyi** [comment]
Thank you, I've already looked at those files but I wondered if you're using any kind of auto generation this is why I've asked. Thank you Richard as always.

**Comment by richard-julien** [comment]
Hi @mykolasolonynka. No problem, there is no bad question, i'm glad to have people interested in helping on the source code.
