### ISSUE TITLE
History connector can't connect to OpenCTI server

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1332]
History connector can't connect to OpenCTI server.

## Description

History connector does not work.

## Environment

1. OS (where OpenCTI server runs): Mac OS Big Sur 11.3.1
2. OpenCTI version: OpenCTI 4.5.1
3. OpenCTI client: FrontEnd
4. Other environment details: Safari 14.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Connector Windows
2. Reinitialize Hystory connector

## Additional information

INFO:root:Connector registered with ID:320d1768-e50d-4d85-bac6-cc8d1e130a80
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): 127.0.0.1:4000
DEBUG:urllib3.connectionpool:http://127.0.0.1:4000 "POST /graphql HTTP/1.1" 200 277
INFO:root:Starting listening stream events with SSL verify to: True
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:4000
DEBUG:urllib3.connectionpool:http://127.0.0.1:4000 "POST /graphql HTTP/1.1" 200 98
DEBUG:urllib3.connectionpool:http://127.0.0.1:4000 "GET /stream HTTP/1.1" 500 84
Traceback (most recent call last):
  File "/Users/Jerome/Applications/OpenCTI/./connectors/history/src/history.py", line 99, in <module>
    HistoryInstance.start()
  File "/Users/Jerome/Applications/OpenCTI/./connectors/history/src/history.py", line 94, in start
    self.helper.listen_stream(self._process_message)
  File "/Users/Jerome/Library/Python/3.9/lib/python/site-packages/pycti/connector/opencti_connector_helper.py", line 455, in listen_stream
    messages = SSEClient(
  File "/Users/Jerome/Library/Python/3.9/lib/python/site-packages/sseclient.py", line 48, in __init__
    self._connect()
  File "/Users/Jerome/Library/Python/3.9/lib/python/site-packages/sseclient.py", line 63, in _connect
    self.resp.raise_for_status()
  File "/Users/Jerome/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:4000/stream
DEBUG:urllib3.connectionpool:Resetting dropped connection: 127.0.0.1
DEBUG:urllib3.connectionpool:http://127.0.0.1:4000 "POST /graphql HTTP/1.1" 200 98
DEBUG:urllib3.connectionpool:Resetting dropped connection: 127.0.0.1
DEBUG:urllib3.connectionpool:http://127.0.0.1:4000 "POST /graphql HTTP/1.1" 200 98
DEBUG:urllib3.connectionpool:Resetting dropped connection: 127.0.0.1

**Comment by richard-julien** [comment]
Hi @JeromeSRT , looks like you have an error 500 accessing  http://127.0.0.1:4000/stream
Can you check directly with a web browser if its working, and also check the api logs?
Thanks

**Comment by richard-julien** [comment]
Hi @csandu-certeu ,

For me the dropped connection **DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti** is not the problem explain in this ticket.

This debug message is not  a problem. When using a session the server use a keepalive mecanism to keep an http connection open to improve performance. But the server have a limit of keep alive connections size. When the server reach this limit it will drop the keep alive connection and force the client to create a new one.
If you use nginx you can take a look to https://www.nginx.com/blog/tuning-nginx/ > Keepalive Connections

**Comment by JeromeSRT** [comment]
> Hi @JeromeSRT , looks like you have an error 500 accessing  http://127.0.0.1:4000/stream
> 
> Can you check directly with a web browser if its working, and also check the api logs?
> 
> Thanks

I check with a web browser, i had {"status":"unauthorized"}

**Comment by richard-julien** [comment]
Can you login to opencti and try again?

**Comment by JeromeSRT** [comment]
> Can you login to opencti and try again?

I get a list of events on http://127.0.0.1:4000/stream, but it seems they are not consumed by the history connector,

I get in logs history: http://127.0.0.1:4000 "POST /stream/history HTTP/1.1" 404 154. It's not the right url to consume event stream, i think.

**Comment by JeromeSRT** [comment]
> > Can you login to opencti and try again?
> 
> I get a list of events on http://127.0.0.1:4000/stream, but it seems they are not consumed by the history connector,
> 
> I get in logs history: http://127.0.0.1:4000 "POST /stream/history HTTP/1.1" 404 154. It's not the right url to consume event stream, i think.

Ok, it works now with the OpenCTI release of 2 days ago. Thanks.
