### ISSUE TITLE
How can you access Open CTI from a public IP?

### ISSUE THREAD

**Issue by alikat500** [OpenCTI-Platform/opencti#1336]
## Problem to Solve
I installed a docker version of Open CTI on a VPS. Then, I realized I was unable to browse to the Open CTI's web portal via vps' public IP.
http://vps-publicIP:8080/

I was wondering if Open CTI can only be access locally by design.

If not, is there a way to access Open CTI's instance installed on a vps via its public IP?

Also, I noticed that the open CTI demo site (demo.opencti.io) is publicly available via HTTPS. 

Regards ,

**Comment by HugooB** [comment]
Did you mapped the ports correctly? As in, did you map port 8080 of the container to the VPS? E.g.,
```
ports:
      - "8080:8080"
```

**Comment by alikat500** [comment]
Are you referring to the ports entry in the docker-compose.yml file? If so, it is "8080:8080".
    ports:
      - "8080:8080"

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
