### ISSUE TITLE
Ability to an analyst to "expend an element" inside a Knowledge graph of a report

### ISSUE THREAD

**Issue by kracendo** [OpenCTI-Platform/opencti#1338]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

1. Create some incidents with knowledge in it (observables, relationships...)
2. Create a global report based on those incidents
3. In the report add the possibility to expand an elements based on knowledge in incidents
4. Add the related entity and observables in the global report

For the moment, I was only able to add incidents entities in the report.

## Proposed Solution
Add "Expend" feature in Knowledge graph of a report and update the related entity and observables tabs.

**Comment by SamuelHassine** [comment]
Also, take into account here:

* When expanding an element, have a checkbox to choose if you would like just to see the expanded elements or actually add them to the report. If not, they will be display with a different border color and you will be able to actually add them later on using the toolbar.
