### ISSUE TITLE
after upgrade to 4.5.2 - 'Name does not resolve' error in AlienVault

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#1346]
OS: Ubuntu 20.4
OpenCTI: v4.5.2

After upgrading to v4.5.2, the connector AlienVault logs shows 'Name does not resolve'

![image](https://user-images.githubusercontent.com/20463433/118279460-2d6c4b80-b499-11eb-86c0-b7054555dc9d.png)

in the Dashboard, the AlienVault connectors keeps building-up
![image](https://user-images.githubusercontent.com/20463433/118279733-77553180-b499-11eb-8026-798358b5ff9f.png)

Also, attempted to bring the down the connector and got an issue stopping it  ..
![image](https://user-images.githubusercontent.com/20463433/118279948-b5525580-b499-11eb-8cf9-6666bcea3aa5.png)

**Comment by NetEyes** [comment]
alienvault logs ..

![image](https://user-images.githubusercontent.com/20463433/118344567-d1d3a980-b4fc-11eb-9443-703711321c9a.png)

Worker log ..
![image](https://user-images.githubusercontent.com/20463433/118344597-f9c30d00-b4fc-11eb-9820-0391363ba166.png)

**Comment by richard-julien** [comment]
Looks like alienvault docker container have lost the network with the other containers. Please check your container/docker configuration to be sure that all the containers shared correctly the same network.

**Comment by NetEyes** [comment]
.env
![image](https://user-images.githubusercontent.com/20463433/118383969-a4583000-b5d0-11eb-9aa1-0ff9c4af9426.png)

opencti - docker-compose.yml
![image](https://user-images.githubusercontent.com/20463433/118384036-1466b600-b5d1-11eb-8805-33b7e7827722.png)
![image](https://user-images.githubusercontent.com/20463433/118384059-352f0b80-b5d1-11eb-85e8-cd92f5fc8457.png)

the opencti docker and the connector docker are in one server instance.

Have you guys ever tried to install fresh Ubuntu 20.04.2 LTS with fresh OpenCTI 4.5.2 docker? Humor me, please do and you may see this kind of error.

**Comment by richard-julien** [comment]
Yes we tried @NetEyes. We have multiple instances running on ubuntu.
With your logs it looks like a problem occurs in docker at a network level.
![image](https://user-images.githubusercontent.com/285555/118389243-460b6b80-b629-11eb-86e0-8bcec22c8dfc.png)

It could explains your problem of naming resolution.
Try to stop the complete stack again hoping for no error. Then try to remove completely the alienvault connector and restart the stack.

**Comment by NetEyes** [comment]
1. stop alienvault connector
2. stop opencti docker
3. start opencti docker
4. start alienvault connector again
![image](https://user-images.githubusercontent.com/20463433/118405208-b378c580-b644-11eb-9b16-086efc68e4a7.png)

Note: if I don't stop the alienvault connector, the 'work in progress' will build-up.
![image](https://user-images.githubusercontent.com/20463433/118405249-f0dd5300-b644-11eb-98d3-c657dace2dbe.png)

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
