### ISSUE TITLE
Improve handling of duplicate objects with different parameters (most notably, File objects)

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1353]
## Problem to Solve

**A scenario:** User #1 enters a File observable that has an MD5 hash and filename "rar.exe". Later, User #2 enters a File observable with the **same MD5 hash**, as well as SHA1, SHA256, and filename "winrar.exe".

_What currently happens:_ User #1's observable remains as is, and User #2's entry is not saved by OpenCTI (likely because it is interpreted as a duplicate. 
_What should happen:_ User #1's observable should remain and, barring any conflicts (e.g. a third observable with a different MD5, but same SHA1 as that of User #2's observable), User #2's data (SHA1, SHA256, additional filename) should be added to User #1's object. 

**Another scenario:** User #1 enters a File observable with MD5: A and SHA1: B. User #2 enters a File observable with MD5: A, and SHA1: C. Clearly one of the two users entered an incorrect hash, and this should be flagged to the user. 
_What currently happens:_ User #2's observable is not saved to the platform (likely due to being a duplicate), and the user is not notified of the action or the reasoning behind it. 

## Current Workaround

Notice that User #2's observable wasn't added to the platform, troubleshoot, identify that it's because it's a duplicate of another object, than manually update User #1's object. 

## Proposed Solution

Improve duplicate object handling - cases when a duplicate should be merged, vs when a user should be notified that they attempted to add a duplicate.

**Comment by SamuelHassine** [comment]
Linked to #1533
