### ISSUE TITLE
Marking color

### ISSUE THREAD

**Issue by jlequen** [OpenCTI-Platform/opencti#136]
Currently, the documentation for adding a mark does not exist.

## Problem to Solve

I don't know how to use the color field.

![Capture](https://user-images.githubusercontent.com/7465331/60973462-9e37ff00-a328-11e9-96e6-6be735dbe082.PNG)

## Current Workaround

Don't customize the marking field.

## Proposed Solution

Document this functionality.

**Comment by SamuelHassine** [comment]
The marking definition color was not implemented in the views and the lists. This will be fixed in the next version. The color field will have a color picker.
