### ISSUE TITLE
Any code samples to deploy OpenCTI to kubernetes EKS?

### ISSUE THREAD

**Issue by s1-luc-ibata** [OpenCTI-Platform/opencti#1362]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

I need code samples (manifests/YML files) to deploy to  kubernetes EKS. It's hard to find blogs that talks about this.

## Current Workaround

I tried to use Kubernetes Kompose tool to convert the docker-compose files and deploy to kubernetes but I aws couple services failing.  One of my colleague used a helm chart for elasticsearch and basic deployment for the redis, minio and rabbitmq services (they must live before OpenCTI platform/worker is deployed) - then deploying opencti platform and from there you can deploy worker & connectors.

## Proposed Solution

Similar to your terraform code sample, you guys should suggest the same for EKS.

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by hieuit7** [comment]
Hi @s1-luc-ibata,

I think you can write it if you have basic knowledge DevOps. Try some stack in this role to get it.

**Comment by zanoni23** [comment]
https://github.com/mwatermolen/OpenCTI-HELM-CHART
There is also a current 5.0 fork with a couple of fixes and additions:
https://github.com/zanoni23/OpenCTI-HELM-CHART/tree/zanoni23

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
