### ISSUE TITLE
Bug in the custom dashboard : campaign activity and incidents activity displaying "not implemented yet"

### ISSUE THREAD

**Issue by nicolasleguillou** [OpenCTI-Platform/opencti#1367]
## Description

Custom dashboard doesn't display Campaign Activity and Incidents activity related to a given sector whereas the OpenCTI instance contain incident targeting this sector.. "Not implemented yet" is displayed on the custom dashboard instead.

## Environment

1. OS (where OpenCTI server runs): Debian (Linux)
2. OpenCTI version: OpenCTI 4.5.2
3. OpenCTI client: Frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an incident or a campaign targeting a given sector
2. Click on custom dashboards
3. Add a new dashboard
4. Add a widget Identity or location, select the given sector, select Activity - Campaigns or Incidents. Whith any type of graph it will display "Not implmeented yet"

## Expected Output

If your instance contain campaign and incident targeting the given sector, the user should see a graph of campaign or incident related to this sector.

## Actual Output

The user can only see a graph displaying "Not implemented yet".
 
## Additional information

![image](https://user-images.githubusercontent.com/80690825/118977976-0f11be80-b977-11eb-8459-e3dd11f84af2.png)

**Comment by SamuelHassine** [comment]
Timelines  will be available in #183.
