### ISSUE TITLE
Export investigation in JSON or CSV format

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1374]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It would be useful to be able to export investigations made from the investigation panel into JSON (and maybe CSV), in order to be able to share it with others. 

The envisioned workflow is the following : 
1/ several reports are integrated to OpenCTI
2/ An analyst investigate the knowledge from the investigation tab
3/ Based on the result of the investigation, the analyst write a short analysis/commentary, and join the JSON of his/her OpenCTi investigation in order to share it with partners, constituents, clients etc. 
4/ The JSON can be directly integrated in tools of the partners.

## Current Workaround

Make an investigation from the knowledge tab of a report in order to be able to export it.

## Proposed Solution
The export could be a button at the top right, or a dedicated tab for files, just like it exists in other spaces today.
Only the objects displayed on the graph should be exported, with the displayed relations. This should take into account active filters. 
Attributes and parameters of the object should be exported (source, dates, confidence level).
A useful option could be to be able to add for each object and each relation the list of related reports.

**Comment by manonviallet** [comment]
(For the option about reports, it can be part of the investigation by displaying for each objects which reports "contain" it. However, this make the analyst do a pivot for each object in order to have the list)

**Comment by manonviallet** [comment]
More extensively (maybe should be the object of an other issue, I can open one if necessary), it would be desired to be able to make csv/JSON exports everywhere:

- export a knowledge tab list as a JSON or a CSV (for instance : for a given intrusion set, or campaign export all victims under a CSV format, or the TTPs.). This would allow for integration as tables in reports and written analysis.
- export as a csv the list of analysis (or only of reports) related to an object
- export as a csv or a JSON information contained and display in the kill chains and the timelines

**Comment by SamuelHassine** [comment]
JSON export should be a STIX 2 bundle.
