### ISSUE TITLE
Graph improvement: add a search bar in graphs display

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1375]
## Problem to Solve

When you are on a huge graph with many entities, either in a report or n the investigation space, it can be difficult to find a precise entity in order to visualize and manipulate it (make new pivots, new relations etc.)

## Current Workaround

Scroll and click through the entire graph and play with the filters in order to find the entity.

## Proposed Solution

It would be useful to add in the bottom bar a kind of search bar, or focus bar, which would allow for the user to enter the name of the desired entity (for instance "intrusion set A" which he/she knows is in the graph) and have it either highlighted or have the zoom make a focus on it.

## Additional Information

This would be especially useful for investigation graphs, but could be duplicated for knowledge tabs of reports or any other space where there are graphs.

**Comment by ckane** [comment]
I like the idea of highlighting it / selecting it in the graph - this way you can also more easily satisfy cases where a search string matches more than one element in the graph.
