### ISSUE TITLE
Filter types of entities included in Incident Global Kill Chain/Timeline

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1381]
## Problem to Solve

Incident Kill Chain and Timeline views are great opportunities to visualize data for non-technical people (e.g. C-suite). The ability to filter on the types of entities included in these views would allow users to tailor these visualizations for their own needs. 

## Current Workaround

n/a

## Proposed Solution

A filter that allows users to only display certain types of Entities in the Incident's Global Kill Chain and Timeline views. **Edit: Additionally, adding Attack Patterns to this view would be helpful**

**Comment by manonviallet** [comment]
It would be a useful feature, especially if notes about events can be added in the timeline !
The ideal would be for the user to chose to suppress or add any object on the timeline.

It would also be useful to have the same option as for graph with time (be able to display only part of the kill chain or of the timeline by giving specific or relative dates)

**Comment by manonviallet** [comment]
It would also be useful that the entities displayed in the timeline are clickable (more precisely maybe the relation with the date that triggered its display in the timeline in the first place)
