### ISSUE TITLE
[Data -> Connectors] Missing messages button

### ISSUE THREAD

**Issue by lesleyxyz** [OpenCTI-Platform/opencti#1382]
## Description

In older versions (tested 4.3.4) there was a messages button under the errors button when you clicked a connector in Data -> Connectors.
In the most recent versions (tested 4.5.2 & 4.5.3) it disappeared

![image (1)](https://user-images.githubusercontent.com/5853564/120021839-e0858a80-bfeb-11eb-943c-12833987f5cd.png)

## Environment

1. OS: Debian
2. OpenCTI version: 4.5.3
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Deploy OCTI 4.5.3 using do a docker-compose.yml
2. Goto Data -> Connectors and click a connector
3. The messages button isn't there anymore

## Expected Output

It showed messages, e.g. 'Imported 3 events'

## Actual Output

No button anymore

**Comment by SamuelHassine** [comment]
Messages button is not relevant anymore.
