### ISSUE TITLE
4.5.4 opencti/worker and opencti/platform images

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#1383]
## Description

Hello! Could you commit both the latest worker and platform images to Docker Hub? Apologies if it's just my impatience..! ;-) Can't wait to try ou the latest features! Thanks for the brilliant work!

**Comment by SamuelHassine** [comment]
Hello @s3ns0r1um,

Our CI provider (CircleCI) is encountering a major outage: https://status.circleci.com/.

Our CI process to build images is currently blocked, we apologize for the invonvenience.

Kind regards,
Samuel

**Comment by s3ns0r1um** [comment]
Thanks, Samuel. No problem!
