### ISSUE TITLE
Have the name of the author automatically filled

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1389]
## Problem to Solve

When creating a new object or relation, it would be useful to have the "author" field automatically filled, either : 
- if it is a new object, the name of the author by default should be the name of the user creating the object
- if it is a new relation within a report, the name of the author should be by default the author of the report. 

## Additional information

this feature was implemented in V3

**Comment by manonviallet** [comment]
(This has actually been taken into account so I am closing this issue)

**Comment by nino-filigran** [comment]
Works only in the context of containers (author form the container is added to the created entity/observable within the context of a container)
