### ISSUE TITLE
4.5.4 Import Report connector throws error

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#1392]
## Description

After updating to latest release 4.5.4, the ImportReport connector fails to start and throws the error below (see additional info). The issue only occurs on our test environment: we also set up a new prod server with a fresh instance and there was now error whith DBs still "empty".

## Environment

1. OS (where OpenCTI server runs): Ubuntu Server 20.04.2 LTS
2. OpenCTI version: OpenCTI 4.5.4
3. OpenCTI client: frontend
4. Other environment details: runs on VMWare ESXi

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Update OpenCTI to 4.5.4 (docker-compose.yml and /etc/environment)
2. Deploy OpenCTI stack

## Expected Output

Connector starts without issues.

## Actual Output

Connector can't start.
 
## Additional information

Connector container logs:

INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Cant create key for Connector from empty data
Traceback (most recent call last):
  File "/opt/opencti-connector-import-report/main.py", line 7, in <module>
    connector = ReportImporter()
  File "/opt/opencti-connector-import-report/reportimporter/core.py", line 35, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 409, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_connector.py", line 101, in register
    result = self.api.query(query, connector.to_input())
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 271, in query
    raise ValueError(
ValueError: {'name': 'UnsupportedError', 'message': 'Cant create key for Connector from empty data'}

**Comment by SamuelHassine** [comment]
Hello @s3ns0r1um,

Did you change the environement variables in your .env file?

Especially the `CONNECTOR_IMPORT_REPORT_ID`.

Kind regards,
Samuel

**Comment by s3ns0r1um** [comment]
Hello Samuel

Thanks for getting back to me. If my understanding is correct, one needs to manage the ENV variables in /etc/environment, if the stack is part of a Docker swarm. This is our case. 

I did replace the old with the new connector ID (from CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID to CONNECTOR_IMPORT_REPORT_ID), assigned a new UUID and sourced the file to reload. Is there any other variable that needs changing? 

Thanks for the support.

**Comment by s3ns0r1um** [comment]
Sorry for wasting your time, Samuel. After the seventh or eighth restart of the stack it just worked and all seems fine now. 

Thanks again for your support!
