### ISSUE TITLE
Support of reverse proxy with relative path

### ISSUE THREAD

**Issue by TrinityIsStillMyName** [OpenCTI-Platform/opencti#140]
## Description

When accessing OpenCTI 1.0.2 behind nginx reverse proxy with context path configuration, the URI links in the html-content received from OpenCTI are static. This results in the browser trying to load resources like `/static` or `/graphql` from the "TLD", e.g. `mycooldomain.com/static` instead of `mycooldomain.com/opencti/static`. This is obviously wrong.

## Environment

1. OS (where OpenCTI server runs): Debian 9 with Docker version 18.09.7, build 2d0083d
2. OpenCTI version:  OpenCTI 1.0.2 
3. OpenCTI client: frontend
4. Other environment details: nginx/1.10.3 as reverse proxy with the following vhost config
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name mycooldomain.com;

	location /opencti/ {
		proxy_buffering off;
		proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://127.0.0.1:8080/;
	}
```

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. setup OpenCTI 1.0.2 with docker-compose listening on :8080
2. setup nginx as reverse proxy with proxy_pass connecting to :8080
3. visit OpenCTI Base_URL in Browser

## Expected Output

Browser can load all resources from /opencti

## Actual Output

Browser loads html-content from OpenCTI. The URI links in the html-content are static, etc. /static,  /graphql , .... . The Browser cannot reach the links and OpenCTI-Login is broken
 
## Additional information

I chatted with Samuel on slack about it.

**Comment by richard-julien** [comment]
Development in progress. Its more than just add relative path. Routing are currently done by the client so he needs to be aware of the context path.
Solution will be an extra configuration of the platform.

**Comment by richard-julien** [comment]
My Nginx configuration to also support websocket

```
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name myproxy.com;
    location /proxy/ {
      proxy_buffering off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_pass http://127.0.0.1:4000/;
    }
  }
```
