### ISSUE TITLE
Support Redis cluster

### ISSUE THREAD

**Issue by hieuit7** [OpenCTI-Platform/opencti#1400]
## Problem to Solve

Redis is the only element in the stack that cannot be used in cluster.
Its due to the usage of multiple databases
Database 0 -> Stream and works
Database 1 -> User contexts and locks
Unfortunatly this feature is not available in Redis cluster. See https://redis.io/topics/cluster-spec

## Current Workaround

No

## Proposed Solution

Remove usage of Database 1 and use only the 0 to support cluster deployment.

**Comment by richard-julien** [comment]
Hi @hieuit7 ,

For now Redis cluster is not supported.
Its basically due to the usage of multiple database to split concern that is not compatible with cluster mode (https://redis.io/topics/cluster-spec)

We plan to refactor and change that to support cluster mode but not short term.

**Comment by richard-julien** [comment]
Content of the feature edited.
