### ISSUE TITLE
Importing STIX file from Report doesn't associate objects from the report

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1402]
## Problem to Solve

When importing PDF files from a Report, CTI associates the resulting objects with the report itself.

However, this does not happen when a STIX file is imported. Instead, objects are generated with no association to the report, and have to be found (for Observables) in the main Observables page.

## Current Workaround

Add each generated object to the report after the import

## Proposed Solution

Associate each generated object to the Report where the import of the file occured

**Comment by richard-julien** [comment]
STIX should have the full context.
We can eventually introduce an option in the report import to have the same behavior independently of the STIX "real" definition.
For me its a dangerous usage and should not be the default behavior.
