### ISSUE TITLE
Notes : be able to link notes between each others

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1403]
## Problem to Solve

It would be useful to be able to link notes with each other, when they are about the same or a similar subject. Today, notes can be link through a same report or a same entity (threat actor, intrusion set, malware etc.) but they cannot be linked directly together. 
This would prove quite useful when tracking events which are evolving and for which it would be preferable to keep track of the different dates of evolution of the event (and not of the note).

**Comment by SamuelHassine** [comment]
For the team, find a way to have a special display when a note container another note (child).

**Comment by SamuelHassine** [comment]
Diplicate of https://github.com/OpenCTI-Platform/opencti/issues/2500.
