### ISSUE TITLE
Add a file to a report programatically?

### ISSUE THREAD

**Issue by flyracing** [OpenCTI-Platform/opencti#1410]
Hi All,

I have used the STIX connector to import meta extracted from a file - so far so good - I get a report and the associated entities and relationships.

I'd like to be able to associate the original file (say a pdf that the STIX data was extracted from) with the report and linked observables for reference - no issues with doing this manually from the GUI interface (fro the 'Files' tab within the Report), but I can't work out how to do it programatically, the goal being to automate ingestion of a range of items using other microservices.

I know I can import pdf's and get entity extraction within the tool but we have different file types to process and require more control.

I can't seem to see how to do this with pycti. If I export the meta from a report that has a file attached I can't see any obvious association. Similarly I can't seem to find any record of files I have added manually in Elastic (or by searching in the GUI). I can add a file to the right spot in minio, but it will then not display properly in the GUI - appears to be missing associated meta (fair enough) and I can't seem to find where this is being stored.

Any advice greatly appreciated - even if this it some sort of intermediate work around to insert meta into minio/redis/graph!

**Comment by nor3th** [comment]
Hey

> I'd like to be able to associate the original file (say a pdf that the STIX data was extracted from) with the report and linked observables for reference - no issues with doing this manually from the GUI interface (fro the 'Files' tab within the Report), but I can't work out how to do it programatically, the goal being to automate ingestion of a range of items using other microservices.

If I understood you correctly, than this request is very similar to this one.  #1402
I am working on that.

For what other file types are requiring data extraction and the relationship between the observables and the report?

**Comment by richard-julien** [comment]
Hi @flyracing,

You can currently upload a file inside a report with the python add_file function.
As an example : https://github.com/OpenCTI-Platform/client-python/blob/master/examples/upload_file_to_intrusion_set.py
Just replace the id of the intrusion set by the id of your report, it should do the job

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
