### ISSUE TITLE
OpenCTI with Elasticsearch https

### ISSUE THREAD

**Issue by V1D1AN** [OpenCTI-Platform/opencti#1413]
Hi :)

I try to connect my docker opencti with a elasticsearch in "https".
I have a cluster elasticsearch with the transport ssl enabled.

In my docker-compose, i have add "ELASTICSEARCH_SSL_CA=/path/to/ca.crt" in "environment" but it don't work...

I have change ELASTICSEARCH__URL=https://elastic:password@es01:9200
I have don't seen ELASTICSEARCH_SSL_CERT or ELASTICSEARCH__SSL_KEY in the code of OpenCTI

**Comment by mariodcosta** [comment]
Hey guys,
I am trying to run openCTI Container in my docker. However after run, appears "Exited(1)". With this log:

{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-03-14T19:47:12.550Z","version":"5.2.1"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"ElasticSearch seems down"},"internalData":{},"name":"ConfigurationError","time_thrown":"2022-03-14T19:47:12.579Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-03-14T19:47:12.580Z","version":"5.2.1"}
ConfigurationError: A configuration error has occurred
    at Q0 (/opt/opencti/build/src/config/errors.js:8:10)
    at X0 (/opt/opencti/build/src/config/errors.js:47:53)
    at /opt/opencti/build/src/database/engine.js:159:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at h9t (/opt/opencti/build/src/database/engine.js:149:3)
    at jMe (/opt/opencti/build/src/initialization.js:119:3)
    at rhr (/opt/opencti/build/src/initialization.js:370:5)
    at hjn (/opt/opencti/build/src/boot.js:9:3)
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-03-14T19:47:29.208Z","version":"5.2.1"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"ElasticSearch seems down"},"internalData":{},"name":"ConfigurationError","time_thrown":"2022-03-14T19:47:29.238Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-03-14T19:47:29.238Z","version":"5.2.1"}
ConfigurationError: A configuration error has occurred
    at Q0 (/opt/opencti/build/src/config/errors.js:8:10)
    at X0 (/opt/opencti/build/src/config/errors.js:47:53)
    at /opt/opencti/build/src/database/engine.js:159:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at h9t (/opt/opencti/build/src/database/engine.js:149:3)
    at jMe (/opt/opencti/build/src/initialization.js:119:3)
    at rhr (/opt/opencti/build/src/initialization.js:370:5)
    at hjn (/opt/opencti/build/src/boot.js:9:3)
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-03-14T20:01:54.511Z","version":"5.2.1"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"ElasticSearch seems down"},"internalData":{},"name":"ConfigurationError","time_thrown":"2022-03-14T20:01:54.547Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-03-14T20:01:54.548Z","version":"5.2.1"}
ConfigurationError: A configuration error has occurred
    at Q0 (/opt/opencti/build/src/config/errors.js:8:10)
    at X0 (/opt/opencti/build/src/config/errors.js:47:53)
    at /opt/opencti/build/src/database/engine.js:159:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at h9t (/opt/opencti/build/src/database/engine.js:149:3)
    at jMe (/opt/opencti/build/src/initialization.js:119:3)
    at rhr (/opt/opencti/build/src/initialization.js:370:5)
    at hjn (/opt/opencti/build/src/boot.js:9:3)
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-03-16T10:46:17.515Z","version":"5.2.1"}
{"category":"APP","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"ElasticSearch seems down"},"internalData":{},"name":"ConfigurationError","time_thrown":"2022-03-16T10:46:17.554Z"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-03-16T10:46:17.554Z","version":"5.2.1"}
ConfigurationError: A configuration error has occurred
    at Q0 (/opt/opencti/build/src/config/errors.js:8:10)
    at X0 (/opt/opencti/build/src/config/errors.js:47:53)
    at /opt/opencti/build/src/database/engine.js:159:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at h9t (/opt/opencti/build/src/database/engine.js:149:3)
    at jMe (/opt/opencti/build/src/initialization.js:119:3)
    at rhr (/opt/opencti/build/src/initialization.js:370:5)
    at hjn (/opt/opencti/build/src/boot.js:9:3)

**Anyone can help me?**
