### ISSUE TITLE
Adding same External Reference to Report twice Deletes both

### ISSUE THREAD

**Issue by michaelheider** [OpenCTI-Platform/opencti#1416]
## Description

When the same URL is added as external reference to a report twice, both external references are deleted.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
2. OpenCTI version: 4.5.4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add external reference to report: create a new external reference (by clicking on the plus). Give it a name and an URL.
2. An external reference is created and added as expected.
3. Repeat 1. with the same URL and same or different name.
4. Both external references are deleted from the report.

## Expected Output

The external URL is added once under external refernces due to deduplication.

## Actual Output

The external URL is not present at all in external refernces of the report. Specifically, even the successfully added external reference from step 1. is deleted.

The deduplication works, only one external reference entity is created.

**Comment by richard-julien** [comment]
Thanks for the report @Bauboo . Nice and clean reproducible steps

If exist in the list, creation should not create a new item and activate it, but only update the current item and activate it if not already activated.
