### ISSUE TITLE
UI: Creating Relation in Knowledge Graph

### ISSUE THREAD

**Issue by michaelheider** [OpenCTI-Platform/opencti#1417]
## Problem to Solve

Somewhere between 4.2.3 and 4.5.4, the knowledge graph UI changed quite a bit.

In 4.2.3, creating relations was as simple as clicking and dragging from one entity to another. In 4.5.4, one has to select 2 entities (done by holding Ctrl) and click on the create a relation button at the bottom right. This is not intuitive (especially the holding Ctrl part) and more cumbersome.

## Proposed Solution

Reenable the old way of creating relations, or any other more intuitive, easy and fast way.

## Additional Information

I may be missing a more intuitive way of creating relationships?

**Comment by SamuelHassine** [comment]
@Bauboo we're thinking about re-introduce drag & drop.

**Comment by manonviallet** [comment]
Interested in this one, still relevant with V5 !

**Comment by SamuelHassine** [comment]
This feature is import to speed-up the creation of relationships in the context of a report:

* Re-introduce drag & drop
* Display arrows on the screen that you can move to multiple entities
* Check Analyst Notebook relati'onship creation: https://www.youtube.com/watch?v=zvCvw9NkttQ.
