### ISSUE TITLE
Suppressing an entity does not suppress its relations

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1428]
## Description

When integrating information in a graph, if an entity is suppressed, all the relations created within the graph with this entity are saved and continue to exist. Therefore, even though the relation was created only once in the context of this report, and can no longer be visualized in the report, it can be visualized and called upon through the investigation space. 

This is problematic as if during integration the analyst realize it integrated the wrong campaign/intrusion set/TTPs etc, although he/she has suppress the object to replace it by another, the false relations with the former entity are remaining in the DB. As a result, the relations keep appearing in the kill chain, and in the investigation graph of the entity, as if they were still valid.

Was wondering is this choice is deliberate (because we can create relations with no report in the platform) or because the number of reports the relation is associated with is not counted ? 

It would be relevant to keep the relation if there are still several reports in which it exists, but to suppress it if there is only one report. Another solution would be to ask when the entity is suppressed, if the person want to keep the relations or delete it also ? to have this pop up only if the relation had only this report linked to ?

## Environment

Tested in the demo (V4.5.5)

Here, the malware has been suppressed of the knowledge graph of the report and put again. Although all the relations have been suppressed when then malware was, they are still offered when we want to generate anew relation.
![problem_relation_suppression](https://user-images.githubusercontent.com/49722941/122575889-75aafa80-d051-11eb-8176-bd430eb95548.png)

In the investigation graph, the malware has all these ttps although the relation is no longer in a report
![Test](https://user-images.githubusercontent.com/49722941/122576114-a68b2f80-d051-11eb-905e-0aee0b164a67.png)

In the kill chain view also the TTPs are visible.
![killchain](https://user-images.githubusercontent.com/49722941/122577999-bc99ef80-d053-11eb-807e-f20227cc939e.png)

**Comment by SamuelHassine** [comment]
Hello @manonviallet,

It's not intentional. The idea of the popup to ask confirmation before deleting all relations is a good idea :)
