### ISSUE TITLE
worker_import.py and worker_export.py does not work with last release of pycti

### ISSUE THREAD

**Issue by elrandar** [OpenCTI-Platform/opencti#143]
## Description

When installing following the manual method, upon starting the workers, the OpenCTI class is presented as missing from the pycti module.
This stems from the fact that the module has been rewritten, but the workers python files have not been updated.

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: 1.0.2
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install opencti manually
2. pip3 install pycti
3. python3 $PATH/opencti/worker/worker_import.py

## Expected Output

The worker starts normally

## Actual Output

Python does not find the class OpenCTI
 
## Additional information

```Traceback (most recent call last): 
File "worker_import.py", line 10, in <module>
    from pycti import OpenCTI
ImportError: cannot import name 'OpenCTI' from 'pycti' (/home/user/.local/lib/python3.7/site-packages/pycti/__init__.py)

**Comment by SamuelHassine** [comment]
@elrandar: good catch, sorry for that, this will be solved by the 1.1.0 release in a few days.
