### ISSUE TITLE
Feed subscription / bulletin / digests

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#1433]
## Problem to Solve
 
Have a custom dashboard with a feed subscription

## Current Workaround

None

## Proposed Solution

Allow the user to subscribe to reports streams received on a MOA/ThreatActor or any entity. 
This allows the user to know the latest reports coming on the entities that interest him and not on the whole platform (as is the case in the current dashboard).

## Additional Information

None

**Comment by Bella-chris** [comment]
Hi Samuel,

How can I enable the subscriptions & digests?
![image](https://user-images.githubusercontent.com/92671957/144827838-13c613ad-67f0-46f4-b694-544432de29bd.png)
