### ISSUE TITLE
OpenCTI datasets not being imported

### ISSUE THREAD

**Issue by elrandar** [OpenCTI-Platform/opencti#144]
## Description

The open CTI sectors DataSet is not being imported, even when forcing the importation.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 1.0.2 Docker Image
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable the synchronization of the OpenCTI datasets
2. Select Sectors, Countries and regions as entities to be synchronized
3. Click "Force Now"

## Expected Output

The Sectors from the dataset are imported

## Actual Output

Nothing happens
 
## Additional information

Manual importation works fine

**Comment by SamuelHassine** [comment]
Will be fixed in 1.1.0.
