### ISSUE TITLE
Intrusion-set activities widgets also include "Attack Pattern"

### ISSUE THREAD

**Issue by rguignard** [OpenCTI-Platform/opencti#1440]
## Description

The "Global Intrusion Set activities widget" also include information regarding Attack Pattern. 
Is an intended behavior ?

## Environment

1. OpenCTI version: 4.5.5

## Expected Output

Only have information regarding intrusion-set

## Actual Output

Include activities on intrusion-set and attack pattern 
 
## Additional information

![Capture d’écran 2021-06-21 à 13 16 54](https://user-images.githubusercontent.com/4287665/122754193-a11d2780-d293-11eb-9f49-451fb59c5b8a.png)

**Comment by SamuelHassine** [comment]
Basically the problem of "direction" of stuff. 

Actually we have to find an elegant solution to avoid this but I don't have any clue @richard-julien.

When computing the "activity" of intrusion sets for instances, we are counting the number of relation coming from and to intrusion sets, aggregating the top _n_. Most of the time, top n concern intrusion set, but sometimes, the from or the to of relationship can be in this top.

I will show you a repro case on a clear platform.
