### ISSUE TITLE
the queue of a connector does not want to decrease

### ISSUE THREAD

**Issue by ghost** [OpenCTI-Platform/opencti#1441]
Hi,   
for several days the queue of the alienvault connector is blocked at 1.85 million messages.

## Environment
1. OS: docker
2. OpenCTI version: 4.5.5

## Additional information

I also have the following logs on opencti:

```json
{
   "user":{
      "ip":"::ffff:172.20.0.17",
      "user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f",
      "applicant_id":"a9d1c2e0-404c-46db-bf75-82cdecb45628",
      "call_retry_number":"1"
   },
   "type":"WRITE_ERROR",
   "operation_query":"mutation ReportEditRelationAdd($id:ID!$input:StixMetaRelationshipAddInput){reportEdit(id:$id){relationAdd(input:$input){id}}}",
   "inner_relation_creation":0,
   "operation":"ReportEditRelationAdd",
   "time":60,
   "size":144,
   "error":{
      "data":{
         "reason":"Missing reference to handle creation",
         "http_status":404,
         "category":"business",
         "input":{
            "relationship_type":"object",
            "toId":"relationship--45b3e66d-3c6f-4e1c-995d-53e87a75a196",
            "fromId":"cde6be22-c768-46a5-8b31-565b4560f095"
         },
         "unresolvedIds":[
            "relationship--45b3e66d-3c6f-4e1c-995d-53e87a75a196"
         ]
      },
      "stacktrace":[
         "MissingReferenceError: Element not found",
         "at m (/opt/opencti/build/index.js:1:5275)",
         "at S (/opt/opencti/build/index.js:1:6450)",
         "at ce (/opt/opencti/build/index.js:1:50068)",
         "at async Be (/opt/opencti/build/index.js:1:67231)"
      ]
   },
   "category":"APP",
   "version":"4.5.5",
   "level":"warn",
   "message":"API Call",
   "timestamp":"2021-06-21T12:07:16.124Z"
}
```

**Comment by SamuelHassine** [comment]
Hello @lyess-ow,

In recent days, some AlienVault pulses have contained a lot of entities. This leads OpenCTI to take more time to ingest. In some cases, after the whole processing of the pulse, RabbitMQ could tell the OpenCTI workers that the processing has been too long and the message cannot be ack. 

This make OpenCTI enter in a loop of processing those messages, and should be  visible in the logs with `Channel error on connection <####> : operation none caused a channel exception precondition_failed: consumer ack timed out on channel 1`.

If you have this kind of errors, that's normal. Just configure your RabbitMQ with an extended consumer timeout (or in the Docker env vars):

```
$:/etc/rabbitmq# cat rabbitmq.conf 
consumer_timeout=8600000
``` 

Then restart RabbitMQ and wait a few days more, queues will start to be consumed.

Kind regards,
Samuel

**Comment by ghost** [comment]
Hello,  

thank you for your reply,  
i will try this and tell you if it worked,  

regards,

**Comment by Ken-Abruzzi** [comment]
Hello, @SamuelHassine 
How can I set "consumer_timeout=8600000" in the docker-compose.yml file?
![image](https://user-images.githubusercontent.com/68931768/124250201-19c08700-dad1-11eb-8681-7190ae6e1508.png)

Thank you!
Kind regards

**Comment by tigre-bleu** [comment]
I have the same symptoms: Queue not decreasing and Alienvault reports not ingested.

In the error.log file I can see a lot of those:

```json
{"user":{"ip":"127.0.0.1","user_id":"xxx","applicant_id":"xxx","call_retry_number":""},"type":"WRITE_ERROR","operation_query":"mutation MarkingDefinitionAdd($input:MarkingDefinitionAddInput){markingDefinitionAdd(input:$input){id standard_id entity_type parent_types definition_type definition x_opencti_order x_opencti_color created modified created_at updated_at}}","inner_relation_creation":0,"operation":"MarkingDefinitionAdd","time":64679,"variables":{"input":{"definition_type":"TLP","definition":"TLP:WHITE","x_opencti_order":0,"x_opencti_color":null,"stix_id":"marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9","created":"2017-01-20T00:00:00.000Z","modified":null,"update":false}},"size":240,"error":{"data":{"reason":"Execution timeout, too many concurrent call on the same entities","http_status":500,"category":"business","participantIds":["marking-definition--0e75d955-265a-59a5-8ae2-51361befc08e","marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"]},"stacktrace":["LockError: Lock timeout","at error (/opt/opencti/5.0.0/build/src/config/errors.js:8:10)","at LockTimeoutError (/opt/opencti/5.0.0/build/src/config/errors.js:87:3)","at created (/opt/opencti/5.0.0/build/src/database/middleware.js:2792:13)","at addMarkingDefinition (/opt/opencti/5.0.0/build/src/domain/markingDefinition.js:22:9)"]},"category":"APP","version":"5.0.0","level":"error","message":"API Call","timestamp":"2021-09-15T07:13:32.416Z"}
```

**Comment by GiuseppeLaurenza** [comment]
A small dump to ask if someone know how to modify the timeout in the docker-compose file

**Comment by pyred123** [comment]
@Ken-Abruzzi were you able to find out how to do this on the docker compose file? I seem to be having the same issue

**Comment by Ken-Abruzzi** [comment]
> @Ken-Abruzzi were you able to find out how to do this on the docker compose file? I seem to be having the same issue

Hello. Something like this.
![image](https://user-images.githubusercontent.com/68931768/163509163-ce5f8310-ec81-4518-8ac2-beafe95e233b.png)
But I don't know the suitable value of this variable. After I added this setting, the importing processing stopped.

**Comment by mahmut-the-guy** [comment]
@SamuelHassine could you elaborate on what causes queue buildup? I had a MISP connector running for a week, it ended up accumulating 35 million messages, workers acknowledging almost none, with bundles per second nearing zero at all times.

Today, I purged all messages and reset the connector state. Some entities are started to be ingested but I feel like buildup will be inevitable. MISP connector especially seems to be problematic when running from scratch.

For reference, I'm running 4 workers with one platform node. Throwing more workers does not seem to help at all in general. (which is odd, interested to know the why)
