### ISSUE TITLE
User-specific statistics

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1451]
## Problem to Solve

Create the ability to track how many objects have been created by a user in the last X (period of time).  Only certain users should have the ability to view this, such as admins.

## Current Workaround

Track successful web requests by each user

## Proposed Solution

A leaderboard-like functionality that would track which users created the most objects in the last week, month, 3 months, year.

**Comment by Jipegien** [comment]
Covered by the Activity feature.
