### ISSUE TITLE
Question: How do I add local users?

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/opencti#1454]
Hey,

We are now finally willing to use this at our company, but is there some documentation about how do I add local users?

**Comment by nor3th** [comment]
Hello @bLackCat-79 

The documentation is still under development, but you can add local users under "Settings" -> "Accesses" -> "Users".

![select](https://user-images.githubusercontent.com/73965465/125129320-94a42600-e0ff-11eb-865c-39b0541b55a9.png)

Regards,

**Comment by bLackCat-79** [comment]
Ok, I feel stupid now :) Thanks!
