### ISSUE TITLE
Improve elastic-searching from platform. (global searching, author searching, individual entity screen searching)

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/opencti#1455]
Improve elastic-searching from platform. (global searching, author searching, individual entity screen searching)

**Comment by nor3th** [comment]
Hello @kudrew 

Could you please elaborate your feature request a bit further. What exactly should be improved? Please use the feature request description format and at least one use case where the proposed feature would help.

Thanks

**Comment by kudrew** [comment]
Hi @nor3th,

On of my instances has 4.77m entities, 8.56m relationships, and 4.6m total observables and I am seeing long wait times for using the global search for broad statements such as: bear, spider, apt1, apt2 

additionally going into the respective individual screens: analysis, intrusion sets, observables, etc and search from those statements take a good amount of time. 

I have a fairly tough elasticsearch cluster with 3 nodes, 30 cpu total, 200gb of ram, and 100 gb of jvm heap and having searches like the author field when creating certain entities take a while to load is one of the feedback that I received from my end users. 

Samuel and Julien are aware of this and are brainstorming what they can implement. This ticket was opened for them to track. Thanks!
