### ISSUE TITLE
DatabaseError message: Expect only one response

### ISSUE THREAD

**Issue by sreemanshanker** [OpenCTI-Platform/opencti#1457]
## Description

The alienvault connector keeps erroring when retrieving newer reports. 
The error message provided is: {'name': 'DatabaseError', 'message': 'Expect only one response'}. 
The source message provided is:
{"type": "bundle", "id": "bundle--753897ec-7484-4dc7-b1cd-78b706da9f71", "spec_version": "2.1", "objects": [{"id": "report--e86d683c-e06e-11eb-ac23-02420a000717", "created_by_ref": "identity--e7222dd2-e06e-11eb-ac23-02420a000717", "created": "2021-07-01T16:36:47.992Z", "modified": "2021-07-05T00:01:28.856Z", "name": "Russian GRU Conducting Global Brute Force Campaign to Compromise Enterprise and Cloud Environments", "description": "The US National Security Agency (NSA) has issued a report on a Russian military intelligence (GRU) cyber campaign, which has already targeted hundreds of government and private sector targets around the world.", "report_types": ["threat-report"], "published": "2021-07-01T16:36:47.992Z", "object_refs": ["intrusion-set--e8696f16-e06e-11eb-ac23-02420a000717", "attack-pattern--e86983b6-e06e-11eb-ac23-02420a000717", "attack-pattern--e8699018-e06e-11eb-ac23-02420a000717", "attack-pattern--e8699a04-e06e-11eb-ac23-02420a000717", "attack-pattern--e869a468-e06e-11eb-ac23-02420a000717", "attack-pattern--e869addc-e06e-11eb-ac23-02420a000717", "attack-pattern--e869b7b4-e06e-11eb-ac23-02420a000717", "attack-pattern--e869c254-e06e-11eb-ac23-02420a000717", "attack-pattern--e869cd08-e06e-11eb-ac23-02420a000717", "attack-pattern--e869d762-e06e-11eb-ac23-02420a000717", "attack-pattern--e869e1da-e06e-11eb-ac23-02420a000717", "attack-pattern--e869ec34-e06e-11eb-ac23-02420a000717", "attack-pattern--e869f6a2-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a008e-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a0ad4-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a151a-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a1f74-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a2a0a-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a345a-e06e-11eb-ac23-02420a000717", "attack-pattern--e86a3fa4-e06e-11eb-ac23-02420a000717", "relationship--ceb19b6d-c984-49bf-8098-f25eab60554d", "relationship--6e51542c-7a8e-4f2e-bb11-9bb3b03db34d", "relationship--8a922e71-83ad-45a9-bb3e-e92c55c1d73e", "relationship--7b967121-0130-4bdc-b336-924ffe67b343", "relationship--6072fdbd-70ef-4548-92d3-fdc736121338", "relationship--dc6e3058-49d2-43c5-8a2b-fe9529ba08b4", "relationship--ea0d0f06-605e-4704-9f99-873772d17a8d", "relationship--03c88f7e-59df-4f5a-af52-613a2e580d72", "relationship--ec81d7bb-767d-4d68-a2b7-f03563ce5d43", "relationship--870cfb98-43aa-4a9d-a807-39b5d3fb631c", "relationship--b6ff37ac-1416-4582-a8c9-36aa45faadec", "relationship--c38a0a75-121c-4737-bb13-465e7e2bc744", "relationship--f1d95c33-57be-4054-9885-80f3a102ff40", "relationship--ceddd809-1d24-42d1-92db-a44832ab9677", "relationship--ff2ba7e9-8969-4152-9694-495171d140f2", "relationship--1380cc89-c9a2-4ce2-878e-aec8bbd0f330", "relationship--71375934-654f-41f1-ac7b-ff006ff25816", "relationship--3bbb60a4-d3e2-4efd-b393-9c989d8daa96", "relationship--ff74f6f3-6c4a-4553-9a2f-cd5a4954068f", "identity--e86c2f80-e06e-11eb-ac23-02420a000717", "identity--e86c3728-e06e-11eb-ac23-02420a000717", "relationship--fe8cc705-8f14-426e-b54e-e4259363ceae", "relationship--914e37f6-cf08-4721-85e9-1fba39cfefe0", "location--e86c5230-e06e-11eb-ac23-02420a000717", "relationship--8b892fca-eceb-4e81-85eb-64a14249d3c2", "indicator--e86c6860-e06e-11eb-ac23-02420a000717", "relationship--630bd0f7-d39e-47e3-99fb-16423f5531a1", "relationship--5d7d20ea-7fd8-47b9-9639-62576477e3d8", "relationship--bfd77744-0c1a-49fd-be02-61ca4680bba3", "relationship--ee87c62a-61c5-4b3d-8138-22ab1a581ad5", "relationship--411e3899-ebf5-4c29-bc23-1bdf5db34cf1", "relationship--0a950b55-3790-4893-8ecb-51d2de668a6a", "relationship--eb8b9285-007f-49e2-8932-80f6b751f3c6", "relationship--98ee06ec-676e-4c88-9fcd-e70cbc4bcb8a", "relationship--010cd017-bdde-4424-b6c2-7cbdccb4db2a", "relationship--0ed21c51-6c59-44b0-816c-f3a639d97b7a", "relationship--25a91b96-9e99-49df-a44f-166e292b81c6", "relationship--d18ff184-c00e-4952-a0a5-da200dc0071a", "relationship--8f03015e-de23-44ba-bbfc-0f8edc161263", "relationship--a6504777-45d0-405c-bd9e-181fdfe2c72a", "relationship--df8db581-649c-40d0-93fd-4ab595b9aa56", "relationship--59fe54b5-d404-49a7-920b-3776e3afab5a", "relationship--182d0d51-1386-44a5-aa7b-3b8ea45f9e24", "relationship--78202ed1-c4f9-40ae-a0d1-c4d54f4b40b9", "relationship--3ba9de86-cd38-4cb6-9f4d-d4e77bc29522", "relationship--4f2add2a-8059-48d1-99c0-ae9a0e5c70e1"], "labels": ["APT28", "Fancy Bear", "GRU", "Strontium"], "confidence": 65, "external_references": [{"source_name": "AlienVault", "url": "https://otx.alienvault.com/pulse/60ddef2060d5524232502eb5", "external_id": "60ddef2060d5524232502eb5"}, {"source_name": "AlienVault", "url": "https://media.defense.gov/2021/Jul/01/2002753896/-1/-1/1/CSA_GRU_GLOBAL_BRUTE_FORCE_CAMPAIGN_UOO158036-21.PDF"}], "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"], "x_opencti_report_status": 0, "type": "report", "spec_version": "2.1", "nb_deps": 447}]}

## Environment

1. OS : ubuntu 20.04
2. OpenCTI version: 4.5.5
3. Other environment details: Running on container instance

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Daily connector refresh

## Expected Output

Reports to be downloaded and parsed from alienvault

## Actual Output

Errors out when getting the report and thus no new reports are created under analysis
 
## Additional information

![1](https://user-images.githubusercontent.com/33079691/125238667-20919a00-e31a-11eb-8a25-e428c7daf61c.JPG)
![2](https://user-images.githubusercontent.com/33079691/125238674-225b5d80-e31a-11eb-9cf3-fae557646d65.JPG)
[docker-compose.txt](https://github.com/OpenCTI-Platform/opencti/files/6798890/docker-compose.txt)

**Comment by nor3th** [comment]
Hey @sreemanshanker 

What's the output of `docker logs opencti_connector-alienvault_1`? (Please adapt the container name if yours is called differently)

**Comment by sreemanshanker** [comment]
Hey @nor3th ive attached the logs here. Thanks for taking a look

ive also removed the lines with "INFO:root:Bundle has been sent" to save space.
[Alienvaultlog.txt](https://github.com/OpenCTI-Platform/opencti/files/6805528/Alienvaultlog.txt)

**Comment by nor3th** [comment]
Hey @sreemanshanker 

Thanks for the log file. Interesting, those logs don't show any errors. What does `docker logs opencti_opencti_1` say?

**Comment by sreemanshanker** [comment]
Hi @nor3th find attached the logs. I just restarted the container - but immediately while fetching data i already have 7 errors (also as attached). I think it couldbe due to this line? 
7-15T00:40:26.375Z"}
{"error":{"message":"request entity too large","expected":138857,"length":138857,"limit":102400,"type":"entity.too.large"},"category":"APP","version":"4.5.5","level":"error","message":"[EXPRESS] Error http call","timestamp":"2021-07-15T00:51:30.334Z"}
[opencti_opencti.txt](https://github.com/OpenCTI-Platform/opencti/files/6819685/opencti_opencti.txt)
[newerror.txt](https://github.com/OpenCTI-Platform/opencti/files/6819686/newerror.txt)
![Snapshot_2021-07-15_091009_13 70 199 190](https://user-images.githubusercontent.com/33079691/125712281-384ed7d1-dfaa-4003-bcaf-c5ebc7d9c8b3.png)

**Comment by nor3th** [comment]
Thanks for the log entry, we'll look into it.

**Comment by sreemanshanker** [comment]
@nor3th ive got a fresh set of logs. these have more errors in it. hope its able to show whats wrong.
[new 7.txt](https://github.com/OpenCTI-Platform/opencti/files/6827133/new.7.txt)

**Comment by richard-julien** [comment]
2 different problematic in this ticket.

> Expect only one response 

This should not happens and can reflect a injection problem where one ID match multiple elements.
You need to find the error in the opencti logs to have more information. 
You should have the ID, type and number of hits found along with the error.
Please provide this information.

>  request entity too large

This is the first time i see this. Looks like express refuse the call because the query is too large. 
By default is 100kb and maybe you have a big amount of text in an event your want to inject.
I think we need to push the limit and add an option in opencti to let people setup the maximum they want.
I created the feature request https://github.com/OpenCTI-Platform/opencti/issues/1486 to hande that.

**Comment by sreemanshanker** [comment]
Hi @richard-julien, sorry i have not replied sooner. Have been out sick - so did not manage to check here.
First off - thanks for looking into the issue.

For problem 1 - I Have been trying to find the error, but to no joy. Could you direct me on how to better handle this and provide the logs necessary. Ive looked in the alienvault container logs as well as the opencti_opencti_1 logs, but cant find it.

For problem 2 - i have left it to the default settings of importing the Alienvault reports.

**Comment by sreemanshanker** [comment]
Following up to see if you need additional logs.

**Comment by dark6naw** [comment]
I am on ubuntu 20.04 opencti 4.5.5 and I also encounter the same issue. Attached is a screenshot of the Alienvault error

![Screenshot 2021-09-08 at 12 29 24 AM](https://user-images.githubusercontent.com/34785594/132379722-d32d58d5-bfe2-4c19-81dc-a29e394f9540.png)

No errors on elasticsearch or opencti. 

Attached are logs from Alienvault and Worker
[alienvault.txt](https://github.com/OpenCTI-Platform/opencti/files/7123169/alienvault.txt)
[worker.txt](https://github.com/OpenCTI-Platform/opencti/files/7123170/worker.txt)

**Comment by xme** [comment]
I'm facing the same error...
```
worker_1                      | INFO:root:Creating Report {Trend Micro njRAT 2018}.                                                                                                                                                                                                       [0/99495]
worker_1                      | ERROR:root:Expect only one response
worker_1                      | ERROR:root:{'name': 'DatabaseError', 'message': 'Expect only one response'}
```
How can I help to debug this?

**Comment by richard-julien** [comment]
For this problem of 'Expect only one response' i can try to help but the source of the problem will be different for every people on this ticket. When you have this error, the platform try to resolve a specific element with an id and the database respond with more than one element, situation that should not happen. So something goes wrong on injection maybe long time ago.
This kind of errors could be seen on the connectors monitoring with the original content responsible for it but without the metadata require to understand a bit more the problem. 

@sreemanshanker and @xme you need to find the logs on opencti.log that match this problem to get more metadata information and come to the slack to have direct help.

@dark6naw same than sreemanshanker  and xme but also take a look to the error "error loading ids" that is also not expected and a complete different error.

Thanks in advance.
