### ISSUE TITLE
I have the following error when I run (yarn serv) command!!

### ISSUE THREAD

**Issue by yousefhawwari** [OpenCTI-Platform/opencti#1459]
Dears,
Hope you're doing great.

I have the following error when I run (yarn serv) command!!
![OpenCTI-Error](https://user-images.githubusercontent.com/25611301/125427072-a335a362-c270-4607-aa3a-2134cf0cad67.PNG)

Kindly please help!
Best Regards,
Yousef H.

**Comment by SamuelHassine** [comment]
Hello,

This error is pretty clear, MinIO access key is not correct in your configuration.

Kind regards,
Samuel

**Comment by yousefhawwari** [comment]
Thanks Samuel for your response.

Can you please let me know, how to configure it? Sorry because I'm not too familiar with it.

Appreciate your help!
Thank you :)

**Comment by SamuelHassine** [comment]
@yousefhawwari I don't understand your question, MinIO access/secret keys must be the same in your MinIO instance and in your OpenCTI configuration. So OpenCTI can access to MinIO without any problem. Please double check your configuration to give a proper access to your S3 bucket.

**Comment by yousefhawwari** [comment]
I'm not using S3 buckets (AWS), my installation is manual install.

**Comment by yousefhawwari** [comment]
Must I have instance/server for each dependency (MinIO, RabbitMQ, ElasticSearch, etc...) to run the OpenCTI?

**Comment by nor3th** [comment]
Yes, please check the installation page for setting up a functional OpenCTI setup. https://github.com/OpenCTI-Platform/opencti#installation
