### ISSUE TITLE
Workers/Connectors: UI Error

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1460]
## Description

Connectors and Workers are running, but I can't get their status as before.
![image](https://user-images.githubusercontent.com/37035465/125511780-89d9be24-b5f0-4b02-b7dc-9ed2d734e93a.png)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1 .
2. OpenCTI version: 4.5.5

## Expected Output

Status of live connectors and number of workers.

## Actual Output

Just an error in Data>Connectors
Connectors are working as the platform is receiving data!
![image](https://user-images.githubusercontent.com/37035465/125512280-753d7a0c-f932-4154-b452-0af057907577.png)

Looping @maxifjaved 

Regards,
Khalid

**Comment by SamuelHassine** [comment]
Hello @khalidrehan,

Can you please provide the log from the platform with the error occuring when you display the Connector page?

Kind regards,
Samuel

**Comment by khalidrehan** [comment]
Hello @SamuelHassine 

Logs:
`{"user":{"ip":"::ffff:192.168.8.123","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"http://192.168.8.192:4000/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":66,"variables":{},"size":2,"error":{"stacktrace":["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"]},"category":"APP","version":"4.5.5","level":"error","message":"API Call","timestamp":"2021-07-13T19:51:42.046Z"}`

Regards,
Khalid

**Comment by nor3th** [comment]
`["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"]}` This error indicates that RabbitMQ can't be reached. Please make sure that RabbitMQ is up and running and reachable under the configured IP address.

**Comment by khalidrehan** [comment]
Hi @nor3th 
RabbitMQ-Server is running because the platform is running and RabbitMQ-Server is essential to it.

```
cti@cti:~$ sudo systemctl status rabbitmq-server.service
[sudo] password for cti:
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-06 06:51:34 UTC; 1 weeks 1 days ago
 Main PID: 427 (beam.smp)
   Status: "Initialized"
    Tasks: 35 (limit: 19660)
   CGroup: /system.slice/rabbitmq-server.service
           ├─427 /usr/lib/erlang/erts-12.0.3/bin/beam.smp -W w -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 500000
           ├─453 erl_child_setup 32768
           ├─547 inet_gethost 4
           └─548 inet_gethost 4

Jul 06 06:51:33 cti rabbitmq-server[427]:   TLS Library: OpenSSL - OpenSSL 1.1.1  11 Sep 2018
Jul 06 06:51:33 cti rabbitmq-server[427]:   Doc guides:  https://rabbitmq.com/documentation.html
Jul 06 06:51:33 cti rabbitmq-server[427]:   Support:     https://rabbitmq.com/contact.html
Jul 06 06:51:33 cti rabbitmq-server[427]:   Tutorials:   https://rabbitmq.com/getstarted.html
Jul 06 06:51:33 cti rabbitmq-server[427]:   Monitoring:  https://rabbitmq.com/monitoring.html
Jul 06 06:51:33 cti rabbitmq-server[427]:   Logs: /var/log/rabbitmq/rabbit@cti.log
Jul 06 06:51:33 cti rabbitmq-server[427]:         /var/log/rabbitmq/rabbit@cti_upgrade.log
Jul 06 06:51:33 cti rabbitmq-server[427]:   Config file(s): (none)
Jul 06 06:51:34 cti rabbitmq-server[427]:   Starting broker... completed with 3 plugins.
Jul 06 06:51:34 cti systemd[1]: Started RabbitMQ broker.
```

**Comment by nor3th** [comment]
Is RabbitMQ also reachable to the correct port. It seems like a network issue from my side. Like I already said, please check the documentation for setting up OpenCTI https://github.com/OpenCTI-Platform/opencti#installation

**Comment by khalidrehan** [comment]
![image](https://user-images.githubusercontent.com/37035465/125618609-04ff9d40-be18-44f5-8450-05dcb48f2b1b.png)

@nor3th

**Comment by nor3th** [comment]
Is RabbitMQ also reachable from `127.0.0.1:15672` ?

**Comment by khalidrehan** [comment]
```
cti@cti:~$ sudo netstat -nlpt | grep 15672
[sudo] password for cti:
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      427/beam.smp
cti@cyberxcti:~$
```
![image](https://user-images.githubusercontent.com/37035465/125682589-dbc8b31b-df5c-473c-8fa6-118363e09e81.png)

**Comment by fflahaut-t** [comment]
Hello,

We have the same issue on one of our instances when we upgrade NodeJS from v16 to v18.

 ## Environment
* OpenCTI v5.5.2 (same behavior with 5.5.1) manually installed from tar.gz package
* Ubuntu 20.04.5 LTS
* Python 3.9.5
* Opensearch 2.4.1
* RabbitMQ 3.11.6-1 **up and running**
* Redis 6:7.0.7-1rl1~focal1
* minio version RELEASE.2023-01-12T02-06-16Z (commit-id=7bc95c47a322971aff7d4d4c270dcf28a933e84b)

All these components are locally installed with apt or release packages, no container. 

## Issue

* when OpenCTI is running on NodeJS 16.19, everything is ok : connectors & workers running ok and feeds imported correctly, no UI issue
* when OpenCTI is running on NodeJS upgraded to 18.13.0 :  connectors & workers still running ok and feeds still imported correctly, but:
  * RabbitMQ displayed as "Disconnected" in the parameters pane
  * the "Data - Connectors" page displays the red error message
  * OpenCTI server logs the error message below when we access to the "Data - Connectors" page:
```
{
  "category": "APP",
  "error":
  {
    "stacktrace":
    [
      "Error: connect ECONNREFUSED ::1:15672",
      "at Function.sY.from (/opt/opencti/build/node_modules/axios/lib/core/AxiosError.js:89:14)",
      "at yT.handleRequestError (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:526:25)",
      "at yT.emit (node:events:513:28)",
      "at ClientRequest.xyt.<computed> (/opt/opencti/build/node_modules/follow-redirects/index.js:14:24)",
      "at ClientRequest.emit (node:events:513:28)",
      "at Socket.socketErrorListener (node:_http_client:496:9)",
      "at Socket.emit (node:events:513:28)",
      "at emitErrorNT (node:internal/streams/destroy:151:8)",
      "at emitErrorCloseNT (node:internal/streams/destroy:116:3)",
      "at processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "WorkersStatusQuery",
  "operation_query": "query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}",
  "size": 2,
  "time": 19,
  "timestamp": "2023-01-17T09:55:51.212Z",
  "type": "READ_ERROR",
  "user":
  {
    "ip": "::ffff:<instance_IP>",
    "referer": "https://<instance_hostname>/dashboard/data/connectors",
    "user_id": "<user_id>"
  },
  "variables":
  {},
  "version": "5.5.2"
}
```
* if we downgrade NodeJS back to 16.19, everything is ok again.

**Comment by fflahaut-t** [comment]
We found the cause of our problem, we had a bad `/etc/hosts` configuration for IPv6 on this instance:
`::1 localhost ip6-localhost ip6-loopback`

Once the `/etc/hosts` configuration restored to its nominal value
`::1 ip6-localhost ip6-loopback`
and NodeJS updated to version 18, we no longer have the above issue when accessing the connector monitoring page, and RabbitMQ version is correctly displayed in the parameters pane.

Seems that NodeJSv18 sometimes uses IPv6 to access localhost resources when NodeJSv16 seems not to.
