### ISSUE TITLE
I encountered some problems while executing "yarn serv"

### ISSUE THREAD

**Issue by Sla-le** [OpenCTI-Platform/opencti#1470]
How should i solve this problem
![image](https://user-images.githubusercontent.com/49434485/125895530-3c433d89-ff4a-4c1c-b24a-253acf87edc9.png)
{"type":"READ_ERROR","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":21,"size":2,"error":{"data":{"http_status":401,"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at m (/root/opencti/opencti/build/index.js:13:627)","at u (/root/opencti/opencti/build/index.js:13:786)","at k.authenticationControl (/root/opencti/opencti/build/index.js:217:949)","at m.resolve (/root/opencti/opencti/build/index.js:217:1698)","at field.resolve (/root/opencti/opencti/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","at resolveField (/root/opencti/opencti/node_modules/graphql/execution/execute.js:464:18)","at executeFields (/root/opencti/opencti/node_modules/graphql/execution/execute.js:292:18)","at executeOperation (/root/opencti/opencti/node_modules/graphql/execution/execute.js:236:122)","at executeImpl (/root/opencti/opencti/node_modules/graphql/execution/execute.js:116:14)","at Object.execute (/root/opencti/opencti/node_modules/graphql/execution/execute.js:60:35)","at /root/opencti/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:261:48","at Generator.next (<anonymous>)","at /root/opencti/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","at new Promise (<anonymous>)"]},"category":"APP","version":"4.5.5","level":"warn","message":"API Call","timestamp":"2021-07-16T13:05:47.053Z"}

**Comment by richard-julien** [comment]
Hi @595cyi ,

A bit difficult to answer your question because you dont specify any repro case or actions that can explains this message.
The only thing i can imagine is because you try to access the page without being logged ...
> AuthRequired: You must be logged in to do this
