### ISSUE TITLE
Report titles appear blank when creating relationships

### ISSUE THREAD

**Issue by jocelynjyl** [OpenCTI-Platform/opencti#1471]
## Description

Report titles don't show up when trying to create a relationship between a campaign and a report. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 (focal) 
2. OpenCTI version: 4.5.4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Have at least 1 campaign and 1 report. 
2. Under Campaigns > Knowledge, select "Related Entities" on the right-hand side toolbar. 
2. Click the + and select the 'Report' section. Report titles appear blank. 

## Expected Output

Report titles should appear. When added, the Report Name should show up under the Name column. 

## Actual Output

See screenshot below. If a report is selected, the "Name" appears as Unknown. 
 
## Additional information

<img width="836" alt="Screenshot 2021-07-16 at 12 05 55" src="https://user-images.githubusercontent.com/8165187/125932795-5d4df1ea-157e-4eb4-8ed8-102a9f98647a.png">

**Comment by richard-julien** [comment]
Thanks for the bug report @jocelynjyl
