### ISSUE TITLE
Opencti on https ssl?

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/opencti#1472]
Hi,

We have an opencti instance running on http on port 8080.
Now if I want to use opened provider, it requires that the callback URL has SSL (https).

Do I need to setup an nginx proxy that forwards and upgrades port HTTP 8080 to https port 8081 for example? (we cannot use port 443)

Can I let all my connectors still connect to port 8080?

**Comment by richard-julien** [comment]
Hi @bLackCat-79 .

Yes its possible,

![image](https://user-images.githubusercontent.com/285555/125952014-5d58300c-b572-45dd-83dd-759497cd4f36.png)

See https://www.notion.so/luatix/93dd0f2899254b2581553d8b7df362da?v=979adbb6cb8b4e58aeef7c3bfb4c4624

**Comment by bLackCat-79** [comment]
I added this to my docker-compose.yml file, but the key path cannot be found, do I need to copy the certs to my docker image? Or can it read from the docker host?

**Comment by SamuelHassine** [comment]
Hello,

Using volumes, you can definitely mount cert from Docker host.

Kind regards,
Samuel
