### ISSUE TITLE
OpenCTI users can't see data

### ISSUE THREAD

**Issue by Tx0n** [OpenCTI-Platform/opencti#1475]
Hello,

I have a problem with the users I create in OpenCTI. If these users don't have the role "Bypass all capabilities", which is basically the administrator role, they won't see any information once connected to the platform. I may be missing something, but I can't figure out the problem.

Thanks for the help

**Comment by JeromeSRT** [comment]
> Hello,
> 
> 
> 
> I have a problem with the users I create in OpenCTI. If these users don't have the role "Bypass all capabilities", which is basically the administrator role, they won't see any information once connected to the platform. I may be missing something, but I can't figure out the problem.
> 
> 
> 
> Thanks for the help

Hello,

The information are protected by TLP level, and only users of the group TLP WHITE can see information of TLP WHITE level. You have to define the different groups accessing to TLP level, and put your users in the TLP group.
Go to configuration panel, create your TLP group with group function on the right of the configuration tab.

**Comment by Tx0n** [comment]
> 
> 
> > Hello,
> > I have a problem with the users I create in OpenCTI. If these users don't have the role "Bypass all capabilities", which is basically the administrator role, they won't see any information once connected to the platform. I may be missing something, but I can't figure out the problem.
> > Thanks for the help
> 
> Hello,
> 
> The information are protected by TLP level, and only users of the group TLP WHITE can see information of TLP WHITE level. You have to define the different groups accessing to TLP level, and put your users in the TLP group.
> Go to configuration panel, create your TLP group with group function on the right of the configuration tab.

Ho I see, thanks a lot !
