### ISSUE TITLE
How much storage is normal?

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/opencti#1476]
On my instance, (running in docker) the whole opencti takes now 500GB storage.
Is that normal? What sizing can I expect (I have 12 connectors configured)

**Comment by manonviallet** [comment]
Hello @bLackCat-79,

I would suggest joining the slack channel of Luatix (https://slack.luatix.org/), were you will definitely find a lot of people to answer your question. For that type of issues/questions, it is usually easier to do so. 
The amount of storage might depend on how much data your connectors are importing.

Have a nice weekend,
Manon
