### ISSUE TITLE
Internal server error when launching pdf file import

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#1478]
## Description

Lunching a pdf file import throws an error. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1 LTS
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
4. Other environment details: VM

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upload pdf
2. Launch import of file

## Expected Output

Clean run of pdf import connector.

## Actual Output

Internal server error.
 
## Additional information

Log:

INFO:root:Reporting work update_received opencti-work--50e9a4d5-3b32-4780-afcd-54d4ca135f94
INFO:root:Importing the file http://opencti:8080/storage/get/import/Report/b717045d-906d-46eb-8fcf-e52db8de8595/Report_Oilrig.pdf
INFO:root:Listing Identities with filters null.
ERROR:root:Internal server error
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 152, in _data_handler
    message = self.callback(json_data["event"])
  File "/opt/opencti-connector-import-report/reportimporter/core.py", line 68, in _process_message
    entity_indicators = self._collect_stix_objects(self.entity_config)
  File "/opt/opencti-connector-import-report/reportimporter/core.py", line 118, in _collect_stix_objects
    entries = custom_function.list(
  File "/usr/local/lib/python3.9/site-packages/pycti/entities/opencti_identity.py", line 162, in list
    result = self.opencti.query(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 276, in query
    raise ValueError(
ValueError: {'name': 'Internal server error', 'message': 'Internal server error'}
INFO:root:Reporting work update_received opencti-work--50e9a4d5-3b32-4780-afcd-54d4ca135f94
INFO:root:Message (delivery_tag=2) processed, thread terminated

**Comment by nor3th** [comment]
Hey @s3ns0r1um 

`ValueError: {'name': 'Internal server error', 'message': 'Internal server error'}` seems like something doesn't work on the OpenCTI server side. Can you please post the logs from the OpenCTI docker container?

 `docker logs opencti_opencti_1` (or something similar)

**Comment by s3ns0r1um** [comment]
Here goes.. thanks for taking a look, I appreciate it! 

=================================================

{"resource":{"path":"import/global","filename":"Report_Oilrig.pdf","metadata":{}},"auth":{"email":"adm[@]local.org","ip":"::ffff:10.0.0.2","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"hxxp://192.168.40.16:8080/dashboard/import"},"category":"AUDIT","version":"4.5.5","level":"info","message":"UPLOAD","timestamp":"2021-07-23T09:22:25.524Z"}
{"user":{"ip":"::ffff:10.0.1.138","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","applicant_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"type":"READ_ERROR","operation_query":"query Identities($types:[String]$filters:[IdentitiesFiltering]$search:String$first:Int$after:ID$orderBy:IdentitiesOrdering$orderMode:OrderingMode){identities(types:$types filters:$filters search:$search first:$first after:$after orderBy:$orderBy orderMode:$orderMode){edges{node{id standard_id entity_type parent_types spec_version created_at updated_at createdBy{...on Identity{id standard_id entity_type parent_types spec_version identity_class name description roles contact_information x_opencti_aliases created modified objectLabel{edges{node{id value color}}}}...on Organization{x_opencti_organization_type x_opencti_reliability}...on Individual{x_opencti_firstname x_opencti_lastname}}objectMarking{edges{node{id standard_id entity_type definition_type definition created modified x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}externalReferences{edges{node{id standard_id entity_type source_name description url hash external_id created modified}}}revoked confidence created modified identity_class name description x_opencti_aliases contact_information ...on Individual{x_opencti_firstname x_opencti_lastname}...on Organization{x_opencti_organization_type x_opencti_reliability}}}pageInfo{startCursor endCursor hasNextPage hasPreviousPage globalCount}}}","inner_relation_creation":0,"operation":"Identities","time":288,"variables":{"types":null,"filters":null,"search":null,"first":500,"after":null,"orderBy":null,"orderMode":null},"size":100,"error":{**"stacktrace":["Error: Cannot return null for non-nullable field Organization.identity_class."**,"at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:559:13)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeAbstractValue (/opt/opencti/node_modules/graphql/execution/execute.js:680:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:584:12)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:556:21)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)","at /opt/opencti/node_modules/graphql/execution/execute.js:620:25","at Array.map (<anonymous>)","at safeArrayFrom (/opt/opencti/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)"]},"category":"APP","version":"4.5.5","level":"error","message":"API Call","timestamp":"2021-07-23T09:23:30.650Z"}

=================================================

**Comment by richard-julien** [comment]
Looks like a side effect of organization creation with a missing information but mandatory when reading (identity_class).
Any idea @SamuelHassine where the api can create identity without identity_class?

**Comment by nor3th** [comment]
I just modified one of the test cases from
```
class IdentityOrganizationTest(IdentityTest):
    def data(self) -> Dict:
        return {
            "type": IdentityTypes.ORGANIZATION.value,
            "name": "Testing Inc.",
            "description": "OpenCTI Test Org",
        }
```
to
```
class IdentityOrganizationTest(IdentityTest):
    def data(self) -> Dict:
        return {
            "name": "Testing Inc.",
            "description": "OpenCTI Test Org",
        }
```
The creation is executed via 
```
self.api_client.identity.create()
```
And I the return message I got was
`
FAILED tests/02-integration/stories/test_entity_crud.py::test_entity_create[identity_organization] - ValueError: {'name': 'Variable "$input" got invalid value null at "input.type"; Expected non-nullable type "IdentityType!" not to be null.', 'message': 'Variable "$input" got invalid value null at "input.type"; Expected non-nullable type "IdentityType!" not to be null.'}
`

So I would guess, that it is not possible from the API side...
