### ISSUE TITLE
Workspaces : Add type of entity when selecting an entity for widget creation

### ISSUE THREAD

**Issue by elrandar** [OpenCTI-Platform/opencti#148]
## Problem to Solve

It is not possible to know what type an entity belongs to when selecting one to make a widget. This causes issues since campaigns/malwares can be named similarly.

## Current Workaround

Guessing the entity you chose is the right one, and comparing the output on the widget.

## Proposed Solution

Adding the [type] before the entity.

## Additional Information

Exemple problematic case : 
![screenshot 10](https://user-images.githubusercontent.com/26814183/61546565-f61de680-aa49-11e9-886c-f3fe48a40064.jpg)
![screenshot 11](https://user-images.githubusercontent.com/26814183/61546569-f8804080-aa49-11e9-95d2-29e52d4881f5.jpg)

**Comment by SamuelHassine** [comment]
This issue will be solved in the next release. Nevertheless, we plan to start a full refactor of the workspace section after the next release.
