### ISSUE TITLE
BAD_USER_INPUT error makes pages inaccessible

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1481]
## Description

Several pages (notably in Reports) become inaccessible to users with error "An unknown error occurred. Please contact your administrator or the OpenCTI maintainers."

The error is not reproducible for all Reports. It's not unclear which Reports are vulnerable to this error, or what actions cause it. 

The return error is "BAD_USER_INPUT". More information can be found in the screenshots

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.4
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Visit Report Overview
2. Select "Observables" page

## Expected Output

View the Observables content for a report

## Actual Output

Error message. Other pages in the Report also return the error "This page is not found on this OpenCTI application." This continues until the user 
 
## Additional information

Query found in query.txt. Response found in httplog.txt
[httplog.txt](https://github.com/OpenCTI-Platform/opencti/files/6875287/httplog.txt)
[query.txt](https://github.com/OpenCTI-Platform/opencti/files/6875288/query.txt)

**Comment by richard-julien** [comment]
Hi, looks like an error in ordering option.

> "message": "Variable \"$orderBy\" got invalid value \"observable_value\"; Value \"observable_value\" does not exist in \"StixObjectOrStixRelationshipsOrdering\" enum.",

**Comment by securitiz** [comment]
Is this something that can be fixed in an upcoming version of CTI, or is likely to be specific to my instance?

**Comment by richard-julien** [comment]
Its not specific to your instance. If you try to order by observable_value it will fail. 
Looks like its not possible in the demo (maybe already fixed in the master) ? Can you try to reproduce on the demo instance?

**Comment by richard-julien** [comment]
Looks like the same problem than https://github.com/OpenCTI-Platform/opencti/issues/1394.

Can you try to clear the filter directly in the URI and have a write here a clear repro case?

**Comment by securitiz** [comment]
Hi @richard-julien , when I clear the "sort" parameters from the URI and try to visit the page, it re-adds the sort URI parameters and I get the same error

**Comment by richard-julien** [comment]
You can try to force the sort instead : sortBy=name

**Comment by securitiz** [comment]
Thanks. This worked - sort of. I don't get the error, but I do get an empty Observables page. I confirmed by looking at the Overview section that Observables should be listed

**Comment by richard-julien** [comment]
Are you sure you dont have any searchTerm in the url?

**Comment by securitiz** [comment]
The full URL is "https://[reacted].com/dashboard/analysis/reports/77475477-9a01-41ab-aa5b-875c0d08cd73/observables?sortBy=name&orderAsc=true&searchTerm="

I tried removing the searchTerm parameter completely, and it keeps returning

**Comment by SamuelHassine** [comment]
@securitiz, please use: `sortBy=entity_type&orderAsc=true&searchTerm="`.

Is this solve the problem?

Kind regards,
Samuel

**Comment by securitiz** [comment]
Hi Samuel,

The URI parameters above returned the same "Unknown error occurred" page.

I tried again adding a quotation mark at the end, so that it became: `sortBy=entity_type&orderAsc=true&searchTerm=""`
This did not return the error, but did showed a page of empty observables. I've attached screenshots for this last query

![image](https://user-images.githubusercontent.com/78382789/128908040-a801e5af-47ad-4ade-89fb-7aaf9f817c6e.png)

![image](https://user-images.githubusercontent.com/78382789/128908147-4106b8b0-a759-4ed9-96c3-a187f9d677c8.png)
