### ISSUE TITLE
Full text search for documents

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#1483]
## Problem to Solve

Use case:
- Analyst A  uploads a pdf report, create a report object and indicators, observables, etc... 
- Analyst A misses an important string X inside the pdf report (E.G. a key used by a dropper to decrypt the second stage) 

Few months later...  
- Analyst B works on a incident where the string X is used
- Analyst B search in OpenCTI if the string X is documented
  - no results :confused:

## Current Workaround

None (CTRL+F) 

## Proposed Solution

Index documents uploaded in elasticsearch.

## Additional Information

https://www.elastic.co/fr/blog/elastic-app-search-a-free-product-for-building-great-search-experiences

**Comment by SYNchroACK** [comment]
I would also add OCR capability during PDF report ingestion in order to read the text contained images that then will be searchable.

**Comment by Archidoit** [comment]
Sorting file result (by name or 'attached entity type' is not working : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/0dcc0cd2-af39-4200-a811-761b4cd014f5)

**Comment by marieflorescontact** [comment]
> Sorting file result (by name or 'attached entity type' is not working
> 
> Note: Would be great to also be able to sort by the number of occurences

it is not implemented yet, we need to discuss about it with @Jipegien
