### ISSUE TITLE
[worker] Bundle import is missing in connector works overview

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/opencti#1487]
## Description

When importing a stix bundle, the size of the bundle is shown in the connector overview page, but not in the detail page/

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 4.5.5
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Run the test_external_import test case from 
https://github.com/OpenCTI-Platform/client-python/pull/199
https://github.com/OpenCTI-Platform/client-python/pull/199/files#diff-487d383a306529b47bfba658ee8141d6ab190537f76327e1b3de60d5e1102795R76-R119

**execution**``` pytest --connectors -k test_external_import_connector ```

## Expected Output

Works are registered with GraphQL and shown in connector works

## Actual Output

Works are not registered with GraphQL, hence not shown in the connector site. Only the overview shows that 2 items are being imported.
 
## Additional information

I assume that it has nothing to do if the data comes from a connector, but maybe when the bundle doesn't contain a report. Another test connector which was working with a report was displaying its info on the detail site without problems.

![connector1](https://user-images.githubusercontent.com/73965465/127223624-e00efbc0-985c-4498-8f2c-a0b7b6efb743.png)

![connector2](https://user-images.githubusercontent.com/73965465/127223635-682bef9a-5d2e-4a83-ab69-4b51407ebb49.png)

![connector3](https://user-images.githubusercontent.com/73965465/127223713-1c5f7e75-9291-4ea1-b3f7-5a40aa23c35c.png)

If the test closes too quickly to see the result, add a `time.sleep(30)` here (https://github.com/OpenCTI-Platform/client-python/pull/199/files#diff-60a3e10f39d5be3c5589d4722fd100b3b01fe69f6a8384fd538bd532dbec1067R92) to get some more time.

**Comment by richard-julien** [comment]
Hi @nor3th ,

Bundle size is directly fetch from RabbitMQ.
Works must be managed by the connectors itself.

Looks like the test did not manage the work creation, so nothing unexpected for me here.

Take a look to https://github.com/OpenCTI-Platform/connectors/blob/master/mitre/src/mitre.py

```
work_id = self.helper.api.work.initiate_work(
     self.helper.connect_id, friendly_name
)
```

```
self.helper.send_stix2_bundle(
    pre_attack_data,
    entities_types=self.helper.connect_scope,
    update=self.update_existing_data,
    work_id=work_id,
 )
```

and

`self.helper.api.work.to_processed(work_id, message)`

**Comment by nor3th** [comment]
Hey @richard-julien 

Thanks a lot for that input. That did the trick indeed.

However for the internal import test connector import a single report, the work creation `initiate_work()` wasn't necessary for the work to be shown in the connector overview page.
https://github.com/OpenCTI-Platform/client-python/pull/199/files#diff-60a3e10f39d5be3c5589d4722fd100b3b01fe69f6a8384fd538bd532dbec1067R219-R250

**Comment by nor3th** [comment]
Ok, if no work id is specified, it's considered as manual import. Thanks for the clarification!! :) Closing this for now.
