### ISSUE TITLE
OpenCTI is not able to be start on AWS ECS

### ISSUE THREAD

**Issue by realzacharycheng** [OpenCTI-Platform/opencti#1488]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description
I am using aws ecs to create opencti, however when I tried to using the docker compose command to create the service in the  aws ecs the system keeps failing due to the opencti platform cannot connect to the Elasticsearch 

## Environment

1. AWS ECS Fargate kernel version Linux/4.14.225-168.357.amzn2.x86_64/amd64
2. 4.5.5
3. N/A
4. N/A

## Reproducible Steps
1. pull the docker-compose.yml file 
2. set up the aws context 
3. RUN docker compose up

## Expected Output

the openCTI instance successfully start up in the AWS ECS

## Actual Output

Due to OpenCTI cannot connect to the Elasticsearch, the task is failed.
 
## Additional information

![Screenshot 2021-07-29 at 1 14 25 PM](https://user-images.githubusercontent.com/79446411/127435604-c14b6b89-168e-46e8-9f79-d8a31c266ceb.png)
![Screenshot 2021-07-29 at 1 14 41 PM](https://user-images.githubusercontent.com/79446411/127435615-89f6f057-4f44-4ca1-a0fb-339099e4d586.png)

**Comment by richard-julien** [comment]
Hi, we already have a lot of users with opencti deployed on AWS.
Looks like a problem in your network/docker configuration.
Really difficult to help you on that. Double check your container configuration to see if your network/container address are accessible from the opencti container

**Comment by realzacharycheng** [comment]
Right now I am using the docker-compose file to start up the ecs, wondering if i have to set anything on the networking or security group in the docker-compose.yml file ? Thanks

**Comment by SamuelHassine** [comment]
Hello @realzacharycheng,

Nothing specific to set but some network flows need to be opened between containers. Basically, best is the whole stack can community to each others.

Kind regards,
Samuel
