### ISSUE TITLE
Report bulk "delete entities/observable" must removes the association, not the entities

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/opencti#1503]
## Description

When removing entities in a report via the checkbox and then delete, those SDOs/SCOs are entirely removed from OpenCTI instead of simply removing the link between the SDO/SCO and the report. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Under Analysis -> Create a new report
2. Add an entity to the report (for example a vulnerability)
3. Select all entities via the "select all" checkbox
4. Click on trash symbol to delete the entity
5. Entity is entirely deleted

![delete](https://user-images.githubusercontent.com/73965465/128209019-9792db92-2829-40d3-876c-ac66b23a96e7.png)

## Expected Output

Link between the SDO/SCO and the report is removed, but the SDO/SCO still exists. Like when clicking on the **:** next to the entity details (in the report entity list) and then clicking on remove, only the link between the SDO and the Report is removed.

## Actual Output

SDO/SCO is entirely deleted
 
## Additional thoughts about the implementation

For SDOs I'd prefer only removing the relationship between the report and the SDO, while for an SCO, I wouldn't mind having both options. If you for example automatically import observables from a pdf report and then you want to throw away false imports, deleting SCOs entirely might even be the proper way of going about it. Since I don't want to keep this SCO either way. Would it also be possible to get a warning when entirely removing an SCO if that SCO is also embedded in another report?

**Comment by richard-julien** [comment]
Hi @nor3th ,

For now its a "normal" behavior :)  The mass action screen is generic and so deletion will really delete the entities.
Now I understand that in this case its not really what you expect, its more about remove the association.

Put that as a feature request.
