### ISSUE TITLE
Handle search box filtering in bulk actions

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1504]
## Problem to Solve

Ability to take action (such as delete or export) objects in bulk, without selecting each one individually. For example, delete all observables that contain the string "temp", by filtering on all observables then deleting them.

It's possible to filter on objects, but when selecting all, all objects are selected (not just the filtered ones), so that the following "delete" action applies to all objects as well.

## Current Workaround

Manually select each object the action should be applied to

## Proposed Solution

Ensure that the "select all" button applies to only the visible objects (after a filter is enabled)

**Comment by richard-julien** [comment]
Hi @securitiz ,

Looks like its already the case for all filters except the free search box.

![image](https://user-images.githubusercontent.com/285555/128487640-dfce5f6f-c832-41e7-8ed4-39a68417f244.png)

Do you confirm?

**Comment by securitiz** [comment]
Apologies, I only tested with the search box and should have specified that in the issue
