### ISSUE TITLE
yarn serv exit code 1 [TR/ENG] Help

### ISSUE THREAD

**Issue by ugurkocmen** [OpenCTI-Platform/opencti#1511]
Hi, I'm having trouble installing opencti. I installed Nodejs, but I have a problem with the" yarn serv " command.

`$ yarn serv
yarn run v1.22.5
$ node build/index.js
{"category":"APP","version":"4.5.5","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-08-09T23:12:57.404Z"}
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-08-09T23:12:57.413Z","data":{"reason":"Redis seems down","http_status":500,"category":"technical"},"internalData":{}},"category":"APP","version":"4.5.5","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-08-09T23:12:57.413Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

System version : Ubuntu 20.04 LTS
Node version :  v14.17.4
yarn version :  1.22.5

![hata](https://user-images.githubusercontent.com/86979659/128786463-0828e5c1-9971-4c1e-a36f-5d738cde31c2.png)

**Comment by SamuelHassine** [comment]
Hello,

The log is pretty clear: "Redis seems down" means the platform is not able to connect to your Redis (on 127.0.0.1 port 6379).

Kind regards,
Samuel

**Comment by ugurkocmen** [comment]
> Hello,
> 
> The log is pretty clear: "Redis seems down" means the platform is not able to connect to your Redis (on 127.0.0.1 port 6379).
> 
> Kind regards,
> Samuel

Ok, I fixed the redis error but i have another error. I guess...
![new error](https://user-images.githubusercontent.com/86979659/128954311-97acead6-38ee-429d-a081-5a85287c7105.PNG)

**Comment by nor3th** [comment]
Hey 

The log is pretty clear: "ElasticSearch seems down" means the platform is not able to connect to your Elastic instance (on 127.0.0.1 port 9200).

FYI, you can also use the docker compose file, then you don't have to manually set up the dependencies and dbs.

Regards,

**Comment by ugurkocmen** [comment]
> Hey
> 
> The log is pretty clear: "ElasticSearch seems down" means the platform is not able to connect to your Elastic instance (on 127.0.0.1 port 9200).
> 
> FYI, you can also use the docker compose file, then you don't have to manually set up the dependencies and dbs.
> 
> Regards,

Hi sir, I tried installing with docker but I didn't because I never installed or used docker. Also I couldn't find any video for opencti installation. I want to install OpenCTI as it is very interesting for me. I have been trying to install for a few days with excitement. Sir, could you help me for installation OpenCTI?

**Comment by nor3th** [comment]
No worries, here's the setup description for the docker setup (for an Ubuntu server).
https://github.com/OpenCTI-Platform/docker

If you want, I wrote a small python script to automatically change the `ChangeMe` values. Give it a try if you want and let me know what you think of it.
https://github.com/nor3th/docker/blob/env_init/init.py (make sure to install the relevant dependencies)

**Comment by ugurkocmen** [comment]
> No worries, here's the setup description for the docker setup (for an Ubuntu server).
> https://github.com/OpenCTI-Platform/docker
> 
> If you want, I wrote a small python script to automatically change the `ChangeMe` values. Give it a try if you want and let me know what you think of it.
> https://github.com/nor3th/docker/blob/env_init/init.py (make sure to install the relevant dependencies)

Hello, i did everything with docker-compose. However, i have a problem. When i want go to localhost:8080, i don't seeing anything.

Edit :i started again and i saw this error.

![hata](https://user-images.githubusercontent.com/86979659/129484925-0d2a8280-7795-4c93-b29b-91da2bba636d.png)

**Comment by nor3th** [comment]
What's the log output of `docker logs opencti_minio`? Maybe increasing the memory does the trick?
Since docker should be running as a privileged service, there should be no need for starting docker with `sudo` rights.

`docker-compose -f docker-compose.yml up -d` usually works for me
