### ISSUE TITLE
Ability to filter objects by Creator

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#1512]
## Problem to Solve

There is no way to filter objects by the Creator. Users can only filter by the author. 

## Current Workaround

n/a, possibly use graphql or the API

## Proposed Solution

Create the ability to filter by Creator

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Already implemented in 5.4.0 for data/entities section.

This issue is kept to add creator at least in:

* Reports
* Observables
* Indicators
* Vulnerabilities

The creator must be visible in the data table and available in the filters of these 4 screens.
