### ISSUE TITLE
Live Streams vs TAXII Collections

### ISSUE THREAD

**Issue by trappersec** [OpenCTI-Platform/opencti#1519]
Hi,

I am wondering about a practical difference between the Live Streams and TAXII collections. 

How are the use cases different for each of them?

Thank you.

**Comment by richard-julien** [comment]
Hi @trappersec ,
Thats a really good question.
There is 2 big differences

1. Fetch vs Push

**Taxii collections** respect the TAXII standard that aims to let you consume stix data information. You can create collection to select the type of objects you want and consume it. It use standard http requests on the client side to fetch a bunch of 500 elements and the paginate to have more results. 

**In live stream** (data sharing) the client connect to a stream of taxii information using http SSE system. So every time something happen in the server the information is directly pushed to the client as fast as possible.

2. Specific vs consistant

With **Taxii collections** the server doesnt do any consistency actions, he only answers the 500 results of the type you ask for. You have to get the connected refs/objects information by yourself asking for another collection.

In **live stream** the server will ensure that the data sended to the client is consistant. So every dependencies/refs will be resolved and push in the stream if required. That really improve the simplicity of the consumers. This mode also permits to get deletion events with the content of the stix data before its deletion.

----
There is more difference and we plan to write a specific blog post about that.

Hope this explanation will help :)

**Comment by trappersec** [comment]
Hi @richard-julien,

Great answer. Thanks a lot for the clarification. 

Hope you have a good rest of your day.

**Comment by githubroom** [comment]
Hello, @richard-julien,
Is the blog post you mentioned earlier somewhere ready and posted? If so, can you share link?

Thanks

**Comment by richard-julien** [comment]
Hi @githubroom , not yet written. Really need to manage some time to do it. Lot of stuff to also explain on the latest 5.3.0.
