### ISSUE TITLE
Unable to manually create "observed data" entry

### ISSUE THREAD

**Issue by dcode** [OpenCTI-Platform/opencti#1525]
## Description

On the Events -> Observed data page, there is a '+' button allowing manual creation of an ObservedData, but the form fails function.

## Environment

1. OS (where OpenCTI server runs): GKE Kubernetes
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: Frontend
4. Other environment details: Firefox 91.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open the Activities -> Events -> Observed data page.
2. Click '+' button in bottom right.
3. Change the 'Number observed' field to anything besides default value of '1' using either keyboard or form controls.
4. Click 'Create' button.

## Expected Output

Expected an 'ObservedData' object to be created given the information provided.

## Actual Output

Get an error message claming `N` is not an integer, where `N` is the value entered in step 3 above.

 
## Additional information

NOTE: This screenshot was after I tried to manually change it back to '1' after attempting to submit '2' or anything else. Once the form field is marked as changed, it no longer parses the value as an integer.

![image](https://user-images.githubusercontent.com/171574/129765920-a6fe45ae-06de-446b-b4c6-8c4a4df1c434.png)

**Comment by SamuelHassine** [comment]
This bug will be solved in 5.0.0.
