### ISSUE TITLE
ElasaticSearch failure possibly causing connector issue

### ISSUE THREAD

**Issue by trappersec** [OpenCTI-Platform/opencti#1527]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I have to reset (as indicated below)

docker-compose up -d
docker rm -f $(docker ps -a -q)

my connectors evey so often as sometimes my platform is not working when I go to the Data>Connectors. From all connectors I can only see one working, that's typically the AlienVault. I have about 7 other ones currently, which show no messages. 
Once I go and reset them in the platform, the platform typically stops working. 

## Environment

1. OS (where OpenCTI server runs): { Centos7 }
2. OpenCTI version: { 4.5.5 }
3. OpenCTI client: { docker }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
 Run OpenCTI
Browse to Data > connectors

## Expected Output

Working connectors

## Actual Output

"at java.lang.Thread.run(Thread.java:831) [?:?]",
"Caused by: org.elasticsearch.action.NoShardAvailableActionException",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:500) ~[elasticsearch-7.13.1.jar:7.13.1]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:449) [elasticsearch-7.13.1.jar:7.13.1]",
"... 83 more"] }
{"type": "server", "timestamp": "2021-08-23T10:33:58,862Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "docker-cluster", "node.name": "f24df0f737ee", "message": "path: /opencti_internal_objects*%2Copencti_stix_meta_objects*%2Copencti_stix_domain_objects*%2Copencti_stix_cyber_observables*/_search, params: {ignore_throttled=false, index=opencti_internal_objects*,opencti_stix_meta_objects*,opencti_stix_domain_objects*,opencti_stix_cyber_observables*, _source_excludes=rel_*, _source_includes=*, track_total_hits=true}", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg" ,
"stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",

 
## Additional information

There is many more lines that show up in the erorr output, can supply if needed.

**Comment by nor3th** [comment]
Hey @trappersec 

This seems more like an elastic issue. Does your elastic instance have enough memory? The error log indicates that the elastic shards are not accessible. What to the opencti (`docker logs opencti_opencti-1`) logs say?

Regards,

**Comment by trappersec** [comment]
Hi @nor3th ,

What typically happens is that I docker rm -f $(docker ps -a -q) & docker-compose up -d my docker and the platform works. Then I only see one connector working, so I restart all of the other ones, which I suppose crashes my platform.

All I see in my platform logs (sorry do not have opencti_opencti-1) is the following : 
{"type":"READ_ERROR","operation_query":"query RootPublicQuery{settings{platform_theme platform_login_message platform_providers{name type provider}...AppThemeProvider_settings ...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}fragment AppThemeProvider_settings on Settings{platform_theme platform_theme_dark_primary platform_theme_dark_secondary platform_theme_dark_logo platform_theme_light_primary platform_theme_light_secondary platform_theme_light_logo}","inner_relation_creation":0,"operation":"RootPublicQuery","time":52,"variables":{},"size":2,"error":{"stacktrace":["TypeError: Cannot read property 'error' of null","at /opt/opencti/build/index.js:1:31119","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:94:5)","at async J (/opt/opencti/build/index.js:1:45877)"]},"category":"APP","version":"4.5.5","level":"error","message":"API Call","timestamp":"2021-08-23T10:57:36.504Z"

Thanks for your time.

**Comment by nor3th** [comment]
Hey

FYI: `docker-compose down -v` does the same trick as `docker rm -f $(docker ps -a -q) ` (if only opencti is running).
It is possible that due to the increased memory consumption, elastic might misbehave.

Could you please post the logs from `docker logs opencti_elastic-1` (or however your elastic container is called)

Thanks

**Comment by trappersec** [comment]
Hi @nor3th,

Please find the logs below.
{"type": "server", "timestamp": "2021-08-31T14:01:29,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "loaded module [x-pack-voting-only-node]" }
{"type": "server", "timestamp": "2021-08-31T14:01:29,663Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2021-08-31T14:01:29,664Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2021-08-31T14:01:29,761Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/centos-root)]], net usable_space [14.8gb], net total_space [45gb], types [xfs]" }
{"type": "server", "timestamp": "2021-08-31T14:01:29,762Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "heap size [7.7gb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2021-08-31T14:01:30,058Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "node name [4fe0cfe122e3], node ID [T1fCcisiTp6AMV1tOFOPdg], cluster name [docker-cluster], roles [transform, data_frozen, master, remote_cluster_client, data, data_content, data_hot, data_warm, data_cold, ingest]" }
{"type": "server", "timestamp": "2021-08-31T14:01:39,461Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
{"type": "server", "timestamp": "2021-08-31T14:01:40,684Z", "level": "INFO", "component": "o.e.i.g.LocalDatabases", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/usr/share/elasticsearch/config/ingest-geoip] for changes" }
{"type": "server", "timestamp": "2021-08-31T14:01:40,686Z", "level": "INFO", "component": "o.e.i.g.DatabaseRegistry", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "initialized database registry, using geoip-databases directory [/tmp/elasticsearch-9126829764383846936/geoip-databases/T1fCcisiTp6AMV1tOFOPdg]" }
{"type": "server", "timestamp": "2021-08-31T14:01:41,753Z", "level": "INFO", "component": "o.e.t.NettyAllocator", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]" }
{"type": "server", "timestamp": "2021-08-31T14:01:41,926Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "using discovery type [single-node] and seed hosts providers [settings]" }
{"type": "server", "timestamp": "2021-08-31T14:01:43,104Z", "level": "INFO", "component": "o.e.g.DanglingIndicesState", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
{"type": "server", "timestamp": "2021-08-31T14:01:44,008Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "initialized" }
{"type": "server", "timestamp": "2021-08-31T14:01:44,008Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "starting ..." }
{"type": "server", "timestamp": "2021-08-31T14:01:44,031Z", "level": "INFO", "component": "o.e.x.s.c.f.PersistentCache", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "persistent cache index loaded" }
{"type": "server", "timestamp": "2021-08-31T14:01:44,251Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "publish_address {172.20.0.19:9300}, bound_addresses {0.0.0.0:9300}" }
{"type": "server", "timestamp": "2021-08-31T14:01:44,949Z", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "cluster UUID [Ky7MMsmOR96TubnsNPuSxg]" }
{"type": "server", "timestamp": "2021-08-31T14:01:45,102Z", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "elected-as-master ([1] nodes joined)[{4fe0cfe122e3}{T1fCcisiTp6AMV1tOFOPdg}{aD8S9pKMQPSoygNJj8eMtQ}{172.20.0.19}{172.20.0.19:9300}{cdfhimrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 515, version: 8349, delta: master node changed {previous [], current [{4fe0cfe122e3}{T1fCcisiTp6AMV1tOFOPdg}{aD8S9pKMQPSoygNJj8eMtQ}{172.20.0.19}{172.20.0.19:9300}{cdfhimrstw}]}" }
{"type": "server", "timestamp": "2021-08-31T14:01:45,233Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "master node changed {previous [], current [{4fe0cfe122e3}{T1fCcisiTp6AMV1tOFOPdg}{aD8S9pKMQPSoygNJj8eMtQ}{172.20.0.19}{172.20.0.19:9300}{cdfhimrstw}]}, term: 515, version: 8349, reason: Publication{term=515, version=8349}" }
{"type": "server", "timestamp": "2021-08-31T14:01:45,342Z", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "publish_address {172.20.0.19:9200}, bound_addresses {0.0.0.0:9200}", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:45,343Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "started", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:45,970Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "license [145fb34f-304a-46ab-ac02-9eb8d43bd79f] mode [basic] - valid", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:45,972Z", "level": "INFO", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "Active license is now [BASIC]; Security is disabled", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:45,973Z", "level": "WARN", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:45,983Z", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "recovered [10] indices into cluster_state", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }
{"type": "server", "timestamp": "2021-08-31T14:01:51,330Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[opencti_stix_domain_objects-000001][0]]]).", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg"  }

**Comment by trappersec** [comment]
I have got a couple more questions, if I may.

1) How can I monitor for changes in health of the critical images?
2) If this is a memory issues, how much more should I allocate? 

Many thanks.

**Comment by nor3th** [comment]
Hey @trappersec 

The health of elastic can be monitored using the cluster health status https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html . If you have more than one elastic node, then the status should mostly be green. With only one node, also yellow is fine. If the status is red like in your last log entry, I would try giving elastic more memory.
`
"type": "server", "timestamp": "2021-08-31T14:01:51,330Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "4fe0cfe122e3", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[opencti_stix_domain_objects-000001][0]]]).", "cluster.uuid": "Ky7MMsmOR96TubnsNPuSxg", "node.id": "T1fCcisiTp6AMV1tOFOPdg" }
`

I define the RAM threshold for my elastic server like this in the docker config. If this issue persists, try increasing the memory.
```
environment:
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
```

Regards,
