### ISSUE TITLE
Add the exclude function in filter

### ISSUE THREAD

**Issue by realzacharycheng** [OpenCTI-Platform/opencti#1528]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Excluding some kind tag / label in reports or observables

## Current Workaround

currently either to include all the tag / label or there is no solution to filter out the unwanted tagged / labeled reports or observables

## Proposed Solution

Add the excluding tag / label function in the filter

**Comment by richard-julien** [comment]
Close, will be handle in https://github.com/OpenCTI-Platform/opencti/issues/2588
