### ISSUE TITLE
Can not delete "marking definition" on incident page

### ISSUE THREAD

**Issue by M-J-LIN** [OpenCTI-Platform/opencti#1529]
## Description

Can not delete "marking definition"  on incident update page.
![image](https://user-images.githubusercontent.com/21030410/130721378-f1b9b58b-1354-4e21-9e7c-5a5e499c01b5.png)

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: OpenCTI 4.4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to "Events" -> "Incidents" page
2. Create new incident or click on existing one
3. Click "Update"
4. Click "x" on any of markings
5. The markings still stay on the old state

## Expected Output

The marking should be deleted after click "x"

## Actual Output

Nothing happened
 
## Additional information

It seems to the frontend bug. When clicking the "x" button on marking, the graphQL will send "XOpenCTIIncidentEditionOverviewRelationAddMutation" API, but it should send "XOpenCTIIncidentEditionOverviewRelationDeleteMutation" API I think.

**Comment by amr-cossi** [comment]
The same issue seems to still be here for the field "Confidence level" of incidents (tested on current demo).

**Comment by SamuelHassine** [comment]
Thanks! Solved now!
