### ISSUE TITLE
GraphQL not launch.

### ISSUE THREAD

**Issue by Orcun-Karatas** [OpenCTI-Platform/opencti#153]
## Description
GraphQL not launch...

## Environment

1. Ubuntu 15.0
2. OpenCTI version:1.0.2 
3. OpenCTI client:frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.
2.docker-compose up
 worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...

**Comment by SamuelHassine** [comment]
@Orcun-Karatas: you are using the previous version of OpenCTI which is no longer compatible with the Python library and other components. Are you able to use the latest version 1.1.0 and redo your docker-compose? 

```
$ docker-compose down
$ git pull origin master
$ docker-compose up
```

**Comment by Orcun-Karatas** [comment]
thanks I've done the steps you wrote, but the problem still continues. 

worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...

Maybe I need delete all components and clear installation?

**Comment by richard-julien** [comment]
Hi @Orcun-Karatas , can you check the logs of the opencti platform docker? Maybe you forget to setup all the env variables needed in the docker compose file, can you take a look if admin token and password are correctly setup? If not take a look to https://opencti-platform.github.io/docs/installation/docker

**Comment by SamuelHassine** [comment]
@Orcun-Karatas: you are still on the old version. The worker does not wait for GraphQL to launch anymore and integration does not exists anymore. Have you updated the `docker-compose.yml` file with the latest version of the Github repository?

**Comment by Orcun-Karatas** [comment]
Thanks for the help but the problem was not resolved. This time, I get worker HTTP error.
Same error.
https://github.com/OpenCTI-Platform/opencti/issues/155

**Comment by richard-julien** [comment]
Seems to be a configuration problem, dont hesitate to reopen the issue if needed.
