### ISSUE TITLE
help me with default creds 

### ISSUE THREAD

**Issue by kimreq** [OpenCTI-Platform/opencti#1532]
Hi folks ,

I'm trying to setup opencti which is more complicated than i thought , but mean while i need to see demo instances , could you please help me with default creds for demo ?

**Comment by nor3th** [comment]
Hey @kimreq 

What issue are you having when setting up OpenCTI? Have you tried using the docker compose file? With that the setup works usually really well and smoothly.

Concerning the demo instance, you can register an account there yourself as well. 
Open the URL https://demo.opencti.io/dashboard , then click on "Login with Citeum Collective" and then click on the a bit hidden "Register" link.
![screen](https://user-images.githubusercontent.com/73965465/131253130-841db423-b101-4600-8875-17e8a8065482.png)

Regards,

**Comment by kimreq** [comment]
thanks i got it , i thought some default creds are available
