### ISSUE TITLE
how can i add the relation "CONSISTS_OF" between INFRASTRUCTURE and OBSERVED_DATA

### ISSUE THREAD

**Issue by letitbezh** [OpenCTI-Platform/opencti#1534]
i have read code and stix2.1
```
[`${ENTITY_TYPE_INFRASTRUCTURE}_${ENTITY_TYPE_CONTAINER_OBSERVED_DATA}`]: [RELATION_CONSISTS_OF],
```

but how can i add the relation "CONSISTS_OF" between INFRASTRUCTURE and OBSERVED_DATA

**Comment by nor3th** [comment]
Hey @letitbezh 

I just checked and via the UI entities are added as referenced objects to an observed data, but the relationships window for an infrastructure doesn't allow for a `consists_of` relationship to be created. I would classify this as bug, @SamuelHassine ?

Regards,
