### ISSUE TITLE
Be able to go back or cancel suppression

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1536]
## Problem to Solve

When suppressing an item, a confirmation window "are you sure you want to delete this item" or a "go back/cancel the last action would be highly useful to avoid mistakes and misclicks.

## Current Workaround

Recreate what has been suppressed by error.

**Comment by SamuelHassine** [comment]
Logical deletion.

**Comment by SamuelHassine** [comment]
Also, in the confirmation, add the details about the element which will be deleted like: "You are about to delete the Intrusion Set XXXX, do you confirm?".

**Comment by nino-filigran** [comment]
Update on this functionnality: we will introduce the concept of "removal" (in comparison with delete).

When a user will delete an entity, the user will not exactly delete but remove the entity from the data set. As an effect, it will remove the entity from any view, any count, and the entity will be marked as remove, but not deleted. 
Then, all the entities marked as removed will be cleaned (or permanently deleted) via a Retention policy that will be built-in.

Whenever the user will filter on the Remove entities, the user will be able to see all entities that are removed and decide individually (or through mass operation) if the selected entities need to be restored.

This way, if a user mistakenly deletes an entity, the user will always be able to restore the given entities.
