### ISSUE TITLE
Frontend fails to compile. 'Module parse failed: Unexpected character '#' : three.module.js'

### ISSUE THREAD

**Issue by BigBallard** [OpenCTI-Platform/opencti#1537]
## Description

I have cloned the repository and ran npm install on both the frontend and graphql folders. I also ran the python install for the graphql. 

I start up the graphql server with npm start and once it loads successfully I startup the frontend with npm start. After like 5 minutes the frontend finally starts and an error shows up that prevents me from accessing the UI.

```
Failed to compile.

./node_modules/three/build/three.module.js 6583:18
Module parse failed: Unexpected character '#' (6583:18)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     key: "alphaTest",
|     get: function get() {
>       return this.#alphaTest;
|     },
|     set: function set(value) {
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
```

I have not made any code changes so this is straight from a clone.

## Environment

1. Windows 10
2. OpenCTI master branch, commit d420ce
3. Python 3.9.6
4. NPM 7.18.1, node 16.4.0
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run `npm install` in **opencti-platform/opencti-graphql**
2. Run `npm install` in **opencti-platform/opencti-front**
3. Run `pip3 install -r requirements.txt` in **opencti-platform/opencti-graphql/src/pyhon**
4. Start up the docker containers from the root directory with `docker-compose up -d`
5. Start up the graphql server in opencti-platform/opencti-graphql with `npm start`
6. Start up the frontend in opencti-platform/opencti-front with `npm start`
7. Wait for the frontend to build and load, should observe the error above.

## Expected Output

Expected the OCTI frontend to load and be prompted to login

## Actual Output

The error above

**Comment by nor3th** [comment]
Hello @DallasP9124 

It seems more to be an issue with a dependency library...
One the other hand, I don't have this issue with the libraries on my system.
Try deleting all node_modules, download them again and then see if the issue is still there.

Regards,

**Comment by SamuelHassine** [comment]
Hello @DallasP9124 @nor3th, I think you should use the latest version of the master repository and use `yarn` instead of `npm`, the file `yarn.lock` will ensure you have exactly the same stack as we have.

**Comment by BigBallard** [comment]
I did both delete all modules and redid the install using yarn. This made the frontend render so not sure if it was the reinstall of the modules or if it was yarn. Either way, if yarn is the preferred package manager, I would think that would be noted somewhere in the documentation.
