### ISSUE TITLE
OIDC redirect causes 'too many redirects' on successful login from Keycloak

### ISSUE THREAD

**Issue by BigBallard** [OpenCTI-Platform/opencti#1540]
## Description

After a successful login using a third party OIDC provider, namely Keycloak, the redirect to <opencti>/auth/oic/callback causes the browser to present **ERR_TOO_MANY_REDIRECTS**.

## Environment

1. Windows 10
2. OpenCTI master branch, commit d420ce
3. Python 3.9.6
4. NPM 7.18.1, node 16.4.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure opencti-platform/opencti-graphql to use an OIDC provider
2. Configure the callback to http://localhost:4000/auth/oic/callback
3. Startup opencti-platform/opencti-graphql with yarn start
4. Startup opencti-platform/opencti-front with yarn start
5. Wait for frontend to render
6. Select 'loging with <oic provider> (Keycloak in my case)
7. Login with oic provider
8. Should see ERR_TOO_MANY_REDIRECTS

## Expected Output

Redirect to callback url and display dashboard

## Actual Output

Browser error ERR_TOO_MANY_REDIRECTS
 
## Additional information

No code changes have been made. This is occurring with the direct code pulled from repository master branch

**Comment by SamuelHassine** [comment]
Hello @DallasP9124,

Can you please try with the callback to `http://localhost:4000/auth/oic/callback`? Once redirected you can go back on port 3000.

Tell me if it works.

Kind regards,
Samuel

**Comment by BigBallard** [comment]
@SamuelHassine sorry, that was a typo on my behalf. The URL I have configured is on port 4000 not 3000. So the issue stands the same. And Ill update the url in the ticket.

**Comment by richard-julien** [comment]
Do you have any error logs?

**Comment by BigBallard** [comment]
@richard-julien the only error that occurs per redirect on the graphql server side is:
```
{"error":{"errno":-4058,"syscall":"open","code":"ENOENT","path":"src\\http/../../public/index.html"},"category":"APP","version":"5.0.0","level":"error","message":"[EXPRESS] Error http call","timestamp":"2021-09-02T16:28:23.529Z"}
```

**Comment by richard-julien** [comment]
Ok. Do you have any reason to start the front and back separately? This is for developement purpose?
If not, this is not the way we need to start opencti.
You have to:
* Build the front with opencti-platform/opencti-front with yarn build
* Build the back with opencti-platform/opencti-graphql with yarn build
* Startup opencti-platform/opencti-graphql with yarn serv
Then access http://localhost:4000 that will contains everything you need

**Comment by BigBallard** [comment]
@richard-julien yes it is for development reasons which I can't imagine is an uncommon thing so simply building and serving shouldn't be the only fix to inf redirects.

**Comment by richard-julien** [comment]
For development the redirect of the OIC should be done on the front port and not graphql port

**Comment by BigBallard** [comment]
@richard-julien is this documented anywhere?

**Comment by richard-julien** [comment]
I dont think. There is not a lot of documentation. We need to improve that but its really time consuming and hard to maintains.

**Comment by BigBallard** [comment]
But necessary don't you think? Especially when there are these types of 'gotchias' that are required to get a development environment to even work properly.

In any case switching the port fixed my issue. Thank you!

**Comment by richard-julien** [comment]
Glad it solve your problem.
