### ISSUE TITLE
Allow comparing activity by Connector.

### ISSUE THREAD

**Issue by eliataylor** [OpenCTI-Platform/opencti#1544]
## Problem to Solve

It's difficult to compare Connectors. It seems some come with costs, so it would be nice to see which provide the most optimal reads / adds / edits / deletes. 

## Current Workaround

Apparently, there isn't a way to see which connector imported what.

## Proposed Solution

log format:
`timestamp` | `connector id` | `crud verb` | `stix id` | maybe `levenshtein distance` of change on updates

While I'd be satisfied with these logs in `docker` it would be great to add a data table and graph to the interface comparing Connectors by activity. 

A. Use [worker.py](https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-worker/src/worker.py) to write to graphql.
B. Add a class in [pycti](https://opencti-client-for-python.readthedocs.io/en/latest/pycti/pycti.html#classes) to handle this logging to graphql.

_either of these would greatly benefit from a config option to only keep X most recent log items in this table_

C. Add the `connector id` as a `Label` to every stix object effected (using `pycti`). This won't support what changed or when, but at least allow comparing activity.

D. ???

**Comment by SamuelHassine** [comment]
Add a view to compare logs between multiple users in the administration.

**Comment by SamuelHassine** [comment]
Done in activity monitoring + custom dashboard with "creator" filters.
