### ISSUE TITLE
Worker HTTP Connection Problem

### ISSUE THREAD

**Issue by kaganisildak** [OpenCTI-Platform/opencti#155]
Greetings
I try install opencti via docker on my server but I get the following error although I do what is written in the document.

> worker-import_1      | ERROR:root:An unexpected error occurred: { HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feab6d43c88>: Failed to establish a new connection: [Errno 111] Connection refused')) }
> elasticsearch_1      | [2019-07-25T00:25:25,000][WARN ][o.e.x.s.a.s.m.NativeRoleMappingStore] [b9iks9A] Failed to clear cache for realms [[]]
> worker-import_1      | INFO:root:Received a new message of type "stix2-bundle"
> worker-import_1      | INFO:root:Importing a marking-definition
> worker-import_1      | ERROR:root:An unexpected error occurred: { HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feab6ce5550>: Failed to establish a new connection: [Errno 111] Connection refused')) }
>

**Comment by richard-julien** [comment]
Hi @kaganisildak can you check if you configure correctly the OPENCTI_TOKEN env variable of the worker-import image. It need to be equals to the UUID you configure for the APP__ADMIN__TOKEN variable.

**Comment by SamuelHassine** [comment]
Hi @kaganisildak: The error message is `Failed to establish a new connection, connection refused`. So the worker is not able to connect to the GraphQL API. You have to check:

- the Docker `opencti` is launched and that the GraphQL API is started ;
- the Docker is named `opencti` (corresponding hostname) ;
- `APP__PORT` is `8080` or you have to change the URL in the worker environement variables.

Best regards,
Samuel

**Comment by richard-julien** [comment]
Seems to be a configuration problem, dont hesitate to reopen the issue if needed.

**Comment by Liloker** [comment]
I meet the same problem, I think the vision of urllib3 used by python3 in several docker image to high, which cause these problems.
![image](https://github.com/user-attachments/assets/d9052bbe-208e-40c8-a146-6994a8d3a188)

**Comment by dominictory** [comment]
> I meet the same problem, I think the vision of urllib3 used by python3 in several docker image to high, which cause these problems. ![image](https://private-user-images.githubusercontent.com/55574496/367219392-d9052bbe-208e-40c8-a146-6994a8d3a188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Njg2NzIsIm5iZiI6MTcyOTY2ODM3MiwicGF0aCI6Ii81NTU3NDQ5Ni8zNjcyMTkzOTItZDkwNTJiYmUtMjA4ZS00MGM4LWExNDYtNjk5NGE4ZDNhMTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA3MjYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzU5YzNjMmI0YzE1OWViNTBhYzI4MTE4NGE1OTFkYjQyMmEzODQ5Njc5MjU0ZDI3ZWMzNDVhMjhkNzNhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DGObrQNBz2EYbx4o3yPjNfYzSxjucuIBtlqNTVDIETg)

I'm getting a lot of these too on 6.3.6. Eventually, workers (even though connected according to UI) just show connection reset errors after a while, bundles stop getting processed.
