### ISSUE TITLE
How to use OpenCTI without SMTP server

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#1553]
## Description

I have no SMTP server on my computer and OpenCTI do not start.

## Environment

1. OS (where OpenCTI server runs): Mac OS 11.5.1
2. OpenCTI version: OpenCTI 5.0.0
3. OpenCTI client: front end
4. Other environment details: Safari 14.1.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. OpenCTI Platform can't start cause SMTP server is down (I don't use SMTP server, and I won't to use it)
2. 
3. 

## Expected Output

OpenCTI platform works

## Actual Output

An "SMTP server seems down" error. Where can I disable the subscription manager ?

**Comment by nor3th** [comment]
Hey @JeromeSRT 

You can disable the subscription manager with the either following environment variable in the docker config
```
- SUBSCRIPTION_SCHEDULER__ENABLED=false
```
or for the manual setup you set `enabled` to false in the `default.json` config.
```
"subscription_scheduler": {
    "enabled": false,
    "lock_key": "subscription_manager_lock",
    "interval": 10000
  },
```

Regards,

**Comment by JeromeSRT** [comment]
> Hey @JeromeSRT 
> 
> 
> 
> You can disable the subscription manager with the either following environment variable in the docker config
> 
> ```
> 
> - SUBSCRIPTION_SCHEDULER__ENABLED=false
> 
> ```
> 
> or for the manual setup you set `enabled` to false in the `default.json` config.
> 
> ```
> 
> "subscription_scheduler": {
> 
>     "enabled": false,
> 
>     "lock_key": "subscription_manager_lock",
> 
>     "interval": 10000
> 
>   },
> 
> ```
> 
> 
> 
> Regards,
> 
> 

Hey @nor3th,

Thanks a lot... It runs, the arguments are missing in my production.json file...

Regards,

**Comment by 11eddie** [comment]
I've tried changing the default.json config from enabled false to true in default,json and I added subscription scheduler env variable to .env but subscription manager is still listed as disabled in the UI, how to I enable subscription manager

**Comment by JeromeSRT** [comment]
> I've tried changing the default.json config from enabled false to true in default,json and I added subscription scheduler env variable to .env but subscription manager is still listed as disabled in the UI, how to I enable subscription manager

Hey @11eddie,

You have to change the configuration of the production.json file, if you have a manual installation as indicated in https://www.notion.so/Manual-deployment-b911beba44234f179841582ab3894bb1.
Copy/paste default.json, and rename it production.json, then make the change of the configuration for your OpenCTI platform.

Regards, Jerome
