### ISSUE TITLE
Line break in description fields for notes and relations is not displayed

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1559]
## Description
In the description field of notes and for relations, linebreaks are not taken into account : no matter how much spacing is added between two lines in the form, the display does not show the linebreaks.

In description fields for entities, the line break is displayed, but only a single one, no matter how much are put in the form.

In all these cases, when the form is opened again for modification, the intended linebreak put by the user is visible.

## Environment

Reproduced in the demo instance today.
Active on OpenCTI V4.5.5

## Reproducible Steps
1. Go to notes or a relation
2. Open the modify form
3. add a description with linebreaks
4. close the form and look at the display in the description field

## Expected Output

Linebreaks intended by the user should be displayed as such.
 

## Screenshots (optional)
Example with notes : in the form
![test_saut_lignes](https://user-images.githubusercontent.com/49722941/132194856-c579f6d1-f2f6-4fa8-8890-bfae2bdb0fde.png)

example with notes : display
![example_saut_lignes_notes](https://user-images.githubusercontent.com/49722941/132196140-dbd49968-0a21-41c4-9a0a-d0acf97cc05f.png)

Example for relations (the window allow to see both the intended spacing by the user and the displayed spacing)
![linebreak_broken_relations](https://user-images.githubusercontent.com/49722941/132195559-1be6856a-22f8-4dbf-9328-deb911f206be.png)

Example for entities : when in the form
![line_break_entitioes](https://user-images.githubusercontent.com/49722941/132195575-e1de376c-48ce-4040-ac2c-c4f020800045.png)

Example for entities : when displaying

![test_linebreak_entity](https://user-images.githubusercontent.com/49722941/132195566-2fb907b0-fb7b-4f49-9e92-8699915efd84.png)

**Comment by SamuelHassine** [comment]
All markdown field have been aligned and should have the same display now.

Common marks are now supported to break lines:
```
fdfsdff
\
\
\
fdsfsd
\
\
dsqdqsdsd
```
