### ISSUE TITLE
Add "Signature" Observable Type

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/opencti#1561]
## Use case

As a Threat Intelligence Analyst, I need to track Malware/IDS/IPS signatures so I can correlate and identify signatures across multiple vendors.

## Current Workaround

Hardcoding aliases to Malware Objects

## Proposed Solution

Expand the Observed data types to include 'Signature' as a Type

## Additional Information

None

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Hello @TechBurn0ut,

Signatures are Indicators in STIX. We already have pattern types SNORT, SURICATA that are IDS signatures. If you need more pattern types than the existing, please let us know and we will implement them.

Kind regards,
Samuel
