### ISSUE TITLE
Open ID Provider configuration fails with Keycloak server with self signed certificate

### ISSUE THREAD

**Issue by BigBallard** [OpenCTI-Platform/opencti#1562]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I am attempting to get the openid provider configured with a URL to a Keycloak server in a development environment with a self-signed certificate. When running opencti-graphql I get an error refering to self signed certificates:

```
yarn run v1.22.11
$ webpack --mode development
{"category":"APP","version":"5.0.0","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-09-07T18:55:07.292Z"}
{"category":"APP","version":"5.0.0","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-09-07T18:55:07.323Z"}
{"category":"APP","version":"5.0.0","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-09-07T18:55:07.332Z"}
{"category":"APP","version":"5.0.0","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-09-07T18:55:07.637Z"}
{"category":"APP","version":"5.0.0","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-09-07T18:55:07.643Z"}
{"category":"APP","version":"5.0.0","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-09-07T18:55:07.644Z"}

E:\web\opencti\opencti-platform\opencti-graphql\node_modules\openid-client\lib\issuer.js:265
    const err = new AggregateError(errors);
                ^
AggregateError: Issuer.discover() failed.
    RequestError: self signed certificate
    RequestError: self signed certificate
    at Function.discover (E:\web\opencti\opencti-platform\opencti-graphql\node_modules\openid-client\lib\issuer.js:265:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Question, how do we get self signed https providers to work?

## Environment

1. Windows 10
2. OpenCTI version: master branch
3. OpenCTI client: master branch
4. Other environment details: yarn 1.22.11, node 16.4.0, npm 7.18.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure opencti-graphql provider with server that has self signed certificate for https
2. Startup opencti-graphql with yarn start
3. Should observe error similar to above.

**Comment by fdevillard** [comment]
Hello 👋 

Have you tried this: https://github.com/panva/node-openid-client/issues/157 ?

Obvsly, that should leave a dev environment 🙃

**Comment by BigBallard** [comment]
@fdevillard thank you. This resolved the issue.
