### ISSUE TITLE
The deleted or merged entities should not be imported once again.

### ISSUE THREAD

**Issue by Ken-Abruzzi** [OpenCTI-Platform/opencti#1564]
## Use case

The entities fetched by the connectors sometimes have different names but have the identical contents. In this case, I will try to merge these entities. Sometimes the entity's name is too ambiguous to understand, so I will try to rename it to make it easy to understand.

## Current Workaround

 In both circumstances, the relative entities will be imported again even though I set the environmental variable "CONNECTOR_UPDATE_EXISTING_DATA=false" for every connector. 

![deleted today](https://user-images.githubusercontent.com/68931768/132638703-c19df589-177f-4896-9a4c-6af2787935f1.png)
_Figure 1. These entities are merged or renamed by the adminstrator on Sep 6_

![task complete](https://user-images.githubusercontent.com/68931768/132638905-a78e6524-8dba-4ab1-95a6-bb05cb060e7e.png)
_Figure 2. The modification task was complete on Sep 6_ 

![image](https://user-images.githubusercontent.com/68931768/132639104-0709e089-400b-4c1c-9c4e-5bd56c0e29cd.png)
_Figure 3. The relative entities are imported again on Sep 8_ 

## Proposed Solution

I hope the OpenCTI can have the memory about what entities are modified by the administrator, and no automatic modification should be appended to these entities.

Thank you!

**Comment by richard-julien** [comment]
You're right, looks like we forget the propagate the stix ids of the merged report.

We will change that in the next version

**Comment by Ken-Abruzzi** [comment]
> You're right, looks like we forget the propagate the stix ids of the merged report.
> 
> We will change that in the next version

Thank you! I'm looking forward to it!

**Comment by Ken-Abruzzi** [comment]
@richard-julien Hello! Thanks for your efforts. But something is still wrong. I merged some identical entities into one and rename it, and the new entity's stix ids are shown as Figure 1.
![image](https://user-images.githubusercontent.com/68931768/138280735-99af31e7-c0e4-444e-b194-5186e9b8d30d.png)
Figure 1. The identical entities are merged into one and given a new name.

But after some connectors work, the old entity name shows up again as in Figure 2.
![image](https://user-images.githubusercontent.com/68931768/138280666-f757b9f2-52a3-4d78-ab57-0843fa5868a0.png)
Figure 2. The renamed entity are modified to the previous one.

As you can see, the stix ids underlined in red in Figure 1 and Figure 2 are the same.

**Comment by richard-julien** [comment]
Hi @Ken-Abruzzi ,

Thanks for your feedback. Thats a side effect and obviously a new problem :)

Today we dont have any mecanism to "freeze" an element, so each time you receive again one of the element of the merge, we will try to update the field (if update=true in the connector). The name is part of the update and so the name will be change along with the standard_id because name is part of key.

Im not very sure how we can solve that. Maybe some kind of mecanism to freeze a field to explicitly tell to absorption that now this field will never be updated. WDYT? any other idea?

**Comment by Ken-Abruzzi** [comment]
Thanks @richard-julien . I have already set the "connector_update_existing_data" environmental variable as "false" for every connector. Why do they still update the entity? Maybe you can set one attibute of the entity modified by the administrator as "true". If the attribute is true, it should never be updated automatically.

**Comment by richard-julien** [comment]
With connector_update_existing_data this behavior is not normal. Do you know what connector is responsible for this update?

**Comment by Ken-Abruzzi** [comment]
> With connector_update_existing_data this behavior is not normal. Do you know what connector is responsible for this update?

Sorry. I also have no idea. I will tell you if I find the answer someday. Thank you!

**Comment by richard-julien** [comment]
Do you use the history connector? If you use a different user for each connector you should be able to know who and when in the history element menu

**Comment by Ken-Abruzzi** [comment]
@richard-julien Hello! There is only one user that is me. Is it necessary to install a history connector?

**Comment by richard-julien** [comment]
Its not require to install the history connector if you don't need it.
But the best practice is to create a specific user for each connector in order to have the possibility to have a correct actions traceability in the stream/history.
