### ISSUE TITLE
Implement the STIX malware-analysis object

### ISSUE THREAD

**Issue by debelyoo** [OpenCTI-Platform/opencti#1565]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

- [x] Add STIX 2.1 Malware-Analysis SDO in OpenCTI datamodel
- [ ] Create panels for displaying Malware-Analysis SDO data in the platform
    - [x] Create Malware-Analysis custom Overview Tab
    - [x] Create Malware-Analysis Data Tab
    - [x] Create Malware-Analysis History Tab
    - [ ] Modify File/URL/NetworkTraffic/Artifact/Domain/Hostname Overview Tab to display the list of related Malware-analysis
 - [ ] Modify [[Hybrid Analysis enrichement connector](https://github.com/OpenCTI-Platform/connectors/tree/master/internal-enrichment/hybrid-analysis-sandbox)](https://github.com/OpenCTI-Platform/connectors/tree/master/internal-enrichment/hybrid-analysis-sandbox) to have a means to feed the platform with the newly Malware-Analysis SDO. This connector will now (in addition of what it is currently doing):
    - create a Malware-Analysis SDO with properties filled in
    - add the enriched SCOs (File, URL or Network Traffic) as a Nested Object of the Malware-Analysis instance
    - add every SCOs created and related through the enrichment process as Nested Objects of the Malware-Analysis instance.
- [ ] Create [[Hybrid Analysis import connector](https://github.com/OpenCTI-Platform/connectors/issues/295)](https://github.com/OpenCTI-Platform/connectors/issues/295) that will ingest the [[Hybrid Analysis public json feed](https://www.hybrid-analysis.com/feed?json)](https://www.hybrid-analysis.com/feed?json) based on:
    - some configuration flags, at least related to “Threatscore” and “Threatlevel_human” values
    - Create a Malware-Analysis instance for each filtered element of the feed
    - create an external reference for the full Hybrid Analysis report
    - create all related SCOs with adequate relations
- [ ] Publish a blog article to explain the feature

**Comment by securitiz** [comment]
I'm also curious about this

**Comment by richard-julien** [comment]
I dont think there is a reason to not doing it. Should be added in opencti at some point. wdty @SamuelHassine , valid feature request?

**Comment by SamuelHassine** [comment]
It is a valid feature request.

**Comment by Jipegien** [comment]
@yassine-ouaamou I have updated the description to match what is expected as MVP. You can refer to the "Epic" Notion page for further information about the context.
