### ISSUE TITLE
Why is OpenCTI API so heavy on CPU usage ?

### ISSUE THREAD

**Issue by debelyoo** [OpenCTI-Platform/opencti#1626]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hello.
I setup the MISP connector and would like to load the events from my MISP instance. When importing the events, it leads to 1M+ messages in MISP connector’s queue (rabbitMQ).
I have 3 workers processing the messages and the bundles are processed at a rate of circa 9 bundles / sec which leads to a very long ingestion.
Checking the CPU usage of the different components (mainly the workers, OpenCTI API and elasticsearch) I notice that the API often uses 100% of CPU whereas ES is pretty quiet.
When I profile the API, I notice that most of the time is spent in the updateAttributeRaw() function. I’m not sure to understand exactly what this function does. I don’t see any calls to the backends in it. Could you give me some more details about the role of this function ?

## Environment

1. OS (where OpenCTI server runs): CentOS 7
2. OpenCTI version: 5.0.1
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start MISP connector (with a decent number of events to import)
2. Let the ingestion run with 3 workers

**Comment by sukesh-ak** [comment]
Code for updateAttributeRaw() is here

https://github.com/OpenCTI-Platform/opencti/blob/c3aca19e52fe6d5b5353fbf92653394d5d51eb81/opencti-platform/opencti-graphql/src/database/middleware.js#L1492

**Comment by richard-julien** [comment]
Hi @debelyoo,

When injecting data openCTI will do a lot of resolution/checking to be able to enrich/merge ... the elements. When a connector try to inject an already existing element  OpenCTI will try to update the element if needed, so its basically why if you inject an already "know" dataset we will have a lot of call in this function.

For the CPU usage i dont have any explanation, you are the first reporting this kind of problem. With 3 workers maybe you have to upgrade you api cpu capacity.

**Comment by debelyoo** [comment]
Thanks for the explanation.
Regarding the high CPU load of the API, this was due to a duplicated marking-definition object in the system (pushed by a custom connector). It is fixed now.
