### ISSUE TITLE
Worker does not send ack when processing a long running task

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#163]
## Problem to Solve

If the import or export message implies a long-running task, the worker is not able to send the ack to RabbitMQ. That leads to process messages multiple times and infinite processing.

## Current Workaround

None.

## Proposed Solution

Implement a threaded process and use the pika `connection.sleep` to maintain the connection as [described here](https://github.com/pika/pika/issues/930).

## Additional Information

None.

**Comment by richard-julien** [comment]
Agree. A threaded model will also permits to use the basic_consume for each queue. For me we need to have the control in the main thread (list queue, create thread, etc), and a specific thread for each queue we need to consume. With this approach we also should be able to display the number of active worker in the UI.

**Comment by SamuelHassine** [comment]
Deal :)
