### ISSUE TITLE
Line breaks are not correctly implemented

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1638]
## Description
Following up on issue https://github.com/OpenCTI-Platform/opencti/issues/1559
PS: this can be a feature of the md editor, but at least the first one is a problem. The second one would be useful to adapt to allow analysts to format the text in the description box as they would like + they lose time in formating that is not taken into account.

In V5, line breaks are taken into account, but there are still issues with the markdown editor:
- if there is only one hit on "enter key" to display the text on the line below, it will be displayed next to the above line.
![Capture d’écran du 2021-10-18 16-53-36](https://user-images.githubusercontent.com/49722941/137758697-3a39cc7b-39e7-4089-add5-b5512f86eda8.png)

![Capture d’écran du 2021-10-18 16-53-49](https://user-images.githubusercontent.com/49722941/137758718-f1be1f36-90ff-441a-8dec-42db8b3a59fc.png)

- if several line breaks are implemented, only one is displayed
![Capture d’écran du 2021-10-18 16-54-35](https://user-images.githubusercontent.com/49722941/137758638-07c4853a-9327-4c0a-9597-bad2a1191036.png)

![Capture d’écran du 2021-10-18 16-54-45](https://user-images.githubusercontent.com/49722941/137758651-94e739d3-5c4e-4dc5-b741-d6f4213e11aa.png)

## Environment

1. demo instance today
2. OpenCTI version: v5.0.1
3. OpenCTI client: frontend

**Comment by SamuelHassine** [comment]
Hello @manonviallet,

This is not a bug, please re-read the markdown specifications for line breaks: https://gist.github.com/shaunlebron/746476e6e7a4d698b373.

You can put whether: 
- 2 spaces at the end of a line to force a line break
- A backslash at the end of the line
- 2 line breaks will be displayed

Also note:
- `<br>` is not supported

Kind regards,
Samuel
