### ISSUE TITLE
Delay to take into account changes resulting in dropping them

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#1639]
## Description

When modifying a description in a relation, the modification is often not taken into account. The reasons why seems quite aleatory. This was the case in V4 and is still the case in V5. It happens regularly and can be frustrating and long (if you have to double check by closing and opening again all the relations you are modifying) + it definitely result in information loss if the analyst does not see the problem. This seems to be the case more especially when making modification from the graph view (by clicking on the links in the graph view to modify them), but was also seen when modifying description fields of entities from the entity view (at least in V4, so far, could not be reproduced in V5).

Several reasons are suggested below but could not be verified empirically. 
- in some cases (but not all) it seems that waiting some time (5 to 10 seconds) after the last keystroke and before closing the window would make the difference between a change taken into account or not taken into account.
- it seems that too many connections to the platform at the same time impair the ability of the platform to properly registered changes: tests were conducted on the demo around 5:25PM to 5:35PM on the 18/10 and all changes (including dates modifications, which usually does not failed) failed, with an error message indicating that to many competing accounts were making modification. This message did not appeared every time modifications failed. during this timeframe ;
- usually, the workaround that works efficiently against this issue is to make a modification and click (just click) on the date field before closing the window.
- this bug was seen whether the closing of the window was made using the cross at the top left or just randomly clicking somewhere else on the page.

## Environment

1. Tested on the V5 today
2. OpenCTI version : latest V4 and v5.0.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open an already existing relation between two entities in a graph view (knowledge from a report)
2. Make a modification in the description field (adding or deleting text) and close the window.
3. Open back the modification window of the relation to see if the modification was properly taken into account.

## Suggested evolution 

In addition to fixing this bug, it would be interesting to have a button at the bottom of the window to validate modification and close the window (analysts have to click anyways to close it, and it would be more user-friendly, the absence of such a feature usually disorientate users).

**Comment by SamuelHassine** [comment]
This should be fixed now. Please don't test on the demo and test on local instance.
