### ISSUE TITLE
Search Query Latency Issue (Identities, ...)

### ISSUE THREAD

**Issue by jieyu-lin** [OpenCTI-Platform/opencti#1661]
## Use case
We have encountered a search query when create an object on opencti platform.
It takes long latency and sometimes has no result of searching an author name.
This query name is: IdentityCreationIdentitiesSearchQuery

## Current Workaround
Currently, we refresh page and retry this query again. Sometimes it works, but sill face latency issue.

## Proposed Solution
Improve speed of searching identity entities or cache some name when first chosen.

## Additional Information
<img width="380" alt="截圖 2021-10-22 14 14 54" src="https://user-images.githubusercontent.com/51392682/138403409-8d6be845-e290-4d22-a7a4-fd165ef66041.png">

## If the feature request is approved, would you be willing to submit a PR?
No

**Comment by richard-julien** [comment]
HI @jieyu-lin , can you open your browser dev console and capture the call in order to have an idea of the latency you taking about? Can you also tell use how many author do you have in your platform? Thanks.

**Comment by jieyu-lin** [comment]
Hi @richard-julien, I take a screen shot of waiting time with the waiting time of my name.
Our platform author is about 16k entities (all individual and organization sum).

<img width="1160" alt="截圖 2021-10-25 14 41 21" src="https://user-images.githubusercontent.com/51392682/138646734-1e499658-4fc5-45d9-9ac4-ed158522534d.png">

**Comment by richard-julien** [comment]
Ok thanks. I will dig in to improve that search speed.

**Comment by richard-julien** [comment]
We change the way we do search to use more efficiently the elasticsearch indices.
Some results could be different than before but the speed of search its 20x faster

**Comment by jieyu-lin** [comment]
Wonderful!!! thank you!!
