### ISSUE TITLE
Add Basic and bearer authentication session validation

### ISSUE THREAD

**Issue by fdevillard** [OpenCTI-Platform/opencti#1676]
## Description

The authentication headers (like the user's API token) are stored in the sessions/cookies, which then take precedence over the bearer token. 

This causes two security issues / inconsistencies:
1. A user is still authenticated even if the bearer token is not supplied anymore,
2. Let say we have two bearer tokens (`t1`, `t2`) associated with two different users (`u1`, `u2`), querying the API with `t1` then with `t2` will result with the second call being associated to `u1` rather than `u2` (except if the cookies are clean in the meantime).

## Environment

1. OS (where OpenCTI server runs): MacOS and on the demo
2. OpenCTI version: master + demo
3. OpenCTI client: Postman
4. Other environment details: Nop.

## Reproducible Steps

1. Find a user's API token
2. Query the endpoint that requires authentication without the secret  (for example with the query below)
3. This should return a >= 400 status code (if not, clean your cookies)
4. Run the query with the bearer token
5. This should return a 200 status code
6. Remove the bearer token and re-run the query

Possible GraphQL query to run:
```
POST /graphql
{
  me {
    user_email
    id
  }
}
```

## Expected Output

A >=400 status code should be return as the user shouldn't be authenticated.

## Actual Output

The user is still authenticated, and a 200 status code is return.
 
## Additional information

_The code where it happens_: 

```
export const authenticateUser = async (req, user, provider) => {
  // Build the user session with only required fields
  const sessionUser = await buildCompleteUser(user);
  logAudit.info(userWithOrigin(req, user), LOGIN_ACTION, { provider });
  req.session.user = sessionUser;
  return sessionUser;
};
```

My suggestion is to refactor how the authentication is done as follow:
- Define a passport strategy for the bearer token,
- Use passport directly to authenticate API call (-> get rid of the `authenticateUserFromRequest` function).

It should be up to the passport strategy to decide if a secret should be stored in the cookies/sessions or not.

I might be able to find some time to refactor / fix this issue, possibly end of week / next week.

## Screenshots (optional)
N/A

**Comment by fdevillard** [comment]
@SamuelHassine Thanks for checking :) Do you think to work on it? Or do you expect an MR before the next release? 🙃

**Comment by richard-julien** [comment]
Hi @fdevillard, create a session for the user for all login way (form, sso, basic auth, bearer) is today a choice. Getting the user and the associated rights at each call is a performance killer.

I will take a look to see if i can enforce a check between the session and the bearer to keep the session but to refuse and kill the connection if a session exists but the bearer is not correctly associated to it

**Comment by richard-julien** [comment]
Just added basic and bearer session validation enforcing.
For bearer, we validate that the token is still available and match the session.
For basic auth we validate the user/pass is still valid.
If not, we invalidate the current session and directly try to relog with the provided information.
