### ISSUE TITLE
Error Loading Mitre

### ISSUE THREAD

**Issue by asucrews** [OpenCTI-Platform/opencti#169]
## Description

Error  when running OpenCTI 1.1.0 from docker-compose 

## Environment

1. Ubuntu 18.04
2. OpenCTI 1.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. git clone
2. edit docker-compose.yml
3. docker-compose --compatibility up

## Expected Output

No ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'

## Actual Output

worker-import_4      | INFO:root:Worker has been loaded with type: import
connector-mitre_1    | ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'
worker-import_1      | INFO:root:Worker has been loaded with type: import
worker-import_2      | INFO:root:Worker has been loaded with type: import
connector-mitre_1    | INFO:root:Fetching the MITRE knowledge...
connector-mitre_1    | ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'
worker-export_1      | INFO:root:Worker has been loaded with type: export
worker-import_3      | INFO:root:Worker has been loaded with type: import
worker-export_2      | INFO:root:Worker has been loaded with type: export
worker-import_4      | INFO:root:Worker has been loaded with type: import
worker-import_1      | INFO:root:Worker has been loaded with type: import
connector-mitre_1    | INFO:root:Fetching the MITRE knowledge...
worker-import_2      | INFO:root:Worker has been loaded with type: import
connector-mitre_1    | ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'
connector-mitre_1    | INFO:root:Fetching the MITRE knowledge...
connector-mitre_1    | ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'
worker-export_1      | INFO:root:Worker has been loaded with type: export
worker-import_3      | INFO:root:Worker has been loaded with type: import
worker-export_2      | INFO:root:Worker has been loaded with type: export
worker-import_4      | INFO:root:Worker has been loaded with type: import
worker-import_1      | INFO:root:Worker has been loaded with type: import
worker-import_2      | INFO:root:Worker has been loaded with type: import
connector-mitre_1    | INFO:root:Fetching the MITRE knowledge...
connector-mitre_1    | ERROR:root:'malware--c41a8b7c-3e42-4eee-b87d-ad8a100ee878'
 }

**Comment by SamuelHassine** [comment]
The issue will be fixed in the next release (1.1.1: 2019-08-04).
