### ISSUE TITLE
Manifest files not found IVRE & import connector

### ISSUE THREAD

**Issue by Bella-chris** [OpenCTI-Platform/opencti#1761]
Hello,

I tried to connect IVRE connector but whenever I run it I get the below error:
Pulling connector-ivre (opencti/connector-ivre:5.0.4)...
ERROR: manifest for opencti/connector-ivre:5.0.4 not found: manifest unknown: manifest unknown

Also for import file connector it was working fine in version 5.0.4, but once I made the update to 5.1.1 I got similar error to IVRE:
Pulling connector-import-report (opencti/connector-import-report:5.1.1)...
ERROR: manifest for opencti/connector-import-report:5.1.1 not found: manifest unknown: manifest unknown

**Comment by SamuelHassine** [comment]
Hello @Bella-chris,

The IVRE connector is only available from version 5.1.0: https://hub.docker.com/repository/docker/opencti/connector-ivre.

Kind regards,
Samuel
