### ISSUE TITLE
Platform needs to log in console for easy docker logs access

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#180]
## Description

Platform needs to log in console for easy docker logs access

## Expected 

In production the platform will logs in standard output

**Comment by richard-julien** [comment]
Version 1.1.1 released this 25 days ago --> August 4
Commit of @SamuelHassine and me --> July 22 on documentation already introduce this concept.
So this one is already covered

```
export const DEV_MODE = environment !== 'production';
logger.add(
  new winston.transports.Console({
    format: winston.format.simple(),
    level: DEV_MODE ? 'debug' : 'warning'
  })
);
```

If you are agree @SamuelHassine , you can just close the issue.

**Comment by SamuelHassine** [comment]
@richard-julien yes I know we already implemented this issue but it is not working, when launching in production mode, no log are displayed in the console (even error).
