### ISSUE TITLE
Change the behavior of auto-complete field

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#182]
## Problem to Solve

The current behavior of auto complete field prevent user to use the backspace to delete the content.

## Current Workaround

Just type something.

## Proposed Solution

Refactor the auto complete field for a better behavior and a better design.

## Additional Information

None.

**Comment by graememeyer** [comment]
2.1.4 - Demo Environment, using FireFox 72.0.2 (64-bit) (Win10). Also seems to replicate on Chrome 80.0.3987.87 (Official Build) (64-bit)



Perhaps I'm misunderstanding this issue, but backspace to delete entries in the Marking and Tag fields (when creating objects) does work. Ctrl+A to select all (e.g. for deletion) does not work however.

The Author field when creating a threat actor seems to have some bugs though and I can't seem to delete an entry/selected author once it's selected.
