### ISSUE TITLE
Implement a timeline visualization for multiple entities

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#183]
## Problem to Solve

Analysts need to be able to compare the evolution of multiple entities in a unique timeline.

## Current Workaround

None.

## Proposed Solution

Implement a timeline component in workspaces.

## Additional Information

None.

**Comment by Stoffe** [comment]
+1 on this, also adding.
Beeing able to cooperate on timeline.
Adding date and time and comments(journal) or information on each timeline entries (beeing able to add manually as well as automatic)

plus beeing able to export this timeline to PDF after incident is closed.

On the timeline, beeing able to mark (tag) an event, such as "First entry in system detected"
Also beeing able to add an event that happened early so you both can view the timeline of events happening as well as events beeing posted, for instance.
I see a data breach, timeline starting.
Something happening
But then I realice that there was a breach before the first one, then I want to add that now.

To be able to see both the event as they occur and beeing entered as well as beeing able to see the events as they are happening in the system is 2 important features.

**Comment by SamuelHassine** [comment]
+ timeline in dashboards.

**Comment by manonviallet** [comment]
Exemple of a desired usecase: be able to have a timeline for an intrusion set of different campaigns. The goal would be to be able to visualize the beginning and the end of each campaign, to see when the intrusion set has been less active and when he has been more active (visualize campaigns superposition). The desired view would be therefore to have a display by periods of time (months, years, days). It would be interesting to be able to selectively add so additional information: notes about a specific event, drop of a malware, spearphishing email sent etc.
(link with issues #1385 et #1381)
The vertical view today is really nice and avoid problems of scale which are frequent when it is horizontal.

**Comment by SamuelHassine** [comment]
I'm closing this issue since timelines in dashboard are now available. Further issues will be opened to be able to visualize multiple entities in the same graphs (ie. compare indicators activity of multiple malwares).

**Comment by SamuelHassine** [comment]
To follow this issue: #1554.
