### ISSUE TITLE
Getting this error when I build using docker.

### ISSUE THREAD

**Issue by VikramKharvi** [OpenCTI-Platform/opencti#188]
ERROR:root:An unexpected error occurred: { HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0c4de7240>: Failed to establish a new connection: [Errno -2] Name or service not known')) }

**Comment by ghost** [comment]
Yup.. facing the same issue.

**Comment by richard-julien** [comment]
Hi. Do you use the provided docker compose? What is your docker version?

**Comment by ghost** [comment]
> Hi. Do you use the provided docker compose? What is your docker version?

Yes, I used **docker-compose up** for installation. The platform is up and running now, however some reports are showing wrong year in the **publication date**. e.g. - **August 17, 2042**

**Comment by richard-julien** [comment]
Can you check the publication date of the element in the remote source? Currently the connector only do format validation check.

**Comment by richard-julien** [comment]
Close for inactivity. Don't hesitate to reopen or create a new one if you still have a problem on the publication date
