### ISSUE TITLE
Not valid STIX identifier when processing data exposed over TAXII2 API

### ISSUE THREAD

**Issue by RomainGUIGNARD** [OpenCTI-Platform/opencti#1909]
## Description

When consuming STIX entities exposed over the TAXII2 API, some entity seems not to have a valid STIX identifier.
Some entities with identifier of type {object}--temporary are returned.

Example of exceptions when processing objects: 

`stix2.exceptions.InvalidValueError: Invalid value for Relationship ‘target_ref’: not a valid STIX identifier, must match <object-type>--<UUID>: malware--temporary`

**Comment by richard-julien** [comment]
Looks like resolution is correctly done in the taxii server code. Maybe this problem come from an inconsistent relation in the database. This situation should not happens but the first thing to do is to verify in the database if the relation is well defined and if the source and target are available. If not this relation should be remove.

**Comment by SamuelHassine** [comment]
@RomainGUIGNARD since we have discussion on Slack on this one, I'm closing this issue. We need to investigate why this relationship is still here and target_ref is not existing anymore.
