### ISSUE TITLE
OpenCTI development environment documentation is outdated

### ISSUE THREAD

**Issue by AhmedAkkarii** [OpenCTI-Platform/opencti#196]
## Description

The development environment installation is outdated as some of the files indicated in the documentation they are no longer exist in the main project, from the documentation section
 **GraphQL API** and below begging from  _Start_, There are no such files called `worker_export.py` and `worker_import.py` there is only `worker.py` and no such folder called `opencti-integration` and `connectors_scheduler.py` it does not exist.

**Comment by richard-julien** [comment]
Thanks for the report. We will fix that as soon as possible. If you want dont hesitate to fix it and submit a PR :)

**Comment by AhmedAkkarii** [comment]
The problem is that i'm unable to fix it on my own 🙁

**Comment by AhmedAkkarii** [comment]
I've tried, there are some issue here and there..
