### ISSUE TITLE
Integrate the MarkingDefinition restriction to domains queries (aka data segregation)

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#2]
## Problem to Solve

The goal is to be able to create groups who have access to specific marking definitions and prevent the other to access these marking definitions.

## Current Workaround

None.

## Proposed Solution

Implement a grakn rule to infer permissions and check the permission for each query.

## Additional Information

None.

**Comment by SamuelHassine** [comment]
Duplicate #75.

**Comment by richard-julien** [comment]
What about https://github.com/OpenCTI-Platform/opencti/issues/884 @SamuelHassine ?
We will split and restrict only on TLP?
