### ISSUE TITLE
Grakn error on docker install

### ISSUE THREAD

**Issue by mathurin68** [OpenCTI-Platform/opencti#218]
This is the latest git pull on Ubuntu 18.

Ran command 
sudo docker-compose up      (--compatibility didn't work for me)

I should also mention I am running this on the same box I have MISP installed. 

```
opencti_1            | Waiting Grakn to launch...
worker-import_1      | INFO:root:Message (type=stix2-bundle, delivery_tag=51) processed, thread terminated
worker-import_1      | INFO:root:Processing a new message (type=stix2-bundle, delivery_tag=52), launching a thread...
worker-import_1      | INFO:root:Importing a marking-definition
worker-import_1      | ERROR:root:An unexpected error occurred: { ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) }
worker-import_1      | INFO:root:Message (type=stix2-bundle, delivery_tag=51) processed, thread terminated
worker-import_1      | INFO:root:Processing a new message (type=stix2-bundle, delivery_tag=52), launching a thread...
worker-import_1      | INFO:root:Marking definitions imported in: 0secs
worker-import_1      | INFO:root:Importing a identity
worker-import_1      | ERROR:root:An unexpected error occurred: { ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) }
worker-import_1      | INFO:root:Message (type=stix2-bundle, delivery_tag=52) processed, thread terminated
worker-import_1      | INFO:root:Processing a new message (type=stix2-bundle, delivery_tag=53), launching a thread...
worker-import_1      | INFO:root:Importing a marking-definition
worker-import_1      | ERROR:root:An unexpected error occurred: { ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) }
worker-import_1      | INFO:root:Message (type=stix2-bundle, delivery_tag=52) processed, thread terminated
worker-import_1      | INFO:root:Processing a new message (type=stix2-bundle, delivery_tag=53), launching a thread...
worker-import_1      | INFO:root:Marking definitions imported in: 0secs
worker-import_1      | INFO:root:Importing a identity
worker-import_1      | ERROR:root:An unexpected error occurred: { ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) }

```
Thanks!

**Comment by richard-julien** [comment]
Hi @mathurin68 , I cant say more than the message Waiting Grakn to launch...
Please take a look of the grakn container logs to see whats happen.

**Comment by mathurin68** [comment]
Got it...I can do that!  Is there an install log somewhere?  I don't see one and I didn't see anything in /var/lib/docker or /var/log    .... but I don't know much about docker. 
Thank you for your help!

**Comment by mathurin68** [comment]
OK -
I ran 
` sudo docker-compose logs -f -t >> myDockerCompose.log`

no idea how that worked BUT found this in the logs 

` cat myDockerCompose.log | grep grakn`

grakn_1              | 2019-09-16T20:24:45.041338908Z                                                                                       Version: 1.5.8
grakn_1              | 2019-09-16T20:26:06.725946746Z Starting Storage......FAILED!
grakn_1              | 2019-09-16T20:26:06.726329390Z Unable to start Storage.

I found this entry- 
https://github.com/OpenCTI-Platform/opencti/issues/137
and this box does only have 4GB of storage total, since this is a VM I can get that upgraded tomorrow. 

The other entry 
https://github.com/OpenCTI-Platform/opencti/issues/110
and it says the grakn problem was resolved when they cleared /var/lib/docker, ran a git pull again and tried it, but this doesn't work for me.  

Again, thanks for your help!

**Comment by richard-julien** [comment]
You can access the logs with the command

`docker logs [CONTAINER_ID]`

You can obtain the CONTAINER_ID with the command `docker ps`

Use the docker logs command to get all the logs of the grakn container, it could be useful to know exactly why Grakn cant start.

**Comment by mathurin68** [comment]
@richard-julien thank you so much for your patience!!!

I ran
```
screen -S docker
sudo docker-compose up
```
ctrl-a-d to exit screen

```
sudo docker ps 
sudo docker logs 'container_id' 
```
... this is really cool! 
For whatever reason it's working now... no idea why, but I'll take it.  

Got a problems with the MISP connector but I'll start another ticket with that one.  

Again, very cool and thank you!
