### ISSUE TITLE
Unable to add "localized in" relation

### ISSUE THREAD

**Issue by michaelheider** [OpenCTI-Platform/opencti#219]
## Description

When connecting an intrusion set to a country in the fronted, there are three suggestions for the relationship type: _related to_, _targets_ and _localized in_. However, _localized in_ does not work.

## Environment

1. OS (where OpenCTI server runs): demo instance
2. OpenCTI version: OpenCTI 1.1.2
3. OpenCTI client: frontend
4. Other environment details: tried on demo instance

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new relation between an intrusion set and a country.
2. Set relationship type _localized in_
3. Click away to confirm

## Expected Output

We expect a new relation to be formed, like with any other relationship type.

## Actual Output

The _Create a relationship_ overlap appears hang up, the loading icon continues forever.
When clicking away again, it closes, but no new relationship is formed.
 
## Additional information

When viewing an intrusion set, the knowledge tab has a section _Attribution_. I assume that a _localized in_ relation would lead to an entry in this section. This bug effectively prevents one from defining attributions.

It does also not work in 1.1.1, but there at least an error message is displayed: "An unknown error has occurred! Please try again later."

**Comment by SamuelHassine** [comment]
@Bauboo the relation `localization` cannot be added directly on an `Intrusion-Set`, which is more a technical element for malicious activities (aka. APT). If you want to add a `localization`, you have to attribute the `Intrusion-Set` to a `Threat-Actor` and then localize the `Threat-Actor`.

**Comment by SamuelHassine** [comment]
We will implement the `localization` relation for `Threat-Actor` in the next release.
