### ISSUE TITLE
Inferred relation instrusion set - country - region

### ISSUE THREAD

**Issue by michaelheider** [OpenCTI-Platform/opencti#220]
## Problem to Solve
When an intrusion set attacks a country that is located in a region, then there is an inferred relation that states that the intrusion set also attacks the region.
However, when the intrusion set is set to attack the region, which has a country located in it, then there is no inferred relation that states that the intrusion set also attacks the country.
This causes attacking intrusion sets not to be displayed when viewing an individual country, even though intrusion sets that are targeting a region that includes the country clearly are also targeting the single country.

## Current Workaround

None.

## Proposed Solution

Implement inferred relation also the other way round, as described above.

## Additional Information

None.

**Comment by SamuelHassine** [comment]
Will be fixed in 2.0.0.
