### ISSUE TITLE
Tag - threat category

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#226]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Indicate that OpenCTI entities (threat actors, reports, intrusion sets, etc) belong to a given categories

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Create a threat category tag.
Could be customize by the organisations using CTI.
In our case we use the following:

- cyber espionage
- cyber crime
- cyber war
- cyber terrorism
- hacktivism
- censorship
- sovereignty

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by richard-julien** [comment]
Duplicate https://github.com/OpenCTI-Platform/opencti/issues/229 @SamuelHassine ?

**Comment by SamuelHassine** [comment]
Implementation of tagging is done, PR #252.
