### ISSUE TITLE
worker errors

### ISSUE THREAD

**Issue by cybert79** [OpenCTI-Platform/opencti#234]
## Description

worker errors

## Actual Output

Error pops up
 
## Additional information

awaiter (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:3:12)"]}}}
worker-import_1      | ERROR:root:You are not allowed to do this.
worker-import_1      | ERROR:root:An unexpected error occurred: { 'NoneType' object is not subscriptable }
worker-import_1      | INFO:root:Message (type=stix2-bundle, delivery_tag=909) processed, thread terminated
worker-import_1      | INFO:root:Processing a new message (type=stix2-bundle, delivery_tag=910), launching a thread...
worker-import_1      | INFO:root:Importing a marking-definition
opencti_1            | error: You are not allowed to do this. {"locations":[{"line":3,"column":17}],"path":["stixDomainEntities"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"ForbiddenAccess","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2019-09-23T17:09:32.109Z","data":{"type":"authentication"},"internalData":{},"_stack":"ForbiddenAccess: You are not allowed to do this.\n    at AuthDirective.authenticationControl (/opt/opencti/dist/schema/authDirective.js:45:22)\n    at field.resolve.args (/opt/opencti/dist/schema/authDirective.js:69:97)\n    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)\n    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:503:18)\n    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:470:16)\n    at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:311:18)\n    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:255:122)\n    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:102:14)\n    at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:62:35)\n    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:239:46\n    at Generator.next (<anonymous>)\n    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:3:12)","stacktrace":["ForbiddenAccess: You are not allowed to do this.","    at AuthDirective.authenticationControl (/opt/opencti/dist/schema/authDirective.js:45:22)","    at field.resolve.args (/opt/opencti/dist/schema/authDirective.js:69:97)","    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:503:18)","    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:470:16)","    at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:311:18)","    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:255:122)","    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:102:14)","    at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:62:35)","    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:239:46","    at Generator.next (<anonymous>)","    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:7:71","    at new Promise (<anonymous>)","    at __awaiter (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:3:12)"]}}}
worker-import_1      | ERROR:root:You are not allowed to do this.
worker-import_1      | ERROR:root:An unexpected error occurred: { 'NoneType' object is not subscriptable }

**Comment by richard-julien** [comment]
Duplicate https://github.com/OpenCTI-Platform/opencti/issues/233
