### ISSUE TITLE
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

### ISSUE THREAD

**Issue by symsal** [OpenCTI-Platform/opencti#2347]
## Description
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS docker
2. OpenCTI version:  5.3.7
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a user with group dedicated with the same permission of default
2. login with this user and try to update a report clicking on icon of pen
3. Error

## Expected Output

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information
Firefox Console error: 

TypeError: l is undefined
    getFormatHelperText https://opencti/static/js/opencti-3343EXMJ.js:7926
    IPt https://opencti/static/js/opencti-3343EXMJ.js:8125
    jle https://opencti/static/js/opencti-3343EXMJ.js:8125
    h5n https://opencti/static/js/opencti-3343EXMJ.js:5
    fnt https://opencti/static/js/opencti-3343EXMJ.js:5
    art https://opencti/static/js/opencti-3343EXMJ.js:9
    nrt https://opencti/static/js/opencti-3343EXMJ.js:9
    xKa https://opencti/static/js/opencti-3343EXMJ.js:9
    d4e https://opencti/static/js/opencti-3343EXMJ.js:9
    N7n https://opencti/static/js/opencti-3343EXMJ.js:7
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    unstable_runWithPriority https://opencti/static/js/opencti-3343EXMJ.js:1
    EQ https://opencti/static/js/opencti-3343EXMJ.js:5
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    QP https://opencti/static/js/opencti-3343EXMJ.js:5
    qnt https://opencti/static/js/opencti-3343EXMJ.js:9
    gRa https://opencti/static/js/opencti-3343EXMJ.js:5
    htt https://opencti/static/js/opencti-3343EXMJ.js:5
    Qet https://opencti/static/js/opencti-3343EXMJ.js:5
    ytt https://opencti/static/js/opencti-3343EXMJ.js:5
    ytt https://opencti/static/js/opencti-3343EXMJ.js:5
    cKa https://opencti/static/js/opencti-3343EXMJ.js:5
    trt https://opencti/static/js/opencti-3343EXMJ.js:9
    nrt https://opencti/static/js/opencti-3343EXMJ.js:9
    xKa https://opencti/static/js/opencti-3343EXMJ.js:9
    d4e https://opencti/static/js/opencti-3343EXMJ.js:9
    N7n https://opencti/static/js/opencti-3343EXMJ.js:7
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    unstable_runWithPriority https://opencti/static/js/opencti-3343EXMJ.js:1
    EQ https://opencti/static/js/opencti-3343EXMJ.js:5
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    QP https://opencti/static/js/opencti-3343EXMJ.js:5
    yz https://opencti/static/js/opencti-3343EXMJ.js:7
    enqueueSetState https://opencti/static/js/opencti-3343EXMJ.js:5
    setState https://opencti/static/js/opencti-3343EXMJ.js:1
    e https://opencti/static/js/opencti-3343EXMJ.js:41
    _onQueryDataAvailable https://opencti/static/js/opencti-3343EXMJ.js:41
    _onQueryDataAvailable https://opencti/static/js/opencti-3343EXMJ.js:41
    next https://opencti/static/js/opencti-3343EXMJ.js:41
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    l https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    _handleNext https://opencti/static/js/opencti-3343EXMJ.js:12
    l https://opencti/static/js/opencti-3343EXMJ.js:11
    cVa https://opencti/static/js/opencti-3343EXMJ.js:11
    _next https://opencti/static/js/opencti-3343EXMJ.js:11
    _schedule https://opencti/static/js/opencti-3343EXMJ.js:11
    _next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    l https://opencti/static/js/opencti-3343EXMJ.js:11
    next https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:54
    promise callback*subscribe https://opencti/static/js/opencti-3343EXMJ.js:54
    wBa https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    do https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    n https://opencti/static/js/opencti-3343EXMJ.js:11
    jza https://opencti/static/js/opencti-3343EXMJ.js:11
    _execute https://opencti/static/js/opencti-3343EXMJ.js:12
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    finally https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    Vat https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    do https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    finally https://opencti/static/js/opencti-3343EXMJ.js:11
    OBa https://opencti/static/js/opencti-3343EXMJ.js:11
    subscribe https://opencti/static/js/opencti-3343EXMJ.js:11
    fetch https://opencti/static/js/opencti-3343EXMJ.js:41
    Kct https://opencti/static/js/opencti-3343EXMJ.js:41
    e https://opencti/static/js/opencti-3343EXMJ.js:41
    Ptt https://opencti/static/js/opencti-3343EXMJ.js:5
    ynt https://opencti/static/js/opencti-3343EXMJ.js:5
    art https://opencti/static/js/opencti-3343EXMJ.js:9
    nrt https://opencti/static/js/opencti-3343EXMJ.js:9
    xKa https://opencti/static/js/opencti-3343EXMJ.js:9
    d4e https://opencti/static/js/opencti-3343EXMJ.js:9
    N7n https://opencti/static/js/opencti-3343EXMJ.js:7
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    unstable_runWithPriority https://opencti/static/js/opencti-3343EXMJ.js:1
    EQ https://opencti/static/js/opencti-3343EXMJ.js:5
    wtt https://opencti/static/js/opencti-3343EXMJ.js:5
    O6n https://opencti/static/js/opencti-3343EXMJ.js:1
    onmessage https://opencti/static/js/opencti-3343EXMJ.js:1
    het https://opencti/static/js/opencti-3343EXMJ.js:1
    Me https://opencti/static/js/opencti-3343EXMJ.js:1
    vet https://opencti/static/js/opencti-3343EXMJ.js:1
    Me https://opencti/static/js/opencti-3343EXMJ.js:1
    ort https://opencti/static/js/opencti-3343EXMJ.js:1
    Me https://opencti/static/js/opencti-3343EXMJ.js:1
    n_ https://opencti/static/js/opencti-3343EXMJ.js:9
    Me https://opencti/static/js/opencti-3343EXMJ.js:1
    <anonymous> https://opencti/static/js/opencti-3343EXMJ.js:7845
    <anonymous> https://opencti/static/js/opencti-3343EXMJ.js:143570
opencti-3343EXMJ.js:7:74

**Comment by SamuelHassine** [comment]
Hello @symsal,

I confirm you that this issue was fixed in version 5.3.8.

Kind regards,
Samuel

**Comment by symsal** [comment]
Confirmed. thanks
