### ISSUE TITLE
Add version/build number and minimal system info in dashboard

### ISSUE THREAD

**Issue by 8hur** [OpenCTI-Platform/opencti#236]
## Problem to Solve

When investigating issues or reporting bugs, finding out which version/build is deployed might be needed to avoid duplicates. Also, environment specific issues might be easer to diagnose if the main environment parameters are exposed.

## Current Workaround

Less detailed bug reports

## Proposed Solution

Add a "about" tab with the build number and other useful debugging infos to the settings menu.

**Comment by maertv** [comment]
It seems that Grakn server does not expose its version.
