### ISSUE TITLE
Improve search engine capacity

### ISSUE THREAD

**Issue by 8hur** [OpenCTI-Platform/opencti#237]
## Description

The search engine behaviour is quite unintuitive and can lead analysts to miss informations when capitalising reports.

## Environment

Demo website, ANSSI on-premise.

## Reproducible Steps

In the knowledge tab of any report, search for:

- `DLL`
- `DLL Side-Loading`
- `DLL Side Loading`
- `Side Loading`

And then search for:

- `"DLL Side-Loading"`
- `side-loading`
- `loading`

## Expected Output

All searches show the TTP T1073 called "DLL Side-Loading"

## Actual Output

Only the searches in the second part actually show the TTP

**Comment by richard-julien** [comment]
The current analyzer is clearly not perfect for openCTI needs. We have some jobs to do here :)

**Comment by SamuelHassine** [comment]
I am solving this issue in the described use cases, but still need a specific analyzer. I will create a dedicated issue on this.
