### ISSUE TITLE
Firewall ports and maintaining data in docker...

### ISSUE THREAD

**Issue by mathurin68** [OpenCTI-Platform/opencti#238]
This has been running for a few days and looks soooo good!!!

2 questions, nothing urgent - 

1)  It took several days to get the Mitre info loaded into the dashboard, which is fine BUT it seems to disappear everytime I have to restart docker-compose, or at least it did when I was setting this up.  Is there a way to restart docker-compose without losing the data and having to re-download it everytime? 

2)  In order to get this to work I had to turn off the Ubuntu firewall, but I need to turn it back on...is there a list of ports to leave open for this (I'm still figuring out docker)

```
money@MISP:~$ sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6666          0.0.0.0:*               LISTEN      1514/python3
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1964/mysqld
tcp        0      0 127.0.0.1:6250          0.0.0.0:*               LISTEN      2036/redis-server 1
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1736/redis-server 1
tcp        0      0 127.0.0.1:45581         0.0.0.0:*               LISTEN      1637/containerd
tcp        0      0 0.0.0.0:50000           0.0.0.0:*               LISTEN      31364/python
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      753/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1806/sshd
tcp        0      0 0.0.0.0:8001            0.0.0.0:*               LISTEN      17136/apache2
tcp6       0      0 ::1:6250                :::*                    LISTEN      2036/redis-server 1
tcp6       0      0 :::48555                :::*                    LISTEN      8085/docker-proxy
tcp6       0      0 ::1:6379                :::*                    LISTEN      1736/redis-server 1
tcp6       0      0 :::80                   :::*                    LISTEN      17136/apache2
tcp6       0      0 :::8080                 :::*                    LISTEN      8951/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1806/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      17136/apache2

```
Thanks!

**Comment by richard-julien** [comment]
Hi @mathurin68,
Question 1:
You need to configure the docker volume of at least grakn and elasticsearch. (See section *data persistence* in https://opencti-platform.github.io/docs/installation/docker and https://docs.docker.com/compose/compose-file/)

Question 2:
For me the only port you need to open in your firewall for external connection is the http port of the openCTI UI (8080). Every other ports can only be open for local communications (localhost).

**Comment by richard-julien** [comment]
Close for inactivity. Please reopen if needed
