### ISSUE TITLE
Multiple authors for reports

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#239]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

1. Reports or observables might be collected from an original source via an intermediate (e.g. source A via Alienvault, or source B via MISP). In such case, both the orginal source and the intermediate should be identified as authors

2. Reports might be co-authored by more than on organisation

## Current Workaround

None

## Proposed Solution

Allow for more than one author per report.

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by Fred-certeu** [comment]
Samuel, this issue is still not critical but it is becoming important as the number of connectors increases. For example, with the alienvault connector, you can get reports from several sources creating pulses on alienvault otx. However, they all come with the author = Alienvault.
So, it would be nice to have author(s) = Alienvault + [name of the organisation which created the pulse].

**Comment by SamuelHassine** [comment]
Ok @Fred-certeu, scheduled for the next milestone.

**Comment by csandu-certeu** [comment]
Unfortunately, it is not possible to add more than 1 author for a report. We could open a new issue with all details.
