### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by symsal** [OpenCTI-Platform/opencti#2390]
## Description

Upload of documents pdf fails

## Environment

1. OS (where OpenCTI server runs): { docker }
2. OpenCTI version: { 5.3.13 }
3. OpenCTI client: { frontend }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. {Click to data
3. Upload document

## Expected Output

Upload success

## Actual Output

No visual error but in Console Browser:  "413 Request Entity Too Large" on post requests

**Comment by symsal** [comment]
Console browser error: wss://openctihostname/graphql  --- 400 Bad request

**Comment by richard-julien** [comment]
Hi. Can you specify the size of the report you try to upload?
Thanks

**Comment by symsal** [comment]
> Hi. Can you specify the size of the report you try to upload? Thanks

2.8 mb

**Comment by SamuelHassine** [comment]
Hello @symsal,

The platform supports very large upload payload. Do you have a reverse proxy in front of your platform?

**Comment by symsal** [comment]
> Hello @symsal,
> 
> The platform supports very large upload payload. Do you have a reverse proxy in front of your platform?

Yes, I have already modify client_size var on nginx and it doesn't worked. 

This could be the point:
https://github.com/apollographql/apollo-server/issues/288

**Comment by symsal** [comment]
Any update?

**Comment by symsal** [comment]
update?

**Comment by symsal** [comment]
@SamuelHassine update?
