### ISSUE TITLE
Used credentials in docker-compose.yml doesn't work

### ISSUE THREAD

**Issue by SEQNUL** [OpenCTI-Platform/opencti#240]
Ok, I installed OpenCTI on my Macbook (macOS Mojave 10.14.6) using Docker. The installation worked fine and I am able to start up the OpenCTI platform. But it is not possible to login...

I entered the credentials in docker-compose.yml (e-mailaddress and password) in plane text. But when I try to login on the OpenCTI dashboard it says even the username (e-mail adres) or password is incorrect.... I can't find te issue...

`Version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.8
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    restart: always
  opencti:
    image: opencti/platform:1.1.2
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=my@emailaddress.nl
      - APP__ADMIN__PASSWORD=mypassword
      - APP__ADMIN__TOKEN=89425d60-18d0-452a-852a-3b7499cad64f
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    restart: always
  worker-import:
    image: opencti/worker:1.1.2
    environment:
      - WORKER_TYPE=import
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=89425d60-18d0-452a-852a-3b7499cad64f
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 4
    restart: always
  worker-export:
    image: opencti/worker:1.1.2
    environment:
      - WORKER_TYPE=export
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://localhost:8080
      - OPENCTI_TOKEN=89425d60-18d0-452a-852a-3b7499cad64f
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 2      
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:1.1.2
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OPENCTI_NAME=OpenCTI
      - OPENCTI_CONFIDENCE_LEVEL=5
      - OPENCTI_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - OPENCTI_ENTITIES=identity,sector,region,country,city
      - OPENCTI_INTERVAL=1 # Days
      - OPENCTI_LOG_LEVEL=info
    depends_on:
      - opencti
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:1.1.2
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MITRE_NAME=MITRE\ ATT&CK
      - MITRE_CONFIDENCE_LEVEL=3
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_ENTITIES=identity,attack-pattern,course-of-action,intrusion-set,malware,tool
      - MITRE_INTERVAL=7 # Days
      - MITRE_LOG_LEVEL=info    
    depends_on:
      - opencti
    restart: always            
volumes:
  grakndata:
  esdata:`

This is what I can find in terminal:

`opencti_1            | error: [ELASTICSEARCH] getAttributes > error getting V446632connect ECONNREFUSED 172.18.0.9:9200 {"name":"ConnectionError","meta":{"body":null,"statusCode":null,"headers":null,"warnings":null,"meta":{"context":null,"request":{"params":{"method":"GET","path":"/stix_domain_entities/_doc/V446632","body":null,"querystring":"","headers":{"User-Agent":"elasticsearch-js/7.2.0 (linux 4.9.184-linuxkit-x64; Node.js v11.15.0)"},"timeout":30000},"options":{"warnings":null},"id":10},"name":"elasticsearch-js","connection":{"url":"http://elasticsearch:9200/","id":"http://elasticsearch:9200/","headers":null,"deadCount":0,"resurrectTimeout":0,"_openRequests":0,"status":"alive","roles":{"master":true,"data":true,"ingest":true,"ml":false}},"attempts":3,"aborted":false}},"stack":"ConnectionError: connect ECONNREFUSED 172.18.0.9:9200\n    at onResponse (/opt/opencti/node_modules/@elastic/elasticsearch/lib/Transport.js:220:13)\n    at ClientRequest.request.on.err (/opt/opencti/node_modules/@elastic/elasticsearch/lib/Connection.js:114:9)\n    at ClientRequest.emit (events.js:193:13)\n    at Socket.socketErrorListener (_http_client.js:397:9)\n    at Socket.emit (events.js:193:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at processTicksAndRejections (internal/`

**Comment by SamuelHassine** [comment]
@Seqreel: can you tell us if you have the same problem with the new 2.0.0?

**Comment by richard-julien** [comment]
Close for inactivity. Please reopen if you still have the problem.
