### ISSUE TITLE
Migration to react-intl 3

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#248]
## Problem to Solve

Migration of the frontend to react-intl 3.

## Current Workaround

None.

## Proposed Solution

See https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md

## Additional Information

None.

**Comment by mmudunuri** [comment]
https://formatjs.io/docs/react-intl/upgrade-guide-3x
