### ISSUE TITLE
Add a tags field on creation forms

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#266]
## Problem to Solve

Tags can only be added/removed in the "view" of an entity (threat actor, intrusion sets, etc.).

## Current Workaround

None.

## Proposed Solution

Add a tags field in the creation forms of entities like the MarkingDefinition.

## Additional Information

None.

**Comment by maertv** [comment]
It seems that following views are missing tag related functionality:
- Tools - details (overview) and update form missing tags.
- Vulnerabilities - details (overview) and update form missing tags.
- Observables - listing, details (overview) and update form missing tags.
- Reports - listing, details (overview) and update form missing tags.

Maybe it is clearer to create separate issues for each case if the view needs to handle tags.

**Comment by Fred-certeu** [comment]
Hi, I confirm that tagging is crucial for reports
Thanks

**Comment by SamuelHassine** [comment]
@Fred-certeu I confirm that tagging will be added for Tools/Vulnerabilities/Observables/Reports (#345)
