### ISSUE TITLE
ERROR:root:<urlopen error [Errno 113] No route to host>

### ISSUE THREAD

**Issue by Tukali** [OpenCTI-Platform/opencti#273]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

when i start it ,and that is happened:

connector-opencti_1  | INFO:root:Fetching OpenCTI datasets...
connector-mitre_1    | INFO:root:Fetching the MITRE knowledge...
connector-opencti_1  | ERROR:root:<urlopen error [Errno 113] No route to host>
connector-mitre_1    | ERROR:root:<urlopen error [Errno 113] No route to host>

and what should i do 

## Environment

i install it with docker 

1. OS (where OpenCTI server runs): Ubuntu server 18.04 
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by richard-julien** [comment]
Hi @Tukali. Don't really know what kind of problem you have. Are you sure docker have access to fetch data outside the containers? Can look into the logs of the container?
