### ISSUE TITLE
Elasticsearch version  dependency for the latest version of openCTI

### ISSUE THREAD

**Issue by alexhui01** [OpenCTI-Platform/opencti#2741]
## Description

I'm trying to launch OpenCti into k8s and make some adjustments for our own helm charts. However, we are not a big fun of managing the Elasticsearch cluster.  I didn't find anything related to the elasticsearch version support.   Amazon Opensearch only supports the old version of ES cluster (1.5 to 7.10 versions).  Would that be a problem for future upgrade? 

What would be the recommended way for the ES cluster provisioning? We are expecting to see the data increases to more than 20TB in a big possibility. 

## Additional information
https://filigran.notion.site/Configuration-a568604c46d84f39a8beae141505572a#49d10f7b8c0f470ebeba901fa97aa2bb

**Comment by SamuelHassine** [comment]
Hello,

As the example in our Docker repository (https://github.com/OpenCTI-Platform/docker.git), we recommend to run OpenCTI with the latest version of ElasticSearch or OpenSearch.

Kind regards,
Samuel

**Comment by alexhui01** [comment]
Thanks for the quick reply. So the answer is we can use the latest version of opensearch for OpenCti, am I right?

**Comment by SamuelHassine** [comment]
Yes, but ElasticSearch is recommended instead of OpenSearch, but both are supported.

**Comment by alexhui01** [comment]
That resolves my concerns. Thanks a lot!

**Comment by alexhui01** [comment]
I'm facing issues after running with latest Amazon Opensearch service - v2.3.  
Opencti version -> 5.5.2 

Any ideas? 
The error as below:
>ategory":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"StatusTemplate"}},{"match_phrase":{"parent_types.keyword":"StatusTemplate"}}]}}],"must_not":[]}},"size":5000,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-01-16T10:34:03.394Z","version":"5.5.2"}
{"category":"APP","error":{"context":{},"message":"{\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}","name":"ResponseError","stack":"ResponseError: {\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}\n    at wxe.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:535:17)\n

**Comment by TheMatrix97** [comment]
I'm facing this issue with opensearch 1.2.4, which in theory is equivalent to ElasticSearch 7.10. Is there any mechanism to skip the ES verification?
Thanks!

**Comment by securitiz** [comment]
@alexhui01 were you able to find a solution for your error?
