### ISSUE TITLE
Cannot export some reports

### ISSUE THREAD

**Issue by khalid1515** [OpenCTI-Platform/opencti#276]
i am having an issue with the latest release, 

currently some reports cannot be exported as when i try to export them i get 
(generating report in progress..) 

it is stuck on this state, even when i tried to restart the whole vm and relaunch docker again the (in progress message) still appears. 

you support is highly appreciated.

**Comment by SamuelHassine** [comment]
Hello @khalid1515,

The issue is now fixed in 2.0.0.
