### ISSUE TITLE
no inference relationship 

### ISSUE THREAD

**Issue by khalid1515** [OpenCTI-Platform/opencti#277]
the inference relationship is not working, meaning if i create a report and create the following relation:

intrusion-set target organization, 
campaign  attributes to intusion-set

if i go to the campaign page, i do not see the organization as targeted. i need to specify a third relation

campaign targets organization

is this normal or am i missing something. 

regards.

**Comment by SamuelHassine** [comment]
Hello @khalid1515,

This issue is now fixed in 2.0.0.
