### ISSUE TITLE
Be able to consume a given live stream from thousands of OpenCTI platforms

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#2863]
## Use case

Be able to consume a given live stream with dependencies from thousands of OpenCTI platforms without performance issue.

**Comment by TechBurn0ut** [comment]
would love to see the tests on this one

**Comment by richard-julien** [comment]
Closing for now as stix loading was improved to reduce load for stream and taxii.
Will be reopen later if needed
