### ISSUE TITLE
Implement a specific ElasticSearch analyzer for the OpenCTI data schema

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#289]
## Problem to Solve

Currently, ElasticSearch is indexing only for fulltext search and basic filtering.

## Current Workaround

None.

## Proposed Solution

Implement a specific ElasticSearch analyzer for the OpenCTI data schema.

## Additional Information

None.

**Comment by richard-julien** [comment]
Not sure it will bring a real value for now. Closing the issue
