### ISSUE TITLE
Add simple state management for connectors.

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#291]
## Problem to Solve

Implement a method in the API to store a state for a connector

## Current Workaround

None.

## Proposed Solution

Add a state in the new connector API implementation.
On the client python, get the state at connector registration and then push it to the API every time the connector do a ping/pong with the API. The state will be automatically updated every 30 seconds.

**Comment by richard-julien** [comment]
We should propose a simple API around connector state instead
