### ISSUE TITLE
Any problems with the AWS bucket?

### ISSUE THREAD

**Issue by cybert79** [OpenCTI-Platform/opencti#297]
Hey guys, got it on docker on debian sid; but I see the following error:

error: [API] Bootstrap error > The access key ID you provided does not exist in our records. {"code":"InvalidAccessKeyId","bucketname":"opencti-bucket","resource":"/opencti-bucket","requestid":"15D19C21D2D0FB1F","hostid":"7542d240-ac41-4ceb-b2c2-da1134d9ef65","amzRequestid":null,"amzId2":null,"amzBucketRegion":null,"stack":"S3Error: The access key ID you provided does not exist in our records.\n    at Object.parseError (/opt/opencti/node_modules/minio/dist/main/xml-parsers.js:83:11)\n    at /opt/opencti/node_modules/minio/dist/main/transformers.js:153:22\n    at DestroyableTransform._flush (/opt/opencti/node_modules/minio/dist/main/transformers.js:77:10)\n    at DestroyableTransform.prefinish (/opt/opencti/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:129:10)\n    at DestroyableTransform.emit (events.js:209:13)\n    at prefinish (/opt/opencti/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:607:14)\n    at finishMaybe (/opt/opencti/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:616:5)\n    at endWritable (/opt/opencti/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:629:3)\n    at DestroyableTransform.Writable.end (/opt/opencti/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:567:22)\n    at IncomingMessage.onend (_stream_readable.js:687:10)\n    at Object.onceWrapper (events.js:297:20)\n    at IncomingMessage.emit (events.js:214:15)\n    at endReadableNT (_stream_readable.js:1178:12)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)"}
opencti_1                     | info: 🚀 OpenCTI started in production mode with embedded file

**Comment by SamuelHassine** [comment]
Hello @cybert7, the error message is `The access key ID you provided does not exist in our records.`. Are you sure that the parameters :

```
MINIO_ACCESS_KEY: ChangeMeAccess
MINIO_SECRET_KEY: ChangeMeKey
```

and 

```
- MINIO__ACCESS_KEY=ChangeMeAccess
- MINIO__SECRET_KEY=ChangeMeKey
```

are the same?

**Comment by cybert79** [comment]
I feel stupid,...

**Comment by criptk** [comment]
I got the same error. Not running on docker though, it says we only need to edit production.json ... 

djpsantos@opencti:/usr/local/share/OpenCTI/opencti$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
djpsantos@opencti:/usr/local/share/OpenCTI/opencti$ ls
opencti-release-3.3.2.tar.gz opencti
djpsantos@opencti:/usr/local/share/OpenCTI/opencti$ 
djpsantos@opencti:/usr/local/share/OpenCTI/opencti$ sudo yarn serv
yarn run v1.22.5
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-09-17T23:19:19.029Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-09-17T23:19:19.055Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-09-17T23:19:19.069Z"}
{"error":{"code":"InvalidAccessKeyId","bucketname":"opencti-bucket","resource":"/opencti-bucket","requestid":"1635B5758C827B12","hostid":"697b6570-5f85-4007-b7d1-5d1f5b220cc6","amzRequestid":null,"amzId2":null,"amzBucketRegion":null},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-09-17T23:19:19.081Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
djpsantos@opencti:/usr/local/share/OpenCTI/opencti$
