### ISSUE TITLE
[back] Bump antlr4 to 4.12.X

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#2973]
## Use case

Bump antlr4 to 4.12.X.

**Comment by SamuelHassine** [comment]
Right now, bumping this lib prevents the backend to start.

**Comment by richard-julien** [comment]
Waiting information of https://github.com/antlr/antlr4/issues/4211

**Comment by SamuelHassine** [comment]
Renovate is now enabled.
