### ISSUE TITLE
Add global trimming string when preparing data for ingestion

### ISSUE THREAD

**Issue by Chasbrot** [OpenCTI-Platform/opencti#3022]
## Use case

When creating an observable or entity and entering strings into a value field automatically trim any whitspaces from the value before checking the value.

## Current Workaround

Preciscion copy-pasting and laserfocused whitespace searching.

## Proposed Solution

Add a auto-trim to the string 

## If the feature request is approved, would you be willing to submit a PR?
No

**Comment by SamuelHassine** [comment]
It is a good practice to trim everything in all attributes both at creation and modification.

In this feature, we also need to trim the open vocabularies values in addition to the attributes.
