### ISSUE TITLE
Add Minio version in the "About tab"

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#315]
## Problem to Solve

Minio version is not displayed in the "About" tab of dependencies.

## Current Workaround

None.

## Proposed Solution

Add the Minio version.

## Additional Information

None.

**Comment by maertv** [comment]
The _minio-js_ client does not have a method for getting the server version. Instead, the server version is included in the Server header of the response (https://github.com/minio/minio-js/issues/810) of every HTTP request.

**Comment by ckyoog** [comment]
This issue needs re-open, because the MinIO version is gone after version 5.

And I am confused.

@SamuelHassine You asked for this feature. But it is also you who removed it in commit https://github.com/OpenCTI-Platform/opencti/commit/45792a566ca8a0d0d1f148dc2567a3cc1507f010
