### ISSUE TITLE
Technical error thrown when not logged in

### ISSUE THREAD

**Issue by intelwolf** [OpenCTI-Platform/opencti#319]
## Description

If you are not logged in in the OpenCTI platform the opencti docker image is constantly throwing error messages which sometimes crash the service

## Environment

1. Debian 9
2. OpenCTI version: 2.0.2
3. OpenCTI client: frontend
4. Chrome browser, MacOS
5. using docker-compose

## Reproducible Steps
1. Login the OpenCTI interface and open the page 'Connectors and Workers'. 
2. Open a 2nd window to the interface and log out from OpenCTI in that window.
3. Check the logs from the OpenCTI platform docker image using docker logs <container> and notice the following errors throw every few seconds:

## Expected Output
no output

## Actual Output
error: [OPENCTI] Technical error > You are not allowed to do this. {"locations":[{"line":2,"column":3}],"path":["logout"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"ForbiddenAccess","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2019-11-06T15:14:02.012Z","data":{"type":"authentication"},"internalData":{},"_stack":"ForbiddenAccess: You are not allowed to do this.\n    at AuthDirective.authenticationControl (/opt/opencti/dist/schema/authDirective.js:45:22)\n    at field.resolve (/opt/opencti/dist/schema/authDirective.js:69:97)\n    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)\n    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)\n    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)\n    at /opt/opencti/node_modules/graphql/execution/execute.js:244:18\n    at /opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10\n    at Array.reduce (<anonymous>)\n    at promiseReduce (/opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)\n    at executeFieldsSerially (/opt/opencti/node_modules/graphql/execution/execute.js:241:37)\n    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:55)\n    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)\n    at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)\n    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:240:46","stacktrace":["ForbiddenAccess: You are not allowed to do this.","    at AuthDirective.authenticationControl (/opt/opencti/dist/schema/authDirective.js:45:22)","    at field.resolve (/opt/opencti/dist/schema/authDirective.js:69:97)","    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","    at /opt/opencti/node_modules/graphql/execution/execute.js:244:18","    at /opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10","    at Array.reduce (<anonymous>)","    at promiseReduce (/opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)","    at executeFieldsSerially (/opt/opencti/node_modules/graphql/execution/execute.js:241:37)","    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:55)","    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)","    at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)","    at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:240:46"]}}}

**Comment by SamuelHassine** [comment]
Token error / Login error should be at the `warning` log level.
