### ISSUE TITLE
Ability for connector developers to offer a configuration GUI

### ISSUE THREAD

**Issue by JasonKeirstead** [OpenCTI-Platform/opencti#327]
## Problem to Solve

Currently the only place to configure a connector is in the YAML file and/or environment variables inside the connector itself that is modified on the file system or gets pushed to docker. End-users can not configure the connector inn the OpenCTI GUI. This makes connectors much less plug-and-play than they could be.

## Current Workaround

As a work-around, in my connector i am using Flask to run my own secondary GUI on a different webserver port. 

## Proposed Solution

Ideally on the connectors page, you could select a connector and click "Configure", which would open a dialog box. The dialog box would be dynamically drawn based on a configuration that described the parameters/variables, their names, and types. Something like JSON forms ( https://jsonforms.io/examples ) is a great way to do this.

**Comment by SamuelHassine** [comment]
@JasonKeirstead For the moment we do not intend to implement GUI configuration of connectors.
