### ISSUE TITLE
Organization to threat actor relations

### ISSUE THREAD

**Issue by 8hur** [OpenCTI-Platform/opencti#329]
## Problem to Solve

Intelligences agencies or offensive securities companies should be able to be linked to a threat actor (eg: NSA is part of the "five-eyes" threat actor)

## Current Workaround

Use the "linked to" relation

## Proposed Solution

Add a "attributed to" or "is part of" relation

**Comment by Fred-certeu** [comment]
I also see the same issue.
The linked to relation will help.
However, I don't see how to avoid duplication. Indeed, some organizations "are" at the same time
- threat actors. 
and
- normal organizations (that could be targeted or be the author of reports)

So I don't see how we could avoid duplicating...
Or let an organization be also a threat actor ... possible ?
