### ISSUE TITLE
Exchange graphql query against a bugfix PR (misp connector)?

### ISSUE THREAD

**Issue by andurin** [OpenCTI-Platform/opencti#337]
Hi,

## Description

While connecting our MISP Instance to OpenCTI I've detected a smaller bug in the misp.py connector causing to simply not run in the "docker-way". While debugging I felt over a self-made mistake causing a import of all existing MISP events, not only the ones which I tagged for importing. 
Now I would like to ask here for a safe query to delete all observables within the graphql instance to clean the installation up a bit without loosing the other imports like mitre and co. I'm not yet fit enough for graphql and won't kill some relations which are necessary for the rest of OpenCTI - i would only delete all observables or maybe better all observables by their datatype. Any suggestions for this?

In the meantime I'll prepare the fix for the misp-connector as a separate PR in it's repository.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 16.04
2. OpenCTI version: OpenCTI/platform 2.0.2
3. OpenCTI client: frontend
4. Other environment details:

Regards,
Hendrik

**Comment by richard-julien** [comment]
Hi @andurin , unfortunately we don't have any graphql api to be able to bulk delete elements like Observable.

You can eventually get all observables with this kind of query:
`query getObservables {
  stixObservables(first: 100) {
    edges {
      node {
        id
      }
    }
  }
}`

Of course you need to adapt to paginate if you have a lot of observables.

Then you can use the delete mutation like this.

`mutation deleteObservable($id: ID!) {
  stixObservableEdit(id: $id) {
    delete
  }
}`

Hope this help.

**Comment by andurin** [comment]
Hi @richard-julien ,

thanks for the help but unfortunately I'm not able to combine your queries in the right way. Your query works like a charm and will list all the (paginated) observable ids and I also the mutation will delete successfully an observable as long as I pass one explicit observable id to the mutation.
But I can't see how to do s.th. like "delete by query" to use the mutation based on the queried IDs.

Of course it would work by setting the variable for each run - no fun for 2000+ observables.

**Comment by richard-julien** [comment]
Hi @andurin. These 2 commands are the basics to be able to script what you want but i agree that it will not solve your problem if you have to do it by hand... Do you have some development skill to be able to do it? A python script with the help of https://github.com/OpenCTI-Platform/client-python could be a good way to start.

**Comment by richard-julien** [comment]
Hi @andurin , Any progress on that?

**Comment by SamuelHassine** [comment]
We released the 3.0.0. I close this issue. Please re-open it if you still encounter some problems with the latest version.
