### ISSUE TITLE
Exited with code 1

### ISSUE THREAD

**Issue by hiltek73** [OpenCTI-Platform/opencti#338]
Receiving error "exited with code 1" with almost everything after using:
"docker-compose --compatibility up"

1. Fresh installation of Ubuntu 18.04 Server with all updates installed
2. v2.0.2
3. Frontend

Followed the steps exactly as provided on:
https://opencti-platform.github.io/docs/installation/docker

I'm starting to doubt the docker-compose.yml config enclosed. Please advise.

[OPENCTI_CONFIG_2.txt](https://github.com/OpenCTI-Platform/opencti/files/3868124/OPENCTI_CONFIG_2.txt)

![Capture](https://user-images.githubusercontent.com/30078378/69224642-d40daf80-0b74-11ea-9e7b-3b500fc31b6b.JPG)

**Comment by richard-julien** [comment]
Looks like Grakn doesnt start. Can you check the logs of the grakn container?

**Comment by hiltek73** [comment]
Did a "docker logs (with ID of the Grakn cointainer)" and all I'm receiving is the known Grakn Core display with the following output:

Starting Storage......FAILED!
Unable to start Storage.

Is my docker-compose.yml correct (see previous attachment) or does it have any errors?

**Comment by hiltek73** [comment]
In the meantime I've removed the opencti container scripts, including the workers & connectors, from the docker-compose.yml and ran it again. Grakn seems to be starting up smoothly but just not with the opencti container.

Also tried with version 2.0.1 and 2.0.0 but without luck.

I'm running it on a VM with 10GB RAM. The vm.max_map_count has also been set for ES, as mentioned in the documentation.

Any thoughts?

**Comment by richard-julien** [comment]
I dont think opencti have a direct impact on grakn container. When grakn fail to start do you have more information than just "Starting Storage......FAILED!"? If you success to start it alone, can you add the remaining opencti definition in the yaml and start again? It should just add the missing containers.

**Comment by richard-julien** [comment]
I close the issue for inactivity. Feel free to reopen if needed but it seems only related to the grakn container.
