### ISSUE TITLE
Add Read-Only Account

### ISSUE THREAD

**Issue by VVX7** [OpenCTI-Platform/opencti#367]
## Problem to Solve

Account permissions are too permissive. It should be possible to expose a public OpenCTI instance in guest/demo mode with read-only access.

## Current Workaround

None

## Proposed Solution

Add read-only account role.

**Comment by SamuelHassine** [comment]
Linked to #75

**Comment by richard-julien** [comment]
Duplicate https://github.com/OpenCTI-Platform/opencti/issues/75
