### ISSUE TITLE
Running opencti behind corporate proxy

### ISSUE THREAD

**Issue by krelac-bit** [OpenCTI-Platform/opencti#374]
mentioned in Docker-compose build behind a HTTP proxy #116 
"This environment variable is used by the docker daemon to download images for example but not inside the container."

Downloading of images works fine but after images are started connectors are not using defined proxy and cannot fetch data via proxy from Internet. Is it possible to have connectors be proxified and fetch data via proxy?

**Comment by 2xyo** [comment]
Yes, you can set `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` in `environment` section of [each connector](https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml#L123) in your `docker-compose.yml`. See https://docs.docker.com/compose/environment-variables/

**Comment by krelac-bit** [comment]
all good. thx
