### ISSUE TITLE
Get out of bluebird in the backend, replace by native Promise and remove dependency

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#3832]
## Use case

Get out of bluebird in the backend, replace by native Promise and remove dependency

**Comment by SamuelHassine** [comment]
BlueBird is not maintened anymore (and has vulnerabilities): https://github.com/petkaantonov/bluebird

**Comment by Jipegien** [comment]
won't do. See with @richard-julien
