### ISSUE TITLE
Migation to STIX 2.1

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#387]
## Problem to Solve

The current data model of OpenCTI is based on STIX 2.0.

## Current Workaround

None.

## Proposed Solution

Migrate the internal model, the import library and the export capabilities.

## Additional Information

None.

**Comment by 2xyo** [comment]
Here is a good candidate to test STIX 2.1 : https://github.com/MBCProject/mbc-stix2/blob/master/mbc.json 

> The Malware Behavior Catalog has been expressed in STIX 2.1 JSON using the STIX 2.1 Committee Specification Draft 03 (CSD03)
> The Malware Behavior Catalog (MBC) is a catalog of malware objectives and behaviors, created to support malware analysis-oriented use cases, such as labeling, similarity analysis, and standardized reporting.

**Comment by SamuelHassine** [comment]
STIX 2.1 differs from STIX 2.0 in the following ways:

New objects: Grouping, Infrastructure, Language-Content (internationalization), Location, Malware-Analysis, Note, Opinion
=> Location:  (region, country, city)
=> Note & Opinion: functional logs

Objects that have undergone significant change: Malware, all SCOs
=> Ok

New concepts: Confidence
=> Confidence: confidence_level

STIX Cyber-observable Objects can now be directly related using STIX Relationship Objects
=> Already implemented

Renamed conflicting properties on Directory Object, File Object, Process Object, and Windows Registry Key Object.
=> Ok

Added relationship from Indicator to Observed Data called "based-on".
=> Already implemented.

Added a description to Sighting and added a name to Location.
=> Ok

Made some SCO relationships external on Domain-Name, IPv4-Addr, and IPv6-Addr.
=> Ok

**Comment by 2xyo** [comment]
Once OpenCTI will be STIX 2.1 compliant, it could be interesting to pass  the STIX "Self-Certification Program for Automated Cyber Threat Intelligence Sharing"  from https://oasis-stixpreferred.org/ and to be [the first on the list](https://oasis-stixpreferred.org/preferred-product-registry/)... 

> To promote interoperability, OASIS enables implementations of the Structured Threat Information eXpression (STIX™) v2 and the Trusted Automated eXchange of Intelligence Information (TAXII™) v2 to be self-certified by suppliers. The process uses industry-defined conformance test documents developed by members of the OASIS Cyber Threat Intelligence Technical Committee.

> Products that meet the self-certification requirements are granted exclusive permission to use the “STIX2 Preferred” or “STIX/TAXII2 Preferred” certification mark.


The main advantage of this certification is to be able to use this fat logo on opencti.io 

 ![image](https://user-images.githubusercontent.com/31675/81699439-a4769a80-9467-11ea-92a2-0af0c8361496.png)

Note: the STIX **2.1** is not yet published - http://docs.oasis-open.org/cti/stix-taxii-2-interop-p1/v1.1/stix-taxii-2-interop-p1-v1.1.html
