### ISSUE TITLE
Login forbidden error

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#397]
After installing opencti in Ubuntu 18 on docker-compose. Tried to login but unable to - displayed "Login Forbidden".

What is the default username/password?
Or
Where can I see config file describing the username/password?

Note: I changed the ADMIN_TOKEN & ADMIN_PASSWORD but it seems  not working.

**Comment by richard-julien** [comment]
Hi @NetEyes ,

There is no default username / password, you have to configure it in the docker compose file according to the documentation. (APP__ADMIN__EMAIL and APP__ADMIN__PASSWORD).

Can you share your docker compose file ? Can you also check the platform docker logs?

Thanks.
