### ISSUE TITLE
Pre-installed OpenCTI iso or ready VM?

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#398]
Any chance to get a pre-installed OpenCTI on Ubuntu 18  ISO or ready made VM instead?

**Comment by NetEyes** [comment]
Greetings,
We implemented MISP server in our environment. And we would like to implement OpenCTI platform to interact with our MISP. It would be greatly appreciated if you provide us a ready OpenCTI VM that we can use in production. We will just need to hardened it and configure it to work in our environment. Many thanks.

**Comment by 2xyo** [comment]
OpenCTI is integrated in "[SIEMonster Community VM](https://siemonster.com/community-edition/)".

Note: The Community version of SIEMonster is limited and you need to provide PII to download the VM :grimacing:

**Comment by NetEyes** [comment]
> OpenCTI is integrated in "[SIEMonster Community VM](https://siemonster.com/community-edition/)".
> 
> Note: The Community version of SIEMonster is limited and you need to provide PII to download the VM 😬

Have you used the community version of SIEMonster?

**Comment by 2xyo** [comment]
> Have you used the community version of SIEMonster?

Nope. I play with https://github.com/OpenCTI-Platform/docker

**Comment by NetEyes** [comment]
I'm still having trouble making opencti works on ubuntu 18 (with 8gb ram, 2vcpu, 80gb disk space).
I tried the docker - but no luck
I tried the manual install - but no luck. (all the dependencies are easy to install, except the opencti . always got an error when running the opencti server.js).

It would be great if there is already a pre-configured VM ready to test.

**Comment by SamuelHassine** [comment]
The VM template (OVA) is now ready and will be published with the 3.0.0 release.

**Comment by VictorSalazar10** [comment]
299/5000
I downloaded the preconfigured OpenCTI virtual machine (VM). I executed it however I cannot access the dashboard (http: // {IP_ADDRESS}: 8080). Apparently no process is running on the VM.
How can I fix it?
  In Lima - Peru we are very interested in being able to use this tool.
![opencti_capture](https://user-images.githubusercontent.com/36339680/90303808-e2c09300-de76-11ea-9c8e-e7917dafdf98.PNG)

**Comment by baquetraque** [comment]
Downloaded the OVA yesterday. Exactly the same problem as  VictorSalazar10. Opencti does not seem to be automaticaly started with the ova

**Comment by bpna** [comment]
downloaded the OVA today and having the same issue. The VM is visible if I ping it from the host machine. Doesn't seem to be an opencti service available at 8080

**Comment by RianzGITHUB** [comment]
Same as above - OVA setup and running but no service available at 8080. Ill try the docker way, but wanted to test the OVA first before.
