### ISSUE TITLE
OpenCTI manual installation. Cannot start worker. OpenCTI API seems down

### ISSUE THREAD

**Issue by EtherealCod3** [OpenCTI-Platform/opencti#400]
## Description
Trying to start OpenCTI worker fails with the following message:

ValueError: OpenCTI API seems down

## Environment

1. OS (where OpenCTI server runs): Ubuntu 16.4
2. OpenCTI version: OpenCTI rolling release 20193112
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run python3 worker.py &

3. I got the error

## Expected Output

Worker running

## Actual Output

**dev@dev:~/opencti/worker$ INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "worker.py", line 174, in <module>
    worker = Worker()
  File "worker.py", line 120, in __init__
    self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
  File "/usr/local/lib/python3.6/dist-packages/pycti/api/opencti_api_client.py", line 106, in __init__
    raise ValueError('OpenCTI API seems down')
ValueError: OpenCTI API seems down**

**Comment by richard-julien** [comment]
Can you check if you have correctly created the file config.yml based on the sample config.yml.sample in the src directory?

**Comment by SamuelHassine** [comment]
I close this issue for inactivity. Please re-open it if you still need help.
