### ISSUE TITLE
installing OpenCTI manually - can't find the config/default.json

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#401]
Installing OpenCTI manually ..
installed all dependencies on Ubuntu 18.0

-- attempting to install OpenCTI ---
step1:  sudo mkdir /opt/opencti && cd /opt/opencti
step2:  sudo git clone https://github.com/OpenCTI-Platform/opencti.git
step 3: cd opencti
step 4: ls
AUTHORS       CODE_OF_CONDUCT.md  LICENSE                opencti-platform  README.md
CHANGELOG.md  CONTRIBUTING.md     opencti-documentation  opencti-worker

# configure the application based on the documentation
huh? where is the config/default.json  ???

Is your documentation even updated?

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

We advise you to use the release archive available here: https://github.com/OpenCTI-Platform/opencti/releases/download/2.1.2/opencti-release-2.1.2.tar.gz. The file `config/default.json` is directly available.

If you still want to use the `master` branch of the repository, the file `config/default.json` is in `opencti-platform/opencti-graphql`. Be careful by using the master branch as we update it every days. For instance, the `master` branch is currently required Grakn 1.6.1 and the last release only Grakn 1.5.9.

Kind regards,
Samuel

**Comment by NetEyes** [comment]
found the actual tar ...
sudo wget https://releases.opencti.io/opencti-20190420.tar.gz
 
unto the next steps ..

got stuck in installing python modules ..
$ cd src/utils/stix2

can't find this src/utils/stix2
