### ISSUE TITLE
OpenCTI manual installation. ElasticSearch paginate fail

### ISSUE THREAD

**Issue by EtherealCod3** [OpenCTI-Platform/opencti#402]
## Description

After logon, the following error appears on console:

**error: [ELASTICSEARCH] Paginate fail > ResponseError: search_phase_execution_exception**

As a result, portal navigation is broken. Portal sections return an empty page with no results.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI rolling release 20191231
3. OpenCTI client: frontend
4. Other environment details: OpenCTI manual installation

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Manual install OpenCTI and dependencies.
2. Error shows up after logging on the portal.

## Expected Output

There should be no error.

## Actual Output

The above error appears.
 
## Additional information

Seems that the error originates from **build/index.js**

            return r.j.debug(`[ELASTICSEARCH] paginate > ${JSON.stringify(_)}`), g.search(_).then(e => {
                const n = Object(d.map)(e => {
                    const n = Object(d.pipe)(Object(d.assoc)("id", e._source.internal_id_key), Object(d.assoc)("_index", e._index))(e._source);
                    return n.relationship_type ? F(n, N) : n
                }, e.body.hits.hits);
                if (f) {
                    const a = Object(d.map)(e => ({
                        node: e
                    }), n);
                    return Object(m.a)(i, T, a, e.body.hits.total.value)
                }
                return n
            })**.catch(e => (r.j.error(`[ELASTICSEARCH] Paginate fail > ${e}`), Object(m.a)(0, 0, [], 0)))**

**Comment by EtherealCod3** [comment]
When run in docker container, the issue persists, however I get a verbose output that might be of help:

elasticsearch_1  | {"type": "server", "timestamp": "2020-01-05T00:03:42,181Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "docker-cluster", "node.name": "ff339219e6f0", "message": "[stix_observables][0], node[swVGNJozQ2CNFXE_M92bnQ], [P], s[STARTED], a[id=WBbDAITISFSucaL2Hz4BnA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[stix_observables], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={\"from\":0,\"size\":10,\"query\":{\"bool\":{\"must\":[{\"match_all\":{\"boost\":1.0}},{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type\":{\"query\":\"Stix-Observable\",\"slop\":0,\"zero_terms_query\":\"NONE\",\"boost\":1.0}}},{\"match_phrase\":{\"parent_types\":{\"query\":\"Stix-Observable\",\"slop\":0,\"zero_terms_query\":\"NONE\",\"boost\":1.0}}}],\"adjust_pure_negative\":true,\"minimum_should_match\":\"1\",\"boost\":1.0}}],\"adjust_pure_negative\":true,\"boost\":1.0}},\"_source\":{\"includes\":[],\"excludes\":[\"rel_*\"]},\"sort\":[{\"created_at\":{\"order\":\"desc\"}}],\"track_total_hits\":2147483647}}]", "cluster.uuid": "5g0J_aajR5SSp4vSeaCLIg", "node.id": "swVGNJozQ2CNFXE_M92bnQ" ,
elasticsearch_1  | "stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [ff339219e6f0][172.18.0.5:9300][indices:data/read/search[phase/query]]",
elasticsearch_1  | "Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [created_at] in order to sort on",
elasticsearch_1  | "at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:387) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:153) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.parseSource(SearchService.java:762) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createContext(SearchService.java:586) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:545) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:348) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:146) ~[elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0.jar:7.5.0]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:830) [?:?]"] }

**Comment by SamuelHassine** [comment]
@EtherealCod3, the error `elasticsearch_1 | "Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [created_at] in order to sort on"` is "normal", this is because you do not have any observable at that time. Just create one observable and this will be solved. This error does not have any impact on the application or on the UI.
