### ISSUE TITLE
Automating the OpenCTI Manual Install Process

### ISSUE THREAD

**Issue by p-rs** [OpenCTI-Platform/opencti#406]
## Problem to Solve

The manual install document: https://opencti-platform.github.io/docs/installation/manual was pretty difficult to follow and does not cover prerequisites installation and certain pitfalls when going through this process.

## Current Workaround

I created a script to automate this process and had success: https://gist.github.com/p-rs/5e67b811efd30ef704be7078cbd758a8

## Proposed Solution

You may use the script I created: https://gist.github.com/p-rs/5e67b811efd30ef704be7078cbd758a8 and add it as a bootstrap process for people that do not want to use or cant use the docker containers.

## Additional Information

This was a very long Dungeons and Dragons quest to complete... if anyone is interested in using this, feel free to use AS IS, and feel free to comment/suggest changes on the gist - thank you!

**Comment by richard-julien** [comment]
Hi @p-rs ! Nice initiative !
We focused for now to deliver a simple deployment through docker and we clearly lack of an automated script to manually deploy the platform.
Have you considered using chef, puppet or ansible (or other tools of this kind) before manually scripting it?

**Comment by p-rs** [comment]
Thanks and yes, this was taken into consideration but those tools do not exactly fit our build process as this is tested in a cloud formation process and a bootstrap was created as a last step.

**Comment by SamuelHassine** [comment]
I refered the script in the documentation: https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1.

**Comment by p-rs** [comment]
Hi Samuel!

Late response but thank you for referencing the script, super cool!

I updated the gist:
https://gist.github.com/p-rs/5e67b811efd30ef704be7078cbd758a8 to work with
the latest OpenCTI (3.3.1) and it provides systemd unit files for both the
server and workers.

Thank you!
p-rs
