### ISSUE TITLE
Bootstrap error > Python3 with STIX2 module is missing

### ISSUE THREAD

**Issue by jibrilha** [OpenCTI-Platform/opencti#408]
## Description
Unable to start the server.js When try to start the server with "node server.js &" I get the following error,

error: [API] Bootstrap error > Python3 with STIX2 module is missing {"stack":"Error: Python3 with STIX2 module is missing\n    at checkPythonStix2 (/home/apps/opencti/dist/database/utils.js:154:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}

## Environment
OS (where OpenCTI server runs): Debian 18.04
OpenCTI version: OpenCTI 2.1.2
OpenCTI client: frontend
Other environment details: Demo VM

## Actual Output
root@ubu18:/home/apps/opencti/dist# info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
error: [API] Bootstrap error > Python3 with STIX2 module is missing {"stack":"Error: Python3 with STIX2 module is missing\n    at checkPythonStix2 (/home/apps/opencti/dist/database/utils.js:154:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}
[1]+  Exit 1                  node server.js

## Additional information
Looking at the stix2 reqs (in ../src/utils/stix2/) as below, all requirement are already satisfied. 

root@ubu18:/home/apps/opencti/src/utils/stix2# pip3 install -r requirements.txt
Requirement already satisfied: stix2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: stix2-validator in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: simplejson in /usr/local/lib/python3.6/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: stix2-patterns in /usr/local/lib/python3.6/dist-packages (from stix2->-r requirements.txt (line 1))
Requirement already satisfied: requests-cache in /usr/local/lib/python3.6/dist-packages (from stix2-validator->-r requirements.txt (line 2))
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from stix2-validator->-r requirements.txt (line 2))
Requirement already satisfied: jsonschema>=2.5.1 in /usr/lib/python3/dist-packages (from stix2-validator->-r requirements.txt (line 2))
Requirement already satisfied: appdirs in /usr/local/lib/python3.6/dist-packages (from stix2-validator->-r requirements.txt (line 2))
Requirement already satisfied: antlr4-python3-runtime>=4.7; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from stix2-patterns->stix2->-r requirements.txt (line 1))

**Comment by richard-julien** [comment]
Can you check if the command "python3 -V" works correctly? Thanks

**Comment by jibrilha** [comment]
output is Python 3.6.9 and i've passed this point, thanks.

**Comment by mcitarella00** [comment]
Can you please let us know how this was solved?
