### ISSUE TITLE
[Doc] nodejs version on Ubuntu 18.04 is too old

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#413]
## Description

The documentation "Development environment installation"  recommends the installation of a recent version of nodejs but the version installed if we follow the instructions is old.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.3 LTS
3. Doc: https://opencti-platform.github.io/docs/development/installation 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install fresh Ubuntu 18.04 
2. `sudo apt install nodejs`

## Expected Output

Node.JS version >= 12.* < 13.0.0 installed

## Actual Output

```
$ apt show nodejs 2>/dev/null |head -n 2
Package: nodejs
Version: 8.10.0~dfsg-2ubuntu0.4
```
 
## Fix

```
VERSION=node_12.x
DISTRO="$(lsb_release -s -c)"

curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list

sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install -y nodejs yarn python3 python3-pip
```

**Comment by SamuelHassine** [comment]
Documentation will be updated with the NodeJS version and changed to Ubuntu 19.04.

**Comment by 2xyo** [comment]
> Documentation will be updated with the NodeJS version and changed to Ubuntu 19.04.

The Ubuntu 19.04 release arrived almost 9 months ago, on April 18, 2019. But as it's a non-LTS release it only gets 9 months on going app updates and security patches. And those 9 months are already up since January 23, 2020. :open_mouth: See https://wiki.ubuntu.com/Releases
