### ISSUE TITLE
infinite loading of reports using specific sort options

### ISSUE THREAD

**Issue by intelwolf** [OpenCTI-Platform/opencti#416]
## Description

When using a certain sort order in the report overview the system ends in an infinite loading stats. Changing order is fixing the issue.
Sorting on Author in reverse order is bringing you in this state.

https://demo.opencti.io/dashboard/reports/all?sortBy=createdByRef&orderAsc=false&searchTerm=

## Reproducible Steps

Go to the report section and set sort order to reverse Author.
 
## Expected Output

Infinite loading of reports

## Actual Output

Report overview
 
## Additional information

Direct url of demo system: https://demo.opencti.io/dashboard/reports/all?sortBy=createdByRef&orderAsc=false&searchTerm=

**Comment by richard-julien** [comment]
After looking on it its a grakn performance issue. For now we dont have any way to improve that so we will remove this ordering capability waiting for a performance improvement on grakn side.
