### ISSUE TITLE
Duplicated relationships beween entities (e.g. attack patterns attached to a malware)

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#426]
When viewing tactics related to a malware, the same tactic will appear several times in the list if it has been reported and attached to the malware several times (in several reports).

For an analyst, the tactic should appear only once. When there is a lot of different tactics attached to a malware, having each of them several times in the list will create confusion.

This issue seems to be more global. I.e. not just for the malware <-> attack pattern relationship, but all relationships between objects.

**Comment by SamuelHassine** [comment]
Hello @Fred-certeu, this is a desired behavior, since malware (or any threat) could evolve in time and used a TTP in 2015, then stopped to use it, and finally used it in 2020. The TTPs display has been enhanced for a better understanding of this behavior.

**Comment by Fred-certeu** [comment]
Good. I also share your views. The point is that we need to accommodate two objectives:
- have a synthetic visualization of techniques/tactics used by a malware (or any threat)
- understand when they where used or stopped being used.
Also bearing in mind that it is not because a threat stop using a technique/tactic that it has banned for ever.

**Comment by SamuelHassine** [comment]
Ok @Fred-certeu I agree with your points. The fact is as you can see in the "TTPs" and the "Victimology" of a threat knowledge section (threat actor, intrusion set, etc.), we try to continuously improve the different view and enhance the default "relations list" by working view by view on different types of visualization for a better understanding.

I propose to close this issue and open more precise issues on the view we want for the different data types, for instance: "Enhance malwares list of an intrusion set, introduce synthetic visualization of malwares used by an intrusion set, add a chronology, etc.".
