### ISSUE TITLE
OpenCTI class diagram/blueprints

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#431]
Greetings,
Please provide class diagram of opencti project. 
How the backend works? Please described the system work flow.

example ..
1. worker will retrieve threat feeds from the sources
2. worker will store the ingested feed to database (Grakn)
.. etc.

I am thinkering of converting OpenCTI to .NET platform. 
One option is to develop the front-end running in  asp.net and connects to OpenCTI backend as is.
second option is to make it run in windows platform and keep the code as much as possible.
third option, totally convert the .net platform. (why? java dependencies)

**Comment by SamuelHassine** [comment]
I think the new PKB (https://www.notion.so/luatix/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) as well as the first webinar (https://www.notion.so/luatix/Webinar-01-Introduction-to-the-platform-632e65af1541450e87c1cc5c042ace5d) are answering to all questions. We will continue to enhance documentation about the architecture in the next weeks.
