### ISSUE TITLE
Custom 502 error on demo.opencti.io

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#434]
## Problem to Solve

When https://demo.opencti.io/ is unavailable, an ugly default  "502 Bad Gateway" error is displayed :frowning:.

A hurried visitor may be tempted to never come back to test the demo because they may think that the demo does not work at all :cold_sweat:.

## Proposed Solution

Configure nginx with a _shiny_ custom `error_page 502 /502.html;`. 

## Additional Information

* http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page

**Comment by SamuelHassine** [comment]
Hello @2xyo,

Thanks for this comment, it is a very important issue for us. We decided to make the demonstration more stable and modified this evening all the infrastructure as well as the deployment process. The demo instance should now be accessible and never return a 502. I close this issue and will reopen it if we encounter new troubles with this instance.

**Comment by 2xyo** [comment]
Hi, looks like demo.opencti.io has been down [today](https://www.webpagetest.org/result/210711_BiDc1G_4ebe6589db4c198e1fb6348ac521f6b0/) with a 502 error  :worried:

**Comment by essal0815** [comment]
Down Again ? [Test Result](https://www.webpagetest.org/result/211007_AiDcMF_975055781c58fd3bf8b1877a705036cf/)
