### ISSUE TITLE
Enhance global and local search

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#438]
## Problem to Solve

The search features in the OpenCTI platform is very basic.

## Current Workaround

None.

## Proposed Solution

We need to implement an intelligent search engine with autocomplete.

## Additional Information

None.

**Comment by Fred-certeu** [comment]
Good point.
I wanted to create an issue on this matter.
For observables (for example), an advance search would be welcomed - combining:
- value (equals or contains)
- type 
- date (=, <, >)
- creator

**Comment by csandu-certeu** [comment]
A couple of aspects to consider for the search:
- currently the search is looking in all entities which is quite resource consuming; an option could perhaps be the possibility to split the search into: 
   - search for indicators/observables 
   - search for all other entities.  

This way, if the user is not interested in searching for an observable/indicator, the platform won't consume resources to search those.
- in case of searching multiple words, one thing that helps is wrapping the search term in between "". Ex: "ANTHROPOID SPIDER"

**Comment by manonviallet** [comment]
Ideas for the search field :
- be able to save a search for later re-run ;
- have a search history (who searched what) --> could be in the admin pannel
