### ISSUE TITLE
Importing/Pivoting from Security Onion?

### ISSUE THREAD

**Issue by LotoQ** [OpenCTI-Platform/opencti#455]
Hello all,

I've been playing around pretty excitedly with OpenCTI these last two weeks or so, and have gone through multiple installations to fully understand how it all seems to work, checked out the API, integrated MISP connectors and some other things.. So far, I'm in love, and let me tell you, the DARK THEME is the best part of this project so far! Much respect for that.

I'm wondering though if anyone has been able to or has thought of the possibility to pivot into OpenCTI from a Kibana or something? I currently have Security Onion running, and for my analysis I would like to be able to take queries, or entities/indicators like IPs from a particular session, and be able to get that data into OpenCTI without hand-jamming.. Hopefully thats clear enough. I had seen that MISP was able to integrate with SecurityOnion (and by turn integrate with OpenCTI?), but it didnt seem like it was going to be able to do what I wanted to be able to do.

Please forgive me if this isn't the best way/format to post this type of question, I didnt feel like it belonged as a feature request or bug reporting (obviously). 

Cheers,
Loto

**Comment by 2xyo** [comment]
Would you mean "_adding custom drilldown menu in Kibana with a link to the current item (hash/IP/etc..)  in OpenCTI_ "? Something like this https://github.com/elastic/kibana/issues/8042  - https://github.com/elastic/kibana/issues/12560 ? 

If yes, you can simply use the search function `https://{opencti_hostname}/dashboard/search/{QUERY}` like this https://demo.opencti.io/dashboard/search/test :)

**Comment by LotoQ** [comment]
Hmm, I took a look at those pages, and it is kind of along the lines of what I was talking about yes, but this only would work if the data is already in OpenCTI, correct? My problem is that I dont have the same data in OpenCTI as I do in Kibana.. Lets say for example I am hunting my network, and I see that 192.168.1.1 and 10.0.0.1 are communicating, and this traffic is of interest to me.. I would like to map it and form relations and reports with that data in OpenCTI. As far as I can tell, currently, I have to first go and create those indicators ( one for 192.168.1.1 and another for 10.0.0.1 ) by going to the Signatures page, and adding an IPv4 indicator for each IP manually.. What I would like to happen is somehow be able to do this auto-MAGICALLY from kibana.. Though now I'm thinking I might be able to do this through the API.. lol

**Comment by LotoQ** [comment]
going to close this issue since I have a way forward with my question, thanks to 2xyo. May reopen if i have something to contribute to the community or if i have further questions..
