### ISSUE TITLE
OpenCTI 2.1.3 folder "serv" do not exist.

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#457]
Greetings,

I tried to download the latest release from https://github.com/OpenCTI-Platform/opencti/releases/download/2.1.3/opencti-release-2.1.3.tar.gz
.. extracted it and try to follow the documentation.

>yarn serv
No such file or directory 'serv'

Please advise how to run the latest release.

**Comment by SamuelHassine** [comment]
@NetEyes In which directory are you launching `yarn serv`? And could you please provide the output of `yarn --help`.

**Comment by SamuelHassine** [comment]
We released the 3.0.0. I close this issue. Please re-open it if you still encounter some problems with the latest version.
