### ISSUE TITLE
Error Message when accessing the connectors page in the UI 

### ISSUE THREAD

**Issue by adimenia** [OpenCTI-Platform/opencti#463]
Hello

I'm running OpenCTI on Ubuntu 18.04 x64 AWS EC2 instance. when accessing the connectors page on the UI I get a simple Error message. see the screenshot below.
![OpenCTI](https://user-images.githubusercontent.com/5006200/73916377-00101580-48c6-11ea-8c4b-97d54a1c10c4.png)
once received, I can't navigate to any other locations in the UI.
I've tried looking into some logs on the system but couldn't find any evidence for the cause of the problem.

**Comment by richard-julien** [comment]
Hi @adimenia ,

It's not really possible to help you without more information. Can you provide the docker compose if you use docker or your configuration files if you deploy manually ? Same for logs (docker logs or api logs).

Thanks.

**Comment by SamuelHassine** [comment]
@adimenia: I close this issue for inactivity. You can re-open it if you still need help.
