### ISSUE TITLE
STIX2 file import error (example with the latest CERT-FR publication)

### ISSUE THREAD

**Issue by jlequen** [OpenCTI-Platform/opencti#465]
## Description

I can't import stix2 this ANSSI publication (http://www.cert.ssi.gouv.fr/uploads/CERTFR-2020-CTI-001-STIX2.json)

## Environment

1. OS : Ubuntu 16.4
2. OpenCTI version:  OpenCTI 2.1.4 (fresh install) Docker
3. Grakn :1.6.2
4. Elasticsearch : 7.5.2
5. RabbitMQ : 3.7.17
6. Redis : 5.0.5
7. MinIO : RELEASE.2019-10-12T01-39-57Z
8. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install OpenCTI (docker)
2. Import this stix2 export : https://www.cert.ssi.gouv.fr/uploads/CERTFR-2020-CTI-001-STIX2.json

## Actual Output

![Capture](https://user-images.githubusercontent.com/7465331/73941517-b6d3bc00-48ed-11ea-8e0b-3327a9c3a422.PNG)

**Comment by SamuelHassine** [comment]
Hello @jlequen,

Thanks for this bug report, we are aware of this situation that will be fixed in the next release. We work hard to create a stable import/export system that could be used by all OpenCTI instances.

Kind regards,
Samuel
