### ISSUE TITLE
Create person fails with "Thing does not have exactly one key of type [user_email]." error.

### ISSUE THREAD

**Issue by graememeyer** [OpenCTI-Platform/opencti#472]
## Description

{ You get an error when trying to create a person, either directly on the entities/persons page, or indirectly in the author drop-down box. Exact error is:

> Thing [V330477808] does not have exactly one key of type [user_email]. It either has no keys assigned to it, or it has more than one.

 }

## Environment

1. OS (where OpenCTI server runs): { Demo.OpenCTI.io (2.1.4)}
2. OpenCTI version: { Demo.OpenCTI.io (2.1.4) }
3. OpenCTI client: { web gui / front-end }
4. Other environment details: Firefox 72.0.2 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Log in to the demo instance }
2. { Click entities / sectors in the left sidebar/panel }
3. { Click Persons button in the top banner } 
4. { Click orange plus button in the bottom right }
5. { Fill in example information, including seemingly any combination of valid information }
6. { Receive red error banner at the top ("Thing [V330477808] does not have exactly one key of type [user_email]." etc. }

## Expected Output

{ Person object created}

## Actual Output

{ Red error banner, person not created. }
 
## Additional information

{ 

Demo.OpenCTI.io (2.1.4) - Firefox 72.0.2 (64-bit)

I also tried to create a person via the author selection drop down (when trying to create an organisation), and that produced the same error.

Screenshot example attached:

![image](https://user-images.githubusercontent.com/3931530/74109691-6c686e80-4b7d-11ea-960a-f43170379b6b.png)

 }

**Comment by SamuelHassine** [comment]
Hello,

Thank you for this bug report, this will be fixed in the next release.
