### ISSUE TITLE
Improve filtering / sorting of reports

### ISSUE THREAD

**Issue by 8hur** [OpenCTI-Platform/opencti#479]
## Problem to Solve

With a large number of reports, it can be complicated to find a specific report or a set of reports of interest.

## Current Workaround

Use the search engine

## Proposed Solution

- Add a "Date added" column: This could be particularly useful to find the latest report imported to populate it.

- For each column (except title), allow selection of values that reports need to have to be shown with boxes to tick: For example, one could be able to only show reports with status "New" or "In Progress" with a marking of "TLP:AMBER". For the dates, the best would be to be able to set boundaries values.

**Comment by SamuelHassine** [comment]
Linked to #172.
