### ISSUE TITLE
Merge duplicates entities

### ISSUE THREAD

**Issue by 8hur** [OpenCTI-Platform/opencti#480]
## Problem to Solve

When something is known under multiples names, multiples entities in opencti can be created for the same thing.

For example they could be one entity for SOGU and one for PlugX.

## Current Workaround

Choose the least used entity, add the most used entity in every report where it appears then delete the least used entity.

## Proposed Solution

Allow merging of entities, keeping every link associated to both of the previous entities.

**Comment by richard-julien** [comment]
Looks like https://github.com/OpenCTI-Platform/opencti/issues/246 but seems a bit different. For this use case maybe we should add a specific relation **similar-to** between group(s) and elect the group that will represents the others. Dont know if STIX define this kind of situation. @SamuelHassine?

**Comment by 8hur** [comment]
My bad. I haven't searched properly before filling the bug.
