### ISSUE TITLE
Export improvement. Use file to ask list of ids or queries

### ISSUE THREAD

**Issue by CGarat** [OpenCTI-Platform/opencti#481]
## Problem to Solve

There is currently no way to search for more than one entry in the platform, e.g. provide a file with multiple observables (hundreds, thousands..) of different types and get all entities that match these values in the platform.

## Current Workaround

Look up each entry individually.

## Proposed Solution

Have a "file import" feature linked to the search bar. Files may include multiple entities of different types. After the import, matches would be displayed to the user in the platform or in a file to be exported.

**Comment by SamuelHassine** [comment]
Related to #2336.

After doing the bulk search of SCOs, be able to export directly from the search result screen/
