### ISSUE TITLE
Markdown editor 

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#491]
## Problem to Solve

There is no assistance to edit Markdown content. 

Even if Markdown is not so complicated, having an editor is convenient especially for non-technical people who can work on the non-technical side of threat analysis  and who are used to using a WYSIWYG editor.

## Current Workaround

Use an external editor like:

- https://stackedit.io/
- https://dillinger.io/

Copy/past in OpenCTI

## Proposed Solution

- Add a light button next to the fields that may contain Markdown. On click:
  - Opening  a modal dialog component with an integrated markdown editor
    - Classic buttons: italics, bold, titles, links, image (embedded in base64), etc.
    - Preview and/or live preview   
    - Bonus: Full screen / distraction free mode 

## Additional Information

React examples:

- https://codesandbox.io/s/react-mde-latest-bm6p3 
- https://jedwatson.github.io/react-md-editor/

**Comment by rhaist** [comment]
+1 for this feature. If we boost the capabilities of the various "description" fields with full markdown contents (+pictures) OpenCTI can be a full grown reporting platform handling even long-form TI report drafting and releases.
