### ISSUE TITLE
Client local settings persistence is enforced

### ISSUE THREAD

**Issue by ghost** [OpenCTI-Platform/opencti#4975]
## Description
Search field inputs, like in the search in malwares, threat actors, intrusion sets are persistent.

## Environment

1. OS (where OpenCTI server runs): Debian Trixie
2. OpenCTI version: 5.11.12
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to /dashboard/arsenal/malwares
2. Search for something
3. Go on any other site within the app
4. go back to /dashboard/arsenal/malwares
5. see that the search persist

Also it's persistent if a session expires or the user is logged out.
In any cases the url is directly expanded with the search query.

## Expected Output
A clear view without any previous search queries.

## Actual Output
The last search query is persistent.

## Additional information
The input is cached in the local storage (view-malwares, e.g.). 
A persistence in a session storage would already be questionable, but in local storage it makes absolutely no sense. If a person needs specific information of a malware or a search result it can be temporary persisted in  a new tab.
But the current implementation forces me to see everytime i go to a page where i've searched something that i see the last search result.
As mentioned in my comment below this also affects other settings.
I would recommend to make it an option to persist local settings or forget it immediately.

**Comment by ghost** [comment]
Ok, I've looked more in the data that are stored and updated the title. There is much more persisted than only the search query but also the sort direction and sort fields.
I update therefore the title.

**Comment by Jipegien** [comment]
This is intended. Persistence in filters and searches allows users to refine views for making them more meaningful, without having to reproduce it after logoff. 
Clearing a search is done by removing the keyword from the search bar and launch the search.
Regarding filter, next release will come with a "reset filter" button.
