### ISSUE TITLE
Ask for confirmation before suppressing an entity from a graph from the pannel 

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#499]
## Problem to Solve

When in the graph view to capitalize knowledge from a report, if an entity is already in the graph, when the analyst look for it in the research pannel, it is ticked in blue. However, if the analyst click on it, it automatically deselected the entity and suppress it from the graph (with the attached relations) without asking for confirmation. 

## Current Workaround

None

## Proposed Solution

Have a pop-up window asking for confirmation of suppression before validating the action.

**Comment by manonviallet** [comment]
Linked to issue #500
