### ISSUE TITLE
Full refactor of knowledge graph and graph everywhere

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#504]
- Change library (or update)
- Introduce graph everywhere

**Comment by manonviallet** [comment]
A desired feature would be the following : to have a relational "master" graph in Intrusion-Set and Threat-Actor knowledge

# Problem to Solve

Create a view window such as in "Report/xxxx/knowledge" that would be located in "Intrusion-Set/xxxx/knowledge" or "Threat-Actor/xxxx/knowledge" that would add all of them up automatically.  

The app is currently missing an automatic "relational master graph" of a threat actor or an Intrusion-set. 
Therefore, we have to visualize each relational graph seperately. 

The idea would be to create a view window that displays a relational graph representing all the information gathered in "Report/xxxx/knowledge". 


For instance

Analysis could be improved by having a view window in "Intrusion-Set/APT28/knowledge" nammed "APT28 Relational Graph" for instance, and displayed under "Overview" tab. 

This relational graph would be automatically created and fueled by any other relational graphs created in "Report/xxxx/knowledge" based on reports IoCs.

For instance, when adding new links to an indicator related to APT28 in "Report/xxxx/knowledge", the links would be automatically created in the relational graph located in "Intrusion-Set/APT28/knowledge/APT28 Relational Graph". 


   
# Current Workaround

Create an APT28 report myself and add each entity related to APT28.

**Comment by manonviallet** [comment]
It would be interesting if analysts could edit the graph (remove relations, ask to display more relations around some object) and export it in image format (PNG) and / or CSV/JSON :
- this could be merely display (no change on the knowledge, once the analyst leave the page everything is reset, but if so, have a small message to warn) ;
- this could be durable change (changes made by the analyst are saved) --> would need to be saved in the activity.
What about the level of jumps ? How is it decided how far we go ? It could be based on inferences scenarios (Intrusion sets --> all its campaigns --> all incidents in the campaigns --> all malware, orgs, sectors in the incidents ?)

it would be interesting to be able to filtrate the graph display based on dates and level of marking

it would be necessary to be able to quickly export the graph (see above)
