### ISSUE TITLE
Create a threat activity dashboard

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/opencti#505]
All in the title ;)

**Comment by Fred-certeu** [comment]
Suggestions.

There should be two dashboards
1. platform activity
2. threat activity

The platform activity corresponds to what is implemented now.
There could be more granularity as regards ingested entities: new/total malware, intrusions sets, attack patterns, etc

The threat activity dashboard could include:
- top x most active malware
- top x most active intrusion sets / threat actors
- top x most active campaigns
- top x most affected countries
- top x most affected organisations

There could be a filter to select the time window to calculate the "top x most active zzz":
- last 24H
- last week
- last month
- last 3 months
- last 6 months
- last 12 months

**Comment by Fred-certeu** [comment]
Referring to my proposal above (platform activity vs threat activity)

Under platform activity we currently have:
- last reports
- last observables

It could also be useful to have:
- last intrusion sets
- last malware

**Comment by manonviallet** [comment]
Suggestions and ideas for refactoring dashboards :

- be able to compare through time and for a definite period of time (for instance : a year) activity between different entities of the same type (malware, APT, threat actors, but also campaigns or incidents) using a timeline ;

- have a map display with countries or regions highlighted depending on the number of hits/attacks (by malware, by intrusion sets, by campaign) with a darker color if more hits ;

- be able to filtrate both by region/country and by sector of activity (for instance : attacks in country X but only in sector Z) when displaying in lists or in any other type of view ;

- be able to have lists of the most used malwares or tools for a given period of time or of the most hit sectors or countries/regions by a given malware or intrusion set ;

- timelines on intrusion sets activities (incidents and campaigns), timelines of malware use or of TTPs use ;

- comparison of campaigns or incidents for a given intrusion set or a given organization of country (timeline of malware detection and of TTPs) ;

More generally, interesting usecases for dashboards could be the following : comparing different entities in a given type with different sets of metrics and visuals : 

- following incidents occurrences within an organization, a sector or a country, with detected malware and tools, used TTPs, identified intrusion sets etc.

- malware comparison : time of use, versions, linked intrusion sets, targeted countries, targeted sectors.

- intrusion sets comparison : last activity, sectors targeted, countries or region targeted, malware and tools used, TTPs used, malware or TTPs or indicators in common.
