### ISSUE TITLE
Problem when trying to add an external reference to a Threat Report 

### ISSUE THREAD

**Issue by AZobec** [OpenCTI-Platform/opencti#510]
## Description

I created a new Threat report.
I created a new external reference.
I wanted to add this new reference to the new report previously created.

And I got an error from grakn :

`opencti_1                     | error: [GRAKN] executeWrite error > Cannot read property 'map' of null {"stack":"TypeError: Cannot read property 'map' of null\n    at /opt/opencti/build/index.js:1:28310\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async W (/opt/opencti/build/index.js:1:5188)\n    at async xe (/opt/opencti/build/index.js:1:27869)\n    at async Me (/opt/opencti/build/index.js:1:30421)"}
opencti_1                     | error: [OPENCTI] Technical error > Cannot read property 'map' of null {"locations":[{"line":6,"column":5}],"path":["externalReferenceEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'map' of null","    at /opt/opencti/build/index.js:1:28310","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async W (/opt/opencti/build/index.js:1:5188)","    at async xe (/opt/opencti/build/index.js:1:27869)","    at async Me (/opt/opencti/build/index.js:1:30421)"]}}}`

I tested to add external references to old Threat Reports, I had the same issue. 

## Environment

1. OS (where OpenCTI server runs): { Debian 10.2 }
2. OpenCTI version: { OpenCTI 3.0.0 }
3. OpenCTI client: { frontend  }
4. Other environment details: Using docker with latest images

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. going on http://opencti.local.cert.opmd.fr/dashboard/reports/all and then click "+" to create a new report
2. Create a new external reference while on the report page (with "+" button)
3. Error : "Une erreur est survenue, merci de réessayer plus tard"
4. Grakn Error : `opencti_1                     | error: [GRAKN] executeWrite error > Cannot read property 'map' of null {"stack":"TypeError: Cannot read property 'map' of null\n    at /opt/opencti/build/index.js:1:28310\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async W (/opt/opencti/build/index.js:1:5188)\n    at async xe (/opt/opencti/build/index.js:1:27869)\n    at async Me (/opt/opencti/build/index.js:1:30421)"}
opencti_1                     | error: [OPENCTI] Technical error > Cannot read property 'map' of null {"locations":[{"line":6,"column":5}],"path":["externalReferenceEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'map' of null","    at /opt/opencti/build/index.js:1:28310","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async W (/opt/opencti/build/index.js:1:5188)","    at async xe (/opt/opencti/build/index.js:1:27869)","    at async Me (/opt/opencti/build/index.js:1:30421)"]}}}`

## Expected Output

I expected to link the external references I created to my Threat Report.

## Actual Output

Nothing - just the error message

**Comment by SamuelHassine** [comment]
Hotfixed in the new image of the 3.0.0.

**Comment by SamuelHassine** [comment]
Hotfixed in the new image of the 3.0.0. If you are using Docker, please re-pull the images, if you are using manual deployment, please use the new packages.
