### ISSUE TITLE
have the same presentation in the frontend for countries and regions than for sectors/subsectors

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#532]
## Problem to Solve

In the frontend, make visible that countries belong to regions and subregions (copy what as been implemented for sectors, with two things :
- in the region list, only have the main regions and be able to develop the view to see sub regions and then countries ;
- when in a country or region overview, have a middle box in the view to show regions or countries linked to the entity (such as for sectors and subsectors).

**Comment by SamuelHassine** [comment]
@manonviallet can you please elaborate on this issue? We fully understood what you mean but can you explain why this is needed and the actual use case?
