### ISSUE TITLE
Filtering of kill chain view by marking (and other fields)

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#535]
## Problem to Solve

It would be usefull to be able to filter displayed entities in the knowledge part according to marking, especially for exporting the view to a png format.

It could also be interesting to filter by date / period of time, by techniques, by author etc.

## Current Workaround

None

**Comment by SamuelHassine** [comment]
Please @manonviallet can you be more specific on this one? Which "knowledge" part are you talking about?

**Comment by manonviallet** [comment]
linked to #1404 
Both issues are similar. Maybe this one can be closed and the other used as a reference as it is more detailed (sorry for the repetition)

**Comment by manonviallet** [comment]
Three things are to be taken into account, which are dealt with in both issues:
- display the marking level of relations next to the related entity, especially in the tables accessed from the "knowledge" tab (where you can see the knowledge associated to an entity, such as which malware an intrusion set uses etc.)
- be able to filter the display by marking level
- be able to export under PNG or CSV or JSON the result, with the filters taken into account.
