### ISSUE TITLE
Improve list view with dimensions and advanced filtering

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#536]
## Problem to Solve

The malware view could be improved on the same model than the other categories in "knowledge". Ideas of organisation could be :
- list alphabetically
- regroup each malware occurence (like for sectors and regions sightings)
- regroup malware by techniques when identified
- display marking level

Allow filtering by some of the fields (marking, dates, names, techniques).
Allow PNG and CSV exports of the malware list.

## Current Workaround
USe of currently display

**Comment by manonviallet** [comment]
Linked with issue #535

**Comment by SamuelHassine** [comment]
@manonviallet I'm sorry but for this one, you need to be more specific. You bullet points are radically different one for each other, and it is missing a lot of details here. For instance, when you say: "regroup malware by technique", do you mean if a malware is using 10 techniques it should be duplicated 10 times?

Also, speaking about PNG export in list seems to be not doable, PNG export should be implemented in more "suitable" views for display. Finally "filtering" on field seem to be already implemented. 

Is it possible to rewrite this issue with what is exactly needed and also prioritize a little the bullet points so we can iterate?

Thanks.
