### ISSUE TITLE
Additional fields for filtering indicators

### ISSUE THREAD

**Issue by maertv** [OpenCTI-Platform/opencti#537]
## Problem to Solve

Currently it is not possible to filter indicators by _score_. In addition to _score_ it would be useful to have some additional filterable fields, like _modified_, _created_, _valid_from_, _valid_until_, _created_at_ (How it differs from _created_?)
and _updated_at_ (How it differs from _modified_?). 

Perhaps there are other fields that should be filterable.

## Current Workaround

None

**Comment by SamuelHassine** [comment]
Hello,

- `created` and `modified` are non-technical fields that can be updated by the user (in case of import, these fields are added from STIX 2).
- `created_at` and `updated_at` are technical fields of the platform:
  - `created_at` is the date when the entity/relation has been created in the OpenCTI instance.
  - `updated_at` is the date when the entity/relation has been updated in the OpenCTI instance.
