### ISSUE TITLE
Need help to configure docker installation

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/opencti#542]
Hi,

I tried the automatic installation, and the Docker installation, by scrupulously following the indications of the documentation, but in vain.

Between the yarn serv which returns an: ERROR: [Errno 2] for a complete install...
And the docker-compose - compatibility up which does nothing for a docker install...
And the fact that docker-compose.yml does not contain the info to modify ...

A little difficult to understand how to simply install the platform...

Is there any simple way to install the tool?

Thanks

**Comment by SamuelHassine** [comment]
Hello @weSh,

You can use the [OVA file](https://opencti-platform.github.io/docs/installation/auto) if you are not intend to use OpenCTI in production. Docker installation documentation has been updated and we really recommend to use Docker stack (part of the default Docker installation). Could you please provide the full log of the OpenCTI container and the Grakn container for debugging?

Thanks!

**Comment by AntoninHL** [comment]
Hey @SamuelHassine 

In fact, what I want to do is a production platform
I don't want to test this on my laptop. I know the tool. ;-)

I just remade a freshly installed machine.
I cloned docker.git and I started: docker-compose --verbose up

ERROR: compose.cli.main.main:
         Can't find a suitable configuration file in this directory or any
         parent. Are you in the right directory?

         Supported filenames: docker-compose.yml, docker-compose.yaml

while obviously the file is there...

I can even force the use of the conf file... same result...

**Comment by AntoninHL** [comment]
Forget the previous message...
I found the answer:
snap remove docker
apt-get install docker.io docker-compose
and reboot

Seems that there is an issue with docker installed via snap

But I still have a question: where in the docker-compose.yml file should I change the email, password and token variables.
I see a lot of calls to these variables, but nowhere to define them.

**Comment by AntoninHL** [comment]
So,
 I tried to create 3 variables here:

opencti:
    image: opencti/platform:latest
    environment:
      - OPENCTI_ADMIN_EMAIL=xxxxxx
      - OPENCTI_ADMIN_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxx
      - OPENCTI_ADMIN_TOKEN=xxxxxx-xxxxx-xxxxxx-xxxxxx

It seems that this is not a problem.
I'm starting ... but nothing seems to be open on port 8080

**Comment by richard-julien** [comment]
Hi @weSh , You can find a example of a complete docker compose file here https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml

Here a sub part of the file
```
 opencti:
    image: opencti/platform:latest
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
```

You can see here that we by default use system env variables to populate docker image configuration.
So you have multiple options:
- Setup directly some environment variables (OPENCTI_ADMIN_EMAIL ...)
- Create a .env file (see https://docs.docker.com/compose/environment-variables/) and put your configuration (OPENCTI_ADMIN_EMAIL, ...)
- Replace directly the values in the file, but be careful to replace everywhere is needed (opencti, connectors, ...)

Hope this help

**Comment by AntoninHL** [comment]
Thanks @richard-julien !

I created the variables directly in the file, and it seems to work.

But when I start, the dockers start well, but nothing more. And obviously no listening on the 8080.

**Comment by richard-julien** [comment]
Can you copy/paste the result of command 'docker ps' ? And also 'docker logs [ID OF THE OPENCTI DOCKER] ? Thanks

**Comment by weSh** [comment]
`CONTAINER ID        IMAGE                                                  COMMAND                  CREATED              STATUS                          PORTS                                                 NAMES
6306a39dedfa        opencti/worker:latest                                  "/entrypoint.sh"         32 seconds ago       Up 3 seconds                                                                          opencti_worker.3.gcold6a2jeatw5sfij1wxolmq
9a481b74983c        opencti/connector-import-file-stix:latest              "/entrypoint.sh"         41 seconds ago       Up 17 seconds                                                                         opencti_connector-import-file-stix.1.i9ga9psny5y9tl4syr1v3xbem
6eec5c1490ad        opencti/worker:latest                                  "/entrypoint.sh"         41 seconds ago       Up 12 seconds                                                                         opencti_worker.2.yi7vv3yer8b8ec7wcdv4hz6dc
aa39239f70ff        opencti/connector-import-file-pdf-observables:latest   "/entrypoint.sh"         47 seconds ago       Up 17 seconds                                                                         opencti_connector-import-file-pdf-observables.1.5yl3hx8e8p72wbbsobcpytp0y
5c57632067bd        opencti/worker:latest                                  "/entrypoint.sh"         About a minute ago   Up 13 seconds                                                                         docker_worker_1
18a6cee9325a        opencti/platform:latest                                "/entrypoint.sh"         About a minute ago   Restarting (1) 35 seconds ago                                                         docker_opencti_1
40ab299209c3        rabbitmq:3.7.17-management                             "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes                    4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   docker_rabbitmq_1
7ca533173a72        graknlabs/grakn:1.6.2                                  "./grakn-docker.sh"      2 minutes ago        Up 2 minutes                    0.0.0.0:48555->48555/tcp                              docker_grakn_1
8bde33e47197        opencti/connector-export-file-stix:latest              "/entrypoint.sh"         2 minutes ago        Up 25 seconds                                                                         docker_connector-export-file-stix_1
fbf7db222cb2        opencti/connector-import-file-stix:latest              "/entrypoint.sh"         2 minutes ago        Restarting (0) 25 seconds ago                                                         docker_connector-import-file-stix_1
d2b71ce58f64        docker.elastic.co/elasticsearch/elasticsearch:7.5.2    "/usr/local/bin/dock…"   2 minutes ago        Up 9 seconds                    9200/tcp, 9300/tcp                                    docker_elasticsearch_1
b48720aef44e        opencti/connector-import-file-pdf-observables:latest   "/entrypoint.sh"         2 minutes ago        Up 10 seconds                                                                         docker_connector-import-file-pdf-observables_1
a78bb5e8a342        redis:5.0.5                                            "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes                    6379/tcp                                              docker_redis_1
9afe84f33af0        minio/minio:RELEASE.2019-10-12T01-39-57Z               "/usr/bin/docker-ent…"   2 minutes ago        Up About a minute (healthy)     0.0.0.0:9000->9000/tcp                                docker_minio_1
247a7f3aa60d        opencti/connector-mitre:latest                         "/entrypoint.sh"         2 minutes ago        Restarting (0) 18 seconds ago                                                         docker_connector-mitre_1
cfc963265bfb        opencti/connector-export-file-csv:latest               "/entrypoint.sh"         2 minutes ago        Restarting (0) 31 seconds ago                                                         docker_connector-export-file-csv_1
295e883abf4a        opencti/connector-opencti:latest                       "/entrypoint.sh"         2 minutes ago        Restarting (0) 20 seconds ago                                                         docker_connector-opencti_1
3bee0ddd1fc1        rabbitmq:3.7.17-management                             "docker-entrypoint.s…"   About an hour ago    Up About an hour                4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   opencti_rabbitmq.1.teukkd5apu8ozgb80xmzlor22
0246f1eb1993        redis:5.0.5                                            "docker-entrypoint.s…"   About an hour ago    Up About an hour                6379/tcp                                              opencti_redis.1.06u1hbcxg33fhwrpxfwnugi7a`

**Comment by AntoninHL** [comment]
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED              STATUS                          PORTS                                                 NAMES
6306a39dedfa        opencti/worker:latest                                  "/entrypoint.sh"         32 seconds ago       Up 3 seconds                                                                          opencti_worker.3.gcold6a2jeatw5sfij1wxolmq
9a481b74983c        opencti/connector-import-file-stix:latest              "/entrypoint.sh"         41 seconds ago       Up 17 seconds                                                                         opencti_connector-import-file-stix.1.i9ga9psny5y9tl4syr1v3xbem
6eec5c1490ad        opencti/worker:latest                                  "/entrypoint.sh"         41 seconds ago       Up 12 seconds                                                                         opencti_worker.2.yi7vv3yer8b8ec7wcdv4hz6dc
aa39239f70ff        opencti/connector-import-file-pdf-observables:latest   "/entrypoint.sh"         47 seconds ago       Up 17 seconds                                                                         opencti_connector-import-file-pdf-observables.1.5yl3hx8e8p72wbbsobcpytp0y
5c57632067bd        opencti/worker:latest                                  "/entrypoint.sh"         About a minute ago   Up 13 seconds                                                                         docker_worker_1
18a6cee9325a        opencti/platform:latest                                "/entrypoint.sh"         About a minute ago   Restarting (1) 35 seconds ago                                                         docker_opencti_1
40ab299209c3        rabbitmq:3.7.17-management                             "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes                    4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   docker_rabbitmq_1
7ca533173a72        graknlabs/grakn:1.6.2                                  "./grakn-docker.sh"      2 minutes ago        Up 2 minutes                    0.0.0.0:48555->48555/tcp                              docker_grakn_1
8bde33e47197        opencti/connector-export-file-stix:latest              "/entrypoint.sh"         2 minutes ago        Up 25 seconds                                                                         docker_connector-export-file-stix_1
fbf7db222cb2        opencti/connector-import-file-stix:latest              "/entrypoint.sh"         2 minutes ago        Restarting (0) 25 seconds ago                                                         docker_connector-import-file-stix_1
d2b71ce58f64        docker.elastic.co/elasticsearch/elasticsearch:7.5.2    "/usr/local/bin/dock…"   2 minutes ago        Up 9 seconds                    9200/tcp, 9300/tcp                                    docker_elasticsearch_1
b48720aef44e        opencti/connector-import-file-pdf-observables:latest   "/entrypoint.sh"         2 minutes ago        Up 10 seconds                                                                         docker_connector-import-file-pdf-observables_1
a78bb5e8a342        redis:5.0.5                                            "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes                    6379/tcp                                              docker_redis_1
9afe84f33af0        minio/minio:RELEASE.2019-10-12T01-39-57Z               "/usr/bin/docker-ent…"   2 minutes ago        Up About a minute (healthy)     0.0.0.0:9000->9000/tcp                                docker_minio_1
247a7f3aa60d        opencti/connector-mitre:latest                         "/entrypoint.sh"         2 minutes ago        Restarting (0) 18 seconds ago                                                         docker_connector-mitre_1
cfc963265bfb        opencti/connector-export-file-csv:latest               "/entrypoint.sh"         2 minutes ago        Restarting (0) 31 seconds ago                                                         docker_connector-export-file-csv_1
295e883abf4a        opencti/connector-opencti:latest                       "/entrypoint.sh"         2 minutes ago        Restarting (0) 20 seconds ago                                                         docker_connector-opencti_1
3bee0ddd1fc1        rabbitmq:3.7.17-management                             "docker-entrypoint.s…"   About an hour ago    Up About an hour                4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   opencti_rabbitmq.1.teukkd5apu8ozgb80xmzlor22
0246f1eb1993        redis:5.0.5                                            "docker-entrypoint.s…"   About an hour ago    Up About an hour                6379/tcp                                              opencti_redis.1.06u1hbcxg33fhwrpxfwnugi7a

**Comment by AntoninHL** [comment]
docker logs docker_opencti_1
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1

**Comment by AntoninHL** [comment]
@richard-julien here are the copy/paste...
not sure it's very readable... :-(

**Comment by richard-julien** [comment]
Looks like the grakn container fail to start. Grakn can have some problem to start on docker when other process are part of the docker compose. A bug is open on grakn github. The current workaround for now is to try to start grakn alone in the compose and then add the other dependencies, or install grakn outside docker

**Comment by AntoninHL** [comment]
OK...
Never mind then.
I give up.
It's too bad it's so complicated to install the tool.
Version 1 and 2 seemed interesting to me. I'd done a lot of testing.

But now it's getting a little tedious.
My job is to do Threat Intelligence, not to dev in a docker.

Many Thanks again for all your help and time.

**Comment by SamuelHassine** [comment]
@weSh: We can help you to deploy OpenCTI on the machine. Just talk to me on Slack and I will be able to do that.

**Comment by richard-julien** [comment]
@weSh, like Samuel said, we are ready to help you more on that. OpenCTI have a lot of requirements and we try hard to make it simple to install (OVA, docker ...). I think your docker configuration should be good but for now the database (grakn) have sometimes some problem to start in a docker environment (see https://github.com/graknlabs/grakn/issues/5570).

**Comment by rupeshvirat** [comment]
hello @SamuelHassine @weSh ,

We are also trying to install openCTI for production use but we are facing issue i.e. APT is not reachable. 

We are try to fix this issue from last 3-4 days but hard luck.
Please help us on this to solve this problem.

Thanks

**Comment by richard-julien** [comment]
Please join the slack and start a conversation. Will try to help you

**Comment by rupeshvirat** [comment]
Hello @richard-julien 

Please help me out to how to join new slack

**Comment by richard-julien** [comment]
https://slack.luatix.org/

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity. If you have any questions regarding the OpenCTI deployment please feel free to join the Slack channel.
