### ISSUE TITLE
Be able to filter by countries/regions AND sectors

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#544]
## Problem to Solve

It would be useful to be able to view malicious activities (intrusion set targeting, malware targeting, campaigns, incidents etc.) according to both a certain sector and a region/country, ie. all intrusion sets targeting the retail sector in South East Asia, or all campaigns targeting the transportation sector in Europe...

## Current Workaround

It is possible from an intrusion set to view both the sectors it targets and the countries/regions, but to establish correspondence between those two types, you have to go to a report and view the knowledge in the graph.

It is today not possible from the sectors or from the regions tabs to filter with the other type.

## Proposed Solution

From the sector tab and from the region tab, be able to filter malicious activity depending the other type of data : maybe by adding in the knowledge view of the sector a tab on the right "region" which indicates all the regions/countries for which malicious activities in this sector were reported.

**Comment by SamuelHassine** [comment]
In the "overview" of the "knowledge" for identities and locations, add after the figures:

* all the "targets" relationships as a list, with filters such as: "also targeting X"  where X can be an identity or a location.
