### ISSUE TITLE
Observables / Indicators: Sighting

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#55]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It should be possible to associate sightings to observables/indicators:
We plan to use it to:
o	handle sightings from others (e.g. MISP) and push (our) sightings to MISP
o	handle sightings generated by CERT-EU SOC based on their alerts generated from the use of observables

## Current Workaround

N/A

## Proposed Solution

The sighting information should include:
- date (when the sighting was observed)
- organisation (where the sighting was observed)
- type (false positive, true positive)
- count (how many FP, TP)

## Additional Information

N/A

**Comment by alidhamieh** [comment]
@Fred-certeu I cannot see the observed-data objects of sighting in OpenCTI GUI. Attached you can see "sighted in/at" relationship but not observed-data relationships (observed_data_refs). Below is the sighting that was sent using OpenCTIConnectorHelper python client. 
`{'type': 'sighting', 'spec_version': '2.1', 'id': 'sighting--e7b10990-9460-45d3-8ad7-344670a8dd74', 'created_by_ref': 'identity--c5456c97-cf65-5abf-85d5-2fb443c51624', 'created': '2021-12-02T15:28:20.204566Z', 'modified': '2021-12-02T15:28:20.204572Z', 'first_seen': '2021-12-02T15:28:20.204578Z', 'last_seen': '2021-12-02T15:28:20.204598Z', 'count': 1, 'sighting_of_ref': 'indicator--70e9d0ae-d0ad-53b9-bb4c-4ccaf9bb60cf', 'observed_data_refs': ['observed-data--5d001ce9-2451-436e-a334-2852ed3c6241', 'observed-data--6c834f95-6db6-4168-9162-7430a5105b48', 'observed-data--759561bc-5b20-40aa-ab16-1bc5af80f2c5', 'observed-data--784fe39b-9b14-4c8f-b8ff-c45323771505', 'observed-data--13b062e2-a851-424e-b472-4db597aec394', 'observed-data--16f7cecd-ce8f-4503-8fe7-c3ef541de8df', 'observed-data--e56e1642-acc7-45c8-9c26-0e4b080e3b8d', 'observed-data--f2c6870c-67fa-42c2-ba3d-6a7d070d2076', 'observed-data--e13b10de-5dca-4d1b-80dd-c4aa7d3cd01a'], 'where_sighted_refs': ['identity--234bb226-94b8-4b78-b3f6-3414d1f55a10']}`
<img width="797" alt="sighting" src="https://user-images.githubusercontent.com/66278376/144456899-6a755142-10ec-42eb-af5b-0384b41a7e5e.PNG">
What is the issue? I am suspecting OpenCTI does not implement the observed-data (observed_data_refs) relationships for sighting in GUI or anything wrong with my sighting json fields or maybe i can see the observed-data of sighting in different dashboard?
