### ISSUE TITLE
Direct support of HTTPS instead of using a proxy

### ISSUE THREAD

**Issue by powerade661** [OpenCTI-Platform/opencti#550]
How would I do this? Is there a way?

**Comment by richard-julien** [comment]
Hi @powerade661, today the only way is to use an nginx or other http proxy handle this problem. 

I flag your ticket as a feature request.

**Comment by richard-julien** [comment]
Note for later: https://timonweb.com/posts/running-expressjs-server-over-https/

**Comment by powerade661** [comment]
I see. So I'd need to run it under nginx on top of openCTI to add SSL? I am just looking to add an SSL certificate so my passwords aren't in plain text when I login.

**Comment by richard-julien** [comment]
You need to run an nginx with SSL and configure it to redirect to your openCTI instance. https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/ could help

**Comment by powerade661** [comment]
Ah I see. No worries, I can definitely do that! I thought there was a way to add HTTPS directly to the webapp itself. Apologies.

**Comment by richard-julien** [comment]
No yet. I rename your ticket and add the flag feature request.

**Comment by bLackCat-79** [comment]
Is it allready possible now?

**Comment by lnfernux** [comment]
> Is it allready possible now?

It's supposed to be, but I can't get it to work. 

Tried changing `app.port` to `443` and added the `https_certs` node with `key`, `crt` and `reject_unauthorized` filled out (two first pointing to key + signed cert). Then updated worker url (`/worker/config.yml`) to `http://localhost:443`. 

This didn't work, so tried changing the worker url around (https, added domain A record and pointed to https://example.com, https://example.com:443). Also tried changing the port in the configuration file back to 8080 or 4000, and played around with a bunch of settings.

Setting the app.port to 8080 and the worker url to https://example.com with the app.base_url to "https://example.com" actually redirects you to a https site, but it just doesn't forward you to the correct destination.

Any chance for an example config of working https/ssl setup @richard-julien
