### ISSUE TITLE
Create a new inference - part-of type

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#553]
## Problem to Solve

An inference of the type "if A belongs to B which belongs to C, then A belongs to C" would be very useful. For instance, today, if you have an embassy belonging to a specific MFA belonging to the Diplomacy sector, the embassy does not automatically belong to the diplomatic sector.

## Current Workaround

Link directly entity A to entity C as well as with entity B, but makes artificial links (add a second occurrence of entity C which is not wished for)

**Comment by SamuelHassine** [comment]
Rule has been added:

![image](https://user-images.githubusercontent.com/1334279/93071696-c041b580-f680-11ea-8653-e2e39c819f2d.png)

**Comment by SamuelHassine** [comment]
The rule has been added: 

![image](https://user-images.githubusercontent.com/1334279/93071780-da7b9380-f680-11ea-8a88-174961526271.png)
