### ISSUE TITLE
error: [OPENCTI] GraphQL initialization fail > Error: [ADMIN_SETUP] You need to configure the environment vars

### ISSUE THREAD

**Issue by xiangzi-007** [OpenCTI-Platform/opencti#558]
## Description

yarn cannot start opencti, what is ADMIN_SETUP var?
the error log: 
**error: [OPENCTI] GraphQL initialization fail > Error: [ADMIN_SETUP] You need to configure the environment vars**

## Environment

1. OS: Ubuntu 18.04 x64
2. OpenCTI version: 3.0.3
3. OpenCTI client: python
4. Other environment details:

config/production.json:
{
  "app": {
    "port": 4000,
    "logs": "./logs",
    "logs_level": "info",
    "reactive": true,
    "cookie_secure": false,
    "base_path" : "",
    "default_roles": [],
    "admin": {
      "email": "admin@opencti.io",
      "password": "ChangeMe",
      "token": "**10c54549-b141-423c-9c83-c32297f9f6a9**"
    }
  },
  "grakn": {
    "hostname": "localhost",
    "port": 48555,
    "timeout": 30000
  },
  "redis": {
    "hostname": "localhost",
    "port": 6379
  },
  "elasticsearch": {
    "url": "http://localhost:9200",
    "noQueryCache": false
  },
  "minio": {
    "endpoint": "localhost",
    "port": 9000,
    "use_ssl": false,
    "access_key": "ChangeMe",
    "secret_key": "ChangeMe"
  },
  "rabbitmq": {
    "hostname": "localhost",
    "port": 5672,
    "port_management": 15672,
    "management_ssl": false,
    "username": "guest",
    "password": "guest"
  },
  "providers": {
    "facebook": {
      "client_id": "xxxxxx",
      "client_secret": "xxxxxx",
      "callback_uri": "http://localhost:4000/auth/facebook/callback"
    },
    "google": {
      "client_id": "xxxxxx",
      "client_secret": "xxxxxx",
      "callback_uri": "http://localhost:4000/auth/google/callback"
    },
    "github": {
      "client_id": "xxxxxx",
      "client_secret": "xxxxxx",
      "callback_uri": "http://localhost:4000/auth/github/callback"
    }
  }
}

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run ES, redis, rabbitmq, minio, grakn, e.g
2. run: yarn serv

## Expected Output

opencti  start successfully.

## Actual Output

ubuntu@linux:~/opencti$ sudo yarn serv
[sudo] ubuntu password： 
yarn run v1.22.0
$ node --max_old_space_size=8192 build/index.js
info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
info: [PRE-CHECK] > Python3 is available
info: [INIT] > Grakn schema loaded
info: [INIT] > Elasticsearch indexes loaded
info: [MIGRATION] > Starting migration process
info: [MIGRATION] > Read 0 migrations from the database
info: [MIGRATION] > Migration process completed, platform is up to date
info: [ADMIN_SETUP] Initialize admin user
error: [OPENCTI] GraphQL initialization fail > Error: [ADMIN_SETUP] You need to configure the environment vars
    at v (/home/ubuntu/opencti/build/index.js:1:90332)
    at /home/ubuntu/opencti/build/index.js:1:731492
    at n.a (/home/ubuntu/opencti/build/index.js:1:731506)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/ubuntu/opencti/build/index.js:1:732320
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
## Additional information

NO

**Comment by richard-julien** [comment]
Hi @xiangzi-007 , you have to change the value of the password to "changeMe" to something you want. To be secure by default we doesn't want to really provide a default password.

**Comment by xiangzi-007** [comment]
Yes, it works. Thanks.
