### ISSUE TITLE
Syntax validation of observables

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#56]
## Problem to Solve

Avoid errors in devices consuming observables coming from opencti

## Current Workaround

N/A

## Proposed Solution

Validate syntax in the import process, at least for:
o	IP addresses
o	domain names
o	URL/URI
o	hash values
o	email addresses

## Additional Information

N/A

**Comment by SamuelHassine** [comment]
Syntax validation for indicators is #632.
