### ISSUE TITLE
[Connectors] TypeError when "Listing Threat-Actors with filters null"

### ISSUE THREAD

**Issue by toshiro92** [OpenCTI-Platform/opencti#561]
## Description

When I've upgraded to version `3.0.3`, all connectors gave the same error message, and always restart their own container.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 3.0.3
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn first and remove it from the original docker-compose.yml (To avoid failure on Grakn through docker-compose)
2. Execute the docker-compose.yml (Without default connectors)
3. Check every logs of all running containers:
- Redis
- Connector-OpenCTI
- Worker
- openCTI
- RabbitMQ
- Grakn
- Minio (Unhealthy)
4. OpenCTI is up and running, but complains about the following:

`error: [OPENCTI] Technical error > Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile." {"locations":[{"line":3,"column":17}],"path":["registerConnector"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"cause":{},"isOperational":true,"stacktrace":["Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"","    at afterStartOk (/opt/opencti/node_modules/amqplib/lib/connection.js:220:12)","    at /opt/opencti/node_modules/amqplib/lib/connection.js:160:12","    at Socket.recv (/opt/opencti/node_modules/amqplib/lib/connection.js:499:12)","    at Object.onceWrapper (events.js:299:28)","    at Socket.emit (events.js:210:5)","    at emitReadable_ (_stream_readable.js:575:12)","    at processTicksAndRejections (internal/process/task_queues.js:79:21)"]}}}
`

AND

`error: [REDIS] An error occurred on redis > getaddrinfo ENOTFOUND opencti_redis {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"opencti_redis","stack":"Error: getaddrinfo ENOTFOUND opencti_redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}`

5. As OpenCTI still running, launch all connectors.
6. All connectors complain about the same issue:
```
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:An unknown error has occurred!  Please try again later.
'NoneType' object is not subscriptable
```
And ipinfo connector provide a little bit more information with:

```
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:An unknown error has occurred!  Please try again later.
Traceback (most recent call last):
  File "ipinfo.py", line 108, in <module>
    ipInfoInstance = IpInfoConnector()
  File "ipinfo.py", line 20, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 189, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_connector.py", line 61, in register
    return result["data"]["registerConnector"]
TypeError: 'NoneType' object is not subscriptable
```

## Expected Output

Connectors are up, running, and collect data for OpenCTI.

## Actual Output

See **Reproductible steps**.
 
## Additional information

Not Yet

**Comment by SamuelHassine** [comment]
@toshiro92 please can you copy/paste here your `docker-compose.yml` file?

**Comment by SamuelHassine** [comment]
@toshiro92: 

The error: 

```
error: [OPENCTI] Technical error > Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile." {"locations":[{"line":3,"column":17}],"path":["registerConnector"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"cause":{},"isOperational":true,"stacktrace":["Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\""," at afterStartOk (/opt/opencti/node_modules/amqplib/lib/connection.js:220:12)"," at /opt/opencti/node_modules/amqplib/lib/connection.js:160:12"," at Socket.recv (/opt/opencti/node_modules/amqplib/lib/connection.js:499:12)"," at Object.onceWrapper (events.js:299:28)"," at Socket.emit (events.js:210:5)"," at emitReadable_ (_stream_readable.js:575:12)"," at processTicksAndRejections (internal/process/task_queues.js:79:21)"]}}}
```

means that OpenCTI is unable to access to RabbitMQ with the provided credentials. Please double check your RabbitMQ username/password both in the OpenCTI platform container and the RabbitMQ container.

**Comment by SamuelHassine** [comment]
@toshiro92:

The error:
```
error: [REDIS] An error occurred on redis > getaddrinfo ENOTFOUND opencti_redis {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"opencti_redis","stack":"Error: getaddrinfo ENOTFOUND opencti_redis\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)"}
```

means that the Redis Server is not up and running, please double check the status of the Redis container and the hostname you provide in your OpenCTI container configuration.

**Comment by toshiro92** [comment]
Ok I've seen the problem: I forgot the `container_name` option for redis in my `docker-compose.yml` file.

In my modified `docker-compose.yml` file, I'm using the `container_name` to set a specific name for each container. It is also necessary when you need to declare this name in the Docker DNS.

However, this setting is not compatible with `Stack deploy` command provided in the README.md file, as follow:

> env $(cat .env | grep ^[A-Z] | xargs) docker stack deploy --compose-file docker-compose.yml opencti

However, you can bypass this issue by direclty use the classic docker-compose command with the .env configuration file in the same folder: Docker-compose will automatically recognize and use it:

> docker-compose up --compatibility -d

Thank you anyway ;-)
