### ISSUE TITLE
How to upgrade from ver 3.0.2 to 3.0.3

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#562]
Hi,
thank you in providing VM ready instance. 
I am running your provided VM ver 3.0.2 and how do I upgrade this to 3.0.3?

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

We will provide a new image for the 3.0.3 but if you want to upgrade your current VM, just go to `/opt/opencti`, edit the `docker-compose.yml` file and bump all versions to 3.0.3.

**Comment by SamuelHassine** [comment]
The virtual machine template has been rewritten in V4. Upĝrade is now very easy.
