### ISSUE TITLE
[observables did  not incresase] 

### ISSUE THREAD

**Issue by revermaru** [OpenCTI-Platform/opencti#567]
Greetings
I have installed opencti latest version using docker.
(with default docker-compose.yml configuration, changing uuidv4 key values)
so , connector is well done, Total entities value is 4.6K
but Total observables , last observables did  not incresase. (current value 0)
What more should I check? Let me know Plz
Thanks your greate job

**Comment by SamuelHassine** [comment]
Hello @revermaru,

Which connectors have you enabled on your platform?

**Comment by revermaru** [comment]
> 
> 
> Hello @revermaru,
> 
> Which connectors have you enabled on your platform?

connectors in docker-compose.yml is
    image: opencti/connector-export-file-stix:3.0.3
    image: opencti/connector-export-file-csv:3.0.3
    image: opencti/connector-import-file-stix:3.0.3
    image: opencti/connector-import-file-pdf-observables:3.0.3
    image: opencti/connector-opencti:3.0.3
    image: opencti/connector-mitre:3.0.3

**Comment by SamuelHassine** [comment]
@revermaru: the connectors you enabled do not provide any indicator or observable:

- image: opencti/connector-export-file-stix:3.0.3: export to STIX feature
- image: opencti/connector-export-file-csv:3.0.3: export to CSV feature
- image: opencti/connector-import-file-stix:3.0.3: import STIX file from the UI
- image: opencti/connector-import-file-pdf-observables:3.0.3: import PDF file from the UI
- image: opencti/connector-opencti:3.0.3: import sectors/countries/regions
- image: opencti/connector-mitre:3.0.3: import MITRE ATT&CK dataset (intrusion sets, attack patterns, etc.)

So it is normal that observables do not increase.

**Comment by revermaru** [comment]
thanks for reply
so..
What should I add connector ?  
Do I need to develop it myself?
Or do you have a connector to refer to?

**Comment by SamuelHassine** [comment]
@revermaru I do not understand your question, it depends on what is your purpose using OpenCTI. What are you trying to do? What is your use case?

**Comment by revermaru** [comment]
I'm sorry to bother you.
I found the information I needed on the link below. ^__^
https://github.com/OpenCTI-Platform/connectors
Maybe if I apply the external_import connector, the problem will be solved.
Thank you for sharing a good project.
