### ISSUE TITLE
GraphQL result has only 200 nodes

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/opencti#570]
## Description

GraphQL result has only 200 nodes
## Environment

1. OS (where OpenCTI server runs): { CentOS7}
2. OpenCTI version: { 3.0.3 }
3. OpenCTI client: { frontend }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Playground with Graphql
2. Exec
`{
	stixObservables{
    edges{
      node{
        id
        name
        parent_types
        description
      }
    }
  }
}
`

3. Json output has only 200 nodes
## Expected Output

I see 7.9k entities Observables in tab Signatures, so I expect more nodes in the results. The result also has only 200 nodes if I use Query.indicators.

**Comment by phucsnguyenv** [comment]
Forget to add this, I also use curl to save the output to txt file but I still can get only 200 nodes. 
Not sure if I doing it the right way. 
Thanks for looking at this.

**Comment by SamuelHassine** [comment]
Hello @phucsnguyenv,

You have to use pagination parameters if you want to have more results. You can set a higher limit using the `first` parameter (default is 200). If you want to use pagination, please look at the `first` and the `after` parameters. Please refer to the [GraphQL pagination documentation](https://graphql.org/learn/pagination/), think about 

```
"pageInfo": {
  "endCursor": "Y3Vyc29yMw==",
  "hasNextPage": false
}
```
Do not hesitate to ask questions.

**Comment by phucsnguyenv** [comment]
> Hello @phucsnguyenv,
> 
> You have to use pagination parameters if you want to have more results. You can set a higher limit using the `first` parameter (default is 200). If you want to use pagination, please look at the `first` and the `after` parameters. Please refer to the [GraphQL pagination documentation](https://graphql.org/learn/pagination/), think about
> 
> ```
> "pageInfo": {
>   "endCursor": "Y3Vyc29yMw==",
>   "hasNextPage": false
> }
> ```
> 
> Do not hesitate to ask questions.

It really helps Samuel. Thank you!!!
