### ISSUE TITLE
Filters entities in relational graph of report knowledge

### ISSUE THREAD

**Issue by I-Iugo** [OpenCTI-Platform/opencti#574]
## Problem to Solve

For a better reading it would be good to be able to have filters on the entities present in the graph. Maybe link to #41 issue

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/7288882/77080778-0253ac80-69fa-11ea-8329-7fd03718da08.png">

## Current Workaround

None

## Proposed Solution

The solution would be to set up filters by entity types: Malware, Intrusion-set, ...

If we filter an entity B included between 2 entities A and C then we could imagine having a link of inference in the form of a dotted line.

**Comment by Fred-certeu** [comment]
This feature would be great.
Some times the graphs are simply impossible to read (e.g. when there are tons of indicators linked to a malware, for example)
