### ISSUE TITLE
Docker fail to start OpenCTI API

### ISSUE THREAD

**Issue by stephent23** [OpenCTI-Platform/opencti#580]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ I believe that this issue is similar to #322 where the docker image fails to run. The error when running docker-compose --compatibility up is that the OpenCTI API has failed to start. }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu Server and MacOS }
2. OpenCTI version: { 3.0.3 }
3. OpenCTI client: { frontend }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Following the instructions here: https://opencti-platform.github.io/docs/installation/auto#clone-the-repository

## Expected Output

{ The UI to be accessible. However the containers fail to load and continually restart. }

## Actual Output

{ 
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/8761562/77916405-ef11ce00-7290-11ea-8288-f2c519158f1e.png">
}
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by richard-julien** [comment]
Hi @stephent23 , can you check the grakn docker logs to see if the storage success to start?

**Comment by stephent23** [comment]
Hi @richard-julien, thanks for coming back to me. I did that and it had failed so I tried restarting; this failed a number of times but on the 5th/6th attempt seemed to work. Is there anything that may have caused this in my configuration specifically, or is this a known issue?

**Comment by SamuelHassine** [comment]
@stephent23 it is a known issue with Grakn and should be resolved in the next release. If the 3.3.0 of OpenCTI did not solve it, please re-open this issue.
