### ISSUE TITLE
Token configuration must be the same as APP__ADMIN__TOKEN

### ISSUE THREAD

**Issue by MRDJR97** [OpenCTI-Platform/opencti#592]
## Description

I am trying to install on Ubuntu server 18.04 using docker.
When I run the 'docker-compose --compatibility up' command it throws an error for each worker.

"Token configuration must be the same as APP__ADMIN__TOKEN"
ValueError: Token configuration must be the same as APP__ADMIN__TOKEN

I am getting a valid UUID, and pasting it in as the value (with no spaces or quotes) for APP__ADMIN__TOKEN and for each OPENCTI_TOKEN placeholder. 
Am I doing something wrong?

## Environment

1. OS (where OpenCTI server runs): Ubuntu server 18.04 
2. OpenCTI version: OpenCTI 3.1.0
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Try to install using docker, changing the UUID values

## Expected Output

I expected it to work, I know you're supposed to change the configuration of OPENCTI_TOKEN to the same value as the UUID, but it isn't working.

## Actual Output

Token config error thrown

**Comment by richard-julien** [comment]
Duplicated https://github.com/OpenCTI-Platform/opencti/issues/604

**Comment by parmarth-1208** [comment]
I'm trying to manually install opencti to my linux os and I'm getting the below error, how can i resolve this please help me with it:
$ python3 worker.py
Traceback (most recent call last):
File "/home/parmarth/project/opencti/worker/worker.py", line 466, in
worker = Worker()
^^^^^^^^
File "", line 6, in init
File "/home/parmarth/project/opencti/worker/worker.py", line 385, in post_init
self.api = OpenCTIApiClient(
^^^^^^^^^^^^^^^^^
File "/home/parmarth/project/opencti/src/python/venv/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 126, in init
raise ValueError("A TOKEN must be set")
ValueError: A TOKEN must be set
