### ISSUE TITLE
Docker installation failures due to Grakn

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#603]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Numerous people have described issues with the current Docker install some of which are related to Grakn. I've seen suggestions such as run grakn as a separate container or on the host. 

However, if I do 

1. docker exec -it {opencti containerID} sh
2. cd /opt/opencti
3. yarn serv

Everything works as it should. I realize that this is not total automation. And I have thought about trying to add the following to the opencti platform service:

    command: >
          /bin/sh -c "
          while ! nc -z grakn 48555;
          do
            echo sleeping;
            sleep 1;
              done;
              echo Connected!;
            "  
 But it is one simple suggestion for a temporary fix.

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: 3.1.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. docker-compose up -d
2. attempt to login with default credentials

## Expected Output

Dashboard should appear

## Actual Output

Login page does not error out but you remain at login page.
 
## Additional information

docker logs {openctl-platform}

$ node --max_old_space_size=8192 build/index.js
{"code":14,"metadata":{"_internal_repr":{},"flags":0},"details":"failed to connect to all addresses","level":"error","message":"[GRAKN] Seems down > 14 UNAVAILABLE: failed to connect to all addresses","stack":"Error: 14 UNAVAILABLE: failed to connect to all addresses\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/opt/opencti/node_modules/grpc/src/client_interceptors.js:847:24)"}
{"message":"[OPENCTI] GraphQL initialization fail > Error: Grakn seems down\n    at /opt/opencti/build/index.js:1:4871\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/opencti/build/index.js:1:128547\n    at async n.b (/opt/opencti/build/index.js:1:128531)\n    at async /opt/opencti/build/index.js:1:858301","level":"error"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

docker logs {grakn}

Grakn Started

**Comment by richard-julien** [comment]
Hi @smclinden , sometimes grakn fail to start in a container environment and it seems related to the amount of io/process of other containers starting a the same time. So we recommend to start grakn alone in another stack to mitigate this problem. Maybe sleeping the process can help but i dont want to put some specific code in opencti to fix issue on dependencies. An issue is open on grakn https://github.com/graknlabs/grakn/issues/5570 for that.

**Comment by smclinden** [comment]
Understood. I, actually, found some other issues with the Docker version so I've been swapping out the container services for native hosted services and that seems to make things run a lot smoother.
