### ISSUE TITLE
Not seeing all the icons in the left sidebar

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#605]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

In the video tutorials and screenshots for OpenCTI there are a large number of icons in the left sidebar  including what looks to be a Database icon. But in my Docker instance the only icons are:

Dashboard
Threats
Techniques
Signatures
Reports
Entities

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: 3.1.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run docker-compose --compatibility up

## Expected Output

Dashboard that appears in tutorials and documentation.

## Actual Output

See above.
 
## Additional information

<img width="327" alt="Screen Shot 2020-04-06 at 10 38 20 AM" src="https://user-images.githubusercontent.com/8810661/78571124-d60a9f00-77f3-11ea-9ce5-ffe5b4dc9cb1.png">

**Comment by richard-julien** [comment]
Hi @smclinden , looks like your user doesn't have the admin capability. You just bootstrap a fresh platform and logged in as admin user? Can you try to access /dashboard/settings/accesses/users and see what happens? Thanks

**Comment by smclinden** [comment]
Thanks. That did it.

I looked through the documentation but I didn't see this though I figured that roles was, likely, the issue.

**Comment by richard-julien** [comment]
We include a protection for the admin user to always be able to recover from an invalid role configuration. So some part of the screen are not visible according to the role configuration but under the hood the admin user is still granted.
