### ISSUE TITLE
Release of 3.1.0 have incorrect node_modules directory

### ISSUE THREAD

**Issue by powerade661** [OpenCTI-Platform/opencti#606]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.03
2. OpenCTI version: 3.0.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upgrade from 3.0.3 to 3.1.0
2. Run yarn serv
3. Error

![image](https://user-images.githubusercontent.com/10760510/78707374-21957980-78d6-11ea-96d7-9db95ec496a3.png)

## Expected Output
1. Upgrade from 3.0.3 to 3.1.0 
2. Run yarn serv 
3. No error 

![image](https://user-images.githubusercontent.com/10760510/78707540-5a355300-78d6-11ea-834e-e1ef6eebb651.png)

## Actual Output

![image](https://user-images.githubusercontent.com/10760510/78707374-21957980-78d6-11ea-96d7-9db95ec496a3.png)

 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello,

Please re-run `yarn install` after upgrading the platform.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
It seems that you do not upgrade all your files, especially the `node_modules` directory.

**Comment by powerade661** [comment]
So I redownloaded everything and ran yarn install and here is the output I get now. There has to be something I am missing, I don't remember having this much trouble with 3.0.3

![image](https://user-images.githubusercontent.com/10760510/78708807-51458100-78d8-11ea-9dab-aecd8abab5aa.png)

**Comment by richard-julien** [comment]
Looks like the tar.gz of the release if not correct @SamuelHassine .

**Comment by powerade661** [comment]
Thanks again for your help with this guys.

**Comment by SamuelHassine** [comment]
Hello @powerade661,

Thanks for this bug report, good catch! I just re-uploaded a correct package with fixed node_modules in https://github.com/OpenCTI-Platform/opencti/releases/tag/3.1.0.

Now it is working!

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Could you please confirm your problem has been solved?

**Comment by powerade661** [comment]
Am I testing the 3.1.0_musl one?

**Comment by SamuelHassine** [comment]
No, `musl` is the one you had problem with (designed to be run on Linux without glibc). You have to re-download the default package.

**Comment by powerade661** [comment]
It works, no issues at all. Thank you for the quick patch!
