### ISSUE TITLE
Capabilities Missing in User Roles Feature.

### ISSUE THREAD

**Issue by powerade661** [OpenCTI-Platform/opencti#607]
## Description

When an admin attempts to assign roles, no capabilities are displayed to the admin to assign.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 3.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings
2. Accesses (2nd tab)
3. Choose Roles
4. Hit the Plus button
5. Create a role

## Expected Output

Roles capabilities are available to select.

## Actual Output

![image](https://user-images.githubusercontent.com/10760510/78721096-83f97480-78ec-11ea-931d-22cc051372f6.png)

**Comment by SamuelHassine** [comment]
Hello @powerade661,

The bugx #606 has been fixed. I think your problem of capabilities comes from a non-initialized platform. Please reset your ElasticSearch and your Grakn (remove all data or volumes) and start again.

Tell me if this works.

Kind regards,
Samuel

**Comment by powerade661** [comment]
I think I know how to do that with grakn (grakn clean), but not elasticsearch. Can you give me instructions on how to do this?

**Comment by SamuelHassine** [comment]
You have manually deploy Grakn and ElasticSearch or within Docker?

**Comment by powerade661** [comment]
Manually deployed both grakn and elasticsearch

**Comment by SamuelHassine** [comment]
For Grakn:
1. Stop Grakn
2. rm -Rf /opt/grakn/server/db/*
3. Start Grakn

For ElasticSearch:
1. Stop ElasticSearch
2. rm -Rf /var/lib/elasticsearch/*
3. Start ElasticSearch

**Comment by SamuelHassine** [comment]
Ok, capabilities are now in the platform?

**Comment by powerade661** [comment]
That fixed it. I am getting an interesting error with cryptolaemus. 
![image](https://user-images.githubusercontent.com/10760510/78724930-0e91a200-78f4-11ea-977c-da43acdfff1b.png) 

I can see the indicators in OpenCTI, but just thought I'd bring this to your attention as well.

**Comment by SamuelHassine** [comment]
Ok, those errors are not related to this issue and I think it is not critical. If you see content that is not in the platform or inconsistency, feel free to open another ticket. Thanks again for helping us on this issue.
