### ISSUE TITLE
Attribute Error Preventing Connectors From Creating Observables

### ISSUE THREAD

**Issue by powerade661** [OpenCTI-Platform/opencti#608]
## Description

When attempting to add data which is supposed to add an observable, it throws an Atrribute error. It only adds as an indicator. 

## Environment

1. OS (where OpenCTI server runs): 18.04
2. OpenCTI version: 3.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run any connector that adds observables, for example the MISP connector was ran here.

2. Error thrown 
![image](https://user-images.githubusercontent.com/10760510/78732087-3fc79d80-7907-11ea-9832-b82edf174cbf.png)

## Expected Output

Data is added and shown in observables

## Actual Output

There is no data in observables.

![image](https://user-images.githubusercontent.com/10760510/78732098-49e99c00-7907-11ea-91f1-04132c31bab3.png)

![image](https://user-images.githubusercontent.com/10760510/78732375-23783080-7908-11ea-860f-cd99d62ecece.png)

![image](https://user-images.githubusercontent.com/10760510/78732333-04799e80-7908-11ea-80d3-9a3039ef7999.png)

**Comment by SamuelHassine** [comment]
The V4 will solve this.
