### ISSUE TITLE
Organisation : associated IP addresses, domain names, URL-s

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#61]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Detect if ingested IP addresses, domain names or URL-s match with those owned by organisations handled in the OpenCTI platform

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Possibility to associate one or more IP addresses, domain names, URL-s owned by organisations handled in the platform

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Done, relations can now be added in the "Enrichment part" of each observable.
