### ISSUE TITLE
Support Azure AD integration

### ISSUE THREAD

**Issue by Stoffe** [OpenCTI-Platform/opencti#614]
## Problem to Solve

Support Azure AD integration

## Current Workaround

None

## Proposed Solution

Support Azure AD

**Comment by SamuelHassine** [comment]
Link: https://github.com/AzureAD/passport-azure-ad

**Comment by richard-julien** [comment]
Not sure its needed. At the end it looks like to be an OIDCStrategy.
Can you try to configure your azureAD using openID @Stoffe ?

**Comment by richard-julien** [comment]
Looking into passport azure ad

`This library contains two strategies: OIDCStrategy and BearerStrategy.`

So looks like is really not needed. Closing the issue.
Feel free to reopen if i have misunderstood something.
