### ISSUE TITLE
GraphQL initialization fail

### ISSUE THREAD

**Issue by Woody90** [OpenCTI-Platform/opencti#621]
I have installed OpenCTI manually. And now, I am trying to run "**yarn serv**", but I keep getting this error: _**{"message":"[OPENCTI] GraphQL initialization fail > Error: connect ECONNREFUSED 127.0.0.1:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)","level":"error"}**_

Error screenshot attached.
Production.json attached

[Production.json.txt](https://github.com/OpenCTI-Platform/opencti/files/4477340/Production.json.txt)

![OpenCTI Error](https://user-images.githubusercontent.com/6297379/79265940-268a9800-7e97-11ea-90d6-5880057e9b92.PNG)

**Comment by SamuelHassine** [comment]
Hello @Woody90, this message means that OpenCTI is not able to connect to Minio (localhost on port 9000).

**Comment by Woody90** [comment]
Thanks Samuel.
I fixed the minio issue, and I got below output on server side. I think everything is supposed to work fine.
Yet, when I opened the web page on browser, it did not load, and nothing was viewed, as shown below.

Notes: 
I tried different browser, and got the same result.
Also same result on both ports 80 & 4000 (production.json was edited accordingly)

![OpenCTI2](https://user-images.githubusercontent.com/6297379/79369916-066bdf00-7f52-11ea-8799-b3c1ff08eaff.PNG)

![OpenCTI3](https://user-images.githubusercontent.com/6297379/79369927-0bc92980-7f52-11ea-9b75-762e01822a97.PNG)

**Comment by SamuelHassine** [comment]
Can you please give us the output of the Chrome Developer Console when you try to reach the IP on the port 80?

**Comment by rbnor** [comment]
> Thanks Samuel.
> I fixed the minio issue

How did you fix the issue? Im having the same issue, except im using docker. and get the error message with the ip of the docker.  172.20.0.13

**Comment by Woody90** [comment]
> 
> 
> > Thanks Samuel.
> > I fixed the minio issue
> 
> How did you fix the issue? Im having the same issue, except im using docker. and get the error message with the ip of the docker. 172.20.0.13

I just made sure that minio service is running

**Comment by Woody90** [comment]
It worked now.
Thanks Samuel
