### ISSUE TITLE
Connector Performance

### ISSUE THREAD

**Issue by gaelmuller** [OpenCTI-Platform/opencti#623]
## Description

What kind of performance should be expected for data import from connectors ? We are looking at the possibility to create a connector but are wondering about import performance.

On a local instance (v3) run with docker-compose, it took about 5 hours to ingest the base data (12K objects, mainly ATT&CK I suppose).

Is this normal behavior or is there an issue with our setup ?

**Comment by SamuelHassine** [comment]
Hello @gaelmuller, this is the normal behavior if you dont follow the infrastructure requirements. The ingestion speed is independent from OpenCTI but is based on write speed of your Grakn server and your ElasticSearch cluster. We will improve this in the future.

The connector you want to create will inject a lot of data? Which kind of data you want to import?

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity. We improved the performances in the 3.3.0. Please re-open if you still encounter some problems.
