### ISSUE TITLE
Yarn Serv gives connection failed  error

### ISSUE THREAD

**Issue by ganarul** [OpenCTI-Platform/opencti#624]
## Description

{Yarn serv gives connection failed error with grakn and redis . }

## Environment

1.Linux debian based 
2. OpenCTI 3.0.3

whenever i run "yarn serv"
it says ERR_CONNECTION with redis and grakn 
already both the servers are running 
please find the attached file 
![yarn_serv2](https://user-images.githubusercontent.com/63349664/79313501-1073ea80-7f1e-11ea-8db6-f2f3dd1e3c6c.png)

**Comment by richard-julien** [comment]
Can you check if your servers are really accessible from localhost? Looks like they dont.

**Comment by ganarul** [comment]
I checked all the server are running fine . Only this opencti is not running . By default the opencti runs in 8080 port , am I correct
http://localhost:8080 
nothing is coming

**Comment by SamuelHassine** [comment]
The error messages are pretty clear here, your dependencies are not reachable on localhost, from your VM, could you try something like:

`telnet localhost 6379`

Is this leads to a successful connection?

**Comment by richard-julien** [comment]
Close for inactivity. Please open another ticket if you still have some issue
