### ISSUE TITLE
OpenCTI Interface Content is not Loading

### ISSUE THREAD

**Issue by Woody90** [OpenCTI-Platform/opencti#626]
#213  Description

When I opened the web page on browser, it did not load, and nothing was viewed, as shown below.

## Environment

1. OS: Ubuntu 18.04 LTS
2. OpenCTI version: 3.1.0 
3. OpenCTI client: python
4. Other environment details: I used manual installation instructions

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. yarn serv
2. On server side, all works fine
3. On browser, the interface content wont load

## Expected Output

OpenCTI Interface

## Actual Output

Empty web page with tab title "OpenCTI" 
 
## Additional information

I tried different browser, and got the same result.
Also same result on both ports 80 & 4000 (production.json was edited accordingly)
![OpenCTI2](https://user-images.githubusercontent.com/6297379/79397774-341b4d00-7f7f-11ea-8700-0acfbc671dba.PNG)
![OpenCTI3](https://user-images.githubusercontent.com/6297379/79397780-37aed400-7f7f-11ea-80ee-79bf9464e83f.PNG)

[Production.json.txt](https://github.com/OpenCTI-Platform/opencti/files/4484097/Production.json.txt)

**Comment by richard-julien** [comment]
I think you misunderstood the base_path option. "base_path" : "/home/admincti/opencti"
Its not the file system path is the URL base path, useful if you have a reverse proxy in front of openCTI.
Try to back to initial "base_path" : "" and restart.

**Comment by Woody90** [comment]
Thanks Richard.
That did solve the issue.
