### ISSUE TITLE
Elasticsearch exception when searching URL

### ISSUE THREAD

**Issue by rguignard** [OpenCTI-Platform/opencti#629]
## Description

An exception occurred in elasticsearch when searching indicator of type URL.
The problem seems to be that the "/" characters are not escaped.

{"message":"[OPENCTI] Technical error > search_phase_execution_exception","locations":[{"line":12,"column":3}],"path":["stixObservables"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"ResponseError","meta":{"body":{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [*test/test*]","index_uuid":"4vgGWovmSkSEI5iUS3fJVg","index":"stix_observables"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"stix_observables","node":"SUsL4fwGR8O2cBgvB0OfLg","reason":{"type":"query_shard_exception","reason":"Failed to parse query [*test/test*]","index_uuid":"4vgGWovmSkSEI5iUS3fJVg","index":"stix_observables","caused_by":{"type":"parse_exception","reason":"Cannot parse '*test/test*': Lexical error at line 1, column 12.  Encountered: <EOF> after : \"/test*\"","caused_by":{"type":"token_mgr_error","reason":"Lexical error at line 1, column 12.  Encountered: <EOF> after : \"/test*\""}}}}]},"status":400},"statusCode":400,"headers":{"content-type":"application/json; charset=UTF-8","content-length":"807"},"warnings":null,"meta":{"context":null,"request":{"params":{"method":"POST","path":"/stix_observables/_search","body":"{\"from\":0,\"size\":100,\"sort\":[{\"created_at\":\"desc\"}],\"query\":{\"bool\":{\"must\":[{\"query_string\":{\"query\":\"*test/test*\",\"analyze_wildcard\":true,\"fields\":[\"name^5\",\"*\"]}},{\"bool\":{\"should\":[{\"match_phrase\":{\"entity_type\":\"Stix-Observable\"}},{\"match_phrase\":{\"parent_types\":\"Stix-Observable\"}}],\"minimum_should_match\":1}},{\"exists\":{\"field\":\"created_at\"}}],\"must_not\":[]}}}","querystring":"_source_excludes=rel_*&track_total_hits=true","headers":{"User-Agent":"elasticsearch-js/7.6.1 (linux 4.15.0-55-generic-x64; Node.js v12.16.1)","Content-Type":"application/json","Content-Length":"367"},"timeout":30000},"options":{"warnings":null},"id":459569},"name":"elasticsearch-js","connection"

This exception prevents the search for indicator of type URL

## Reproducible Steps

Search "test/test" in the interface

**Comment by richard-julien** [comment]
Fix with https://github.com/OpenCTI-Platform/opencti/commit/88a2cc45e63013aed609fe243753aee6a651b5c0
