### ISSUE TITLE
Organization should implement gathering relations

### ISSUE THREAD

**Issue by soreno123** [OpenCTI-Platform/opencti#635]
Given the following situation:
User John Doe is part of organization B (i.e. ACME CERT)
Organization A (i.e. ACME)  is "related-to" organization B (i.e. ACME CERT)
User won't correctly show up as user belonging to Organization ACME, but only to organization ACME CERT because of the existing relation:
![image](https://user-images.githubusercontent.com/36479898/79744735-2bbc6c80-8307-11ea-9b39-836deff74d17.png)

Would be useful to add a relation of "gathering" between Organizations, so that user of Acme CERT show up also as user of Acme Organization.

**Comment by richard-julien** [comment]
@SamuelHassine ?

**Comment by SamuelHassine** [comment]
It is already available, as you can see here: https://demo.opencti.io/dashboard/entities/organizations/218870e0-95a8-446e-aa89-f50bbbef3238/knowledge/relations/1c619646-a319-4f7a-b473-343ccb9e1113

I updated the documentation here: https://www.notion.so/luatix/Relationships-data-model-288c1c4a2ca94c549d454c4b493109f0
