### ISSUE TITLE
[Connector] Recorded Future connector crashes with unmanaged "None" criticality score

### ISSUE THREAD

**Issue by NiQuintin** [OpenCTI-Platform/opencti#6358]
## Description

The EI Recorded Future connector crashes following an exception probably due to the non-management of the "None" criticality score, which is not currently processed. 
## Environment

N/A

## Reproducible Steps

See ticket OCTI1-508

## Expected Output

N/A

## Actual Output

N/A

## Additional information

N/A

**Comment by nino-filigran** [comment]
@helene-nguyen or @Megafredo are you able to reproduce?

**Comment by Megafredo** [comment]
Yes @nino-filigran, no problem, it was seen! we can take care of it!

**Comment by helene-nguyen** [comment]
The bug can be reproduced:

![image](https://github.com/OpenCTI-Platform/opencti/assets/75518128/5966d9c9-603e-414f-bff0-6c173c922709)

It will be corrected today :)
