### ISSUE TITLE
Additional observables

### ISSUE THREAD

**Issue by rbnor** [OpenCTI-Platform/opencti#637]
## Problem to Solve

 OpenCTI needs to support as many observable types as possible in order to fully functional with for example misp. Two examples of such observables (the most important ones per now) that misp support and OpenCTI does not, that i miss are : 
- JA3-hashes
- User-Agent
Both widely used in such settings. 
https://github.com/MISP/misp-objects/blob/master/objects/ja3/definition.json
https://github.com/MISP/misp-objects/blob/master/objects/http-request/definition.json
. 

## Current Workaround

There are no current workarounds.  

## Proposed Solution

 Aim to support as many misp observables as possible in order to ensure seamless compatability and enable OpenCTI to truly be a central knowledge base. I think it will be hard to get to that position if not all the observable types analysts use are available.  

## Additional Information

Any additional information, including logs or screenshots if you have any.

**Comment by SamuelHassine** [comment]
Hello,

User-Agent has been added in the future V4. About JA3-hashes, we added also a free "String" observable that can be used for this purpose. We would like to stay STIX 2.1 compliant as much as we can.

Kind regards,
Samuel
