### ISSUE TITLE
Issues launching with docker

### ISSUE THREAD

**Issue by rbnor** [OpenCTI-Platform/opencti#643]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description
I want to depploy it with docker stack deploy, used the command from the documentation. However: this does not start the opencti.1 service. So the app does not run, and port 8080 is not exposed. 

the command:
sudo docker service ps  opencti_opencti --no-trunc
 shows a loop of a failing service, i suppose its the same  issue, complaining about grakn not running, however it is running. 

ID                          NAME                    IMAGE                                                                                            NODE                DESIRED STATE       CURRENT STATE
        ERROR                       PORTS
jv3jjnvrou51qm5f0fdtlg53e   opencti_opencti.1       opencti/platform:3.1.0@sha256:1090957d53f284d7b61799269576f08c8d159e703f6a9c6fcd03dec2aada3478   misp                Ready               Ready 2 seconds ago

wsz99n2c5nntgl2idrvknlp9j    \_ opencti_opencti.1   opencti/platform:3.1.0@sha256:1090957d53f284d7b61799269576f08c8d159e703f6a9c6fcd03dec2aada3478   misp                Shutdown            Failed 3 seconds ago
        "task: non-zero exit (1)"
ia6a3s6bevnc1bn7m51ikr058    \_ opencti_opencti.1   opencti/platform:3.1.0@sha256:1090957d53f284d7b61799269576f08c8d159e703f6a9c6fcd03dec2aada3478   misp                Shutdown            Failed 21 seconds ag

When starting with 
sudo docker-compose -f docker-compose1.yml --compatibility up -d
Everything starts, but opencti complains that grakn does not seem to be running. Checking with sudo docker ps it very much is.  And the workers keep on restarting probably because of opencti not running because it cant reach grakn?

## Environment

1. OS Ubuntu 18.04
2. OpenCTI version: latest
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Follow the documentation for docker setup 
2. Start with the docker stack deply command from there
3. Check docker ps and sudo docker service ps  opencti_opencti --no-trunc as well as sudo docker service ps  opencti_grakn --no-trunc
4. stop the services with sudo docker stack rm opencti
5. start with sudo docker-compose up -d
6. check docker ps
7. start with sudo docker-compose up and check the errors it produces. 
## Expected Output

expected it to work. 
## Actual Output
with --comåatibility up: 
opencti_1                                | {"message":"[OPENCTI] GraphQL initialization fail > Error: getaddrinfo EAI_AGAIN minio\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)","level":"er
ror"}

opencti_1                                | error Command failed with exit code 1.
opencti_1                                | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
opencti_1                                | {"message":"[OPENCTI] GraphQL initialization fail > Error: connect ECONNREFUSED 172.20.0.5:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)",
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by rbnor** [comment]
I thought the issue was gone and only a connectivity issue to one of the containers remained, however the status is the same as before, just didnt see the second error the first time, so this is indeed not solved.

**Comment by rbnor** [comment]
Seems to boil down to an minio issue

minio_1  | ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Invalid credentials

I have just put random credentials in the .env file

I assumed this would be used in creation of the containers

**Comment by blabut** [comment]
Hey @rbnor I think I am running into the same issue. Could you please detail how you changed the minio credentials to make it work ? Thanks a lot !

**Comment by ccombs-sqsp** [comment]
@rbnor @paupaulaz Either of you figure it out and want to post it in here?

**Comment by ccombs-sqsp** [comment]
Either of you figure out what credentials you should put in it? @paupaulaz @rbnor
