### ISSUE TITLE
Github OpenCTI connectors enabling web page is not working

### ISSUE THREAD

**Issue by Woody90** [OpenCTI-Platform/opencti#648]
There is an issue in the "Enable Connectors" link, at the OpenCTI installation documentation.

https://opencti-platform.github.io/docs/installation/connectors  

It retrieves below error massage.

![Error](https://user-images.githubusercontent.com/6297379/80170883-4df50980-85e9-11ea-910a-a57e73aaf5c7.PNG)

**Comment by 2xyo** [comment]
Documentation has moved from https://opencti-platform.github.io/ to  https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518 a few days ago (but is stil present in google cache...) 

The page regarding connectors installation is available at: https://www.notion.so/Connectors-4586c588462d4a1fb5e661f2d9837db8

**Comment by Woody90** [comment]
Thanks a lot 2xyo
