### ISSUE TITLE
Inferences - threat actors -intrusion sets

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#649]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When an intrusion set is attributed to a threat actor and when this intrusion set is targeting sectors / countries, one should expect that the threat actor (via inference) is seen as targeting the same sectors / countries.
It seems it is not the case.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

Apply inference to threat actor <-> intrusion set <-> victimology

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by GlennHD** [comment]
Yeah I'm running into this issue now. Wish there was some way to correlate in this manner.  Another thought I had was to converge Threat Actors w/ Country entities and differentiate between Attribution/Threats vs. Victimization. But regardless, our issue is Threat Actor > Intrusion Set > [Specifics].  Would like to see malware inferences rolled up to threat actors.

**Comment by biers04** [comment]
i am running into the same issue as the above. I am attempting to have reports correlate to threat actors, but this is broken due to the above.
