### ISSUE TITLE
Pin/Docking Navigation in WebUI

### ISSUE THREAD

**Issue by GlennHD** [OpenCTI-Platform/opencti#655]
## Problem to Solve
The icons on the left-hand side are not new user-friendly.

## Current Workaround
None

## Proposed Solution
Pinning/Docking the Left-Hand Navigation Pane would allow newer users to see the link text next to the icon as they get familiar with the platform.

## Additional Information
https://imgur.com/a/B2tFsh2 I made an animated GIF to show this in action.

**Comment by SamuelHassine** [comment]
Hey @GlennHD, thanks for this issue! As we have decided to always display the full menu in the V4, I think this is no longer needed :)

Kind regards,
Samuel
