### ISSUE TITLE
Markers on map are not placed at the right place

### ISSUE THREAD

**Issue by lndrtrbn** [OpenCTI-Platform/opencti#6599]
## Description

In the cartographic map we have markers for some entities, for examples cities.
Depending of the zoom level, the markers are not placed at the corresponding latitude longitude.

![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/8b27fb8e-77f4-449e-b7e3-1ac2fe2caf12)

![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/093fe3b3-7257-44cb-95e3-9c493b7ab130)

And the more you zoom out the worst it is.

## Environment

1. OS (where OpenCTI server runs): Edge
2. OpenCTI version: 6.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a city with lat lng (Example: Chantepie 48.08885, -1.61524)
2. Zoom in and out on the map

## Expected Output

Marker always placed where it should be

## Actual Output

Wrong place when zooming out

**Comment by nino-filigran** [comment]
Reproduced on demo
