### ISSUE TITLE
Attack patterns : relationship to indicators (sigma, yara, etc)

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#665]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It doesn't seem to be possible to link an attack pattern to an indicator.

It would be extremely useful to link (for example), sigma or yara rules to an ATT&CK technique.

A use case of OpenCTI would be to store and retrieve different hunting/detection rules (as indicator entities) and link them to ATT&CK techniques that can be "detected" by these rules

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

- allow to create relationships between indicators (especially yara, sigma, etc) and attack pattern
- visualize indicators associated to an attack pattern in the knowledge section of attack patterns

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by jbfeldman** [comment]
The relationship between Indicators and Attack Patterns is documented in both STIX 2.0 and 2.1, so implementing this feature is required to maintain STIX compliance
