### ISSUE TITLE
Adding a tooltip to the menu items icons 

### ISSUE THREAD

**Issue by blabut** [OpenCTI-Platform/opencti#667]
## Problem to Solve

On the /dashboard page, when the left menu is "collapsed", only icons are visible, with no way of knowing where each icon "leads to" when clicked.

## Current Workaround

Either memorise each icon, or uncollapse the left menu.

## Proposed Solution

 I think it would make sense to add the name of the section each button leads to as a tooltip. I would be glad to take care of it as a first contribution.

**Comment by SamuelHassine** [comment]
Hello @paupaulaz,

Thanks for your issue. We decided to display the full menu in the V4 so I think we don't need tooltip anymore ;)

Kind regards,
Samuel
