### ISSUE TITLE
Error Merging Entities

### ISSUE THREAD

**Issue by skc2154** [OpenCTI-Platform/opencti#668]
## Description

OpenCTI instance is having trouble merging two entities together. Specifically, attempted to merge "Emotet" with "Geodo."

## Environment

OS (where OpenCTI server runs): Ubuntu 18.04
OpenCTI version: 3.2.0
OpenCTI client: Frontend
Other environment details:
OpenCTI Setup :
OpenCTI + RabbitMQ + Minio : 16vCPU , 64GB RAM [ On a single server]
ElasticSearch Cluster : 2 Servers ( 4vCPU , 16GB RAM) [ separate cluster]
Grakn Server - 16vCPU , 128GB RAM [ Separate server]

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data Curation
2. Search for Emotet 
3. Select Emotet and Geodo and click merge
4. Error "An unknown error has occured! Please try again later"

## Actual Output
![image](https://user-images.githubusercontent.com/20231261/80516507-91d17100-8951-11ea-9338-d126565419de.png)

 
## Additional information

> {"message":"[OPENCTI] Technical error > parsing_exception","locations":[{"line":7,"column":5}],"path":["stixDomainEntityEdit","mergeEntities"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"ResponseError","meta":{"body":{"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] query does not support array of values","line":1,"col":62}],"type":"parsing_exception","reason":"[term] query does not support array of values","line":1,"col":62},"status":400},"statusCode":400,"headers":{"content-type":"application/json; charset=UTF-8","content-length":"245"},"warnings":null,"meta":{"context":null,"request":{"params":{"method":"POST","path":"/stix_domain_entities_v2%2Cstix_relations%2Cstix_observables%2Cwork_jobs_index/_search","body":"{\"query\":{\"bool\":{\"must\":[{\"term\":{\"internal_id_key.keyword\":[\"7101f9d7-4479-413b-befd-3aecc29a1fb8\"]}},{\"term\":{\"parent_types.keyword\":\"Stix-Domain-Entity\"}}]}}}","querystring":"_source_excludes=rel_*","headers":{"User-Agent":"elasticsearch-js/7.6.1 (linux 5.0.0-1034-gcp-x64; Node.js v12.16.2)","Content-Type":"application/json","Content-Length":"162"},"timeout":30000},"options":{"warnings":null},"id":3897238},"name":"elasticsearch-js","connection":{"url":"hxxp://xx.xxx.xxx.xxx:xxxx/","id":"hxxp://xx.xxx.xxx.xxx:xxxx
/","headers":{},"deadCount":0,"resurrectTimeout":0,"_openRequests":0,"status":"alive","roles":{"master":true,"data":true,"ingest":true,"ml":false}},"attempts":0,"aborted":false}},"stacktrace":["ResponseError: parsing_exception","    at IncomingMessage.<anonymous> (/opt/opencti/opencti/node_modules/@elastic/elasticsearch/lib/Transport.js:296:25)","    at IncomingMessage.emit (events.js:322:22)","    at endReadableNT (_stream_readable.js:1187:12)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}},"level":"error"}

**Comment by rhaist** [comment]
Seeing the same problem on our staging instance with the 3.2.0 release trying to merge Countries.
