### ISSUE TITLE
Installing manually on same box as MISP? 

### ISSUE THREAD

**Issue by mathurin68** [OpenCTI-Platform/opencti#670]
Manual script here, looks amazing. 
https://gist.github.com/p-rs/5e67b811efd30ef704be7078cbd758a8

Any issues with installing and running this on the same box as MISP? 

Thanks!

**Comment by cvdsouza** [comment]
There are two components that intersect with MISP and OpenCTI. those are Redis and Elasticsearch(Optional on MISP) , so I would caution with installation. Based on my understanding there shouldn't be any overlap but I would just use caution with Manual installation. You do have the Docker option with OpenCTI that you can leverage as well which would make deployment easy.

**Comment by powerade661** [comment]
I run mine with a manual install on the same box just fine without issue. Just change the redis port for OpenCTI. :)

**Comment by SamuelHassine** [comment]
@mathurin68, this is a very generic question and if you just take care of "common" dependencies, you will not have any problems. But deploying OpenCTI on only one box and do not use an ElasticSearch cluster for instance is not recommended in production.
