### ISSUE TITLE
Flag when objects (indicators, relationships, etc.) are no longer valid

### ISSUE THREAD

**Issue by jbfeldman** [OpenCTI-Platform/opencti#675]
#213  Problem to Solve

Most STIX2 objects have expiration dates attached to them (often called "valid_to"), a timestamp after which the data should no longer be considered valid. For most objects, OpenCTI also has a field for when the data is valid until. However, beyond that small field it's not immediately obvious when an object is no longer valid

This would be especially helpful for enrichment/import connectors from third parties that have real time threat intelligence that is constantly updating, so we could let users know what relationships are old/obsolete.

## Current Workaround

Manually check the expiration date on every object

## Proposed Solution
Have a red flag or something visually obvious appear when an object has expired and is no longer valid. Additionally, allow filtering based off of whether the data has passed its expiration date or not

**Comment by SamuelHassine** [comment]
Hello @jbfeldman,

This feature was implemented in the intelligence lifecycle, when a indicator is expired (valid_until), the "revoked" field is TRUE.
