### ISSUE TITLE
Set score field to STIX2 confidence

### ISSUE THREAD

**Issue by jbfeldman** [OpenCTI-Platform/opencti#676]
## Problem to Solve

Although this issue has been solved (https://github.com/OpenCTI-Platform/client-python/issues/69), OpenCTI will not import score from the STIX2 confidence scores

## Current Workaround
You can either change the score after creation with the `opencti_api_client.stix_domain_entity.update_field`  or use `opencti_indicator.create()` to create the indicator instead of importing from STIX2

## Proposed Solution

When a stix2 indicator is imported (via the `OpenCTIConnectorHelper.send_stix2_bundle()` function), if the indicator has a confidence field set score equal to that confidence field

**Comment by SamuelHassine** [comment]
This is definitely planned, linked to #387
