### ISSUE TITLE
Data management wont show

### ISSUE THREAD

**Issue by rbnor** [OpenCTI-Platform/opencti#679]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

unable to open the data management dashboard. 

## Environment

Ubuntu 1804, docker latest version. 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
navigate to the data management tab. 

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

Logging: 

{"message":"[OPENCTI] Technical error > Cannot return null for non-nullable field User.name.","locatio
ns":[{"line":19,"column":9},{"line":53,"column":3}],"path":["stixDomainEntities","edges",24,"node","na
me"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return nul
l for non-nullable field User.name.","    at completeValue (/opt/opencti/node_modules/graphql/executio
n/execute.js:560:13)","    at completeValueCatchingError (/opt/opencti/node_modules/graphql/execution/
execute.js:495:19)","    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:435:1
0)","    at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:275:18)","    at col
lectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:713:10)","    at compl
eteObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:703:10)","    at completeAbstra
ctValue (/opt/opencti/node_modules/graphql/execution/execute.js:660:10)","    at completeValue (/opt/o
pencti/node_modules/graphql/execution/execute.js:585:12)","    at completeValue (/opt/opencti/node_mod
ules/graphql/execution/execute.js:557:21)","    at completeValueCatchingError (/opt/opencti/node_modul
es/graphql/execution/execute.js:495:19)","    at resolveField (/opt/opencti/node_modules/graphql/execu
tion/execute.js:435:10)","    at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js
:275:18)","    at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:7
13:10)","    at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:703:10)","
    at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:591:12)","    at complete
ValueCatchingError (/opt/opencti/node_modules/graphql/execution/execute.js:495:19)"]}},"level":"error"
}
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @rbnor,

I dont know how this happened, it seems you have one of your user that does not have any "name" attribute. But the field is mandatory at the creation and at the edition, even in the API.

Are you able to access `/dashboard/settings/accesses/users` ? You may have the same error...

**Comment by rbnor** [comment]
> Hello @rbnor,
> 
> I dont know how this happened, it seems you have one of your user that does not have any "name" attribute. But the field is mandatory at the creation and at the edition, even in the API.
> 
> Are you able to access `/dashboard/settings/accesses/users` ? You may have the same error...

This is probably linked to #646 , there is only one user showing in /dashboard/settings/accesses/users (the default admin user), but it could be that a user without a user name has been created by the AD configuration, somehow, maybe as a result of error handling, not sure..

**Comment by SamuelHassine** [comment]
Yes we discussed with @richard-julien and it is linked to the LDAP authentication, we are working to fix that in the next minor version.

**Comment by rbnor** [comment]
Any suggestions for a quick fix to remove the user without a name? Since i cant see it from the menu. Probably delete it from the DB right? It keeps throwing the same error on a lot of places in the platform and i really need to get going with the testing and usage of the platform.

**Comment by SamuelHassine** [comment]
@rbnor to delete the user that does not have a name, you can use the API Playground (access from your profile). List all users to get the right IDs, then delete all users that are not useful to you.

```
query {
  users {
    edges {
      node {
        id
        user_email
      }
    }
  }
}
```

Then delete those who have no name with a mutation:

```
mutation {
  userEdit(id: "USER_ID_HERE") {
    delete
  }
}
```

**Comment by rbnor** [comment]
Smart, didnt think of that. Thanks!

**Comment by rbnor** [comment]
> @rbnor to delete the user that does not have a name, you can use the API Playground (access from your profile). List all users to get the right IDs, then delete all users that are not useful to you.
> 
> ```
> query {
>   users {
>     edges {
>       node {
>         id
>         user_email
>       }
>     }
>   }
> }
> ```
> 
> Then delete those who have no name with a mutation:
> 
> ```
> mutation {
>   userEdit(id: "USER_ID_HERE") {
>     delete
>   }
> }
> ```

Im not able to get this to work. 

I query and get 200 users, both in python and the playground. After looping through and deleting all, next time, still 200. 

Same at the playground, if i delete one, next query still 200. And this issue remains because im not able to see or delete the users anywhere else.

**Comment by rbnor** [comment]
i think i will just start over :)
