### ISSUE TITLE
Import csv file IOC or Observable

### ISSUE THREAD

**Issue by H4ckTrooper** [OpenCTI-Platform/opencti#684]
import CSV file for IOC or observable

## Problem to Solve
We can export in csv file but i can't import csv for IOC
We can use connector to import pdf file or json but not found for CSV

## Current Workaround
In the Roadmap it write it will be able in Q4 2019 for stix and CSV for export and import
https://www.opencti.io/fr/feuille-de-route/
## Proposed Solution

Create a connector to import CSV file like json

**Comment by SamuelHassine** [comment]
Hello, please refer to : https://github.com/OpenCTI-Platform/connectors/issues/98.
