### ISSUE TITLE
Add customized observable type by admin when creating an observable

### ISSUE THREAD

**Issue by tanyawang1218** [OpenCTI-Platform/opencti#687]
## Problem to Solve

When creating an observable, the observable type is fixed. We can not select other types which are not in the list. Ex. host name (not domain name) is not in the list now.

## Current Workaround

We have no workaround so far.

## Proposed Solution

We would like to add customized observable types by admin role.

## Additional Information

![image](https://user-images.githubusercontent.com/10161931/81047056-3a507980-8eec-11ea-870e-2a2f9727dda0.png)

**Comment by SamuelHassine** [comment]
Linked to #370.

**Comment by tanyawang1218** [comment]
Hi @SamuelHassine , May I know will OpenCTI provide this feature to let user can define customized observable type? If yes, may I know the ETA? If no, could you please help to add below observable types for me as a workaround? Many thanks :)

1.  Cryptographic key (If it useful for SSH keys, RSA keys - for ransomware, RC4/XOR keys for encrypted strings, etc.)
2. Crypto wallet
3. User-Agent.
4. hostname (not domain name)
5. telfhash
6. TLSH
7. PTR record

Regards,
Tanya

**Comment by tanyawang1218** [comment]
Hi @SamuelHassine ,

May I follow up this request?
Thank you.

Regards,
Tanya

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

We have implemented almost all the observable types you requested as well as a free "Text" type where you can put any string your want. For the moment, we do not plan to allow the creation of custom observable types, maybe in the future:

Check it here: https://demo.opencti.io/dashboard/signatures/observables

Kind regards,
Samuel
