### ISSUE TITLE
Not all report types are taken into account in all views

### ISSUE THREAD

**Issue by rbnor** [OpenCTI-Platform/opencti#696]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Reports does not show under author org and are not represented in all graphics and stats. 

## Environment

latest on ubuntu, docker. 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Upload an misp event and a threat report
Check the stats on the author org and check the org -> report. The misp event will not be there the threat report will. 
Then  check the intrution set stats, the misp report will not show in the graph over report sources, other than as admin, not proper author. 
## Expected Output

expect all report types to be counted and show everywhere

## Actual Output
explained in reproduction steps

**Comment by rbnor** [comment]
Moving a report to a different type didnt resolve anything

**Comment by SamuelHassine** [comment]
Hello @rbnor, 

I was not able to reproduce your bug, everything works fine on our side. Could you please find this kind of problem in the demo?
