### ISSUE TITLE
Can anyone provide opencti manual installation components and configuration documents on Ubuntu 19.10?

### ISSUE THREAD

**Issue by 15271843622** [OpenCTI-Platform/opencti#698]
Component configuration is complex and has many thorny problems. Hope to provide help documents and install components such as opencti smoothly

**Comment by richard-julien** [comment]
The best solution is to improve our documentation (https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1) but for that I need to understand a bit more "configuration is complex and has many thorny problems". Can you elaborate that missing in the doc? Thanks

**Comment by 15271843622** [comment]
How to update the opencti template virtual machine to the latest opencti? What commands do you need to execute

**Comment by razzeshsingh** [comment]
@15271843622 I
i configured it manually on centos 7. you need to check the version compatibility

**Comment by 15271843622** [comment]
I have installed these necessary parts separately. How to connect opencti or modify the configuration in components
