### ISSUE TITLE
Write an article about why we choose Grakn over Neo4j

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#7]
## Problem to Solve

To explain technical choices behind OpenCTI, we have to write an article about why we choose Grakn as the main database backend.

## Current Workaround

None.

## Proposed Solution

Clean the Luatix blog and write the article.

## Additional Information

None.

**Comment by SamuelHassine** [comment]
A blog post that explains why we choose Grakn has been published: https://www.luatix.org/en/2019/07/22/open-sourcing-the-opencti-platform/
