### ISSUE TITLE
Update from 3.1 to 3.2

### ISSUE THREAD

**Issue by Rickozono** [OpenCTI-Platform/opencti#709]
How do I update my opencti from 3.1 to 3.2 on a Ubuntu 18.04?
Thanks for any reply.

**Comment by cvdsouza** [comment]
For Manual Deployment : 
https://www.notion.so/Manual-deployment-b911beba44234f179841582ab3894bb1#24590ee4cd4b42309d5277e34c64d114

**Comment by Rickozono** [comment]
I succesfully update opencti.
Thank you very much for your reply
regards
