### ISSUE TITLE
Merging entities : recurring bug

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#710]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

In some cases when trying to merge two entities, the following error is returned:
"There is more than one thing of type [stix_relation_embedded] that owns the key [xxxxxx] of type [internal_id_key]

![image](https://user-images.githubusercontent.com/28398686/82426178-d307fd00-9a87-11ea-9c57-fa79fbe5e0f7.png)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 3.2.2
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

Merging 2 entities

## Actual Output

Merging is not done. Error message (see above)
 
## Additional information

I seems that the bug comes when the two entities to merge share some relationships with other entities (e.g. 2 malware having "indicate" relationships with the same indicators)

**Comment by cvdsouza** [comment]
+1 on this bug. We have seen it in our instance as well.
