### ISSUE TITLE
¿Is there any way of filtering content by users?

### ISSUE THREAD

**Issue by Bondey** [OpenCTI-Platform/opencti#711]
I've been trying to create some kind of filter for the information by users.

With roles, I can give access to all the info or nothing.
Goups with TLP restrictions seems not to work yet, but i't has the disclaimer that it's not fully implemented, so it's ok, it's in the roadmap :)

At the moment, ¿is there any way of filtering the information a user can access?

**Comment by richard-julien** [comment]
Hi @Bondey, there is no way to segregate the data for a specific user for now. Like you said we plan to offer this feature in the future but its not yet planned.
