### ISSUE TITLE
 I encounter a yarn serv error.

### ISSUE THREAD

**Issue by tanhacker** [OpenCTI-Platform/opencti#731]
When I install opencti manually, I encounter a yarn serv error. Please help me
![图片](https://user-images.githubusercontent.com/42628114/83244322-c1360080-a1d1-11ea-9a94-905ab17f0d58.png)

**Comment by richard-julien** [comment]
Hi @tanhacker, do you use opencti-release_3.3.0.tar.gz or opencti-release-3.3.0_musl.tar.gz?

**Comment by tanhacker** [comment]
I installed opencti-release-3.2.2_ musl.tar.gz This file was not found in the modify configuration file production.json Is the document missing from my inspection?

**Comment by richard-julien** [comment]
Ubuntu use the libc so you need to install the opencti-release_3.3.0.tar.gz version (I just add more explanation in the documentation).

production.json is not provided by default. You need to create it if you want to override the default.json configuration

**Comment by tanhacker** [comment]
Thank you for your help. I have reinstalled opencti release_ 3.3.0. tar.gz Version. Execute yarn serv Caton. What's the reason? My system is Ubuntu 19.10
![图片](https://user-images.githubusercontent.com/42628114/83346430-d84e2d00-a34e-11ea-9aef-4fdebd1dc0d3.png)

**Comment by richard-julien** [comment]
Hi @tanhacker, your platform starts perfectly. yarn serv is start in foreground. (take a look to https://linuxize.com/post/how-to-run-linux-commands-in-background/ if you want to start it in background)

**Comment by SamuelHassine** [comment]
I confirm that this log means that the platform is started. Just go to the "IP_ADDRESS" on port 4000.
