### ISSUE TITLE
issue with upgrade platform from 3.2.1 to 3.2.2 (and 3.3.0)

### ISSUE THREAD

**Issue by garanews** [OpenCTI-Platform/opencti#732]
## Description
Having the environment 3.2.1 working, it stop to work when try to upgrade to 3.2.2 or to 3.3.0

## Environment
![image](https://user-images.githubusercontent.com/16938405/83247574-fc213f80-a1a3-11ea-803a-54e0057b0bd1.png)

## Reproducible Steps

For upgrade 3.3.0 first we upgrade grakn (this is a separate vm)
Then upgrade dockerfile with 3.3.0 of all items.

For upgrade 3.2.2 we keep grakn 1.6.x and upgraded docker file from 3.2.1 to 3.2.2 of all items.

Behavior is same:
platform starts but it seems is not listening on 8080.
Entering in docker of platform, output of ps command is:
`/ # ps`
`PID   USER     TIME  COMMAND`
`    1 root      0:00 {entrypoint.sh} /bin/sh /entrypoint.sh`
`    6 root      0:00 node /opt/yarn-v1.19.1/bin/yarn.js serv`
`   27 root      0:04 /usr/local/bin/node --max_old_space_size=8192 build/index.js`
`   44 root      0:00 /bin/sh`
 `  49 root      0:00 ps`
`/ #`

But  netstat output is not showing 8080

`/ # netstat -tanup`
`Active Internet connections (servers and established)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name`
`tcp        0      0 127.0.0.11:33949        0.0.0.0:*               LISTEN      -`
`tcp        0      0 172.25.0.11:34968       172.25.0.16:9200        ESTABLISHED 27/node`
`tcp        0      0 172.25.0.11:51490       172.25.0.8:6379         ESTABLISHED 27/node`
`tcp        0      0 172.25.0.11:48826       192.168.166.30:48555    ESTABLISHED 27/node`
`udp        0      0 127.0.0.11:53800        0.0.0.0:*                           -`

We're not able to find what break things in changes from 3.2.1 to 3.2.2 / 3.3.0

**Comment by richard-julien** [comment]
Hi @garanews, difficult to answer without error logs of opencti.

**Comment by garanews** [comment]
which log do you need?
/opt # cd opencti/
/opt/opencti # cd logs/
/opt/opencti/logs # ls
error.log.2020-05-29    opencti.log.2020-05-29

I see only
{"message":"[ELASTICSEARCH] Seems down","level":"error"}

That is not true and the ES connection  seems working due I see 9200 in netstat established

In fact I deleted logs and restarted container and now I have clean files:
-rw-r--r--    1 root     root             0 May 29 10:17 error.log.2020-05-29
-rw-r--r--    1 root     root             0 May 29 10:17 opencti.log.2020-05-29

So no errors

**Comment by richard-julien** [comment]
Can you try getting logs with docker logs? thanks

**Comment by garanews** [comment]
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"message":"[ELASTICSEARCH] Seems down","level":"error"}
{"error":"Error: ElasticSearch seems down\n    at /opt/opencti/build/index.js:1:42139\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/opencti/build/index.js:1:149641\n    at async n.b (/opt/opencti/build/index.js:1:149564)\n    at async /opt/opencti/build/index.js:1:1033781","level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js

**Comment by garanews** [comment]
Don't know what happened, after 30 mins it worked!
Decided to try the 3.3.0 and it is working too!
Entering in docker I see exactly same process I had previously, but with netstat I see many connections and 8080 listening.
Going to close issue, but it is not clear what happened and logs dind't help.
