### ISSUE TITLE
This error occurred when I replaced opencti-3.3.0. Please help me

### ISSUE THREAD

**Issue by 15271843622** [OpenCTI-Platform/opencti#737]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by 15271843622** [comment]
This is a screenshot of an error report
![image](https://user-images.githubusercontent.com/41221477/83507697-7b43aa00-a4fb-11ea-881b-52c5a5addbb1.png)

**Comment by richard-julien** [comment]
Please try to create a real ticket next time... So if i read correctly your screenshot, the error is really clear: "**reason: RabbitMQ seems down**".

**Comment by 15271843622** [comment]
My rabbitmq server is turned on normally, and the credentials are all correct. Here is the screenshot
![最新报错](https://user-images.githubusercontent.com/41221477/83583648-79b7c780-a577-11ea-94e5-64771319767d.png)

**Comment by richard-julien** [comment]
Version of rabbitMQ ?

**Comment by 15271843622** [comment]
Rabbitmq - version 3.8, which runs normally in version 3.2.2 and is always on


![image](https://user-images.githubusercontent.com/41221477/83617572-dc32b700-a5bb-11ea-94ef-f1bfc2f0af3d.png)

**Comment by richard-julien** [comment]
Can you check in rabbit management if the queue logs_all exists? thanks

**Comment by 15271843622** [comment]
I rebooted the system, and each component was checked to be normal. I updated the pyhton environment of opencti version 3.3. There was no rabbitmq error in yarn serv, but there was a new error
![image](https://user-images.githubusercontent.com/41221477/83988651-7147fe00-a976-11ea-8f45-dcc21523762a.png)

**Comment by richard-julien** [comment]
Close for inactivity. Please open another ticket if you still have some issue
