### ISSUE TITLE
Admin account cannot be auto-created with a migration

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#74]
## Problem to Solve

Today the admin account is: admin / admin, and needs to be change after first login. This behavior is a security issue because every openCTI password can be accessed by anyone if the administrator forget to change the password of this account.

## Current Workaround

No possible workaround

## Proposed Solution

Admin account needs to be part of env configuration:
APP__ADMIN__EMAIL
APP__ADMIN__PASSWORD
APP__ADMIN__TOKEN
When the graphQL API Start, the admin account will be created/reset with this values.

## Additional Information

No

**Comment by ashok1967** [comment]
How to recover forgotten web interface username and password

**Comment by richard-julien** [comment]
Please do not reactivate 3 years old ticket. Join the slack channel or open an new ticket if nonbody is able to answer you on the channel
