### ISSUE TITLE
iso 3166-1 for country code liking with the actual country

### ISSUE THREAD

**Issue by nathmo** [OpenCTI-Platform/opencti#740]
## Problem to Solve

I Have a country Named Russia and a country named RUS I would like them to be the same country

## Current Workaround
Add label and hope that it get linked wiht the duplicate check

## Proposed Solution
add the ISO code of the country as a default label for the country

**Comment by SamuelHassine** [comment]
Hello,

`RUS` is already the ISO code (Alpha-3) code for "Russia", do you mean that we should at the Alpha-2 (2 chars) code?

Reference: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

Kind regards,
Samuel

**Comment by nathmo** [comment]
im sorry wrote only half of what I meant. I'm having this issue with duplicated country where one of them have the full name of the country and one have the iso code (Alpha-3) and i would like them to be linked automatically withouth having to add a label RUS to the RUSSIA country such that they seen as duplicate and are merged

**Comment by richard-julien** [comment]
Im not sure we have to do that because its not the responsibility of openCTI to fix any dataset. wdyt @SamuelHassine?

**Comment by SamuelHassine** [comment]
This is now fixed in the V4.
