### ISSUE TITLE
Start error with manual install (after moving from Docker)

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#742]
## Description

> yarn run v1.22.4
> $ node --max_old_space_size=8192 build/index.js
> {"level":"info","message":"[INIT] > Starting OPENCTI..."}
> {"level":"info","message":"[PRE-CHECK] > Grakn is alive"}
> {"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive"}
> {"level":"info","message":"[PRE-CHECK] > Minio is alive"}
> {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive"}
> {"level":"info","message":"[PRE-CHECK] > Redis is alive"}
> {"level":"info","message":"[PRE-CHECK] > Python3 is available"}
> {"level":"info","message":"[INIT] > Existing platform detected, migration..."}
> {"level":"info","message":"[INIT] > Grakn schema loaded"}
> {"level":"info","message":"[INIT] > Elasticsearch indexes loaded"}
> {"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-02T15:54:51.394Z","data":{"reason":"Expect only one response","category":"technical","terms":[{"internal_id_key.keyword":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},{"parent_types.keyword":"User"}],"hits":[{"_index":"stix_domain_entities_v2","_type":"_doc","_id":"V417944","_score":18.008339,"_source":{"firstname":"Admin","parent_types":["User","Identity","Stix-Domain-Entity","Stix-Domain"],"description":"Principal admin account","created_at":"2020-04-06T19:13:08.061Z","language":"auto","revoked":false,"index_version":"1.0","password":"$2a$10$TF6qlvBW0qKsv2BI6Bdt0.4eYCDt2VcCdn14GM5JXk/MRfkNnIYJu","base_type":"entity","created_at_year":"2020","updated_at":"2020-05-20T14:21:11.521Z","alias":[],"modified":"2020-05-20T14:21:11.521Z","created_at_day":"2020-04-06","id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","grakn_id":"V417944","user_email":"admin@opencti.io","created_at_month":"2020-04","internal_id_key":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","stix_id_key":"identity--88ec0c6a-13ce-5e39-b486-354fe4a7084f","created":"2020-04-06T19:13:08.061Z","lastname":"OpenCTI","external":true,"entity_type":"user","name":"admin"}},{"_index":"stix_domain_entities_v2","_type":"_doc","_id":"V459000","_score":18.008339,"_source":{"user_email":"itsecops@mydomain.com","firstname":"Admin","internal_id_key":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","created_at_month":"2020-06","parent_types":["User","Identity","Stix-Domain-Entity","Stix-Domain"],"stix_id_key":"identity--88ec0c6a-13ce-5e39-b486-354fe4a7084f","created":"2020-06-02T15:34:38.981Z","description":"Principal admin account","created_at":"2020-06-02T15:34:38.981Z","language":"auto","revoked":false,"lastname":"OpenCTI","external":true,"password":"$2a$10$jw2c1/yQ8fzUzw.8oV3VdOHdPxwGRMFoJU6wOeNlbq3dgsuPIHbbS","entity_type":"user","base_type":"entity","updated_at":"2020-06-02T15:34:38.981Z","created_at_year":"2020","name":"admin","alias":[],"modified":"2020-06-02T15:34:38.981Z","created_at_day":"2020-06-02","id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","grakn_id":"V459000"}}]},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
> error Command failed with exit code 1.

## Environment

1. Ubuntu 10.04
2. OpenCTI 3.3.0
3. OpenCTI client: Python
4. Node: 12.16.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. After having issues with the current Docker, I downloaded the latest release of OpenCTI after installing all the dependencies and running them as Linux services. I did not replace anything from the prior Docker installation.
2. I built all the Python requirements in a virtual environment which I activated before using Yarn.
3. yarn serv

## Expected Output

Startup without error

## Actual Output

See above.

**Comment by SamuelHassine** [comment]
Hello,

This is a known issue and we are currently trying to deal with it. Please just wipe everything (including the Docker volumes by `docker volume prune -a`). It should work after that.

**Comment by smclinden** [comment]
Same error. I removed all Docker volumes, containers and images. Prior to that I had moved the docker volumes to local storage which I, also, deleted. I am now running everything as a process/daemon in Linux no containers.

Is there someplace where the data from the previous install might be cached? The services that I moved from docker were, in order of first to last:

redis
grakn
elasticsearch
minio
rabbitmq
opencti

I, then, decided to delete everything from ES with:

curl -XDELETE localhost:9200/_all

And now I get:

> yarn run v1.22.4

> $ node --max_old_space_size=8192 build/index.js
> {"level":"info","message":"[INIT] > Starting OPENCTI..."}
> {"level":"info","message":"[PRE-CHECK] > Grakn is alive"}
> {"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive"}
> {"level":"info","message":"[PRE-CHECK] > Minio is alive"}
> {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive"}
> {"level":"info","message":"[PRE-CHECK] > Redis is alive"}
> {"level":"info","message":"[PRE-CHECK] > Python3 is available"}
> {"level":"info","message":"[INIT] > Existing platform detected, migration..."}
> {"level":"info","message":"[INIT] > Grakn schema loaded"}
> {"level":"info","message":"[INIT] > Elasticsearch indexes loaded"}
> {"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
> error Command failed with exit code 1.

I verified that Minio was running:

root      4413  5750  0 14:56 pts/0    00:00:00 /apps/usr/bin/minio server /apps/data

and that Minio was listening on port 9000

tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      4413/minio  

To access the service I needed to do the following:

./mc config host add local http://localhost:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
Added `local` successfully.

./mc config host ls
gcs  
  URL       : https://storage.googleapis.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v2
  Lookup    : dns

local
  URL       : http://localhost:9000
  AccessKey : minioadmin
  SecretKey : minioadmin
  API       : s3v4
  Lookup    : auto

play 
  URL       : https://play.min.io
  AccessKey : Q3AM3UQ867SPQQA43P2F
  SecretKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  API       : S3v4
  Lookup    : auto

s3   
  URL       : https://s3.amazonaws.com
  AccessKey : YOUR-ACCESS-KEY-HERE
  SecretKey : YOUR-SECRET-KEY-HERE
  API       : S3v4
  Lookup    : dns

I am then able to do:

./mc admin update local/
Server `local/` updated successfully from 2020-05-29T14:08:49Z to 2020-06-01T17-28-03Z

But I am still getting the GraphQL error!

**Comment by richard-julien** [comment]
In my opinion the error you have its because you clean correctly grakn but not elastic. Today opencti doesnt not clean elastic for you if grakn start fresh and so in your case the admin user was indexed twice, preventing the platform to start. 

You have to be sure when you start fresh that all the dependencies are clean.

Please verify and remove all attached volumes for grakn/elastic etc and try to restart.

**Comment by smclinden** [comment]
I tried wiping everything clean, rebooting and doing a fresh install and got the same output.

I agree that this appears to be a credential issue but not sure where. There are buckets for grakn and opencti-bucket (the latter is empty).

My default.json is as follows:

> {
>   "app": {
>     "port": 4000,
>     "logs": "./logs",
>     "logs_level": "info",
>     "cookie_secure": false,
>     "base_path" : "",
>     "platform_demo": false,
>     "performance_logger": false,
>     "admin": {
>       "email": "my email",
>       "password": "my password",
>       "token": "4f2869be-1456-404a-a3b3-bb3bffacd1ba"
>     }
>   },
>   "grakn": {
>     "hostname": "localhost",
>     "port": 48555,
>     "timeout": 30000
>   },
>   "redis": {
>     "hostname": "localhost",
>     "port": 6379
>   },
>   "elasticsearch": {
>     "url": "http://localhost:9200",
>     "noQueryCache": false
>   },
>   "minio": {
>     "endpoint": "localhost",
>     "port": 9000,
>     "use_ssl": false,
>     "access_key": "minioakey",
>     "secret_key": "minioskey"
>   },
>   "rabbitmq": {
>     "hostname": "localhost",
>     "port": 5672,
>     "port_management": 15672,
>     "management_ssl": false,
>     "username": "guest",
>     "password": "guest"
>   },
>   "providers": {
>     "local": {
>       "strategy": "LocalStrategy"
>     }
>   }
> }

**Comment by Rouxgaru** [comment]
I'm having this exact same issue.  Fresh install and everything. I'll be happy to include any files, but it's the same error after the npm test.

**Comment by richard-julien** [comment]
Ticket is now old and so i close it. Please open another ticket if you still have some issue.
