### ISSUE TITLE
Docker-Compose configures volumes

### ISSUE THREAD

**Issue by Tyrell20** [OpenCTI-Platform/opencti#745]
## Description

Hello,
could you please show me how to set-up docker-compose in order to store data inside /app path where the host has more storage? 

## Environment

1. OS (where OpenCTI server runs): { RHEL 7.7 }
2. OpenCTI version: { 3.30 }
3. OpenCTI client: { frontend}

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure docker-compose.yml file in order to indicate volume path as below.  It is done for all image.

 grakn:
    image: graknlabs/grakn:1.7.1
    ports:
      - 48555:48555
    volumes:
      - /app/volumes/grakndata:/grakn-core-all-linux/server/db

2. At the end of the file added lines below:
volumes:
  grakndata:
   driver: local
  esdata:
   driver: local
  s3data:
   driver: local

## Expected Output

the containers save data under /app path as configured in the docker-compose file 

## Actual Output

Docker-compose start opencti but the server is unreachable 
 
## Additional information

A check of space show the output below:
overlay                       8.0G  6.9G  1.2G  86% /var/lib/docker/overlay2/f2101af46adec402126eef59d74e1399fea2fc1b58218dba856bb2e4a7253a94/merged

**Comment by richard-julien** [comment]
OpenCTI use standard docker compose so you can manage the volumes like any other containers (see https://docs.docker.com/compose/compose-file/#volumes).

**Comment by richard-julien** [comment]
Ticket is now old and so i close it. Please open another ticket if you still have some issue.
