### ISSUE TITLE
Connector and activation, but the platform has no entity, what's the reason

### ISSUE THREAD

**Issue by 15271843622** [OpenCTI-Platform/opencti#746]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS (where OpenCTI server runs): {Ubuntu 19.10, etc. }
2. OpenCTI version: { e.g. OpenCTI 3.2.2}
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

The platform and operation are normal. The connector is configured and activated, but the platform cannot see the entity object
![opencti and connectors](https://user-images.githubusercontent.com/41221477/83705570-e8fcec80-a647-11ea-9c94-6963156e532e.png)

**Comment by richard-julien** [comment]
Looks like you forget to start a worker

**Comment by richard-julien** [comment]
Dont know if you deploy manually or with docker but you have to start a worker.
See https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1#56b18206a12b43e4be158630fa87cf02 or https://www.notion.so/luatix/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8#6e582711ba1847ecb6dd894d9102fa25

**Comment by 15271843622** [comment]
Thank you very much for your help. The problem has been solved
