### ISSUE TITLE
Same entity from different sources : use description and notes rather than overwrite

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#747]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

Entities like intrusion sets or malware are sometimes collected from different sources / connectors.
For example source A (e.g. Crowdstrike) and source B (e.g. Mitre ATT&CK) are providing information about the same intrusion-set (e.g. APT28/Sofacy).
If they have a common name and aliases, during the import one description field will overwrite the description of the other.
In the connector parameter, one should then decide which one will overwrite the other.
This solution is not optimal because information is lost.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

When two or sources provide a "description" about the same entity (an intrusion set or a malware, typically).
- Description info of source A should go in the "description" field
- Description info of sources B, C, etc should go in notes attached to the entity

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
The chosen logic is described in [this issue](https://github.com/OpenCTI-Platform/connectors/issues/227) and will be implemented soon.
