### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by oguzhansrky** [OpenCTI-Platform/opencti#748]
## Environment

1. Ubuntu 18.04.04 LTS
2. OpenCTI version: { e.g. OpenCTI 3.0.3 }

connector-export-file-csv_1              | INFO:root:Listing Threat-Actors with filters null.
connector-export-file-csv_1              | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
connector-export-file-stix_1             | INFO:root:Listing Threat-Actors with filters null.
connector-export-file-stix_1             | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
connector-import-file-stix_1             | INFO:root:Listing Threat-Actors with filters null.
connector-mitre_1                        | INFO:root:Listing Threat-Actors with filters null.
connector-mitre_1                        | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
connector-import-file-pdf-observables_1  | INFO:root:Listing Threat-Actors with filters null.
connector-opencti_1                      | INFO:root:Listing Threat-Actors with filters null.

## Description

worker_3                                 | INFO:root:Listing Threat-Actors with filters null.
worker_3                                 | Traceback (most recent call last):
worker_3                                 |   File "worker.py", line 300, in <module>
worker_3                                 |     worker = Worker()
worker_3                                 |   File "worker.py", line 212, in __init__
worker_3                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_3                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 125, in __init__
worker_3                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_3                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
connector-opencti_1                      | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_1                                 | INFO:root:Listing Threat-Actors with filters null.
connector-import-file-stix_1             | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 300, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 212, in __init__
worker_1                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 125, in __init__
worker_1                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_1                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_2                                 | INFO:root:Listing Threat-Actors with filters null.
worker_2                                 | Traceback (most recent call last):
worker_2                                 |   File "worker.py", line 300, in <module>
worker_2                                 |     worker = Worker()
worker_2                                 |   File "worker.py", line 212, in __init__
worker_2                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_2                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 125, in __init__
worker_2                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_2                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

https://www.notion.so/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8

docker-compose --compatibility up

not working. opencti api is not reacheable.

**Comment by richard-julien** [comment]
Please provide the opencti platform logs through docker logs command

**Comment by oguzhansrky** [comment]
OpenCTI platform - docker container logs 

$ node --max_old_space_size=8192 build/index.js
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T11:45:27.542Z","data":{"reason":"Grakn seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T11:46:31.315Z","data":{"reason":"Grakn seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T11:47:37.245Z","data":{"reason":"Grakn seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T11:48:43.368Z","data":{"reason":"Grakn seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by richard-julien** [comment]
Grakn seems down > Check the grakn docker status/logs, try to restart it if he fails to start

**Comment by oguzhansrky** [comment]
Those made;

1) docker exec -it 00301de11942 / bin / bash 00301de11942 = graph container
2) bash docker-graph.sh
3) exit
4) docker ps

okay, everything works and opencti broadcasts on 4000 port.


But the current screen is stuck here.

The screen is completely white and the login screen did not come.

URL:  http://192.168.1.249:4000/login?redirectLogin=L2Rhc2hib2FyZA==

**Comment by oguzhansrky** [comment]
opencti-platform container logs

{"type":"READ_ERROR","operation_query":"query GetConnectors{connectors{id name config{uri listen push}}}","inner_relation_creation":0,"operation":"GetConnectors","time":1,"variables":{},"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at t (/opt/opencti/build/index.js:1:68687)","at m (/opt/opencti/build/index.js:1:68824)","at Ge.authenticationControl (/opt/opencti/build/index.js:1:210156)","at t.resolve (/opt/opencti/build/index.js:1:210836)","at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:275:18)","at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:122)","at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:241:48","at Generator.next (<anonymous>)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"]},"level":"error","message":"API Call"}
{"type":"READ_ERROR","operation_query":"query RootQuery{me{id name lastname language user_email capabilities{name id}}settings{...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}","inner_relation_creation":0,"operation":"RootQuery","time":2,"variables":{},"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at t (/opt/opencti/build/index.js:1:68687)","at m (/opt/opencti/build/index.js:1:68824)","at Ge.authenticationControl (/opt/opencti/build/index.js:1:210156)","at t.resolve (/opt/opencti/build/index.js:1:210836)","at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:275:18)","at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:122)","at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:241:48","at Generator.next (<anonymous>)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"]},"level":"error","message":"API Call"}
{"type":"READ_ERROR","operation_query":"query LoginQuery{settings{platform_demo platform_providers{name type provider}...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}","inner_relation_creation":0,"operation":"LoginQuery","time":4,"variables":{},"size":2,"error":{"data":{"reason":"[GRAKN] TakeReadTx error","category":"technical","grakn":"failed to connect to all addresses"},"stacktrace":["DatabaseError: A database error has occurred","at t (/opt/opencti/build/index.js:1:68687)","at l (/opt/opencti/build/index.js:1:69007)","at /opt/opencti/build/index.js:1:3807","at runMicrotasks (<anonymous>)","at processTicksAndRejections (internal/process/task_queues.js:93:5)","at async C (/opt/opencti/build/index.js:1:3890)","at async ie (/opt/opencti/build/index.js:1:18809)","at async p (/opt/opencti/build/index.js:1:139157)"]},"level":"error","message":"API Call"}
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T12:53:44.931Z","data":{"reason":"[GRAKN] TakeReadTx error","category":"technical","grakn":"failed to connect to all addresses"},"internalData":{}},"level":"error","message":"[OPENCTI] Authentication error 44d35b6e-1f1c-468b-9eab-3d60a6857ffa"}
{"type":"READ_ERROR","operation_query":"query GetConnectors{connectors{id name config{uri listen push}}}","inner_relation_creation":0,"operation":"GetConnectors","time":0,"variables":{},"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at t (/opt/opencti/build/index.js:1:68687)","at m (/opt/opencti/build/index.js:1:68824)","at Ge.authenticationControl (/opt/opencti/build/index.js:1:210156)","at t.resolve (/opt/opencti/build/index.js:1:210836)","at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:275:18)","at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:122)","at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:241:48","at Generator.next (<anonymous>)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"]},"level":"error","message":"API Call"}
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-06-05T12:53:46.079Z","data":{"reason":"[GRAKN] TakeReadTx error","category":"technical","grakn":"failed to connect to all addresses"},"internalData":{}},"level":"error","message":"[OPENCTI] Authentication error 44d35b6e-1f1c-468b-9eab-3d60a6857ffa"}
{"type":"READ_ERROR","operation_query":"query GetConnectors{connectors{id name config{uri listen push}}}","inner_relation_creation":0,"operation":"GetConnectors","time":1,"variables":{},"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at t (/opt/opencti/build/index.js:1:68687)","at m (/opt/opencti/build/index.js:1:68824)","at Ge.authenticationControl (/opt/opencti/build/index.js:1:210156)","at t.resolve (/opt/opencti/build/index.js:1:210836)","at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:275:18)","at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:122)","at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:241:48","at Generator.next (<anonymous>)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"]},"level":"error","message":"API Call"}

**Comment by ahmadmkhan1** [comment]
The issue exists in 3.3.2 also, with manual deployment on Ubuntu 20.04. [#917](https://github.com/OpenCTI-Platform/opencti/issues/917)

**Comment by SamuelHassine** [comment]
The problem should not be solved with the V4 that has just been released. Let us know if it's not the case.
