### ISSUE TITLE
Implement the RBAC system

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#75]
## Problem to Solve

Currently, only an admin and user (with write and read rights) mode exist. 

## Current Workaround

None

## Proposed Solution

Think and bootstrap an ACL system with a first objective of a read-only mode capability. 

## Additional Information

None.

**Comment by richard-julien** [comment]
@SamuelHassine I dont think readonly mode is what we want. Its more about fully handling create/modify/edit/delete rights.
