### ISSUE TITLE
Frontend loop on the user page due to an error on the graphql reply

### ISSUE THREAD

**Issue by secufred** [OpenCTI-Platform/opencti#750]
## Description

{ When going to the user page, the page is always loading ( in a loop). }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu using the opencti docker images  }
2. OpenCTI version: { 3.3.0 }
2a. Grakn version : { 1.7.1 }
3. OpenCTI client: { frontend }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { go on the user page and cluck on users -> /dashboard/settings/accesses/users?sortBy=user_email&orderAsc=false&searchTerm= }
2. page loading and the query to the frontent :  {  
```
POST /graphql HTTP/1.1
***

{"id":"UsersLinesPaginationQuery","query":"query UsersLinesPaginationQuery(\n  $search: String\n  $count: Int!\n  $cursor: ID\n  $orderBy: UsersOrdering\n  $orderMode: OrderingMode\n) {\n  ...UsersLines_data_2ltyuX\n}\n\nfragment UserLine_node on User {\n  id\n  name\n  user_email\n  firstname\n  external\n  lastname\n  created\n}\n\nfragment UsersLines_data_2ltyuX on Query {\n  users(search: $search, first: $count, after: $cursor, orderBy: $orderBy, orderMode: $orderMode) {\n    edges {\n      node {\n        id\n        name\n        firstname\n        lastname\n        ...UserLine_node\n        __typename\n      }\n      cursor\n    }\n    pageInfo {\n      endCursor\n      hasNextPage\n      globalCount\n    }\n  }\n}\n","variables":{"search":"","count":25,"cursor":null,"orderBy":"user_email","orderMode":"desc"}}
``` 
}

3. Reply{ ```
HTTP/1.1 400 Bad Request
***

{"errors":[{"message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2020-06-05T16:30:14.878Z","data":{"reason":"No reason specify","category":"technical"}}]}
``` }

## Expected Output

{ the list of users }

## Actual Output

{ re loop in reload. }

**Comment by secufred** [comment]
Backend error message : 
`{
  "type": "READ_ERROR",
  "operation_query": "query UsersLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:UsersOrdering$orderMode:OrderingMode){...UsersLines_data_2ltyuX}fragment UserLine_node on User{id name user_email firstname external lastname created}fragment UsersLines_data_2ltyuX on Query{users(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode){edges{node{id name firstname lastname ...UserLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}",
  "inner_relation_creation": 0,
  "operation": "UsersLinesPaginationQuery",
  "time": 0,
  "variables": {
    "search": "",
    "count": 25,
    "cursor": null,
    "orderBy": "user_email",
    "orderMode": "desc"
  },
  "size": 80,
  "error": {
    "stacktrace": [
      "GraphQLError: Variable \"$orderBy\" got invalid value \"user_email\"; Expected type UsersOrdering. Did you mean email?",
      "at /opt/opencti/node_modules/graphql/execution/values.js:114:15",
      "at coerceInputValueImpl (/opt/opencti/node_modules/graphql/utilities/coerceInputValue.js:154:5)",
      "at coerceInputValue (/opt/opencti/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
      "at _loop (/opt/opencti/node_modules/graphql/execution/values.js:107:69)",
      "at coerceVariableValues (/opt/opencti/node_modules/graphql/execution/values.js:119:16)",
      "at getVariableValues (/opt/opencti/node_modules/graphql/execution/values.js:48:19)",
      "at buildExecutionContext (/opt/opencti/node_modules/graphql/execution/execute.js:184:61)",
      "at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:89:20)",
      "at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:64:35)",
      "at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:241:48",
      "at Generator.next (<anonymous>)",
      "at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
      "at new Promise (<anonymous>)",
      "at __awaiter (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
      "at execute (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:220:20)",
      "at Object.<anonymous> (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:160:42)"
    ]
  },
  "level": "error",
  "message": "API Call"
}`

**Comment by secufred** [comment]
Issue _solved_ by changing the request to the server ( removed the user_email ) then changed the orderby by licking on an other column. still no idea how my browser**s**   had that orderby user_email

**Comment by richard-julien** [comment]
Thanks for the report. Bug appears when clicking on the email column.
