### ISSUE TITLE
Add export in PNG format for knowledge display for all types of entities

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#752]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It would be useful to be able to export in one click any display in the knowledge tab of any type of entity in OpenCTI (for instance : list of campaigns by a malware, list of vulnerabilities used by the malware, list of intrusion sets targeting a sector etc.), as it is already implemented in some.

## Current Workaround

Scripting to export the list or make screenshots.

**Comment by SamuelHassine** [comment]
Hello Manon,

As we really dont know which kind of colors / representation of the knowledge will be necessary to an organizatrion. We decided to provide ad-hoc scripts for data visualisation and build beautiful images based on OpenCTI data but this will not be part of the core platform.

Kind regards,
Samuel
