### ISSUE TITLE
External references & reports : simplification

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/opencti#754]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When creating an external reference for a report, giving a name to this external reference is mandatory. This mandatory extra step is in many cases not useful.
Furthermore, when the external reference is created, the user also have to select it to have it attached to the report. This should be done by default.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

1. Inserting the URL should suffice to enter an external reference (giving it a name should be optional)
2. There should not be the need to click on the newly created external reference to attach it to the report. It should be attached to the report by default.

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello Frederic,

We have implemented the automatic selection of a created external reference so now we avoid the additional click after the creation. For your first point I'm sorry but "Source name" will remain mandatory as it is mandatory in STIX 2.1 (https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_bajcvqteiard).

Kind regards,
Samuel
