### ISSUE TITLE
OpenCTI Virtual Template Connection Issue

### ISSUE THREAD

**Issue by PandaLyfe** [OpenCTI-Platform/opencti#757]
I am trying to install the virtual template for OpenCTI in VirtualBox, but I am receiving an error when attempting to access the platform. 

Error Message: "This site can’t be reached x.x.x.x refused to connect."

I used the instructions provided in the URL below and nothing more. 

URL: https://www.notion.so/Virtual-machine-template-1789b4442b414dbf87f748db51c85aa5

Any assistance will be appreciated and please let me know if additional information is needed.

**Comment by 1984oran** [comment]
I have the same issue.

**Comment by tushRana** [comment]
Getting same issue... IP is getting assigned to the machine. But hitting the IP at 8080 shows ERR_CONNECTION_REFUSED

**Comment by SamuelHassine** [comment]
The virtual machine template has been rewritten in V4.

**Comment by ramagr** [comment]
the issue still persists, can you pls check?

**Comment by shiblovich** [comment]
I have the same issue ..
