### ISSUE TITLE
OpenCTI-AlienVault Connecter data import issue

### ISSUE THREAD

**Issue by highkay** [OpenCTI-Platform/opencti#758]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I found the AlientVault connecter import the CVE data as type "malware".

## Expected Output

The CVE data should be imported as type "vulnerability"

## Actual Output

The CVE data is imported as type "malware"

**Comment by maertv** [comment]
Please provide addition details:
* AlienVault connector version.
* AlienVault connector configuration.
* Pulse(s) that is(are) imported incorrectly.

**Comment by highkay** [comment]
sorry. The imported data is correct.
