### ISSUE TITLE
GraphQL initialization fail

### ISSUE THREAD

**Issue by Anthons-an** [OpenCTI-Platform/opencti#762]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

With the latest version of OpenCTI(3.3), I'm facing the following error after all necessary containers were up:
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-06-19T07:00:06.980Z"}

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 
2. OpenCTI version: OpenCTI 3.3
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

OpenCTI complains with the following error:
$ sudo yarn start
yarn run v1.22.4
$ webpack --mode development --max_old_space_size=8192

webpack is watching the files…

✔ Compiled successfully!
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-06-19T07:00:04.905Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-06-19T07:00:04.939Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-06-19T07:00:04.959Z"}
{"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-06-19T07:00:04.981Z"}
{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-06-19T07:00:05.028Z"}
{"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-06-19T07:00:05.036Z"}
{"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-06-19T07:00:05.304Z"}
{"level":"info","message":"[INIT] > Existing platform detected, migration...","timestamp":"2020-06-19T07:00:05.493Z"}
{"level":"info","message":"[INIT] > Grakn schema loaded","timestamp":"2020-06-19T07:00:06.922Z"}
{"level":"info","message":"[INIT] > Elasticsearch indexes loaded","timestamp":"2020-06-19T07:00:06.944Z"}
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-06-19T07:00:06.980Z"}

**Comment by bpna** [comment]
check it out it's happening again 
![Screen Shot 2020-08-19 at 2 42 08 PM](https://user-images.githubusercontent.com/3276629/90687757-9684a280-e22a-11ea-83e8-28f42e7fde9c.png)

**Comment by Xmansec** [comment]
It still has this error in version 3.3.2:
`{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-11-05T02:48:37.007Z","data":{"reason":"Grakn seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-11-05T02:48:37.008Z"}`

Here is my docker containers:
![image](https://user-images.githubusercontent.com/17794892/98195130-f3efdc00-1f5b-11eb-9c35-6d4920d3935d.png)

In fact, I also saw the log that grakn started:
`grakn_1                                  | Starting Storage..........SUCCESS
docker_worker_2 exited with code 0
grakn_1                                  | Starting Grakn Core Server.....SUCCESS`
