### ISSUE TITLE
Clarification on MITRE synchronisation

### ISSUE THREAD

**Issue by blabut** [OpenCTI-Platform/opencti#763]
On a fresh install, I can see a lot of data coming from the MITRE dataset, for instance TTPs or malwares. However, when navigating to /dashboard/data/connectors, the MITRE connector does not seem to be registered. Does it mean that by default, a fresh install comes with "static" data from MITRE at the time of install ? Would installing the connector mean having this data update on a regular basis ?

Thanks a lot !

**Comment by richard-julien** [comment]
Hi @paupaulaz, at platform init we create some basic information (admin, roles, capa, marking defs, ..) but no malware or stuff from the MITRE.

**Comment by SamuelHassine** [comment]
You have to use the MITRE Connector to import MITRE data.
