### ISSUE TITLE
Setting up OpenCTI using Docker with Ldap

### ISSUE THREAD

**Issue by Sreejith2k** [OpenCTI-Platform/opencti#764]
**Description**
--------------------------------------------------------------------------------
Setting up OpenCTI using Docker and login using ldap

**Environment**
--------------------------------------------------------------------------------

Docker version 19.03.11, build 42e35e61f3
OpenCTI version: { 3.3.1 }
OpenCTI client: { frontend}

**Reproducable steps**
--------------------------------------------------------------------------------
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.7.2
    ports:
      - 48555:48555
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:6.0.3
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
  opencti:
    image: opencti/platform:3.3.1
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=demo
      - APP__ADMIN__TOKEN=c593484c-b151-11ea-b3de-0242ac130004
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - PROVIDERS__LDAP__STRATEGY=LdapStrategy
      - PROVIDERS__LDAP__CONFIG__URL=ldap://dc01:389
      - PROVIDERS__LDAP__CONFIG__BIND_DN=CN=Opencti,OU=Administration,DC=abc,DC=com
      - PROVIDERS__LDAP__CONFIG__BIND_CREDENTIALS=XXXXX
      - PROVIDERS__LDAP__CONFIG__SEARCH_BASE=OU=User Account,DC=abc,DC=com
      - PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=(sAMAccountName={{Opencti}})"
      - PROVIDERS__LDAP__CONFIG__MAIL_ATTRIBUTE=mail
      - PROVIDERS__LDAP__CONFIG__ALLOW_SELF_SIGNED=true
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy

**Expected Output**
--------------------------------------------------------------------------------
Users in the OU should be able to login

**Actual Output**
--------------------------------------------------------------------------------
name or password is wrong. 
I can use the local user and pwd to login. Only LDAP part is not working

**Comment by SamuelHassine** [comment]
Hello @Sreejith2k, could you please set the `- APP__LOGS_LEVEL=` to `debug` and provide us with the log output of the platform when you try to login?

**Comment by Sreejith2k** [comment]
opencti_1                                | {"error":null,"info":{"message":"Invalid username/password"},"level":"warn","message":"[AUTH ERROR] > ldapauth","timestamp":"2020-06-23T13:46:12.830Z

**Comment by Sreejith2k** [comment]
The issue fixed by itself. Bit strange. Thanks @SamuelHassine for your help. :)

**Comment by Sreejith2k** [comment]
Ahh sorry forgot to add...

Instead of using - PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=(sAMAccountName={{Opencti}})"
pls use- PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=(sAMAccountName={{username}}) this fixed the issue :)
