### ISSUE TITLE
Yarn serv error

### ISSUE THREAD

**Issue by rmsferreira** [OpenCTI-Platform/opencti#767]
HI.
I install the system using the cript provide in yous docs.
When I start the the sistem a receive the error:
yarn serv
yarn run v1.22.4
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-06-24T12:57:41.342Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-06-24T12:57:41.391Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-06-24T12:57:41.414Z"}
{"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-06-24T12:57:41.436Z"}
{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-06-24T12:57:41.615Z"}
{"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-06-24T12:57:41.625Z"}
{"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-06-24T12:57:42.010Z"}
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-06-24T12:57:42.054Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I confirm that my minio is online and I can access to minio sevrer by browser

**Comment by SamuelHassine** [comment]
Hello @rmsferreira,

Which Grakn Core version are you using?

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
I close this issue for inactivity. Please feel free to re-open if you still encounter any problem.

**Comment by smclinden** [comment]
Getting this same issue. Grakn core 1.7.2. I am trying to bring up OpenCTI 3.3.2 in order to migrate to 4.0.
