### ISSUE TITLE
Error on frontend - Connecxtor&workers

### ISSUE THREAD

**Issue by rmsferreira** [OpenCTI-Platform/opencti#770]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS Ubunut 20.04
2. OpenCTI version: 3.3.2
3. OpenCTI client:  frontend 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Access to the page connectors&workers

## Actual Output

{"type":"READ_ERROR","operation_query":"query WorkersStatusQuery($prefix:String){...WorkersStatus_data_3WHZd4}fragment WorkersStatus_data_3WHZd4 on Query{rabbitMQMetrics(prefix:$prefix){consumers overview{queue_totals{messages_ready}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":10,"variables":{"prefix":"import-connectors"},"size":30,"error":{"stacktrace":["Error: Request failed with status code 401","at createError (/opt/opencti/node_modules/axios/lib/core/createError.js:16:15)","at settle (/opt/opencti/node_modules/axios/lib/core/settle.js:17:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/node_modules/axios/lib/adapters/http.js:236:11)","at IncomingMessage.emit (events.js:327:22)","at endReadableNT (_stream_readable.js:1221:12)","at processTicksAndRejections (internal/process/task_queues.js:84:21)"]},"level":"error","message":"API Call","timestamp":"2020-06-25T20:52:48.396Z"}

 
![Capture](https://user-images.githubusercontent.com/22968643/85794544-b8800e00-b72e-11ea-910b-cb37470b635f.PNG)

**Comment by SamuelHassine** [comment]
Hello,

`Request failed with status code 401` means that the credentials for RabbitMQ Management Plugin API are not valid in your configuration.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Is your problem now solved?

**Comment by richard-julien** [comment]
Close for inactivity.
