### ISSUE TITLE
GraphQL initialization fail

### ISSUE THREAD

**Issue by tinamina12** [OpenCTI-Platform/opencti#776]
{ After installing every dependency and running yarn serv i get the graphql initialization fail error. }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 18 }
2. OpenCTI version: {opencti-release-3.3.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { yarn serv }

## Expected Output

{ should be running fine }

## Actual Output

![yarn](https://user-images.githubusercontent.com/32898278/86153651-6dde0780-bb1b-11ea-9d74-6821a1527752.png)

**Comment by p-rs** [comment]
I had this exact issue where my Grakn updated to 1.8.0.  I downgraded to the required version of 1.7.2 and it started working again.

edit:
grakn-core-server="1.7.2"
grakn-console="1.0.5"
grakn-core-all="1.7.2"

**Comment by tinamina12** [comment]
Thank you, the issue is solved :)
