### ISSUE TITLE
Issue with GRAKN - Invalid argument while starting OPENCTI

### ISSUE THREAD

**Issue by mcitarella00** [OpenCTI-Platform/opencti#780]
I am trying to complete the install for OPENCTI on a Linux RedHat 7 box. Running into the issue below - error: [GRAKN] Write error > 3 INVALID_ARGUMENT after running yarn serv command.

Any help or guidance is appreciated. From the wording it appears to be some Javascript error, so I've hit a roadblock.

[root@servername opencti]# yarn serv
yarn run v1.22.4
$ node --max_old_space_size=8192 build/index.js
info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
info: [PRE-CHECK] > Python3 is available
**error: [GRAKN] Write error > 3 INVALID_ARGUMENT:  {"code":3,"metadata":{"_internal_repr":{},"flags":0},"details":"","stack":"Error: 3 INVALID_ARGUMENT: \n    at Object.exports.createStatusError (/apps/openctifiles/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}**
info: [INIT] > Grakn schema loaded
info: [INIT] > Elasticsearch indexes loaded
info: [MIGRATION] > Starting migration process
**error: [GRAKN] executeRead error > 3 INVALID_ARGUMENT:  {"code":3,"metadata":{"_internal_repr":{},"flags":0},"details":"","stack":"Error: 3 INVALID_ARGUMENT: \n    at Object.exports.createStatusError (/apps/openctifiles/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}**
(node:25113) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: 
    at Object.exports.createStatusError (/apps/openctifiles/opencti/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)
    at InterceptingListener._callNext (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:618:8)
    at /apps/openctifiles/opencti/node_modules/grpc/src/client_interceptors.js:1127:18
(node:25113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SamuelHassine** [comment]
Hello,

What is the version of your Grakn Core Server?

Kind regards,
Samuel

**Comment by mcitarella00** [comment]
Hi Samuel, The version we are on is  Version:  1.7.1
thanks!

**Comment by richard-julien** [comment]
Hi @mcitarella00 , it looks like a manual deployment. Can you also give the version of opencti you try to compile/run? Do you checkout the code or use a specific release? Thanks

**Comment by richard-julien** [comment]
Close for inactivity. Please reopen if needed
