### ISSUE TITLE
yarn serv did not work

### ISSUE THREAD

**Issue by 547601659** [OpenCTI-Platform/opencti#784]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

yarn run v1.22.4
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-07-10T04:32:31.175Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-07-10T04:32:31.216Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-07-10T04:32:31.238Z"}
{"error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9000},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-07-10T04:32:31.246Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Current Workaround

{ Please describe how you currently solve or work around this problem, given OpenCTI's limitation. }

## Proposed Solution

open it correctly

## Additional Information

just as above

**Comment by cvdsouza** [comment]
This error is because OpenCTI couldn't connect to minIO server over port 9000. Please make sure minIO is running and try again.

**Comment by 547601659** [comment]
got it .thanks
