### ISSUE TITLE
Automatically Assign Sectors

### ISSUE THREAD

**Issue by ghost** [OpenCTI-Platform/opencti#787]
It would be extremely useful to be able to search for reports related to a particular sector, as possible in the OpenCTI demo. Therefore our team can easily find reports that are directly related to our sector.

However, it is currently a manual process to assign a sector to a report which is not feasible in a production environment, with 1,000s of reports coming in each day.

Would it possible to have the program automatically assign sectors based on report contents such as it mentioning Energy or telecoms.

**Comment by SamuelHassine** [comment]
Hello @40339109,

This will be implemented as an enrichment connector for PDF report, work is ongoing by @amr-cossi. Please refer to https://github.com/OpenCTI-Platform/connectors/issues/304.

Kind regards,
Samuel
