### ISSUE TITLE
Targeted organisations should be able to connect to locations/regions

### ISSUE THREAD

**Issue by espenfjo** [OpenCTI-Platform/opencti#788]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

When I am creating a report describing how a threat actor/intrusion set is targeting a specific sector I need to add details about where this sector is located as not all regions/countries are being targeted by this specific threat.

While I can create a link from the "targets" relation to a location this information is not being presented properly in the GUI. 
Right now, if I go to a country/region I am not able to view targeted sectors. Same the other way around, if I go to a sector I am not able to see in which countries this sector is being targeted.

## Current Workaround

None.

## Proposed Solution

Add GUI elements to utilize the "targets" -> "located in" relationship. Ideally a threat actor/intrusion set should have this overview, as well as Sector/Organization/Location/Region.

## Additional Information

https://demo.opencti.io/dashboard/reports/all/b77665cd-8bdf-4846-80eb-c9a9032ee18a/knowledge - Demo graph

**Comment by SamuelHassine** [comment]
Thanks for this issue. This will be implemented through the future inference system.

**Comment by SamuelHassine** [comment]
This has been implemented in the `Location of targets` rule that will be released in 5.0.0.
