### ISSUE TITLE
GraphQL initialization fail: While Grakn and Elasticsearch running on host, everything else on docker.

### ISSUE THREAD

**Issue by analyst321** [OpenCTI-Platform/opencti#793]
## Description

I have Grakn and Elasticsearch running on osx catalina host. Everything else is on docker. Opencti keeps throwing the following error.

> yarn run v1.19.1
> $ node --max_old_space_size=8192 build/index.js
> {"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-07-20T21:15:54.614Z"}
> {"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-07-20T21:15:54.651Z"}
> {"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-07-20T21:15:54.676Z"}
> {"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-07-20T21:15:54.696Z"}
> {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-07-20T21:15:54.867Z"}
> {"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-07-20T21:15:54.876Z"}
> {"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-07-20T21:15:55.219Z"}
> {"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-07-20T21:15:55.250Z"}
> error Command failed with exit code 1.

## Environment

1. OS: MacOS Catalina 10.15.6
2. OpenCTI version: 3.3.2
3. OpenCTI client: frontend
4. Other environment details: Grakn and Elasticsearch running on host (native). Everything else on docker. 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1- git clone https://github.com/OpenCTI-Platform/docker.git
2- Setup the docker-compose yml files as shown below.
3- Install grakn-core and elasticsearch-full via homebrew. Check ports 9200, 48555 are up.
4- docker-compose --compatibility up

## Expected Output

OpenCTI framework should be up and running. WebUI should be accessible.

## Actual Output

OpenCTI keeps erroring as described and attempting to restart.
 
## Additional information

grakn-core version 1.8.0
elasticsearch version 7.8.0

Docker compose files listed below.
docker-compose.yml
> version: '3'
> services:
>   minio:
>     image: minio/minio:RELEASE.2020-05-16T01-33-21Z
>     volumes:
>       - s3data:/data
>     ports:
>       - "9000:9000"
>     environment:
>       MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
>       MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
>     command: server /data
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
>     restart: always
>   redis:
>     image: redis:6.0.5
>     restart: always
>   rabbitmq:
>     image: rabbitmq:3.8-management
>     environment:
>       - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
>       - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
>     restart: always
>   opencti:
>     image: opencti/platform:3.3.2
>     environment:
>       - APP__PORT=8080
>       - APP__ADMIN__EMAIL=email@email.com
>       - APP__ADMIN__PASSWORD=admin
>       - APP__ADMIN__TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - APP__LOGS_LEVEL=debug
>       - APP__LOGS=./logs
>       - APP__REACTIVE=true
>       - APP__COOKIE_SECURE=false
>       - GRAKN__HOSTNAME=host.docker.internal
>       - GRAKN__PORT=48555
>       - GRAKN__TIMEOUT=30000
>       - REDIS__HOSTNAME=redis
>       - REDIS__PORT=6379
>       - ELASTICSEARCH__URL=http://host.docker.internal:9200
>       - MINIO__ENDPOINT=minio
>       - MINIO__PORT=9000
>       - MINIO__USE_SSL=false
>       - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
>       - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}
>       - RABBITMQ__HOSTNAME=rabbitmq
>       - RABBITMQ__PORT=5672
>       - RABBITMQ__PORT_MANAGEMENT=15672
>       - RABBITMQ__MANAGEMENT_SSL=false
>       - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
>       - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
>       - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
>     ports:
>       - "8080:8080"
>     depends_on:
>       - redis
>       - minio
>       - rabbitmq
>     restart: always
>   worker:
>     image: opencti/worker:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - WORKER_LOG_LEVEL=info
>     depends_on:
>       - opencti
>     deploy:
>       mode: replicated
>       replicas: 3
>     restart: always
>   connector-export-file-stix:
>     image: opencti/connector-export-file-stix:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=5e070500-5c10-4aea-86d6-21ec477bc1e2 # Valid UUIDv4
>       - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
>       - CONNECTOR_NAME=ExportFileStix2
>       - CONNECTOR_SCOPE=application/json
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_LOG_LEVEL=info
>     restart: always
>   connector-export-file-csv:
>     image: opencti/connector-export-file-csv:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=2b7efd09-798c-437b-b83a-32affd6cfbc2 # Valid UUIDv4
>       - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
>       - CONNECTOR_NAME=ExportFileCsv
>       - CONNECTOR_SCOPE=application/csv
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_LOG_LEVEL=info
>     restart: always
>   connector-import-file-stix:
>     image: opencti/connector-import-file-stix:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=0dce570b-7461-4cc8-b7da-9b29d70fd98e # Valid UUIDv4
>       - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
>       - CONNECTOR_NAME=ImportFileStix2
>       - CONNECTOR_SCOPE=application/json
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_LOG_LEVEL=info
>     restart: always
>   connector-import-file-pdf-observables:
>     image: opencti/connector-import-file-pdf-observables:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=ccaa2157-5905-4c8d-b334-d695822b8ced # Valid UUIDv4
>       - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
>       - CONNECTOR_NAME=ImportFilePdfObservables
>       - CONNECTOR_SCOPE=application/pdf
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_LOG_LEVEL=info
>       - PDF_OBSERVABLES_CREATE_INDICATOR=False
>     restart: always
>   connector-opencti:
>     image: opencti/connector-opencti:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=0a78b948-4e1b-4e71-a640-0356e0f22762 # Valid UUDv4
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=OpenCTI
>       - CONNECTOR_SCOPE=identity,sector,region,country,city
>       - CONNECTOR_CONFIDENCE_LEVEL=5
>       - CONNECTOR_UPDATE_EXISTING_DATA=true
>       - CONNECTOR_LOG_LEVEL=info
>       - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
>       - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
>       - CONFIG_INTERVAL=7 # Days
>     restart: always
>   connector-mitre:
>     image: opencti/connector-mitre:3.3.2
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=b0016a5b-8746-4acc-bfde-8afda3023fab # Valid UUDv4
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=MITRE ATT&CK
>       - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_UPDATE_EXISTING_DATA=true
>       - CONNECTOR_LOG_LEVEL=info
>       - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
>       - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
>       - MITRE_INTERVAL=7 # Days
>     restart: always
>   connector-virustotal:
>     image: opencti/connector-virustotal:3.3.1
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=63384ce6-3855-4ca1-82f3-1daf2cda92b1
>       - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
>       - CONNECTOR_NAME=VirusTotal
>       - CONNECTOR_SCOPE=file-md5,file-sha1,file-sha256
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_LOG_LEVEL=info
>       - VIRUSTOTAL_TOKEN=xxxxxx
>       - VIRUSTOTAL_MAX_TLP=TLP:AMBER
>     restart: always
>   connector-malpedia:
>     image: opencti/connector-malpedia:3.3.1
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=804ee9c8-d4d9-40df-b8a1-17ac2a1b65dc
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=Malpedia
>       - CONNECTOR_SCOPE=malpedia
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_UPDATE_EXISTING_DATA=false
>       - CONNECTOR_LOG_LEVEL=debug
>       - MALPEDIA_AUTH_KEY=xxxxxxx
>       - MALPEDIA_INTERVAL_SEC=86400 # Run once every day
>       - MALPEDIA_IMPORT_INTRUSION_SETS=true
>       - MALPEDIA_IMPORT_YARA=true
>     restart: always
>   connector-alienvault:
>     image: opencti/connector-alienvault:3.3.1
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=2b2aec4b-5d1d-4ac7-8fed-aa6afa60c346
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=AlienVault
>       - CONNECTOR_SCOPE=alienvault
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_UPDATE_EXISTING_DATA=false
>       - CONNECTOR_LOG_LEVEL=info
>       - ALIENVAULT_BASE_URL=https://otx.alienvault.com
>       - ALIENVAULT_API_KEY=xxxxxxx
>       - ALIENVAULT_TLP=White
>       - ALIENVAULT_PULSE_START_TIMESTAMP=2020-05-01T00:00:00 # BEWARE! Could be a lot of pulses!
>       - ALIENVAULT_REPORT_TYPE=Threat Report
>       - ALIENVAULT_REPORT_STATUS=New
>       - ALIENVAULT_GUESS_MALWARE=true                       # Use tags to guess malware.
>       - ALIENVAULT_GUESS_CVE=true                           # Use tags to guess CVE.
>       - ALIENVAULT_INTERVAL_SEC=1800
>     restart: always
>   connector-cve:
>     image: opencti/connector-cve:3.3.1
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=39de48b1-acb8-45f0-a54b-9cd584f79562
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=Common Vulnerabilities and Exposures
>       - CONNECTOR_SCOPE=identity,vulnerability
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_UPDATE_EXISTING_DATA=true
>       - CONNECTOR_LOG_LEVEL=info
>       - CVE_IMPORT_HISTORY=true # Import history at the first run (after only recent), reset the connector state if you want to re-import
>       - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
>       - CVE_HISTORY_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/
>       - CVE_INTERVAL=7 # Days
>     restart: always
>   connector-misp:
>     image: opencti/connector-misp:3.3.1
>     environment:
>       - OPENCTI_URL=http://opencti:8080
>       - OPENCTI_TOKEN=b331dcea-f9fb-4a56-a88e-9ca566b1936b
>       - CONNECTOR_ID=62c4353b-1bc6-46c3-b17b-85cdf4699ab3
>       - CONNECTOR_TYPE=EXTERNAL_IMPORT
>       - CONNECTOR_NAME=MISP
>       - CONNECTOR_SCOPE=misp
>       - CONNECTOR_CONFIDENCE_LEVEL=3
>       - CONNECTOR_UPDATE_EXISTING_DATA=false
>       - CONNECTOR_LOG_LEVEL=info
>       - MISP_URL=https://xxxxxx # Required
>       - MISP_KEY=xxxxxx # Required
>       - MISP_SSL_VERIFY=False # Required
>       - MISP_CREATE_REPORTS=True # Required, create report for MISP event
>       - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
>       - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
>       - MISP_IMPORT_TAGS= # Optional, list of tags used for import events
>       - MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
>       - MISP_INTERVAL=1 # Required, in minutes
>     restart: always
> volumes:
>   s3data:

docker-compose-dev.yml
> version: '3'
> services:
>   opencti-dev-redis:
>     container_name: opencti-dev-redis
>     image: redis:6.0.5
>     restart: always
>     ports:
>       - 6379:6379
>   opencti-dev-minio:
>     container_name: opencti-dev-minio
>     image: minio/minio:RELEASE.2020-05-16T01-33-21Z
>     ports:
>       - "9000:9000"
>     environment:
>       MINIO_ACCESS_KEY: ChangeMeAccess
>       MINIO_SECRET_KEY: ChangeMeKey
>     command: server /data
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
>     restart: always
>   opencti-dev-rabbitmq:
>     container_name: opencti-dev-rabbitmq
>     image: rabbitmq:3.8-management
>     restart: always
>     ports:
>       - 5672:5672
>       - 15672:15672

**Comment by analyst321** [comment]
Ah my bad. The required grakn-core version is 1.7.2, just read from the manual deployment table. Downgraded and it works now. Before you close this issue a quick question.

The configuration that I am running this in (grakn/esearch native, everything else docker), I should be safely able to upgrade OpenCTI to newer versions without losing any data right? Thank you.

**Comment by analyst321** [comment]
While I am at it, if you could kindly answer one more question please. If the docker is shutdown/restarts while the initial transfer of data was ongoing for example from malpedia, mips, alienvault etc; these connectors do know to resume right? they won't either miss some data or just start from the very beginning again? 

Can't seem to figure this out from the dashboard when the docker is restarted.

**Comment by richard-julien** [comment]
Hi @analyst321 ,

> The configuration that I am running this in (grakn/esearch native, everything else docker), I should be safely able to upgrade OpenCTI to newer versions without losing any data right? Thank you.

Yes OpenCTI is able to upgrade and keep the data. But of course there is a "but" :) In next major version (v4) we decide to rewrite completely the model so the platform will not be able to just upgrade itself. To manage that they will give you a specific procedure to reinject your data if you really need to. See https://www.notion.so/luatix/OpenCTI-Version-4-15e68a60157742b29fdd809f2f4f8ebd

> If the docker is shutdown/restarts while the initial transfer of data was ongoing for example from malpedia, mips, alienvault etc; these connectors do know to resume right? they won't either miss some data or just start from the very beginning again?

It depends of the connector but yes it should be. OpenCTI provide an API for connector to store a state that can be used to manage this kind of problem. After checking the code, malpedia, misp and alienvault use it (you can check the code looking for usage of set_state and get_state functions.

**Comment by a-ml** [comment]
Hi all,

can anyone help me? because I'm having issue running the OpenCTI on **Ubuntu 18.04 LTS**

**Elasticsearch: 7.10.0**
**Redis 6.0.9** 
**minio version RELEASE.2020-12-03T05-49-24Z**
**grakn 1.8.4**

:~/bin/opencti$ sudo yarn serv
[sudo] password for suoprp01:
yarn run v1.22.5
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-12-10T07:51:27.546Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-12-10T07:51:27.611Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-12-10T07:51:27.628Z"}
{"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-12-10T07:51:27.643Z"}
{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-12-10T07:51:27.798Z"}
{"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-12-10T07:51:27.804Z"}
{"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-12-10T07:51:28.092Z"}
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-12-10T07:51:28.152Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by SamuelHassine** [comment]
The problem should not be solved with the V4 that has just been released. Let us know if it's not the case.
