### ISSUE TITLE
Export Course-Of-Action / Tools to STIX file don't work

### ISSUE THREAD

**Issue by JeromeSRT** [OpenCTI-Platform/opencti#794]
## Description

Export STIX files for Course-Of-Action and Tools are not created.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.
2. OpenCTI version: 3.3.2
3. OpenCTI client: frontend / web client / browser Ubuntu Web
4. Other environment details: grakn 1.7.2 / elastic 7.8.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Technics / Course Of Action or Tools / Export Icon / Plus Icon 
2. Choose Application/JSON in pop-up / Click on Create.

## Expected Output

Export STIX file would appear in the export zone on the right.

## Actual Output

Nothing
 
## Additional information

=> Logs from the export STIX file connector for Course Of Action
INFO:root:Reporting job e52fb277-10c6-4aa7-bf23-a588748fa4da with status progress...
INFO:root:Exporting list: Course-Of-Action/all to 2020-07-22T05:35:23.724Z_(Export File STIX)_course-of-action.json
INFO:root:Listing Course-Of-Actions with filters [].
INFO:root:{"errors":[{"message":"Unknown type \"CourseOfActionsFiltering\". Did you mean \"CoursesOfActionFiltering\", \"CoursesOfActionFilter\", \"CoursesOfActionOrdering\", \"StixRelationsFiltering\", or \"OrganizationsFiltering\"?","locations":[{"line":2,"column":46}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"courseOfActions\" on type \"Query\". Did you mean \"courseOfAction\" or \"coursesOfAction\"?","locations":[{"line":3,"column":17}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pycti/connector/opencti_connector_helper.py", line 100, in _data_handler
    messages = self.callback(json_data)
  File "./connectors/export-file-stix/src/export-file-stix.py", line 75, in _process_message
    bundle = self.helper.api.stix2.export_list(
  File "/usr/local/lib/python3.8/dist-packages/pycti/utils/opencti_stix2.py", line 1321, in export_list
    entities_list = do_list(
  File "/usr/local/lib/python3.8/dist-packages/pycti/entities/opencti_course_of_action.py", line 158, in list
    result["data"]["courseOfActions"], with_pagination
TypeError: 'NoneType' object is not subscriptable
INFO:root:Reporting job e52fb277-10c6-4aa7-bf23-a588748fa4da with status error...
INFO:root:Message (delivery_tag=5) processed, thread terminated

=> Logs from the export STIX file connector for Tools
INFO:root:Reporting job 48a5fc4b-fbf7-4ef7-93ed-c386aa1144ad with status progress...
INFO:root:Exporting list: Tool/all to 2020-07-22T05:22:04.635Z_(Export File STIX)_tool.json
INFO:root:Listing Tools with filters [].
ERROR:root:[opencti_tool] Missing parameters: id or filters
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pycti/connector/opencti_connector_helper.py", line 100, in _data_handler
    messages = self.callback(json_data)
  File "./connectors/export-file-stix/src/export-file-stix.py", line 75, in _process_message
    bundle = self.helper.api.stix2.export_list(
  File "/usr/local/lib/python3.8/dist-packages/pycti/utils/opencti_stix2.py", line 1354, in export_list
    entity_bundle = do_export(
  File "/usr/local/lib/python3.8/dist-packages/pycti/entities/opencti_tool.py", line 395, in to_stix2
    tool["id"] = entity["stix_id_key"]
TypeError: 'NoneType' object is not subscriptable
INFO:root:Reporting job 48a5fc4b-fbf7-4ef7-93ed-c386aa1144ad with status error...
INFO:root:Message (delivery_tag=3) processed, thread terminated

=> Logs from the opencti platform front end :
{"type":"READ_ERROR","operation_query":"query CourseOfActions($filters:[CourseOfActionsFiltering]$search:String$first:Int$after:ID$orderBy:CoursesOfActionOrdering$orderMode:OrderingMode){courseOfActions(filters:$filters search:$search first:$first after:$after orderBy:$orderBy orderMode:$orderMode){edges{node{id stix_id_key stix_label entity_type parent_types name alias description confidence graph_data created modified created_at updated_at createdByRef{node{id entity_type stix_id_key stix_label name alias description created modified ...on Organization{organization_class}}relation{id}}markingDefinitions{edges{node{id entity_type stix_id_key definition_type definition level color created modified}relation{id}}}tags{edges{node{id tag_type value color}relation{id}}}externalReferences{edges{node{id entity_type stix_id_key source_name description url hash external_id created modified}relation{id}}}}}pageInfo{startCursor endCursor hasNextPage hasPreviousPage globalCount}}}","inner_relation_creation":0,"operation":"Unspecified","time":30,"variables":{"filters":[],"search":"","first":500,"after":null,"orderBy":"name","orderMode":"asc"},"size":86,"error":{"stacktrace":["GraphQLError: Unknown type \"CourseOfActionsFiltering\". Did you mean \"CoursesOfActionFiltering\", \"CoursesOfActionFilter\", \"CoursesOfActionOrdering\", \"StixRelationsFiltering\", or \"OrganizationsFiltering\"?","at Object.NamedType (/usr/share/opencti/node_modules/graphql/validation/rules/KnownTypeNames.js:61:29)","at Object.enter (/usr/share/opencti/node_modules/graphql/language/visitor.js:324:29)","at Object.enter (/usr/share/opencti/node_modules/graphql/language/visitor.js:375:25)","at visit (/usr/share/opencti/node_modules/graphql/language/visitor.js:242:26)","at Object.validate (/usr/share/opencti/node_modules/graphql/validation/validate.js:73:24)","at validate (/usr/share/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)","at Object.<anonymous> (/usr/share/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)","at Generator.next (<anonymous>)","at fulfilled (/usr/share/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)","at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"level":"error","message":"API Call","timestamp":"2020-07-22T05:35:23.932Z"}

**Comment by SamuelHassine** [comment]
Tested in V4 and now perfectly working.
