### ISSUE TITLE
Upgrade from 3.0.3 to 3.3.2 and how to upgrade properly

### ISSUE THREAD

**Issue by toshiro92** [OpenCTI-Platform/opencti#795]
Hi! 

I'm planning to upgrade OpenCTI from version `3.0.3` to the latest available (`3.3.2`). OpenCTI is in a `Docker` environment, and I will first perform an upgrade in a test environment, before upgrading in production).

This will mean upgrading the following:

- **OpenCTI 3.0.3 --> 3.3.2**: Is it possible?
- **Elasticsearch 7.5.2 --> 7.8**: [This link](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html#setup-upgrade) and maybe [this post](https://discuss.elastic.co/t/how-to-properly-upgrade-elasticsearch-running-as-docker-containers/221711) for Docker
- **Grakn 1.6.2 --> 1.7.2**: According to release `3.3.0` of OpenCTI, migration is just to use the same grakn data, and change the version to 1.7.1. I assume I can be done the same way for 1.7.2, right?
- **RabbitMQ, Redis and Minio**: No persistency: Only the version will change inside the docker-compose.yml file

Do I need to first jump from `3.0.3` to `3.3.0`, and then upgrade directly to `3.3.2`? Upgrade release by release? Or directly jump from `3.0.3` to `3.3.2`?

Also, is there any documentation about how to properly upgrade depending on the version we are?

**Comment by SamuelHassine** [comment]
Hello @toshiro92 I advise you to wait for the V4, a migration script will be provided.
