### ISSUE TITLE
RFA: Assistance configuring how to register an internal OpenCTI instance with Azure AD

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#796]
Has anyone done this who is willing to share their experiences?

**Comment by richard-julien** [comment]
Hi @smclinden. Auth modes are documented here: https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#f8d2b2bae57b401ab0bebb8e18782696
For Azure AD, maybe you can configure an LDAP connection.

**Comment by richard-julien** [comment]
Close for inactivity. Feel free to recreate a ticket if you still have problem using ldap connection
