### ISSUE TITLE
The derived-from relationship is not supported for all STIX domain objects and cyber observables

### ISSUE THREAD

**Issue by sweet-mentat** [OpenCTI-Platform/opencti#7962]
## Description

I specifically want to have a "derived-from" relationship between two identity objects, but it would be great to get this relationship type supported for every SDO and SCO. According to the STIX 2.1 documentation (https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070612), this is supported. I saw that there was a prior issue submitted (https://github.com/OpenCTI-Platform/opencti/issues/1059) where the "derived-from" relationship was requested between two Indicator Objects, which was implemented. Can this please be expanded to all objects?

## Environment

1. OS (where OpenCTI server runs): Docker image
2. OpenCTI version: 6.2.3
3. OpenCTI client: frontend and python

**Comment by nino-filigran** [comment]
Fix: allow the creation of relation between 2 objects of the same type.
