### ISSUE TITLE
No port 8080 after installation

### ISSUE THREAD

**Issue by khaosus** [OpenCTI-Platform/opencti#799]
I have completed installation using this guide:
https://github.com/OpenCTI-Platform/docker 

There does not appear to be an open port 8080
I can browse to port 9000 (MinIO), it is empty.

### Environment

    OS (where OpenCTI server runs): Ubuntu 18.04
    OpenCTI version: 3.3.2
    OpenCTI client: frontend / web client / browser Ubuntu Web
    Other environment details: grakn 1.7.2 / elastic 7.8.0

### Details
netstat -al

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp        0      0 opencti:ssh             172.19.48.59:1083       ESTABLISHED
tcp        0      0 opencti:ssh             172.19.48.59:1114       ESTABLISHED
tcp        0      0 opencti:48046           opencti:2377            ESTABLISHED
tcp6       0      0 [::]:9000               [::]:*                  LISTEN
tcp6       0      0 [::]:2377               [::]:*                  LISTEN
tcp6       0      0 [::]:7946               [::]:*                  LISTEN
tcp6       0      0 [::]:48555              [::]:*                  LISTEN
tcp6       0      0 [::]:http-alt           [::]:*                  LISTEN
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
tcp6       0      0 opencti:2377            opencti:48046           ESTABLISHED
udp        0      0 0.0.0.0:4789            0.0.0.0:*
udp        0      0 localhost:domain        0.0.0.0:*
udp        0      0 opencti:bootpc          0.0.0.0:*
udp6       0      0 [::]:7946               [::]:*

docker container ls

CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                 PORTS                                                 NAMES
392afd22f126        opencti/connector-import-file-pdf-observables:3.3.2   "/entrypoint.sh"         16 seconds ago      Up 3 seconds                                                                 opencti_connector-import-file-pdf-observables.1.wfo03ll36d8usu6wtxdza4n0s
b4a8b6be0395        opencti/connector-export-file-stix:3.3.2              "/entrypoint.sh"         17 seconds ago      Up 2 seconds                                                                 opencti_connector-export-file-stix.1.ik3v7jl3bpl0zijdropnogvj3
41313de0b9bc        opencti/connector-import-file-stix:3.3.2              "/entrypoint.sh"         18 seconds ago      Up 5 seconds                                                                 opencti_connector-import-file-stix.1.idaigr7jwyi6slkxdb02u3n5g
58bbca595479        opencti/connector-mitre:3.3.2                         "/entrypoint.sh"         19 seconds ago      Up 8 seconds                                                                 opencti_connector-mitre.1.o5oslc3bdu8uy327uuy3kh63h
54b6609c1eff        opencti/connector-opencti:3.3.2                       "/entrypoint.sh"         20 seconds ago      Up 10 seconds                                                                opencti_connector-opencti.1.py03chbf19bcycsdamz7p7juo
eec1b46d60b2        docker.elastic.co/elasticsearch/elasticsearch:7.8.0   "/tini -- /usr/local…"   4 hours ago         Up 4 hours             9200/tcp, 9300/tcp                                    opencti_elasticsearch.1.su0toehofwytsfpkh6n0zko8z
235522be37ee        graknlabs/grakn:1.7.2                                 "./grakn-docker.sh"      4 hours ago         Up 4 hours             48555/tcp                                             opencti_grakn.1.3eoh1gny9pesb712mihpko18r
61e11e2bc8d2        redis:6.0.5                                           "docker-entrypoint.s…"   4 hours ago         Up 4 hours             6379/tcp                                              opencti_redis.1.vdd5jmx58m47t912dtv2ecggn
848002c7c707        rabbitmq:3.8-management                               "docker-entrypoint.s…"   4 hours ago         Up 4 hours             4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   opencti_rabbitmq.1.sjogc4wjs062400c9x046hr2o
7fc727a9d312        minio/minio:RELEASE.2020-05-16T01-33-21Z              "/usr/bin/docker-ent…"   4 hours ago         Up 4 hours (healthy)   9000/tcp                                              opencti_minio.1.fbzinn4so9u44g6gp5x869a5y
r

**Comment by ben12385** [comment]
Hi, port 8080 is usually rewritten as http-alt, if you want to see the port value instead of the name use netstat -aln. As for why you are unable to access the webpage, it can be a multitude of problems. You may want to let us know what is the setup you are using such as if you are running the linux on a vm?

**Comment by azzarin** [comment]
I have the same issue, i have tried this in Ubuntu Server 18 and 20. Both have the same issue. it looks like its nothing on port 8080. 9000 works fine. Im running the ubuntu server as an VM in Vmware ESXi . 

i have tried running the docker as guided and using Portainer. same issue. any cloys ? 

(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0    612 10.10.1.18:22           10.10.1.14:52013        ESTABLISHED -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::19000                :::*                    LISTEN      -                   
tcp6       0      0 :::9000                 :::*                    LISTEN      -                   
tcp6       0      0 :::2377                 :::*                    LISTEN      -                   
tcp6       0      0 :::7946                 :::*                    LISTEN      -                   
tcp6       0      0 :::48555                :::*                    LISTEN      -                   
tcp6       0      0 :::18000                :::*                    LISTEN      -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 10.10.1.18:68           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -                   
udp6       0      0 :::7946                 :::*                                -                   
raw6       0      0 :::58


ic9al6g4i84j        OpenCTI_opencti                                 replicated          0/1                 opencti/platform:3.3.2                                *:8080->8080/tcp

usually this is 1/1 i guesss, maybe this is the issue right now

I have changed ports to 4443 / 4443 
7gg4r7dyoy64        CTI_opencti                                 replicated          1/1                 opencti/platform:3.3.2 

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 10.10.1.18:22           10.10.1.14:53286        ESTABLISHED
tcp        0      0 10.10.1.18:41280        10.10.1.18:2377         ESTABLISHED
tcp6       0      0 :::19000                :::*                    LISTEN     
tcp6       0      0 :::2377                 :::*                    LISTEN     
tcp6       0      0 :::7946                 :::*                    LISTEN     
tcp6       0      0 :::48555                :::*                    LISTEN     
tcp6       0      0 :::18000                :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 10.10.1.18:2377         10.10.1.18:41280        ESTABLISHED
udp        0      0 127.0.0.53:53           0.0.0.0:*                          
udp        0      0 10.10.1.18:68           0.0.0.0:*                          
udp        0      0 0.0.0.0:4789            0.0.0.0:*                          
udp6       0      0 :::7946                 :::*                               
raw6       0      0 :::58                   :::*     

When i had 4443 / 8080 it did listen on 4443 and came up in the netstat command. 

BUMMER! after some times its again:
 7gg4r7dyoy64        CTI_opencti                                 replicated          0/1                 opencti/platform:3.3.2                                *:4443->4443/tcp


Im out of ideas. Im not a docker guru, but this seems like an isse. The VM they have provides does not listen on 8080 either. so i might think it is a an version issue.

**Comment by richard-julien** [comment]
Hi, do you still have the issue? Thanks

**Comment by azzarin** [comment]
> Hi, do you still have the issue? Thanks

No, I belive it had to do with the grakn failing somehow. 
Reinstalled grakn and it start working. Thanks

**Comment by richard-julien** [comment]
Ok thanks! We expect to have less problem with grakn starting in v4 (will be release with grakn 2.0)

**Comment by devanashisha** [comment]
OpenCTI Newbie:

I need help: i have setup Docker, installed Portainer - can access it by Web browser. Installed OpenCTI - now want to open OpenCTI - localhost:8080 (not working) :
[11:45 AM] devan naidoo
get error - https://my/ external ip:8080 (This site can’t be reached
20.12.60.197 took too long to respond.Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT
