### ISSUE TITLE
Cannot massively tag IoCs

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#807]
# Description

It is not possible to tag many IoCs with the same tag

# Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.2.2
	3. OpenCTI client: Platform

# Expected Output

To be able to select all the IoCs and tag them all at the same time
 
# Actual Output 

 Add tag one by one

**Comment by richard-julien** [comment]
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/771
