### ISSUE TITLE
Same language to report type and platform

### ISSUE THREAD

**Issue by manonviallet** [OpenCTI-Platform/opencti#809]
# Problem to Solve

The platform language is sometimes different from the "report" type (Internal Report, Threat Report, ...)
When adding a type of "report", you should be able to add it in English and French so that it is taken into account when changing the plateform's language

Settings/Tags & Attributes/Report types

# Current Workaround

Have the platform language in the same language as the report or observable types

**Comment by SamuelHassine** [comment]
@manonviallet: Report types can be customized in the administration panel and defined also in the configuration of the connectors. So it's not a built-in feature that can easily translated. Can you please tell us what prevent you from customizing your report types in administration and configure the connectors properly to use localized types?

**Comment by manonviallet** [comment]
@SamuelHassine this issue was opened first because we were having discrepancies in version because of traduction, and at the time it seemed like this could be included in the features to be translated, but we understand it is not the case for this functionnality, and with the new updates, it is much clearer. 

We can close this issue as it is no longer relevent.
