### ISSUE TITLE
Integrate with multiple MISP Instances

### ISSUE THREAD

**Issue by seifreed** [OpenCTI-Platform/opencti#81]
I would like to see the possibility to connect as many MISP instances as the admin desires. This could help people that have access to multiple of those instances.
 
## Problem to Solve

Nowadays only accepts connect to one MISP instance

## Proposed Solution

Add the possibility to connect more than one instance

**Comment by SamuelHassine** [comment]
This issues has been moved to [the connectors repository](https://github.com/OpenCTI-Platform/connectors/issues/8).
