### ISSUE TITLE
No container launched on OpenCTI OVA

### ISSUE THREAD

**Issue by JoshuaMart** [OpenCTI-Platform/opencti#819]
Hi,
I wanted to test OpenCTI by downloading the OVA, however after launching the VM the service doesn't seem to launch.

OpenCTI is not accessible via IP:8080, I guess this VM uses docker since the service is installed but no container is launched.
![](https://zupimages.net/up/20/32/6nr5.png)

I'm on Windows 10 with VirtualBox 6.0.22 and I use OpenCTI v3.0.2 OVA.

Regards,
Jomar

**Comment by VictorSalazar10** [comment]
I have the same problem. In this manual:
[https://www.notion.so/Virtual-machine-template-1789b4442b414dbf87f748db51c85aa5](url)

it does not indicate any additional process, which allows me to test the OPENCTI using the pre-configured VM
