### ISSUE TITLE
Export in STIX2 fail the official stix2-validator

### ISSUE THREAD

**Issue by chrisr3d** [OpenCTI-Platform/opencti#82]
Since I am the main developer of all the interactions between MISP and the different STIX formats, I have been working with STIX2 for a couple of months and after a quick review of the document produced via the openCTI export functionality, I saw some little issues.

Within the Oasis github page you can find a tool called [stix2-validator](https://github.com/oasis-open/cti-stix-validator) to find where the issues are.

Here are some ideas for a future improvement of the export capacities with openCTI:
- export some MISP format
- pay attention to the [stix2 python library](https://github.com/oasis-open/cti-python-stix2)

Do not hesitate to keep in touch with the MISP team if you have any question related to one of these two topics I just mentioned above, we would be happy to help

**Comment by SamuelHassine** [comment]
@chrisr3d: Thanks for your report. We will do a hotfix for that and fix the STIX2 errors in the export capabilities of the platform.
