### ISSUE TITLE
Problem in the OPENCTI VM, no service is running

### ISSUE THREAD

**Issue by VictorSalazar10** [OpenCTI-Platform/opencti#823]
358/5000
I downloaded the preconfigured opencti virtual machine (VM). I executed it however I cannot access the dashboard (http: // {IP_ADDRESS}: 8080). Apparently no process is running on the VM.
How can I fix it?
  
![opencti_capture](https://user-images.githubusercontent.com/36339680/90303832-303d0000-de77-11ea-8d9b-d3bc950224e0.PNG)
In Lima - Peru we are very interested in being able to use this tool.

**Comment by baquetraque** [comment]
Same issue here. Downloaded OVA yesterday : no socket listening on 8080

**Comment by cerelacrox** [comment]
Same issue. Looks like a simple problem with a docker certificate, however I have no docker experience.

`$ journalctl -u docker.service`
`...`
`error while loading TLS certificate in /var/lib/docker/swarm/certificates/swarm-node.crt: certificate (1 - psgxmd41unaqpf0s6wevr5toi) not valid after Wed, 20 May 2020 07:18:00 ...`

**Comment by jigsawsecurity** [comment]
Should also add ifconfig so that you can easily modify network without having to edit files. Just a suggestion.

**Comment by SamuelHassine** [comment]
The virtual machine template has been rewritten in V4.
