### ISSUE TITLE
Improve federated SSO authentication

### ISSUE THREAD

**Issue by dcode** [OpenCTI-Platform/opencti#827]
## Problem to Solve

I would like to use the GitHub or Google providers to authenticate users, but I would like to limit the scope of successful authentications. Namely, I don't want to give users access just because they have a GitHub account. The GitHub response includes `profile`, which also lists things like which organization or team a user belongs to. It would be nice to be able to apply a filter based on that.

## Current Workaround

Using local authentication only.

## Proposed Solution

Implement the callback in [passport](http://www.passportjs.org/packages/passport-github/) allowing sufficient filters for these attributes.

## Additional Information

None

**Comment by richard-julien** [comment]
Hi @dcode ,
Implemented for:
* Github: Picking organizations `"organizations": ["OpenEx-Platform"]` 
* Google: Picking domains `"domains": ["gmail.com"]`
* OpenID: Picking roles `"roles": ["opencti_access"]`

Not sure about the google one that is pretty basic. If you need more with role management i need more information and a test environment to develop it.

**Comment by dank07** [comment]
Helllo @richard-julien,
How could I use the definition of Google domains if I'm using the platform through Docker?

For example, instead of using `"domains": ["gmail.com"]` domains, I'm planning to only authorize `"domains": ["organization.com"]` using GSUITE oauth without allowing any public gmail address.

**Comment by dcode** [comment]
@dank07 I've been able to control scope pretty well using GSuite by putting the service behind an "Identity Aware Proxy" (IAP). The upside and downside, is that authentication and authorization happens before the user ever hits OpenCTI. The good part is that this prevents random winds of the Internet from banging on your front door. The downside is that users have to authenticate to the IAP, then click the "Google" button on the OpenCTI login page before they get to their dashboard. This has been a reasonable compromise though. 

For configuring the auth providers in a container, I use environment vars. I _think_ the env var you need to set is `PROVIDERS__GOOGLE__CONFIG__DOMAINS`. To pass that to Docker (like in a compose file), you'd do:

``` 
"PROVIDERS__GOOGLE__CONFIG__DOMAINS=[\"organization.com\"]"
```

**Comment by dank07** [comment]
Great!
Thanks for the help.
I'm gonna try it in both ways to see how it works.  :)
