### ISSUE TITLE
grakn not loading

### ISSUE THREAD

**Issue by zeroploitable** [OpenCTI-Platform/opencti#837]
hello,

![grakn](https://user-images.githubusercontent.com/65870848/91408683-e5df5a00-e84c-11ea-8a6d-109828995179.PNG)
![grakn1](https://user-images.githubusercontent.com/65870848/91408704-eed02b80-e84c-11ea-83b9-bb6e0b6ef777.PNG)

Please can someone help!!

**Comment by zeroploitable** [comment]
I loaded grakn manually.
Still in docker logs, grakn seems down.

![grakn3](https://user-images.githubusercontent.com/65870848/91414744-a832ff00-e855-11ea-9122-ca835fe27573.PNG)
![grakn4](https://user-images.githubusercontent.com/65870848/91414807-c3057380-e855-11ea-90cd-77c6200561ab.PNG)

**Comment by richard-julien** [comment]
Hi @zeroploitable , 

Your latest screenshots are strange.
Looks like grakn start thats fine.
Can you check the opencti api docker logs first?
Then the connectors error "string indices must be integers" is really strange. Do you deploy everything on docker? Can you update your docker compose? thanks
