### ISSUE TITLE
Grakn schema initialization fails

### ISSUE THREAD

**Issue by cyb3rfox** [OpenCTI-Platform/opencti#839]
## Description

I tried to set up a development environment on a Ubuntu 19.10 VM according to this guide (https://www.notion.so/Environment-setup-606996f36d904fcf8d434c6d0eae4a00). Docker and everything loads alright but when I try to start the graphql module it fails with the following error:

    ✔ Compiled successfully!
    {"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-09-01T13:34:13.465Z"}
    {"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-09-01T13:34:15.087Z"}
    {"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-09-01T13:34:15.198Z"}
    {"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-09-01T13:34:15.213Z"}
    {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-09-01T13:34:15.253Z"}
    {"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-09-01T13:34:15.258Z"}
    {"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-09-01T13:34:15.491Z"}
    {"level":"info","message":"[INIT] > New platform detected, initialization...","timestamp":"2020-09-01T13:34:15.997Z"}
    {"error":{"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"syntax error at line 6: \n  internal_id sub attribute,           value string;\n                             ^\nno viable alternative at input 'value'\nsyntax error at line 6: \n  internal_id sub attribute,      value string;\n                             ^\nmismatched input 'value' expecting {'match', 'define', 'undefine', 'insert', 'compute'}. Please       check server logs for the stack trace."},"level":"error","message":"[GRAKN] Write error","timestamp":"2020-09-  01T13:34:16.079Z"}
    {"error":{"code":2,"metadata":{"_internal_repr":{},"flags":0},"details":"syntax error at line 6: \n  internal_id sub attribute, value string;\n                             ^\nno viable alternative at input 'value'\nsyntax error at line 6: \n  internal_id sub attribute, value string;\n                             ^\nmismatched input 'value' expecting {'match', 'define', 'undefine', 'insert', 'compute'}. Please   check server logs for the stack trace."},"level":"error","message":"[OPENCTI] > Platform init fail","timestamp":"2020-09-  01T13:34:16.080Z"}

This appears to be related with the schema initialisation in Grakn. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 19.10
2. OpenCTI version: Checked out a72d15469f55ef324a36b21026d516302a9e5d4a
3. OpenCTI client: none so far
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. according to https://www.notion.so/Environment-setup-606996f36d904fcf8d434c6d0eae4a00
2. fails at    
    $ cd opencti-graphql
    $ yarn start

## Expected Output

Starting correctly

## Actual Output

see above
 
## Additional information

n/a

**Comment by cyb3rfox** [comment]
Unfortunately the Issue is still there. Can you give any advise what to do?

**Comment by SamuelHassine** [comment]
@cyb3rfox The problem is fixed in the 4.0.0 milestone, so you should wait for the next release.

Kind regards,
Samuel

**Comment by cyb3rfox** [comment]
Sorry missed the milestone tag. Stupid me. Thanks.
