### ISSUE TITLE
Provide option to disable auto-enrichment of Observables

### ISSUE THREAD

**Issue by jbfeldman** [OpenCTI-Platform/opencti#841]
## Problem to Solve

{ Currently, an enrichment connector automatically enriches any new Observable once it has been created. However, this can be a problem with Commercial Enrichment connectors, which may have limits on the number of API calls that can be made, or may charge additional costs for a large number of API queries}

## Current Workaround

{ It's possible to change the internal logic of an enrichment connector so that it makes an enrichment API call when certain Tags are present or a certain TLP threshold is met. However, this is annoying and frustrating for both users and connector developers. Users must be constantly adding and checking tags, and it creates more code complexity for developers. }

## Proposed Solution

{ Provide an option (either in the connector helper configs or in the UI) to disable auto-enrichment for an connector. Users should still be able to manually enrich by going to the "Knowledge" tab of an observable and manually restarting the enrichment, but no enrichment will occur with that user action }

**Comment by SamuelHassine** [comment]
This option has been implemented. It is available in the current enrichment connectors (Hygiene, VirusTotal & IpInfo).

**Comment by jbfeldman** [comment]
@SamuelHassine great to here! I have two quick follow up questions - 

1. Is this fix live, or will it be introduced with v4
2. Will it be easy to add this option to newly created enrichment connectors?

Thanks!

**Comment by SamuelHassine** [comment]
@jbfeldman:

1. It will be introduced in the V4
2. Very easy to introduce: in fact, nothing to change ;) Just add "auto" to true/false in the configuration (ie. https://github.com/OpenCTI-Platform/connectors/blob/master/ipinfo/src/config.yml.sample).

The connector helper will take this value (true by default if nothing) and will take care of everything.

Then, you will have something like:

![image](https://user-images.githubusercontent.com/1334279/93004523-0d6e3c00-f548-11ea-9627-8b261bee5609.png)

Kind regards,
Samuel
