### ISSUE TITLE
OpenCTI STIXv2 import drops any objects utilizing STIX Enhancement Proposals (SEPs)

### ISSUE THREAD

**Issue by cvoid-newcontext** [OpenCTI-Platform/opencti#842]
## Description

When importing threat intelligence that leverages a STIX Enhancement Proposal observable objects using the extension are not imported. All other associated objects are imported without issue. For more information on STIX Enhancement Proposals please see https://github.com/oasis-open/cti-sep-repository.

## Environment

OS (where OpenCTI server runs): { Ubuntu 18.04.4 }
OpenCTI version: { OpenCTI 3.3.2 }
OpenCTI client: { frontend }
Other environment details: { Ubuntu VM on 5.3.0-1032-azure }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { Import a STIXv2 bundle that includes attack patterns and observable objects utilizing a SEP.}

## Expected Output

{ SEP observable objects to be imported. }

## Actual Output

{ Objects utilizing the SEP are not imported, non-SEP objects are imported without issue. Attack patterns referencing the SEP observables appear to be intact. }
 
## Additional information

{ None. }

**Comment by SamuelHassine** [comment]
We can implement new SDOs and SCOs if needed but we need to be more precise about the needs and the use cases. please open specific issues if you need anything.
