### ISSUE TITLE
Deleting entities from knowledge graph deletes entities from the threat report

### ISSUE THREAD

**Issue by tinamina12** [OpenCTI-Platform/opencti#848]
## Description

When deleting entities from a very dense knowledge graph, the entity is deleted from the threat report also. How to restore ? do i need to add threat report again?

**Comment by SamuelHassine** [comment]
Hello @tinamina12,

Sorry but I did not understand your question well, can you please be more precise?

 When you are deleting an entity from the knowledge graph in a report, the entity is deleted from the report yes that's normal. And if you are deleting a relationship that is only contained in this report, the relationship will be deleted as well.

**Comment by richard-julien** [comment]
Close for inactivity
