### ISSUE TITLE
Provide support for more Observable types

### ISSUE THREAD

**Issue by cdiraimondi** [OpenCTI-Platform/opencti#85]
## Problem to Solve

The platform currently offers a limited set of observables that are commonly seen in incidents. The platform should offer more observable types which can provide more detailed information when describing incidents.

## Current Workaround

There is no current workaround. You can only use what the platform currently provides.

## Proposed Solution

I would like to see the following Observable types added to the platform, both as an option when adding a specific Observable and checkbox items when filtering a list of observables. An option could also include the ability for a user to specify new Observable types on their own for greater platform flexibility. Use the Mandiant APT1 report STIX json file as an example of some additional available Observable objects: https://oasis-open.github.io/cti-documentation/examples/example_json/apt1.json

File Path
File Name
Registry Key
PDB Path
Service
Scheduled Task
x509-certificate:issuer And x509-certificate:serial_number

## Additional Information

None

**Comment by SamuelHassine** [comment]
@cdiraimondi: These observable types will be implemented in the next release. The MISP connector will be updated as well to take into account these new types.
