### ISSUE TITLE
Cannot filter on person, observables

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#854]
## Description

In menu "Data management/Data curation" : 

- it's impossible to filter on "person", except when you look for a "person" it appears in the table

- a list of observables cannot be searched and deleted

## Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.3.1
	3. OpenCTI client: Platform

## Reproducible Steps

When you go in "Data management/Data curation" you can't filter data on "person" and you can't search for and remove observables.

## Expected Output

Be able to filter on people and observables

## Actual Output 

For people it is possible to find them in the menu bar one by one

There is nothing we can do about observables

## Additional information
![IMAGE1](https://user-images.githubusercontent.com/38727361/93788122-05418b00-fc31-11ea-807f-0fe1b63443dd.PNG)

**Comment by SamuelHassine** [comment]
Hello,

This bug is solved in the V4:

![image](https://user-images.githubusercontent.com/1334279/93810394-e05c1080-fc4e-11ea-8d06-4b8ca6e0b5b6.png)
