### ISSUE TITLE
Note card does not exist

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#859]
## Description

In a knowledge graph you cannot open the note card

## Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.3.1
	3. OpenCTI client: Platform

## Reproducible Steps

1. Go to a report

2. Go to knowledge

3. Add note entity

4. Clic on the info button of note entity

5. Nothing appears

## Expected Output

 It is expected that the card will be seen as for the other entities in the knowledge graph

## Actual Output 

Nothing appears

## Additional information
![IMAGE12](https://user-images.githubusercontent.com/38727361/93794487-6fa9f980-fc38-11ea-9716-5dbb13c0d848.PNG)

**Comment by SamuelHassine** [comment]
This behavior is "normal", Notes cannot be added to a report like that. Please use the "+" button in the overview under the "Notes related to this entity".

To avoid that, I just removed Note and Opinion from the panel in the graph.
