### ISSUE TITLE
Threat Actor relation to an Identity don't exist

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#860]
## Description

In a knowledge graph you cannot related Threat Actor to an Identity

![IMAGE13](https://user-images.githubusercontent.com/38727361/93796553-4b9be780-fc3b-11ea-81ba-48457fdec995.PNG)

## Environment
	1. OS :  Debian 4.9.82-1+deb9u3 (2018-03-02)
	2. OpenCTI version: 3.3.1
	3. OpenCTI client: Platform

## Reproducible Steps

1. Go to a report

2. Go to knowledge

3. Add a Threat actor entity

4. Add a Person entity

4. Connects Person to Threat Actor

5. In relation type, nothing appears

## Expected Output
![IMAGE14](https://user-images.githubusercontent.com/38727361/93796510-37f08100-fc3b-11ea-9c72-22979fc5b3dd.PNG)

## Actual Output 

Nothing appears

## Additional information

**Comment by SamuelHassine** [comment]
Hello,

This is now solved:

![image](https://user-images.githubusercontent.com/1334279/94080307-09bb9e80-fdff-11ea-9251-b623e33e8f49.png)
