### ISSUE TITLE
Include automated import of STIX threat feeds via UI on next release

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#862]
Please include automated import of STIX threat feeds via UI on your next release of OpenCTI

Example UI to import STIX feeds ...

![STIX_Import](https://user-images.githubusercontent.com/20463433/94183045-d2d1a100-fe6f-11ea-8db8-ed8b92cb4c58.GIF)

**Comment by SamuelHassine** [comment]
Hello @NetEyes,

We have decided to not implement this feature. Importing feeds/sources will stay in the different connectors configurations.

Kind regards,
Samuel
