### ISSUE TITLE
Passwords appear in cleartext in logs when auth fails

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#863]
## Description

When an error happens during authentication (and not only a wrong user/password error, a weird duplicate entry in grakn for eg), the user and password appear in cleartext in the logs of the docker opencti-platform.

## Environment

1. Ubuntu + Docker
2. OpenCTI version: 3.3.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Try to auth with a wrong user/password
2. Check logs : docker logs __container_id__

## Expected Output

Password not in clear text, deleted or replaced by ***.

## Actual Output

..."user": "toto", "password": "toto123"...

**Comment by SamuelHassine** [comment]
Hello @amr-cossi,

Can you please provide the full log output please (without the actual user/password obviously)?

Kind regards,
Samuel

**Comment by amr-cossi** [comment]
Hey.
Here are the logs when a user fails to log-in :

```
{"error":null,"info":{"message":"Invalid` username/password"},"level":"warn","message":"[AUTH ERROR] > ldapauth","timestamp":"2020-10-05T15:57:06.339Z"}
{"type":"WRITE_ERROR","operation_query":"mutation LoginFormMutation($input:UserLoginInput!){token(input:$input)}","inner_relation_creation":0,"operation":"LoginFormMutation","time":911,"variables":{"input":{"email":"***","password":"***"}},"size":68,"error":{"data":{"category":"technical"},"stacktrace":["AuthFailure: Wrong name or password","at t (/opt/opencti/build/index.js:1:69669)","at d (/opt/opencti/build/index.js:1:69727)","at Ge.token (/opt/opencti/build/index.js:1:179101)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (internal/process/task_queues.js:93:5)"]},"level":"warn","message":"API Call","timestamp":"2020-10-05T15:57:06.340Z"}
```

The second row shows the password in clear text.

I can't reproduce the other error for now (login fail with the right password) but I'll try.

**Comment by SamuelHassine** [comment]
Thanks a lot!
