### ISSUE TITLE
GraphQL initialization fail with Grakn up

### ISSUE THREAD

**Issue by olivierdestin** [OpenCTI-Platform/opencti#868]
## Description

I can no longer redeploy OpenCTI with Docker, i have the error of grakn seems to be down. But when I see Grakn logs, I see it up and the same for Grakn storage (Success).  opencti/platform restarts every second. I tried to restart and to delete all data but no changes

## Environment

1. Linux
2. OpenCTI version: The last one
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: 

## Reproducible Steps
I reproduced these steps : https://www.notion.so/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8#fd990dd8e3f84a8aa02a810ca720f290

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output
```
sudo docker logs -f f60889924ed4 
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-10-05T16:14:41.521Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 
## Additional information

The very first deployment had worked, but since the second redeployment it no longer works.

**Comment by olivierdestin** [comment]
Hello @richard-julien , do you have a solution for my problem please ?

**Comment by richard-julien** [comment]
Hi @olivierdestin , it looks like you have a configuration problem on your installation. 
Error: getaddrinfo ENOTFOUND redis -> API is not able to find the redis instance.
You have to deploy the docker compose with all elements in once to permits communication between containers.
If you do it differently be careful to configure your stack accordingly.

**Comment by olivierdestin** [comment]
Thanks for you answer @richard-julien , but im deploying all containers in the same docker-composer. 
My Redis logs : 
```
sudo docker logs 3fda31e36997
1:C 07 Oct 2020 13:10:23.743 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 07 Oct 2020 13:10:23.743 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 07 Oct 2020 13:10:23.743 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 07 Oct 2020 13:10:23.744 * Running mode=standalone, port=6379.
1:M 07 Oct 2020 13:10:23.744 # Server initialized
1:M 07 Oct 2020 13:10:23.744 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 07 Oct 2020 13:10:23.744 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 07 Oct 2020 13:10:23.745 * Ready to accept connections
```

**Comment by olivierdestin** [comment]
Problem solved with a modification in my docker-compose

**Comment by adrianovieira** [comment]
Hi @olivierdestin 
here we have similar issue.

Could you share with us what was wrong?
