### ISSUE TITLE
Make a backup of the platform

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#874]
## Problem to Solve
 
Regular backup of the platform could avoid massive loss of data

 
## Current Workaround

Some parts can be exported in .csv file or .json file

## Proposed Solution

In the administration interface we would need the possibility in one click to export all the platform data in STIX2.1 format.

In this case the attached files as well as reports, images, ... would be lost so it should also be possible to download all unstructured data contained in MINIO database.

When importing into a new OpenCTI, the links between the entities and also between the structured elements will have to be made in order to be able to recover its operational platform.

## Additional Information

**Comment by amr-cossi** [comment]
Seems like it will be taken in charge with synchronisation of platforms for V4. To confirm

**Comment by securitiz** [comment]
Hello, any update to this?

**Comment by SamuelHassine** [comment]
@securitiz @amr-cossi it will be here in 5.0. https://github.com/OpenCTI-Platform/connectors/tree/master/stream/backup-files
