### ISSUE TITLE
Add an inference rule for "Intrusion-set" targets "Compagny"

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#875]
## Problem to Solve
 
When an "Intrusion-set" uses "Malware" and the "Malware" targets a "Company" then you don't see the inference relationship: the "Intrusion-set" targets the "Company". However, this relationship exists.
 
## Current Workaround

None 

## Proposed Solution

If "Intrusion-set" USE "Malware" and "Malware" TARGET "Company" THEN "Intrusion-set" TARGET "Company"

The following inference rule could be added:
```bash
AttributionUsesRule sub rule,
when { 
  $malware isa Malware;
  $user isa Intrusion-set
  $rel1_user_usage(user: $user, usage: $malware) isa uses;
  $rel2_source_target(source: $malware, target: $target) isa targets;
},then {
  (source: $user, target: $target) isa targets;
};
```

## Additional Information

**Comment by SamuelHassine** [comment]
This inference is not true. If an Intrusion-Set X and Intrusion Y use the same malware Z, the fact that the malware Z targets the entity A will in this case create knowledge indicating both Intrusion Sets are targeting entity A, which is not true. We should think about an inference rule with more conditions to be certain.
