### ISSUE TITLE
Malware Module Entity

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#877]
## Problem to Solve
 
A malware may contain modules to work. These modules can also be used in other malware. However, we cannot represent these modules in STIX2.1. It should be described as another malware, but it is not correct because it is a module contained in a malware.

Having knowledge about modules used by other malware is very interesting for analysis. If different "Intrusion-set" uses malware that contains the same modules then it may be that they were developed by the same "Intrusion-set"

## Current Workaround

None 

## Proposed Solution

One solution would be to have a new entity called a "malware module"

## Additional Information

**Comment by cvoid-newcontext** [comment]
This seems to be more a question of how to represent that in the STIXv2.1 standard than an OpenCTI issue.

**Comment by cvoid-newcontext** [comment]
I would recommend leveraging the artifact SCO for these components and then using a relationship object to connect them to various malware objects as needed.

**Comment by SamuelHassine** [comment]
@amr-cossi WDYT of the solution proposed by @cvoid-newcontext?

**Comment by cvoid-newcontext** [comment]
The way to do this is to use the 'sample_refs' property of a Malware object to reference Artifact objects containing the modules.
