### ISSUE TITLE
Role played by the indicator in knowledge graph

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#879]
## Problem to Solve
 
For analysis it is easier to see the role played by the indicator on the knowledge graph 

![IMAGE9](https://user-images.githubusercontent.com/38727361/95613111-b5eabf80-0a64-11eb-9976-7a790739f3ef.PNG)

## Current Workaround

None 

## Proposed Solution

2 solutions:

- display it directly under indicator as in the relationship: 
![IMAGE10](https://user-images.githubusercontent.com/38727361/95613124-bbe0a080-0a64-11eb-8466-79eab811daf5.PNG)

- show it when you mouse over it

Giving the user the choice to use either display solution would be even better.

**Comment by SamuelHassine** [comment]
Role_played is no longer available in the V4 and not STIX 2.1 compliant. Explanation about the role of the indicator should be written in the description of the relationship.
