### ISSUE TITLE
OpenCTI fail to start with docker for windows

### ISSUE THREAD

**Issue by richard-julien** [OpenCTI-Platform/opencti#88]
## Description

The platform can be deployed with docker but this is not working with docker for windows

> For info, docker must have at least 4Go of memory to run openCTI in good condition.

**But the platform is not starting**
Seems to be a problem with user rights
`standard_init_linux.go:207: exec user process caused "no such file or directory"`

## Environment

1. Windows 10 pro with docker for windows
2. OpenCTI version: all

## Reproducible Steps

Just docker-compose up on windows

## Expected Output

Docker deployment working for every platform.

**Comment by SamuelHassine** [comment]
@richard-julien can you try with the new docker-compose.yml and the new pre-built Docker images? I fixed a problem of permissions and many others. Thx!

**Comment by richard-julien** [comment]
Fix with release 1.0.2

**Comment by Dviros** [comment]
Hi there,
Having the exact same issue, even when running with the latest default docker.yml config:
standard_init_linux.go:211: exec user process caused "exec format error"

Running on Ubuntu 18.04
