### ISSUE TITLE
Role played by the indicator in "Intrusion-set" menu

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#880]
## Problem to Solve
 
For analysis it is easier to see the role played by the indicator on "Intrusion-sets/Indicators" menu

![IMAGE11](https://user-images.githubusercontent.com/38727361/95613252-f5191080-0a64-11eb-8cd4-eeeabe262a34.PNG)

Then we could have a filter on the right-hand played role so that we could filter all C2 or node server of an Intrusion-set.

## Current Workaround

None 

## Proposed Solution

Add a "role played" column and force the user to fill it (default: Undefined)

Add a "role played" filter to the list of filters on the right

**Comment by SamuelHassine** [comment]
Role_played is no longer available in the V4 and not STIX 2.1 compliant. Explanation about the role of the indicator should be written in the description of the relationship.
