### ISSUE TITLE
Link between victim and attacker IP addresses

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#881]
## Problem to Solve

I would like to be able to keep the link between a victim IP address and an attacker (C2, ...) IP address.
This link would represent the connections between both IP.

## Current Workaround

None

## Proposed Solution

Victim IP address could be an observable type and could be connected to a C2 IP (indicator).

**Comment by SamuelHassine** [comment]
@amr-cossi: Can you please be more specific on how are you seeing this relation (which kind of relationships) using STIX 2.1 modelization?

**Comment by SamuelHassine** [comment]
Up @amr-cossi?

**Comment by SamuelHassine** [comment]
Hello @amr-cossi,

It's now possible using beacons-to or communicates-with relationship:

![image](https://user-images.githubusercontent.com/1334279/143131192-b45d3a1b-d216-47b8-b8bd-a5707f85e551.png)

Kind regards,
Samuel
