### ISSUE TITLE
Add PAP protocol

### ISSUE THREAD

**Issue by amr-cossi** [OpenCTI-Platform/opencti#882]
## Problem to Solve

The Permissible Actions Protocol (PAP) was designed to indicate how the received information can be used. It's the same than TLP but indicates to the analyst how they may use the IoC in this investigating. 

It would be interesting to use it for observables and indicators in order to better understand how to use information according to a standard protocol.

## Current Workaround

None

## Proposed Solution

Implement PAP protocol 

## Additional Information

- https://github.com/MISP/misp-taxonomies/blob/main/PAP/machinetag.json

**Comment by SamuelHassine** [comment]
@amr-cossi,

After discussion with our partner, PAP protocol should be implemented as marking definitions. As it's not different from TLP, it's just another way to mark data. If you have other needs by implementing this protocol, please let us know!
