### ISSUE TITLE
[UX] Ungroup the display of the "Statement Marking" and "TLP Marking"

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#884]
## Problem to Solve

The display of the "TLP Marking" and "Statement Marking"  is grouped together in the same place in the interface.

https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_3ru8r05saera - 7.2.1.3 Statement Marking Object Type
> The Statement marking type defines the representation of a textual marking statement (e.g., copyright, terms of use, etc.) in a definition. [...]. Statement markings are generally not machine-readable, and this specification does not define any behavior or actions based on their values.

https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_yd3ar14ekwrs - 7.2.1.4 TLP Marking Object Type
> The TLP marking type defines how you would represent a Traffic Light Protocol (TLP) marking in a definition property. 

As  "Statement marking" is about "copyright, term of use, etc" and "TLP marking" is about sharing of information, these two pieces of information should not be displayed in the same way and in the same place.

## Proposed Solution

- When a list of entites is displayed, only the "TLP marking" should be displayed instead of "TLP/Statement marking)".
- When a single entitie is displayed, the "TLP marking" should be displayed as  "TLP marking"  and the  "Statement marking" should be displayed but with less importance.

**Comment by SamuelHassine** [comment]
Hello,

For the moment we have decided to process every "Marking definitions" with the same level of importance. We have many users that have "other" markings (no TLP, no statement). 

Kind regards,
Samuel

**Comment by 2xyo** [comment]
Looks understable!
