### ISSUE TITLE
FrontEnd does not display "Sighting" relationship when imported with "Import-File-STIX" connector

### ISSUE THREAD

**Issue by tellerj** [OpenCTI-Platform/opencti#885]
## Description

FrontEnd does not display "Sighting" relationship when imported with "Import-File-STIX" connector
When using the "opencti-connector-import-file-stix" connector to import the STIX 2.1 json example posted here: 
https://oasis-open.github.io/cti-documentation/examples/sighting-of-an-indicator
bundle ID = "bundle--2ac7882f-76a3-4a9b-97b3-811b3af1c7c0"
The resulting message on the import screen does mention the "sighting" SRO was imported: 
![image](https://user-images.githubusercontent.com/41540591/95707179-ad81b880-0c0d-11eb-9e2c-64cb5102feaf.png)

However, the sighting relationship doesn't show when the Indicator object is investigated:
![image](https://user-images.githubusercontent.com/41540591/95707357-284ad380-0c0e-11eb-9eea-10cb51c608bc.png)
"Malicious URL" is the indicator:
![image](https://user-images.githubusercontent.com/41540591/95707429-5f20e980-0c0e-11eb-94e1-f61a8b6cbf43.png)

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: 3.3.2
3. OpenCTI client: FrontEnd
4. Other environment details: Environment set up according to Manual Deployment instructions, using linked .sh scripts
5. Environment has "Import-File-Stix" connector registered

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download and save .json example from Open-Oasis page linked above
2. Click "Data Import" at the top left of the OpenCTI Server Frontend
3. Click "Select your File" upload button in import area, select .json file
4. Hover over import once completed by "import-file-stix" connector -- note "...1 imported sighting" helptext
5. Click Signatures > Indicators > "Malicious URL" (with import time matching import step above)
6. Click "Sightings" tab

## Expected Output

expected to see a link to the "Beta Cyber Threat Intelligence Company" organization-type entity in "Sightings" list

## Actual Output
No entities populate in "Sightings" list
 
## Additional information

It is possible to manually re-create the sighting relationship from the "Sightings" screen: 
![image](https://user-images.githubusercontent.com/41540591/95707840-875d1800-0c0f-11eb-88cb-f844ccac3c38.png)

But that defeats the purpose of the import connector, and is not scalable. Where did the "Sighting" object go??

**Comment by SamuelHassine** [comment]
This is already solved in the V4. Thanks for the very complete issue!
