### ISSUE TITLE
docker-compose up will not start

### ISSUE THREAD

**Issue by alikat500** [OpenCTI-Platform/opencti#89]
[docker-compose up - error.txt](https://github.com/OpenCTI-Platform/opencti/files/3342171/docker-compose.up.-.error.txt)

After issuing 'docker-compose up' the process never finishes. It cycles through sample messages including the ones bellow and keeps repeating
....
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for shared config...
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
integration_1    | Waiting for shared config...
opencti_1        | Waiting ElasticSearch to launch...
...

the issue happens with or without using sudo.

Environment: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

This is a VM running in VMWare Workstation 15.1.0 build-13591040.

Memory: 3GB
CPU: 2
===
Initiating the 'docker-compose up' command from following folder:

/opt/opencti/opencti/opencti-docker
============================
I used Docket install option when I deployed the Ubuntu 18.04.2 server. However, I received message ""Can't find a suitable configuration file". Although, the YAML file was present where I executed 'docker-compose up'.
Based on a suggestion on the following post
https://github.com/docker/compose/issues/6361
I uninstalled docket using snap and installed it using apt:

sudo snap remove docker
sudo apt install docker.io docker-compose

Then when I ran 'docker-compose up',  I received the following message:

“Couldn’t connect to Docker daemon at http+docker://localunixsocket — is it running?”

Based on a suggestion on the following post

https://app.getpocket.com/read/2092902705

I added the use to the  docker group and it resolved the issue.

The last issue is the loop I mentioned above.

I noticed the following error message:
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

I had issued the flowing command installation  instruction for docker:

sysctl -w vm.max_map_count=262144 

I issued the command again:

@opencti:/opt/opencti/opencti/opencti-docker$ sudo sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144

Then ran the "docker-compose up", the same issue happened.

**Comment by richard-julien** [comment]
Hi @alikat500, can your try this command that will remove the containers and associated volumes:
`docker-compose down -v` 
And then retry:
`docker-compose up`

**Comment by alikat500** [comment]
Thanks Richard; It did the trick! I was wondering if you have any thoughts on why it happened initially.

**Comment by richard-julien** [comment]
I think the container bootstrap with the max_map_count config of the system, so the old container was still based on the bad configuration.
