### ISSUE TITLE
Tags design is broken

### ISSUE THREAD

**Issue by jborozco** [OpenCTI-Platform/opencti#8912]
## Description

The design of the tags should be like the one of "no tag"
![Image](https://github.com/user-attachments/assets/aeb8bb7d-9450-4a10-9c9f-c8253ab0adf9)

## Reproducible Steps

go to https://testing.obas.staging.filigran.io/admin/payloads?query=cGFnZT0wJnNpemU9MjAmZmlsdGVyR3JvdXBbZmlsdGVyc11bXSZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJnNvcnRzJTVCMCU1RCU1QnByb3BlcnR5JTVEPXBheWxvYWRfbmFtZSZ0ZXh0U2VhcmNoPXJkcCZrZXk9cGF5bG9hZHM%3D

**Comment by nino-filigran** [comment]
Wrong repo no @jborozco ?

**Comment by jborozco** [comment]
Wrong repo indeed sorry 😅
