### ISSUE TITLE
[import file stix] Improve Error logging 

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#892]
## Problem to Solve

If the import of a STIX file fails through the web interface, the level of details of the errors is insufficient to find the source of the error.

## Current Workaround

N/A

## Proposed Solution

- On https://demo.opencti.io/dashboard/import 
  ![image](https://user-images.githubusercontent.com/31675/96929566-9a4ad480-14ba-11eb-90c1-63bf354fecf3.png)

The user should be given the option to click on the error to view the details of the error (on just a redirection to  ImportFileStix Job) 

- On https://demo.opencti.io/dashboard/data/connectors/4a596ce3-fc6c-478b-99fa-79fafa32a741
  ![image](https://user-images.githubusercontent.com/31675/96929769-f7df2100-14ba-11eb-87a1-634e8b432558.png)
  [Errors]
  ![image](https://user-images.githubusercontent.com/31675/96929796-062d3d00-14bb-11eb-8119-7d2e69a46924.png)

The message should contains the entity concerns by the error. 

## Additional Information

Test file: https://raw.githubusercontent.com/MBCProject/mbc-stix2/master/mbc.json

**Comment by kudrew** [comment]
If you have your own environment:

To track down the errors. set the log level of your worker(s) to `info` and restart them. 

tail the logs of your worker(s), and perform the import again. Usually in my instance v4 rolling release, the error "Missing reference to handle creation" will follow whatever stix object the worker is trying to perform its function on i.e:

```
INFO:root:Adding StixObjectOrStixRelationship {malware--2485b844-4efe-4343-84c8-eb33312dd56f} to Report {1baab842-1d30
-41a5-b31d-449305f67af0}
ERROR:root:Missing reference to handle creation
```

Hope this helps, learning the ins and outs of OpenCTI as I go.

**Comment by 2xyo** [comment]
Thanks @kudrew for the comment. The proposed workaround is totally suitable for an administrator with SSH access, but not for an end user / analyst :)

**Comment by SamuelHassine** [comment]
All errors in the connectors monitoring have now the full original entity at the origin of the error.
