### ISSUE TITLE
new docker install error:  manifest for opencti/platform:4.0.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by dmille6** [OpenCTI-Platform/opencti#893]
new to openCTI. I think it'll be a great solution 

trying a docker install from Ubuntu 20LTS

installed OS
- installed ubuntu 20
- apt update
- apt upgrade -y
- apt dist-upgrade -y

installed docker-ce and docker-compose
cloned repository to /opt/opencti
copyed .env.sample to .env
edited .env 
   - changed admin email
   - changed admin password
   - changed admin_token
left the rest, saved and closed

ran docker-compose up
error:  manifest for opencti/platform:4.0.0 not found: manifest unknown: manifest unknown

any suggestions?

**Comment by sahnoun11** [comment]
open the docker-compose.yml and change the 4.0.0 version of the opencti with 3.3.2

**Comment by richard-julien** [comment]
OpenCTI 4.0 is under development. Please use the latest release for you deployment.
