### ISSUE TITLE
new docker install error: manifest for opencti/platform:4.0.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by rocket-ops** [OpenCTI-Platform/opencti#897]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

When following the directions here:
https://www.notion.so/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8

OpenCTI will not correctly launch.  An error is given:
error: manifest for opencti/platform:4.0.0 not found: manifest unknown: manifest unknown

Please see this Issue which was reported and closed. 
https://github.com/OpenCTI-Platform/opencti/issues/893

The first solution to change the docker-compose opencti entries to 3.3.2 did not fix the problem. It also raises the question should each worker entry be changed to 3.3.2? 

Example: image: opencti/worker:3.3.2. Is this correct?

The issue was then closed with a statement that 4.0.0 is still under development. This is great but how do we get it to work correctly with the current version?

Can someone please help fix docker so it will run correctly or advise how to fix the problem?

**Comment by kudrew** [comment]
```
error: manifest for opencti/platform:4.0.0 not found: manifest unknown: manifest unknown
```

Reason is because there is no such releasing for OpenCTI v4 yet. However there is a "dev" version, `opencti/platform:rolling` from https://hub.docker.com/r/opencti/platform/tags?page=1&ordering=last_updated 

```
It also raises the question should each worker entry be changed to 3.3.2?
```
Yes, if youre trying to deploy platform v3.3.2, your workers have to be v3.3.2 (and likewise so should connectors)

**Comment by SamuelHassine** [comment]
This is now solved. Resetting the docker repository.
