### ISSUE TITLE
Help installing with docker

### ISSUE THREAD

**Issue by a108a108** [OpenCTI-Platform/opencti#898]
Hi guys,
while installing with docker i am getting these errors:

worker_1_a13d92586f52                    | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

worker_3_e2a872b45feb                    | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

worker_2_6b982f80183b                    | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

connector-import-file-pdf-observables_1_a29cb042beeb | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

connector-export-file-stix_1_c857646fd565 | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

connector-import-file-stix_1_b5dd6cfaeaa3 | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

connector-export-file-csv_1_b8cc969dba2c | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

connector-mitre_1_8d1782e80872           | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

docker.errors.APIError: 409 Client Error: Conflict ("b'container 8d0a11fcabfc96bd27e294e6000d89af47c7ea585eca3d81102ccb61ea24dfdb is restarting, wait until the container is running'")

opencti_1_137a84ac2978                   | error Command failed with exit code 1

I believe i followed everything in the install guide i also tried to use the .env.example file

**Comment by richard-julien** [comment]
OpenCTI container only starts if dependencies containers starts. You need to start by checking the status of grakn / elastic and redis containers.

**Comment by SamuelHassine** [comment]
Hello @a108a108,

We have simplified our technological stack in the version 4, you should now be able to run OpenCTI using Docker without any issue. Do you still have problems?

Kind regards,
Samuel

**Comment by drizzit56** [comment]
I have same problem as above when deploying the current docker-compose file. I seem to have tracked this down to the fact that opencti/platform does not initialise. I have tried with 2 different builds of a server running ubuntu 20.04. The container always fails on initialisation, showing the yarn run command returning an error:

> yarn run v1.19.1
>  
> $ node --max_old_space_size=8192 build/index.js
>
> {"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-12-23T00:38:40.970Z","data":{"reason":"[INIT] Fail initialize schema, index already exists","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2020-12-23T00:38:40.971Z"}
> 
> error Command failed with exit code 1.

> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have tried using docker compose, portainer , and portainer swarm all to no avail, I am using this docker-compose file listed here:
https://github.com/OpenCTI-Platform/docker

I saw you pushed a rolling version of the image @SamuelHassine and this reveals the same error when deployed should i move back to an older version or is this a problem with my deployment? I can add any logs that may be required

**Comment by drizzit56** [comment]
Also to add the error about schema already existing occurs after attempting to run the stack after a docker "system purge -a" and the first time it is run after this it does the same but without the index already existing.

**Comment by richard-julien** [comment]
Hi @drizzit56 . 
Can you clean everything and put the first batch of logs you have?
INIT] Fail initialize schema, index already exists > is an error that occurs then the platform is partially initialized (index exists but not required migration entity). Purge everything and restart. Then check the logs of openCTI after some minutes, time for everything to starts.
Thanks

**Comment by richard-julien** [comment]
Closed due to inactivity. Feel free to reopen if needed.
