### ISSUE TITLE
How to Integrate Thehive with OpenCTI

### ISSUE THREAD

**Issue by MarcoGeek** [OpenCTI-Platform/opencti#899]
I have an OpenCTI  and TheHive instance running. I create an Incident to investigate and to generate threat intelligence out of it. Can I push that incident to my TheHive4 server? If Yes then How? Is there anyway to send notification to thehive instance? Please suggest. Thanks in advance.

Regards,
Mustaque

**Comment by vxsh4d0w** [comment]
At the momen it doesn't exist a bidirectional connector that allwos to open a case on TheHive through OpenCti but it exists the chance to use Cortex Analyzer to extract infro from OpenCti and enrich your TheHIve cases. (https://github.com/TheHive-Project/Cortex-Analyzers/pull/725)

**Comment by MarcoGeek** [comment]
Thanks for the information. Appreciate it.

Regards,
Mustaque

**Comment by SamuelHassine** [comment]
Closing, duplicate with #895.
