### ISSUE TITLE
Multiple documentation pages missing

### ISSUE THREAD

**Issue by cdiraimondi** [OpenCTI-Platform/opencti#90]
## Description

There are many missing documentation pages in the official documentation. Many of the links end up in 404 errors.

## Environment

Official OpenCTI github documentation

## Reproducible Steps

By clicking on many of the links in the documentation. One example being the “Add knowledge to a report page” with a missing page to https://opencti-platform.github.io/docs/usage/reference/reference-relation

## Expected Output

Leads to the page mentioned

## Actual Output
404 errors

**Comment by SamuelHassine** [comment]
@cdiraimondi: Thanks for your report. We are working hard to complete the current documentation. I will inform you here when the documentation will be considered as complete.

**Comment by cdiraimondi** [comment]
This reference on the same page is missing.

https://opencti-platform.github.io/docs/usage/python/introduction

**Comment by SamuelHassine** [comment]
Reminder: fix ElasticSearch version and broken links.
