### ISSUE TITLE
Error when connecting to opencti behind a reverse proxy 

### ISSUE THREAD

**Issue by IrootGeek** [OpenCTI-Platform/opencti#902]
## Description

Some errors when connecting to an opencti behind a reverse proxy.

- During the first authentication of a user there is an error message :
_**This page cannot be found on this opencti application.**_

- In the profile part when using the PLAY GROUND button the application does not redirect to APP__BASE_PATH + graphql (<url_opencti>/opencti/graphql) but to (<url_opencti>/graphql). There is an error message :
_**404 Not Found**_

- On the page <url_opencti>/opencti/graphql you have to add the same url in the navigation bar of the opencti application otherwise there is an error message :
_**Server cannot be reached**_

## Environment
1. OpenCTI version: 3.3.2

## Reproducible Steps

1. Opencti behind a reverse proxy with APP__BASE_PATH=/opencti
2. First connection with a new user
3. Click on "PLAY GROUND" in profile
4. reload schema in graphql or use Query 

## Actual Output

- First message error : _**This page cannot be found on this opencti application.**_
- Second message error : _**404 Not Found**_
- third message error : _**Server cannot be reached**_

**Comment by richard-julien** [comment]
Fixed in v4.
