### ISSUE TITLE
"Rich text editor" (report creator + export PDF)

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/opencti#904]
## Problem to Solve

Easily link objects in a report, autocomplete, insert widgets/graphs, etc.

## Current Workaround

Make hypertext links manually.

## Proposed Solution

Add some kind of autocomplement function in the editor to easily reference other objects.

## Additional Information

Example: 
* https://www.misp-project.org/2020/10/08/Event-Reports.html

**Comment by SamuelHassine** [comment]
First version has been implemented, auto-completion & widgets are coming.
