### ISSUE TITLE
Display a confirmation message / error message upon actions

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#905]
## Problem to Solve

When an action such as "Merge" or "Delete" is performed in the section "Data Curation", there should be a information message informing the user about the success/failure of the operation.

## Current Situation
Currently no message is displayed. 
Use case 1: An entity is deleted. A pop-up message appears to ask the user if he is sure about deleting. The deletion succeeds (or not) and the pop-up disappears. The user does not have a feedback on what happened.

Use case 1: 2 entities are merged. A window appears asking the user to confirm the merging. The merging succeeds or not and the window disappears. The user has no feedback on what happened.

## Proposed Solution

Display an information message on top of the page informing the user:
"Entity deleted" or "Deletion failed, please try again."
"Entities merged" or "Merging failed, please try again."

**Comment by maertv** [comment]
The changes are merged into the _master_ branch and should be included in the latest rolling release.

Please check if it works as expected.
