### ISSUE TITLE
Remove the predefined list of items when associating a report with any entity

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#907]
## Problem to Solve
When the user wants to associate any type of entity to a report, the user clicks on the "+" button and it's prompted with a set of entities that seem to be random. (they are in fact the latest objects accessed)
This can create a confusion for the user who might think that she can only chose from the pre-defined list of entities that are in that list. 

## Current Workaround

There is no workaround. The user must be trained to ignore the pre-defined list of entities and use the "Search" functionality to find what she is looking for.

## Proposed Solution

To avoid this potential confusion, there should be no pre-defined list of entities displayed afte the user pressed the "+" button. Instead, a message could be displayed reading "Use the search functionality to find the entity you want to associate".

## Additional Information

![img1](https://user-images.githubusercontent.com/65337190/99185642-7ee68880-274b-11eb-9f08-2466aba7e047.png)

**Comment by maertv** [comment]
Changes are merged to _master_ branch and should be included in the next rolling release.
