### ISSUE TITLE
Show only entities of the selected filter, when associating a report to one/more entities

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#908]
## Problem to Solve

A user wants to associate a report to some Malware. The user finds the report and she clicks on the section "Entities": https://demo.opencti.io/dashboard/analysis/reports/e635eaaf-f295-40e6-9462-5ba31a663105/entities?sortBy=name&orderAsc=false&searchTerm=
The she filters by MALWARE on the right-hand side.

When she will click on the  + button, since she pre-selected the filter "Malware" she will expect to find in the list of entities to associate with only malwares (after she performed the search). Currently this is not the case: despite applying the filter she is presented with a mix of entities (malware, vulnerabilities, indicators etc)

## Current Workaround

None

## Proposed Solution

After pre-selecting the filter, and clicking the + button, the user will perform a search and she will only be presented results that correspond to the filter she selected in the previous step. 

## Additional Information

![img2](https://user-images.githubusercontent.com/65337190/99185964-61b2b980-274d-11eb-9355-1d155c243727.png)

**Comment by maertv** [comment]
Changes are merged to _master_ branch and should be included in the next rolling release.
