### ISSUE TITLE
Export of reports is bugging

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#909]
## Description

Export of reports from the GUI is not functioning. 

## Environment

1. Users' OS: Mac OS 10
2. OpenCTIv4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the Analysys -> Reports section.
2. Narrow down the number of reports by filtering. For example, chose only MISP events.
3. Click on the EXPORT and chose Application/Json
4. A pop-up window remains blocked but not export starts

## Expected Output

The reports list should be exported in the json format.

## Actual Output

No output, the application freezes (see attached)
 
## Additional information

![img3](https://user-images.githubusercontent.com/65337190/99221518-03cfb180-27e1-11eb-9753-2bfca54e38f5.png)

**Comment by maertv** [comment]
Changes are merged to _master_ branch and should be included in the next _rolling_ release.
