### ISSUE TITLE
Link broken releases.opencti.io

### ISSUE THREAD

**Issue by makakin** [OpenCTI-Platform/opencti#91]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Error Msg when init the docker on the first time:
Resolving releases.opencti.io (releases.opencti.io)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'releases.opencti.io'

## Environment

1. OS (where OpenCTI server runs): {CoreOS 2135.4.0}
2. OpenCTI version: {7f3bd87 }
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
./docker-compose up

## Actual Output

Removing intermediate container 2745352225bc
 ---> 97c58597263d
Step 6/11 : RUN wget -O /opt/opencti.tar.gz https://releases.opencti.io/opencti-20190626.tar.gz
 ---> Running in 2faa602d26c9
--2019-06-30 03:07:45--  https://releases.opencti.io/opencti-20190626.tar.gz
Resolving releases.opencti.io (releases.opencti.io)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'releases.opencti.io'
ERROR: Service 'opencti' failed to build: The command '/bin/sh -c wget -O /opt/opencti.tar.gz https://releases.opencti.io/opencti-20190626.tar.gz' returned a non-zero code: 4

**Comment by SamuelHassine** [comment]
@makakin Thanks a lot for your bug report. The infrastructure behind `releases.opencti.io` has suffered a down-time this night. This is now solved so you can run the `docker-compose` without any problem. Could you please confirm that you do not have this problem anymore?

**Comment by richard-julien** [comment]
@SamuelHassine why using a dedicated infra for hosting releases? Github should be a better alternative to fetch the release.

**Comment by SamuelHassine** [comment]
@richard-julien Yes I think so, it was for the time we do not have any release on Github. I will change this on the next version.

**Comment by SamuelHassine** [comment]
All `Dockerfile` are now configured to download the release on Github.
