### ISSUE TITLE
"RabbitMQ seems to be down" - Ubuntu 20.04

### ISSUE THREAD

**Issue by ahmadmkhan1** [OpenCTI-Platform/opencti#913]
## Description

Trying to install OpenCTI manually on AWS EC2 instance. It says Grakn, Elasticsearch and MinIO are alive however, RabbitMQ seems down. I am able to log into my RabbitMQ management console from the web and from CLI but OpenCTI can't seem to figure out that RabbitMQ is running. I've checked the credentials, IP and ports and there isn't anything there that in my understanding would point towards this issue.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 3.3.2
3. OpenCTI client: python3
4. Yarn: 1.22.5
5. Node: v12.19.1
6. RabbitMQ Server: 3.8.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install Grakn-core from apt
2. Install Elasticsearch from apt
3. Install Redis from apt
4. Install MinIO from apt
5. Install RabbitMQ from apt and enable the Management console
6. Follow the official documentation of OpenCTI for manual deployment
7. Add config for all above including RabbitMQ in opencti/config/production.json

## Expected Output

{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-11-23T11:10:37.226Z"}

## Actual Output

{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-11-23T11:10:37.242Z","data":{"reason":"RabbitMQ seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-11-23T11:10:37.242Z"}
 
## Additional information

● rabbitmq-server.service - RabbitMQ broker
	Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
	Active: active (running) since Mon 2020-11-23 12:43:26 UTC; 10min ago
  Main PID: 19103 (beam.smp)
  	Status: "Initialized"
  	  Tasks: 87 (limit: 9449)
  	Memory: 88.2M
  	CGroup: /system.slice/rabbitmq-server.service
  			├─19103 /usr/lib/erlang/erts-11.1.3/bin/beam.smp -W w -K true -A 64 -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 5000000 -stbt db -zdbbl 128000 -- -root /usr/lib/erlang -progname erl -- -h>
  			├─19224 erl_child_setup 32768
  			├─19250 /usr/lib/erlang/erts-11.1.3/bin/epmd -daemon
  			├─19273 inet_gethost 4
  			└─19274 inet_gethost 4

Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Doc guides: https://rabbitmq.com/documentation.html
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Support:    https://rabbitmq.com/contact.html
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Tutorials:  https://rabbitmq.com/getstarted.html
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Monitoring: https://rabbitmq.com/monitoring.html
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Logs: /var/log/rabbitmq/rabbit@ip-172-31-71-59.log
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:         /var/log/rabbitmq/rabbit@ip-172-31-71-59_upgrade.log
Nov 23 12:43:25 ip-172-31-71-59 rabbitmq-server[19103]:   Config file(s): (none)
Nov 23 12:43:26 ip-172-31-71-59 rabbitmq-server[19103]:   Starting broker... completed with 3 plugins.
Nov 23 12:43:26 ip-172-31-71-59 systemd[1]: Started RabbitMQ broker.

**Comment by zweger** [comment]
I might've run into a similar issue a short while ago (but neglected to create an issue here...). Do your RabbitMQ credentials happen to contain RFC 3986 reserved characters? I noticed that OpenCTI doesn't handle encoding those properly.

**Comment by ahmadmkhan1** [comment]
> I might've run into a similar issue a short while ago (but neglected to create an issue here...). Do your RabbitMQ credentials happen to contain RFC 3986 reserved characters? I noticed that OpenCTI doesn't handle encoding those properly.

I initially had "-" in the username/password and thought the same as you have mentioned. So I modified the `production.json` as follows but the issue persists;

`"rabbitmq": {                                                                                                                                                                                                                                  "hostname": "localhost",                                                                                                                                                                                                                     "port": 5672,                                                                                                                                                                                                                                "port_management": 15672,                                                                                                                                                                                                                    "management_ssl": false,                                                                                                                                                                                                                     "username": "rabbituser",                                                                                                                                                                                                                    "password": "rabbitpass"                                                                                                                                                                                                                   }`

Could be a version specific issue related to RabbitMQ or maybe something really dumb that I'm missing.

**Comment by ahmadmkhan1** [comment]
I figured I had `deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang` in   `/etc/apt/sources.list.d/bintray.rabbitmq.list`.
Adding `deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-23.x` instead and then installing rabbitmq-server resolves the issue and gives the output below:

> yarn run v1.22.5
> $ node --max_old_space_size=8192 build/index.js
> {"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-11-26T10:05:12.247Z"}
> {"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-11-26T10:05:12.279Z"}
> {"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-11-26T10:05:12.293Z"}
> {"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-11-26T10:05:12.306Z"}
> {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-11-26T10:05:12.368Z"}
> {"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-11-26T10:05:12.374Z"}
> {"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-11-26T10:05:12.720Z"}
> {"level":"info","message":"[INIT] > New platform detected, initialization...","timestamp":"2020-11-26T10:05:13.124Z"}
