### ISSUE TITLE
Show the reports created by an organisation, by adding a "Display as" view mode

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#916]
## Problem to Solve

Just like OpenCTI v3, the v4 should allow a way to see the manually created reports that have as author a specific organisation.

## Current Workaround

There is no workaround.

## Proposed Solution

Here is the use case:
Step 1: The user manually creates a report. In the field "Author" of the report, the user picks one of the existing entities -> organisations. (organisations X)
Step 2: The user goes to the section Entities -> Organizations and picks the organisation X, used as "author" in the step above.
Step 3: In the OVERVIEW tab of the organisation, there is a section called "Last reports about the element".
Just like in v3, there should be a switch on the report, allowing to change between the layers 
- Display as Author: If the user picks the mode "Author", the section should be called "Last reports wrote by the entity" and it should contain the report mentioned in Step 1.

- Display as Knowledge: If the user picks the mode "Knowledge", the section "Last reports about the element" should remain unchanged. The page displays the reports related to Organisation X.

## Additional Information
Here is how it looked like in v3:
![img4](https://user-images.githubusercontent.com/65337190/100383733-a3c9de00-301e-11eb-809f-7d943c7019a0.png)

And here is in v4:
![img5](https://user-images.githubusercontent.com/65337190/100383991-5bf78680-301f-11eb-88d5-67b26e4d0317.png)

**Comment by SamuelHassine** [comment]
I let this feature open since we need also to refactor the view itself, but thanks a lot @maertv, this start is perfect!
