### ISSUE TITLE
OpenCTI datasets (rolling): only Sectors are imported

### ISSUE THREAD

**Issue by s3ns0r1um** [OpenCTI-Platform/opencti#918]
## Description

Only the Sectors information is being imported. The connector successfully runs through but finishes with 256 errors of the same type: {'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'} . Any ideas why this might be? Thanks in advance for your help! 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1 LTS Server
2. OpenCTI version: 4.0.0 (rolling)
3. OpenCTI client: frontend
4. Other environment details: Ubuntu runs in a VM (ESXi), Grakn v 1.8.3, all OpenCTI connectors: rolling branch

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the opencti-connector (first run/reset connector state yields the same behaviour)

## Expected Output

Successful import of all OpenCTI datasets

## Actual Output

Only Sectors are successfully imported
 
## Additional information

Any additional information, including logs or screenshots if you have any.

![opencti_connector](https://user-images.githubusercontent.com/75171233/100518329-21adf680-3191-11eb-9148-e1895ec7e6bd.png)
![opencti_connector_error](https://user-images.githubusercontent.com/75171233/100518333-25da1400-3191-11eb-8a58-742859c7c018.png)

Container logs:
[docker_log.txt](https://github.com/OpenCTI-Platform/opencti/files/5611988/docker_log.txt)

**Comment by richard-julien** [comment]
Hi @s3ns0r1um,

Thanks for your feedback. I think you already know but the rolling is not stable, it should be used only for development and early testing.
We do some adjustment on this part recently and I think this rolling is not really working :)
Just tested this morning and it looks good.
I think if you update and test again it should be good.

**Comment by richard-julien** [comment]
In fact not, we still have some problems. Will take a look thanks

**Comment by richard-julien** [comment]
Ok so after a checking we need to update also your configuration and everything should be good with the latest rolling.

CONFIG_SECTORS_FILE_URL: https://raw.githubusercontent.com/OpenCTI-Platform/datasets/v4/data/sectors.json
CONFIG_GEOGRAPHY_FILE_URL: https://raw.githubusercontent.com/OpenCTI-Platform/datasets/v4/data/geography.json

**Comment by s3ns0r1um** [comment]
Hey there,

Awesome response time, thank you for getting back to me. Yes, absolutely aware the rolling is unstable :) Having the geodata at hand for testing comes in handy, though! So I modified the docker-compose.yml with the new URLs. Connector runs sucessfully. Sectors all good, I get some regions and no cities. I'm getting a new error (265 of the same kind): 

{'name': 'DatabaseError', 'message': 'Expect only one response'}

Thanks again for your support, it's really appreciated!

**Comment by richard-julien** [comment]
Unfortunately i think you have to reset your platform data... Your previous integration have created some element in an incorrect types so I can't guarantee the behavior :)

**Comment by s3ns0r1um** [comment]
I can live with that ;) It worked. Thanks again for your support!
