### ISSUE TITLE
Documentation Zip is corrupted in release

### ISSUE THREAD

**Issue by matthew-renodin** [OpenCTI-Platform/opencti#919]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I downloaded the zip of the documentation and it states it is corrupted.

## Environment

1.Windows 10
2. opencti-doc-html-20200818.zip
3. N/A
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download zip from github
2. Double click file
3. ... invalid

## Expected Output

I expect to be able to access the zip
## Actual Output

I get an error
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by richard-julien** [comment]
Hi @matthew-renodin ,

Surprising bug for me but you're right the windows explorer is not able to unzip the file :) 
I personally used 7zip but its not an excuse. I will take a look to this asap.

**Comment by richard-julien** [comment]
Looks like its related to long path/name in the zip.
Unfortunately the zip is generated by notion and im not able to generate a zip compatible with the basic zip function of windows.
For now I invite you to use 7zip to unzip the documentation.

**Comment by matthew-renodin** [comment]
I downloaded MINGW and unzip the file run unzip. This worked for me in Windows 10.
