### ISSUE TITLE
Cant start worker.py

### ISSUE THREAD

**Issue by cyberkun12** [OpenCTI-Platform/opencti#920]
## Description

Unable to start the worker.py process.
Gets the error: GRAPHQL_VALIDATION_FAILED
And  OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration.

This is a clean install of platform using the guide provided [here](https://www.notion.so/Manual-deployment-b911beba44234f179841582ab3894bb1)

## Environment

1. Ubuntu 18.04
2. OpenCTI 3.3.2
3. OpenCTI client: python
4. Installed manually 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. yarn serv

{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-12-02T07:56:22.330Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-12-02T07:56:36.160Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-12-02T07:56:36.675Z"}
{"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-12-02T07:56:36.751Z"}
{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-12-02T07:56:36.892Z"}
{"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-12-02T07:56:36.913Z"}
{"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-12-02T07:56:38.444Z"}
{"level":"info","message":"[INIT] > Existing platform detected, migration...","timestamp":"2020-12-02T07:56:41.938Z"}
{"level":"info","message":"[INIT] > Grakn schema loaded","timestamp":"2020-12-02T07:57:01.867Z"}
{"level":"info","message":"[INIT] > Elasticsearch indexes loaded","timestamp":"2020-12-02T07:57:02.040Z"}
{"relationId":"93310e68-c408-5f7f-a5c8-877c9cdf81c2","level":"warn","message":"[ELASTICSEARCH] Relation not found for deletion","timestamp":"2020-12-02T07:57:26.296Z"}
{"level":"info","message":"[ADMIN_SETUP] admin user initialized","timestamp":"2020-12-02T07:57:32.835Z"}
{"level":"info","message":"[MIGRATION] > Read 0 migrations from the database","timestamp":"2020-12-02T07:57:34.054Z"}
{"level":"info","message":"[MIGRATION] > Migration process completed, platform is up to date","timestamp":"2020-12-02T07:57:34.062Z"}
{"level":"info","message":"OPENCTI Ready on port 4000","timestamp":"2020-12-02T07:57:36.005Z"}

2. python3 worker.py

## Expected Output

Worker starting

## Actual Output

Traceback (most recent call last):
  File "worker.py", line 300, in <module>
    worker = Worker()
  File "worker.py", line 212, in __init__
    self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
  File "/home/opencti/.local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 144, in __init__
    "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
 
## Additional information

{"type":"READ_ERROR","operation_query":"query ThreatActors($filters:[ThreatActorsFiltering]$search:String$first:Int$after:ID$orderBy:ThreatActorsOrdering$orderMode:OrderingMode){threatActors(filters:$filters search:$search first:$first after:$after orderBy:$orderBy orderMode:$orderMode){edges{node{id standard_id entity_type parent_types spec_version created_at updated_at createdBy{...on Identity{id standard_id entity_type parent_types spec_version name description roles contact_information x_opencti_aliases created modified objectLabel{edges{node{id value color}}}}...on Organization{x_opencti_organization_type x_opencti_reliability}...on Individual{x_opencti_firstname x_opencti_lastname}}objectMarking{edges{node{id standard_id entity_type definition_type definition created modified x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}externalReferences{edges{node{id standard_id entity_type source_name description url hash external_id created modified}}}revoked confidence created modified name description aliases threat_actor_types first_seen last_seen roles goals sophistication resource_level primary_motivation secondary_motivations personal_motivations}}pageInfo{startCursor endCursor hasNextPage hasPreviousPage globalCount}}}","inner_relation_creation":0,"operation":"Unspecified","time":114,"variables":{"filters":null,"search":null,"first":1,"after":null,"orderBy":null,"orderMode":null},"size":85,"error":{"stacktrace":["GraphQLError: Cannot query field \"standard_id\" on type \"ThreatActor\".","at Object.Field (/opt/opencti/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)","at Object.enter (/opt/opencti/node_modules/graphql/language/visitor.js:324:29)","at Object.enter (/opt/opencti/node_modules/graphql/language/visitor.js:375:25)","at visit (/opt/opencti/node_modules/graphql/language/visitor.js:242:26)","at Object.validate (/opt/opencti/node_modules/graphql/validation/validate.js:73:24)","at validate (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:221:34)","at Object.<anonymous> (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:118:42)","at Generator.next (<anonymous>)","at fulfilled (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)","at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"level":"error","message":"API Call","timestamp":"2020-12-02T08:04:30.582Z"}
INFO:root:{"errors":[{"message":"Cannot query field \"standard_id\" on type \"ThreatActor\".","locations":[{"line":8,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"spec_version\" on type \"ThreatActor\".","locations":[{"line":11,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"createdBy\" on type \"ThreatActor\". Did you mean \"created\", \"createdByRef\", \"created_at\", or \"creator\"?","locations":[{"line":14,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"standard_id\" on type \"Identity\".","locations":[{"line":17,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"spec_version\" on type \"Identity\".","locations":[{"line":20,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"roles\" on type \"Identity\". Did you mean to use an inline fragment on \"User\"?","locations":[{"line":23,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_aliases\" on type \"Identity\".","locations":[{"line":25,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectLabel\" on type \"Identity\".","locations":[{"line":28,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_organization_type\" on type \"Organization\".","locations":[{"line":39,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_reliability\" on type \"Organization\". Did you mean \"reliability\"?","locations":[{"line":40,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Unknown type \"Individual\".","locations":[{"line":42,"column":24}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectMarking\" on type \"ThreatActor\".","locations":[{"line":47,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectLabel\" on type \"ThreatActor\".","locations":[{"line":62,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"standard_id\" on type \"ExternalReference\".","locations":[{"line":75,"column":25}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"aliases\" on type \"ThreatActor\". Did you mean \"alias\"?","locations":[{"line":93,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"threat_actor_types\" on type \"ThreatActor\". Did you mean \"parent_types\"?","locations":[{"line":94,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"roles\" on type \"ThreatActor\". Did you mean \"notes\"?","locations":[{"line":97,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"goals\" on type \"ThreatActor\". Did you mean \"goal\"?","locations":[{"line":98,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"secondary_motivations\" on type \"ThreatActor\". Did you mean \"secondary_motivation\", \"primary_motivation\", or \"personal_motivation\"?","locations":[{"line":102,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"personal_motivations\" on type \"ThreatActor\". Did you mean \"personal_motivation\", \"primary_motivation\", or \"secondary_motivation\"?","locations":[{"line":103,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

Traceback (most recent call last):
  File "worker.py", line 300, in <module>
    worker = Worker()
  File "worker.py", line 212, in __init__
    self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
  File "/home/opencti/.local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 144, in __init__
    "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

**Comment by richard-julien** [comment]
GraphQLError: Cannot query field "standard_id" on type "ThreatActor".","at Object.Field
The python lib you currently use is the dev version, not compatible with OpenCTI 3.3.2.
Please use pycti==3.3.3 in your requirements.txt
See https://github.com/OpenCTI-Platform/connectors/issues/206

**Comment by cyberkun12** [comment]
Hi,

Thank you for the replay.

The parameter pycti is already set to 3.3.3 in my requirements.txt.
Can there be any other issue that might cause this error?

**Comment by richard-julien** [comment]
This is the only reason I see. standard_id is part of the v4 schema.

**Comment by SamuelHassine** [comment]
Hello @cyberkun12, this will be solved in the V4, to be released tomorrow morning.
