### ISSUE TITLE
Export of Observables/Indicators is not working when a filter was applied

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#923]
## Description

The export of Observables / Indicators works well when no filter has been applied or filters such as (Label, Ingested after/before) have been applied.
When the "type of observable" filter is applied, the export is no longer functioning.

## Environment

1. OS : Ubuntu 18
2. OpenCTI version: 4.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the Observables section and filter by "Email address"
2. Click on the export button.
3. Click on the export list and select 
 - Json as expected format (but same error happens if you chose CSV)
4. Click on create. 
5. The dialog window will not close and the export will not start.

## Expected Output

The export should be starting and it should be producing a json or csv file as result.

## Actual Output

No output. The page remains frozen with the dialog window active. 
 
## Additional information
![img5](https://user-images.githubusercontent.com/65337190/101376087-6ed84980-38b0-11eb-84c0-31b9b43434bf.png)

**Comment by maertv** [comment]
Depends on OpenCTI-Platform/connectors/issues/207.
