### ISSUE TITLE
[OPENCTI] GraphQL initialization fail

### ISSUE THREAD

**Issue by a-ml** [OpenCTI-Platform/opencti#924]
Hello,

I'm new to OpneCTI i'm doing the installation followed all the steps now i'm faced with an error without much information on where to look at. 

Can you please help?

## Description

{ Please provide a clear and concise description of the bug. }

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.5 LTS 
2. OpenCTI version: OpenCTI 3.3.2
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Error

:~/bin/opencti$ yarn serv
yarn run v1.22.5
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[INIT] > Starting OPENCTI...","timestamp":"2020-12-07T16:29:54.303Z"}
{"level":"info","message":"[PRE-CHECK] > Grakn is alive","timestamp":"2020-12-07T16:29:54.341Z"}
{"level":"info","message":"[PRE-CHECK] > ElasticSearch is alive","timestamp":"2020-12-07T16:29:54.355Z"}
{"level":"info","message":"[PRE-CHECK] > Minio is alive","timestamp":"2020-12-07T16:29:54.370Z"}
{"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-12-07T16:29:54.535Z"}
{"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-12-07T16:29:54.542Z"}
{"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-12-07T16:29:54.849Z"}
{"error":{},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-12-07T16:29:54.890Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ben12385** [comment]
are you using docker-compose to run? Can you post the docker-compose.yml that you are using?

**Comment by SamuelHassine** [comment]
Hello @a-ml , this will be solved in the V4, to be released tomorrow morning.
