### ISSUE TITLE
Knowledge section of CAMPAIGNS is missing the "Victimology" tab

### ISSUE THREAD

**Issue by csandu-certeu** [OpenCTI-Platform/opencti#928]
## Description

In the KNOWLEDGE section of a CAMPAIGN, the section "Attribution" contains, incorrectly:
- Individual
- Organisation
- Sector
as entities in the bottom left drop-down.
As a result, no organisation/sector/individual can be assocaited with a Campaing, due to the incorrect relationship to be established.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18
2. OpenCTI version: 4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Chose a campaing and go to Knowledge: https://reference.opencti.io/dashboard/threats/campaigns/7563aeca-9e02-4016-8de8-ac33fa4bba36/knowledge/overview
2. Click on ATTRIBUTION and try to add a sector or an organisation. It will not work.

## Expected Output

The 3 entities above, should be contained in a dedicated section called "Victimology". 
The user should be able to add a new "Individual", "Organisation", "Sector" to an existing campaing, by using the section "Victimology" and the STIX relation "related_to".

The section "Attribution" should remain as it is, but, in the bottom left corner, the only entities remaining should be "Threat Actors" and "Intrustion sets". All the rest must be moved to "Victimology"

## Actual Output

The user can't add a new "Individual", "Organisation", "Sector" to an existing campaing, since the relationship to be used is "attributed to" and that is not correct.
 
## Additional information
![img10](https://user-images.githubusercontent.com/65337190/101645028-31052d80-3a36-11eb-9d32-61f73dd4a509.png)

**Comment by maertv** [comment]
> The user should be able to add a new "Individual", "Organisation", "Sector" to an existing campaing, by using the section "Victimology" and the STIX relation "related_to".

Victimology uses the relationship type _targets_ instead of _related-to_.
