### ISSUE TITLE
Duplicate Entry

### ISSUE THREAD

**Issue by tinamina12** [OpenCTI-Platform/opencti#929]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

While running opencti, i am getting the following error please help.

{"error":{"name":"FunctionalError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-12-10T08:13:12.274Z","data":{"reason":"Duplicate entry","category":"business","rule":"There is more than one thing of type [user_role] that owns the key [b71557c6-7483-533c-87c1-37a94ce7e7e3] of type [internal_id_key]. "},"internalData":{}},"level":"error","message":"[OPENCTI] GraphQL initialization fail","timestamp":"2020-12-10T08:13:12.274Z"}

and when i rerun opencti, i get the following error:
{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-12-10T08:17:08.742Z","data":{"reason":"Expect only one response","category":"technical"}

## Environment

1. OS (where OpenCTI server runs):  {Ubuntu 18 }
2. OpenCTI version: { e.g. OpenCTI 3.3.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

**Comment by SamuelHassine** [comment]
Hello @tinamina12, this will be solved in the V4, to be released tomorrow morning.
