### ISSUE TITLE
Ulimit should be increase for elasticsearch

### ISSUE THREAD

**Issue by clopnis** [OpenCTI-Platform/opencti#93]
## Description

Elasticsearch is not able to start because max file descriptors is too low :

`elasticsearch_1  | [1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
`
Issue related here : https://github.com/docker-library/elasticsearch/issues/140

## Environment

1. Opencti on Centos 7 running into LXC

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. get a node with # ulimit -n
4096
2. follow the docker install documentation sysctl -w vm.max_map_count=262144 
3. start # docker-compose up

## Actual Output

Elasticsearch docker is restarting in loop with error following
`elasticsearch_1  | [1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
`
 
## Additional information
if you increase the ulimit on the pod, it works

```
# ulimit -n
65535
```

I don't know if it's better to add a check to have a large ulimit nofile on the documentation or to change the docker-compose.yml with something like on elasticsearch service : 

```
ulimits:
    nofile:
       soft: 65536
       hard: 65536
```

**Comment by SamuelHassine** [comment]
The `docker-compose.yml` file has been updated with new directives for running `ElasticSearch` in production.
