### ISSUE TITLE
Provide pre-built Docker images from Docker Hub instead of building it

### ISSUE THREAD

**Issue by simonsigre** [OpenCTI-Platform/opencti#94]
## Problem to Solve
Provide assurance that `https://hub.docker.com/r/luatix/opencti` is indeed a certified repository via a mention (of sorts) in the `https://opencti-platform.github.io/docs/installation/installation-docker` documentation. The current instance is `10m` old and I am not even sure this is sanctioned?

## Current Workaround

git pull and pray

## Proposed Solution

Provide either a link (proof) on `https://opencti-platform.github.io/docs/installation/installation-docker` and potentially update the image
OR
Update `https://hub.docker.com/r/luatix/opencti` to state that this is no longer maintained.

## Additional Information

![Screenshot from 2019-07-01 08-43-41](https://user-images.githubusercontent.com/14932913/60403097-59032700-9bdc-11e9-907a-5f1c193719e3.png)

**Comment by SamuelHassine** [comment]
@simonsigre: Thank you for your bug report. You are right this Docker image is out of date and no longer maintained. I just deleted it. We will create a Docker image under [this repository](https://hub.docker.com/u/opencti) and use it in the `docker-compose.yml`.

**Comment by SamuelHassine** [comment]
Pre-built Docker images has been built and are now available on the [Docker Hub](https://hub.docker.com/u/opencti).
