### ISSUE TITLE
Observable of type 'Domain-Name' is not correctly formatted

### ISSUE THREAD

**Issue by simonsigre** [OpenCTI-Platform/opencti#941]
## Description
When attempting to define an observable of type "Domain-Name" it fails citing "Observable of type 'Domain-Name' is not correctly formatted" however similar values are being defined (incorrectly?) as a "Hostname".

## Environment

1. OS (where OpenCTI server runs): demo.opencti.io
2. OpenCTI version: Assume 4.0.0 (demo.opencti.io)
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

1. Reports
2. Select a report
3. Observables
4. "+"
5. Domain-Name
(see screenshot)

## Expected Output
It works

## Actual Output
Error message (as seen in screenshot)
 
## Additional information

![Screenshot from 2020-12-16 17-06-49](https://user-images.githubusercontent.com/14932913/102312386-b94d7a80-3fc2-11eb-89ca-db2b356b8e38.png)

**Comment by SamuelHassine** [comment]
Hello @simonsigre, I tried to reproduce exactly your use case and I did not have any errors. Can you please double check that you dont have a trialing space after?

**Comment by simonsigre** [comment]
@SamuelHassine strange indeed.. I can't replicate this today.. has there been a refresh by any-chance as some items look slightly different.
Either way, apologies for any inconvenience (although I did try a good number of times) .
Can we perhaps leave this open for another weeks and ill keep retrying and then ill update and let you know.

**Comment by SamuelHassine** [comment]
No problem, I think the problem is solved. Feel free to re-open or drop a message if you have any problem with this type of observable.
