### ISSUE TITLE
Newly created Indicators are no longer automatically linked to existing Observables

### ISSUE THREAD

**Issue by jbfeldman** [OpenCTI-Platform/opencti#946]
## Description

In Version 3.3.2, if a new Indicator was created via the python helper function `send_stix2_bundle`, it would automatically link it to a matching observable. This was extremely helpful in using/developing enrichment connectors, as a newly created indicator (and any TTPs/Threat Actors linked to that indicator) would automatically be linked to the observable, quikcly creating a comprehensive graph. However, in Version 4.0, the newly created indicator is **not** linked to the observable. 

It's possible that this is not a bug but rather an intended change of the new data model. In that case, some advice on how
## Environment

1. Docker running on Ubuntu
2. OpenCTI version: 4.0.1
3. OpenCTI client: process happens in connector/python, bug observed in frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
( I haven't actually tested it this way, but presumably this would yield equivalent results)

Create an observable (e.g., 8.8.8.8)
Upload a STIX2 bundle that contains an indicator with the pattern `ipv4-addr:value = '8.8.8.8'`. For testing purposes it may also make sense to attach some notes to this indicator in the STIX2 bundle to make it easier to track

## Expected Output

When you click on the observable, it will say it's based on Indicator 8.8.8.8
## Actual Output

The Observable does remains unlinked from an indicator
 
## Additional information

If an indicator is already linked to an observable, when you enrich the observable the new information is correctly added to the linked indicator instead of creating a duplicate indicator. This behavior is expected.

**Comment by SamuelHassine** [comment]
Hello @jbfeldman,

We are well aware of this new limitation, it's mainly because this feature was really partial in the previous version (that worked only for "simple" indicator, not composite ones). We did not fine a proper way to extract observables from any STIX patterns for the moment, the official library does not provide such feature. Any idea or work you can point us on how to implement full extraction of all observables from any type of STIX patterns?

Kind regards,
Samuel

**Comment by jbfeldman** [comment]
Hey @SamuelHassine .

That makes sense. It's probably possible to implement a system for extracting observables from STIX patterns, but it would a significant amount of work. As a workaround for me, is there a proper construction of STIX2 that would link an observable and an indicator? The STIX2 standard is surprisingly unclear about linking the two

**Comment by SamuelHassine** [comment]
Hello,

We choose to use the "based-on" relationship, which normally links Indicator => Observed-Data:

https://demo.opencti.io/dashboard/observations/indicators/b22f3f28-45bb-448c-9c08-d2a9f30b8008
https://demo.opencti.io/dashboard/observations/observables/a8dfa1c1-ecc4-4621-ab7f-7d44eac787aa
https://demo.opencti.io/dashboard/observations/observables/a8dfa1c1-ecc4-4621-ab7f-7d44eac787aa/knowledge/relations/edb1936b-712b-4c8d-886e-e13b824525f7

All current connectors are automatically creating this relationship (MISP, AlienVault, CrowdStrike, Kaspersky, Cybercrime Tracker, etc.).

**Comment by jbfeldman** [comment]
I was able to successfully link observable to indicator by creating an additional relationship in the STIX2 bundle. Feel free to close this issue, or keep it open if you want to track this is an improvment

**Comment by SamuelHassine** [comment]
Thanks @jbfeldman.
