### ISSUE TITLE
Implements spec issue

### ISSUE THREAD

**Issue by matthew-renodin** [OpenCTI-Platform/opencti#948]
## Description

The spec https://spec.graphql.org/June2018/#sec-Interfaces requires the "&" between the values instead of commas

type Business implements NamedEntity & ValuedEntity {
  name: String
  value: Int
  employeeCount: Int
}

## Environment

This is coming from the schema output by the demo server.

## Reproducible Steps

1. Go to the http://demo.opencti.io/graphql 
2. click schema on the right side of the screen and click Download and the the SDL schema
3. Read the schema and witness the error 

## Expected Output

type Individual implements BasicObject & StixObject & StixCoreObject & StixDomainObject & Identity .{..

type Artifact implements BasicObject & StixObject & StixCoreObject & StixCyberObservable & HashedObservable {...

## Actual Output

type Individual implements BasicObject, StixObject, StixCoreObject, StixDomainObject, Identity {...

type Artifact implements BasicObject, StixObject, StixCoreObject, StixCyberObservable, HashedObservable {... 
## Additional information

I contacted Datensen and they pointed out that the file was large with many items. Is there an acceptable approach to having multiple schema files?

Test this out by loading it within Moon Modeler.

**Comment by SamuelHassine** [comment]
Hello @matthew-renodin,

I think this is a problem with the playground itself, because our schema is implemented correctly: https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/schema/opencti.graphql. 

Maybe you can use directly this file?

For splitting the schema file, we have a plan to do so but it's not high priority now, is this large file prevent you for doing anything?

Kind regards,
Samuel

**Comment by matthew-renodin** [comment]
I was only trying to display the file with Moon Modeler. I wanted to see how the entities were connected especially regarding the Stix Relationships. 

The & issue was something Datensen pointed out. Once the commas are replaced with ampersands I can view the file.

The performance of the software was impeded by the number of items. I would suggest that Moon Modeler tile the display so it can handle large sophisticated data models such as this.
