### ISSUE TITLE
Docker-Compose Issue

### ISSUE THREAD

**Issue by aostrovs** [OpenCTI-Platform/opencti#95]
## Environment

1. macOS High Sierra
2. OpenCTI version latest

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. docker-compose up

## Actual Output

Following error occurs (over and over):

opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...

**Comment by codeyourweb** [comment]
Similar thing on docker-compose up
(Env Ubuntu 19.04 / OpenCTI latest version / docker-compose up)

Actual output:
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting for shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting ElasticSearch to launch...
(output loop)

**Comment by SamuelHassine** [comment]
@aostrovs, @codeyourweb: could you please:

1. Clear your docker images and containers
2. Clear all files in the folder `opencti-docker/config`
3. Pull the repository (we fix a bug)
4. Verify you apply `sysctl -w vm.max_map_count=262144 ` as mentioned in the [documentation](https://opencti-platform.github.io/docs/installation/docker).
5. Run `docker-compose up`

Is OpenCTI working now?

**Comment by aostrovs** [comment]
Was able to resolve the issue. Thank you!

**Comment by SamuelHassine** [comment]
@aostrovs, @codeyourweb: we fixed a lot a problems related to the Docker installation in the new release. This should solve all the bugs you encountered. I close this issue, do not hesitate to open a new one if you have any new troubles.
