### ISSUE TITLE
VM Template Not Available

### ISSUE THREAD

**Issue by graememeyer** [OpenCTI-Platform/opencti#951]
The [documentation](https://www.notion.so/Virtual-machine-template-1789b4442b414dbf87f748db51c85aa5) describes the VM template, but the provided link leads to a blank google drive page:

![image](https://user-images.githubusercontent.com/3931530/102543449-3ce29680-40ab-11eb-8f43-4af2a3850bf0.png)

**Comment by SamuelHassine** [comment]
Hello @graememeyer,

The template is now available!

Kind regards,
Samuel
