### ISSUE TITLE
Data import using the connector ImportFileStix2 doesn't work

### ISSUE THREAD

**Issue by cyberkun12** [OpenCTI-Platform/opencti#956]
## Description

When uploading a JSON in stix2 format to OpenCTI, the import is stuck.

## Environment

1. OS: Ubuntu 18.04.5
2. OpenCTI version: 4.01
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upload stix2 file
2. Launch an import of this file

## Expected Output

File imported  to the system

## Actual Output

The import is stuck at 0.
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }
![image](https://user-images.githubusercontent.com/75355829/102713822-6ed64180-42d3-11eb-8598-e6788dd8d707.png)

**Comment by SamuelHassine** [comment]
Hello,

We do not found any problem with these connectors on the demonstration instances and during our testing. Are you sure you have at least one launched OpenCTI worker to process the data?

Kind regards,
Samuel

**Comment by CvetkoM** [comment]
Hello, I'm having the same problem, but then I'm not sure how long it takes to upload a .json file.
