### ISSUE TITLE
Worker should install an official release of the python-client

### ISSUE THREAD

**Issue by jcockhren** [OpenCTI-Platform/opencti#964]
## Description

Having the [worker's requirements file reference the master branch of pycti](https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-worker/src/requirements.txt#L4) prevents clean (re)installs of any version of the platform. 

[Current development on the pycti introduces breaking changes](https://github.com/OpenCTI-Platform/client-python/commit/73a510d98a122ca583df2a4c90ae0de15901f5c2) which causes a graphql schema validation error.

## Environment

1. OS (where OpenCTI server runs): Debian Buster 10.7
2. OpenCTI version: 4.0.3
3. OpenCTI client: worker and platform
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install the worker 4.0.x using pycti from `master`
2. Look at the platform (frontend) & worker logs

## Expected Output

a connected worker

#### 2. Release script

Internally I'm using ansible to ensure I can have reliable installs. In lieu of #965, an ansible playbook would insert the specific version of pycti to install into the requirements file for manual and docker installations.

**Comment by richard-julien** [comment]
Hi @jcockhren,
Thanks for the report. I think we will change the release process to fix the version when we release. It will permits to continue to easily develop without versioning for us and have correct versions correctly fixed for the release.
Does it make sense for you?

**Comment by 2xyo** [comment]
Hi @jcockhren @richard-julien , 

Here is another option, maintain dependencies in two files: 

- `requirements.txt`  stable requirements with version matching (`pycti==4.0.3`)
- `requirements-dev.txt`  development requirements with VCS specifier (`git+https://github.com/OpenCTI-Platform/client-python@master`)

Regarding the [Dockerfile](https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-worker/Dockerfile):

```dockerfile
FROM python:3.9-alpine

ARG REQ=requirements.txt

# Copy the worker
COPY src /opt/opencti-worker

# Install Python modules
# hadolint ignore=DL3003
RUN apk --no-cache add git build-base libmagic && \
    cd /opt/opencti-worker && \
    pip3 install --no-cache-dir -r ${REQ} && \
    apk del git build-base

# Expose and entrypoint
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh 
ENTRYPOINT ["/entrypoint.sh"]
```

````console
$ docker build --build-arg REQ=requirement-dev.txt . -t opencti-worker:dev
$ docker build . -t worker:stable
````


Reference: 
- https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file 
- https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg 
- https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by richard-julien** [comment]
Finally we go for just fix the version in the master.
This is not a problem in development.
