### ISSUE TITLE
Documentation site seems to be unreliable/unavailable

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#979]
## Description

The link to the Documentation that is on the splash page of OpenCTI.io is unresponsive

## Environment

All

## Reproducible Steps

Click on Documentation link at Opencti.io.

## Expected Output

THe he actual OpenCTI documentation would appear.

## Actual Output

Notion.so is experiencing a service outage.
 
## Additional information

Is there some reason why the documentation isn't, also, on the GitHub site?

**Comment by richard-julien** [comment]
Notion experiment some outage, see https://status.notion.so/
