### ISSUE TITLE
Most Active Malware Widget

### ISSUE THREAD

**Issue by PandaLyfe** [OpenCTI-Platform/opencti#992]
## Problem to Solve

Our organization would like to add a "Top 5 Active Malware" section on some of our reporting within a specific timeframe. A widget with this capability would be extremely helpful.

## Current Workaround

No workaround exists

## Proposed Solution

To add a widget that displays most active malware in a specific timeframe. It can be set to a month by default but the user can use specific dates.

## Additional Information

Below are images from Mandiant. Having this capability in OpenCTI would be extremely useful. It would also be helpful if this feature does not require a subscription, but calculates the top 10 with data ingested in OpenCTI or from an Open Source.

![MostActiveMalware](https://user-images.githubusercontent.com/26508991/104369642-c55a2880-54eb-11eb-9d96-b724cc1b72b0.png)

The Most Active Malware Widget with date modifications. This only allows the user to select time frames by weeks, months or quarters. Allowing the user to specify a start date and an end date is preferred.

![MalwareDateMod](https://user-images.githubusercontent.com/26508991/104369757-f20e4000-54eb-11eb-9341-8d09e5ad4099.png)

After dates are specified and malware results are populated, the user can click on a malware and OpenCTI would provide CVE information, associated actors, external references and any additional information related to the specific CVE.

**Comment by richard-julien** [comment]
Related to https://github.com/OpenCTI-Platform/opencti/issues/307
