### ISSUE TITLE
Top Actor Widget

### ISSUE THREAD

**Issue by PandaLyfe** [OpenCTI-Platform/opencti#993]
## Problem to Solve

Our organization would like to add a section regarding most active actors on some of our reporting within a specific timeframe. A widget with this capability would be extremely helpful.

## Current Workaround

No workaround exists 

## Proposed Solution

To add a widget that displays most active or top 5 actors in a specific timeframe. It can be set to a month by default but the user can use specific dates.

## Additional Information

Below are images from Mandiant. Having this capability in OpenCTI would be extremely useful. It would also be helpful if this feature does not require a subscription, but calculates the top 10 with data ingested in OpenCTI or from an Open Source.

![ActorActivity](https://user-images.githubusercontent.com/26508991/104370347-b9229b00-54ec-11eb-8242-e1602694708f.png)

Most active actors widget with date modifications. This only allows the user to select time frames by weeks, months or quarters. Allowing th user to specify a start date and an end date is preferred.

![ActorActivityDateMod](https://user-images.githubusercontent.com/26508991/104370414-d0618880-54ec-11eb-8e60-9c1d0c32c165.png)

After dates are specified and actor results are populated, the user can click on an actor and OpenCTI would provide actor information, external references and any additional information related to the specific actor.

**Comment by richard-julien** [comment]
Related to https://github.com/OpenCTI-Platform/opencti/issues/307
