### ISSUE TITLE
Platform initialization fail

### ISSUE THREAD

**Issue by little-roach** [OpenCTI-Platform/opencti#994]
According to the document of "Using Docker(https://www.notion.so/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8)" to deploy OpenCTI, I copied ".env.sample" to ".env" and modify the relevant parameters.

Then, I used single node Docker to deploy  by command "$sudo docker-compose up -d".

By command "sudo docker-compose ps -a"，the results show as follows:

CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                          PORTS                                                                  NAMES
433b7c6ace35        opencti/connector-export-file-csv:4.0.5                "/entrypoint.sh"         39 seconds ago      Up 4 seconds                                                                                           docker_connector-export-file-csv_1
9287365271c5        opencti/connector-import-file-pdf-observables:4.0.5    "/entrypoint.sh"         41 seconds ago      Up 4 seconds                                                                                           docker_connector-import-file-pdf-observables_1
d0ef66e7300c        opencti/connector-import-file-stix:4.0.5               "/entrypoint.sh"         42 seconds ago      Up 7 seconds                                                                                           docker_connector-import-file-stix_1
339de3bf181d        opencti/connector-export-file-stix:4.0.5               "/entrypoint.sh"         42 seconds ago      Up 7 seconds                                                                                           docker_connector-export-file-stix_1
2f7b1ac8b701        opencti/worker:4.0.5                                   "/entrypoint.sh"         50 seconds ago      Restarting (1) 13 seconds ago                                                                          docker_worker_1
5dd98503d0fa        opencti/connector-history:4.0.5                        "/entrypoint.sh"         50 seconds ago      Restarting (1) 13 seconds ago                                                                          docker_connector-history_1
b79aa7783036        opencti/platform:4.0.5                                 "/entrypoint.sh"         About an hour ago   Restarting (1) 37 seconds ago                                                                          docker_opencti_1
aa563a1e934d        rabbitmq:3.8-management                                "docker-entrypoint.s…"   2 hours ago         Up 2 hours                      4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp   docker_rabbitmq_1
9eccf21ff2eb        docker.elastic.co/elasticsearch/elasticsearch:7.10.1   "/tini -- /usr/local…"   2 hours ago         Up 2 hours                      9200/tcp, 9300/tcp                                                     docker_elasticsearch_1
af07e9466f01        redis:6.0.9                                            "docker-entrypoint.s…"   2 hours ago         Up 2 hours                      6379/tcp                                                               docker_redis_1
9b18cbec6593        minio/minio:RELEASE.2020-12-12T08-39-07Z               "/usr/bin/docker-ent…"   2 hours ago         Up 2 hours (healthy)            0.0.0.0:9000->9000/tcp                                                 docker_minio_1

The status of container "opencti/worker:4.0.5", "opencti/connector-history:4.0.5" and "opencti/platform:4.0.5" are "Restaring".

The logs of container "opencti/platform:4.0.5 " show "[OPENCTI] Platform initialization fail", as follow.

yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-01-13T03:14:40.246Z"}
{"level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-01-13T03:14:40.275Z"}
{"error":{},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-01-13T03:14:40.278Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Can you help me with this problem? I used the latest vestion 4.0.6.

According to the previous questions in Issues,  I had modify " - APP__LOGS_LEVEL=error" to " - APP__LOGS_LEVEL=info" in "docker-compose.yml" file, but it is invalid.

I also modify "- ELASTICSEARCH__URL=http://elasticsearch:9200", "- OPENCTI_URL=http://opencti:8080" to  "- ELASTICSEARCH__URL=http://localhost:9200", "- OPENCTI_URL=http://localhost:8080" or  "- ELASTICSEARCH__URL=http://192.168.7.108:9200", "- OPENCTI_URL=http://192.168.7.108:8080", It is still invalid.

How can I set the parameters and environment?

**Comment by richard-julien** [comment]
Hi @little-roach ,

You dont have to modify the URL.
Please restart from the env example.
Check the doc to setup the env correctly. https://www.notion.so/luatix/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8#00a68f8c25bd4576b68d054c7366348f
Then start the docker compose.
After 2 minutes check the status of ( in this order)
- Elasticsearch
- Minio
- Rabbit
- Redis
- OpenCTI

Thanks

**Comment by little-roach** [comment]
Hi @richard-julien ,

My .env file contents are as follow:

OPENCTI_ADMIN_EMAIL=xxxxxxxx@gmail.com
OPENCTI_ADMIN_PASSWORD=123123123
OPENCTI_ADMIN_TOKEN=de42fdb8-267b-499f-b9bf-77be0d286dde
MINIO_ACCESS_KEY=123123123
MINIO_SECRET_KEY=123123123
RABBITMQ_DEFAULT_USER=guest_user
RABBITMQ_DEFAULT_PASS=guest_password
CONNECTOR_HISTORY_ID=7a80078b-9818-42ff-bc9f-841c78d508d8
CONNECTOR_EXPORT_FILE_STIX_ID=ea8a470f-8181-4b84-b39f-00eadfd6c6be
CONNECTOR_EXPORT_FILE_CSV_ID=a3099de1-57d9-45e2-a66b-c16df905d3e9
CONNECTOR_IMPORT_FILE_STIX_ID=9933e359-ca38-429c-9fc3-bc4a62c2f8c0
CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID=5e90cb94-d514-4c0f-9d43-7c4b87657a7f

I have try the steups in doc(https://www.notion.so/luatix/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8#00a68f8c25bd4576b68d054c7366348f) more than three times, but it still failed.

Using command "sudo docker ps -a" to check the status of dockers.

CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                          PORTS                                                                  NAMES
69c58d45fc38        opencti/worker:4.0.5                                   "/entrypoint.sh"         5 minutes ago       Up Less than a second                                                                                  docker_worker_1
bbd0d2485a7b        opencti/platform:4.0.5                                 "/entrypoint.sh"         5 minutes ago       Restarting (1) 57 seconds ago                                                                          docker_opencti_1
172c19eaa428        docker.elastic.co/elasticsearch/elasticsearch:7.10.1   "/tini -- /usr/local…"   10 minutes ago      Up 5 minutes                    9200/tcp, 9300/tcp                                                     docker_elasticsearch_1
a0a42d5f84e6        opencti/connector-export-file-stix:4.0.5               "/entrypoint.sh"         10 minutes ago      Up 8 seconds                                                                                           docker_connector-export-file-stix_1
3c967ab59799        opencti/connector-import-file-stix:4.0.5               "/entrypoint.sh"         10 minutes ago      Up Less than a second                                                                                  docker_connector-import-file-stix_1
5027a6e519e5        rabbitmq:3.8-management                                "docker-entrypoint.s…"   10 minutes ago      Up 5 minutes                    4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp   docker_rabbitmq_1
a9da2bbe4a12        minio/minio:RELEASE.2020-12-12T08-39-07Z               "/usr/bin/docker-ent…"   10 minutes ago      Up 5 minutes (healthy)          0.0.0.0:9000->9000/tcp                                                 docker_minio_1
661c39e82826        opencti/connector-import-file-pdf-observables:4.0.5    "/entrypoint.sh"         10 minutes ago      Up 1 second                                                                                            docker_connector-import-file-pdf-observables_1
4219b0e4b88e        opencti/connector-history:4.0.5                        "/entrypoint.sh"         10 minutes ago      Restarting (1) 59 seconds ago                                                                          docker_connector-history_1
52175f3698d4        redis:6.0.9                                            "docker-entrypoint.s…"   10 minutes ago      Up 5 minutes                    6379/tcp                                                               docker_redis_1
7d8f85b08170        opencti/connector-export-file-csv:4.0.5                "/entrypoint.sh"         10 minutes ago      Up 10 seconds                                                                                          docker_connector-export-file-csv_1

The status of container "opencti/worker:4.0.5", "opencti/connector-history:4.0.5" and "opencti/platform:4.0.5" are still "Restaring".

Hope you can help me to solve the problem!

**Comment by richard-julien** [comment]
After some painful research with Samuel we find that if you put only numbers for Minio access/pass it will fail silently because of the client thinking you try to use numbers instead of string.
I will push a fix to prevent this kind of situation.
But for now you just have to change the minio config to also use letters.
MINIO_ACCESS_KEY=abcd123123123
MINIO_SECRET_KEY=abcd123123123
Maybe you will have to remove the docker volume of minio.

**Comment by little-roach** [comment]
> After some painful research with Samuel we find that if you put only numbers for Minio access/pass it will fail silently because of the client thinking you try to use numbers instead of string.
> I will push a fix to prevent this kind of situation.
> But for now you just have to change the minio config to also use letters.
> MINIO_ACCESS_KEY=abcd123123123
> MINIO_SECRET_KEY=abcd123123123
> Maybe you will have to remove the docker volume of minio.

Thank you for your help and your patience, problem has been solved!

I suggest adding this part of the content to the doc(https://www.notion.so/luatix/Using-Docker-03d5c0592b9d4547800cc9f4ff7be2b8#00a68f8c25bd4576b68d054c7366348f) .

Thank you very much!

**Comment by richard-julien** [comment]
Cool @little-roach . No need to document this problem, i add specific code to support it :)
Available in version 4.0.7
