### ISSUE TITLE
Issue OpenCTI Docker w/Portainer

### ISSUE THREAD

**Issue by jcandiat** [OpenCTI-Platform/opencti#996]
yarn run v1.19.1

$ node --max_old_space_size=8192 build/index.js

{"level":"error","message":"[INIT] 88ec0c6a-13ce-5e39-b486-354fe4a7084f user have no token to renew, please report this problem in github","timestamp":"2021-01-14T18:48:04.610Z"}

{"error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-01-14T18:48:04.910Z","data":{"reason":"Error updating elastic","category":"technical","error":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-01-14T18:48:04.910Z","data":{"reason":"Error executing bulk indexing","category":"technical","errors":[{"type":"cluster_block_exception","reason":"index [opencti_internal_relationships] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}]},"internalData":{}}},"internalData":{}},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-01-14T18:48:04.910Z"}

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by richard-julien** [comment]
Hi @jcandiat,

What is the version of OpenCTI you try to deploy?
And for the error, looks like elastic complaining
`TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block`
It looks like your harddrive is getting full.

**Comment by jcandiat** [comment]
fixed: increase hard disk space.

Thnk You!
