### ISSUE TITLE
Where is the opencti folder in the provided VM?

### ISSUE THREAD

**Issue by NetEyes** [OpenCTI-Platform/opencti#999]
I downloaded the latest OpenCTI ova and able to run it.
I am looking for opencti folder in the VM so I can look what are the settings in your docker-compose.yml

reason?

I also managed to install OpenCTI docker in my home server labs.
installed successfully but I got blank data. NO connectors defined, NO feeds. All blank.

So how do I start adding threat feeds in OpenCTI?
I am thinking of opening up your sample VMs and see how do you guys managed to pull some feeds.
Please advise.

**Comment by richard-julien** [comment]
Hi @NetEyes , 
OpenCTI is based on a connector ecosystem.
Each connector provide a docker image that can be deployed.
Take a look to the documentation about connector: https://www.notion.so/luatix/Connectors-4586c588462d4a1fb5e661f2d9837db8

In the VM only import/export connectors are deployed by default. If you want to take look you have to look into the portainer UI . See Stack administration in documentation https://www.notion.so/luatix/Virtual-machine-template-1789b4442b414dbf87f748db51c85aa5

**Comment by NetEyes** [comment]
The reason i asked is I am about to migrate your .ova file to proxmox to be a stand-alone linux box. 
I just need to know where did you guys put the opencti .. is it on /opt/opencti?
I may update the yml file later on.

**Comment by richard-julien** [comment]
OpenCTI is deployed with docker inside the VM, its not a manual installation.
